<div class="product-faq-section">
<div class="container reveal1">
<div class="h-title">Frequently asked questions</div>


<div class="faq-list">
  <input type="checkbox" id="title1" />
  <label for="title1">What are the benefits of using Mounjaro?</label>
  <div class="panel-p">
    <ul>
    <li>Shed Pounds: Clinical trials reveal Tirzepatide's remarkable potential for weight loss. Participants lost an average of 11.5% of body weight after just 26 weeks.</li>
<li>Better Blood Sugar Management: Originally designed for type 2 diabetes treatment, Mounjaro not only aids weight loss but also enhances blood sugar control. This reduces the risk of complications like nerve damage, kidney disease, and heart issues.</li>
<li>Less Reliance on Medications: With improved weight and blood sugar control, Tirzepatide may lessen the need for other medications, such as those for hypertension or cholesterol.</li>
<li>Enhanced Quality of Life: Weight loss can alleviate symptoms like joint pain and fatigue while boosting energy levels and overall well-being.</li>
</ul>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title2" />
  <label for="title2">How to get a Mounjaro prescription online?</label>
  <div class="panel-p">
    <p>You can get a Mounjaro prescription from Pharmacy Planet by completing the online clinical consultation. Our prescribers will review the answers to check if it is suitable for you before approving the order. As Pharmacy Planet is a private online pharmacy, we cannot fulfil other prescriptions from external sources.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title3" />
  <label for="title3">How long do you stay on Mounjaro for weight loss?</label>
  <div class="panel-p">
    <p>If you are using Mounjaro for the first time, you may start to notice weight loss within your first few weeks of the initial starting dose. The rate of weight loss in any individual depends on their age, physical activity and diet. However, if you haven’t lost 5% of your body weight within the first 6 months, then a discussion with your clinician should be had to consider alternative treatment options.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title4" />
  <label for="title4">What's the best time to take Mounjaro?</label>
  <div class="panel-p">
    <p>You can take Mounjaro at any time of the day. But it is important inject on the same day each week to ensure you receive the dosage regularly and to minimise potential side effects.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title5" />
  <label for="title5">What happens when you stop Mounjaro?</label>
  <div class="panel-p">
    <p>Once you stop taking Mounjaro , the appetite is expected to be back to normal gradually. Also, weight regain is possible if you don’t follow healthy diet and involve in regular physical exercises. Remember, Mounjaro is not a medicine you take for life. It is designed to help the user develop a healthier, sustainable lifestyle. Once you come off of this medicine, it is important to stay consistent with diet and exercise.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title6" />
  <label for="title6">Can I take Mounjaro if I don't have diabetes?</label>
  <div class="panel-p">
    <p>Yes, you can take Mounjaro if you do not have diabetes. However, you must meet the following requirements:</p> 
<ul>
<li>You must be aged 18-75</li>
<li>Have a BMI that is over 30 -- or 27 or over for patients with weight impacting conditions.</li> 
<li>You are not suffering from or have a history of pancreas or thyroid related health issues.</li>
</ul>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title7" />
  <label for="title7">How to manage the side effects of Mounjaro?</label>
  <div class="panel-p">
    <p>Common side effects caused by Mounjaro should not be severe and starts disappearing over time.  Side effects like Nausea, diarrhoea and heart burn can be resolved by following the tips below:</p>

<ul>
  <li>In case of diarrhoea, acid reflux and heartburn, consume small portions of meals and avoid spicy or strongly flavoured foods. This should help with reducing the level of gastric discomfort and get you back to normal in no time.</li>

<li>For vomiting and nausea, make sure to stay hydrated. Becoming dehydrated can cause other symptoms that can be distressing. Having adequate amounts of water, even in small sips, can help settle the feeling of nausea.</li>
</ul>
  </div>
</div>


<div class="faq-list">
  <input type="checkbox" id="title8" />
  <label for="title8">Are Mounjaro and Wegovy the Same?</label>
  <div class="panel-p">
    <p>No, they are not same even though they are used for weight loss treatments. The key difference is the active ingredients used in these drugs. Tirzepatide is used in Mounjaro while Semaglutide is present in Wegovy. Though they are part of the same family of medicines, both have shown different results depending on the individual and their response to the medicine.</p>

 
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title9" />
  <label for="title9">Switching from Wegovy to Mounjaro?</label>
  <div class="panel-p">
    <p>All patients taking Mounjaro for the first time are required to commence their treatment with the 2.5mg strength. This is still the case even if you are currently using an alternative weight loss medicine (such as Wegovy). This makes sure your body can adjust to the new medicine gradually and minimizes the potential for side effects.</p>
<p>If you are currently using another weight loss medicine (eg. Wegovy), a period of 4 weeks must elapse between your last dose of the current medicine and the first dose of Mounjaro. This is to ensure that your previous weight loss medicine has worked its way out of your system prior to initiating treatment with Mounjaro.</p> 
<p>Although Wegovy and Mounjaro come from the same family of medicines, they are separate distinct drugs which necessitates caution.</p> 
<p>So, in summary, patients new to Mounjaro should order the 2.5mg strength and ensure there is at least a 4 week gap between ending their current medicine and beginning on Mounjaro.</p>

 
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title10" />
  <label for="title10">PATIENT INFORMATION LEAFLET (PIL)</label>
  <div class="panel-p">
    <p>Please read the important safety precautions carefully, as well as other information regarding Mounjaro provided in the patient information leaflet. This can be found in the medication box, or you can use the link provided for a <a href="https://www.ema.europa.eu/en/documents/product-information/mounjaro-epar-product-information_en.pdf" target="_blank" rel="noopener">digital copy</a></p>

 
  </div>
</div>


</div>
</div>

<script>
        document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(checkbox => {
            checkbox.addEventListener('change', function () {
                if (this.checked) {
                    document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(otherCheckbox => {
                        if (otherCheckbox !== this) {
                            otherCheckbox.checked = false;
                        }
                    });
                }
            });
        });
    </script>

 
