<div class="product-faq-section">
<div class="container reveal1">
<div class="h-title"><h2>Weight Loss everything you need to know</h2></div>


<div class="faq-list">
  <input type="checkbox" id="title1" />
  <label for="title1">What is Pharmacy Planet’s Weight Loss Clinic?</label>
  <div class="panel-p">
    <p>Pharmacy Planet’s Weight Loss Clinic is an online pharmacy dedicated to facilitating weight loss through clinical means. Our team includes UK registered clinicians, weight loss experts, and a supportive customer service team that aims to help you reach the very pinnacle of your weight loss goals.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title2" />
  <label for="title2">What do I get with Pharmacy Planet’s weight loss program?</label>
  <div class="panel-p">
    <p>Our approach to weight loss is simple: A healthier lifestyle partnered with scientifically backed treatment. This combined approach will tackle both the physical and mental aspects of losing weight, helping you not only to look good but feel good as well. We not only offer support from a weight related angle but from a clinical perspective. So, if you feel like the medication you have requested isn’t quite working for you, our helpful team of clinicians will be able to get down to the root of the problem and provide an unparalleled level of help.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title3" />
  <label for="title3">What can I expect in the online clinical consultation form?</label>
  <div class="panel-p">
    <p>Our clinical consultation form will cover questions regarding your height, weight, medical history, and lifestyle. Our team of clinicians will assess your order to see whether the treatment is suitable for you. This should take you a few minutes to fill in.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title4" />
  <label for="title4">What results can I achieve from joining Pharmacy Planet’s Weight Loss Clinic?</label>
  <div class="panel-p">
    <p>Everyone’s response to clinical weight loss varies, so results can differ from person to person. With all suggested weight loss medicines accompanied by a healthier lifestyle, you can expect to lose up to as much as 15% of your body weight over a 6-month period. It’s important to set realistic milestones and ensure that you are putting just as much effort into maintaining exercise and dieting habits as you are into consistently taking the medication.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title5" />
  <label for="title5">What is the role of medication in Pharmacy Planet’s weight loss program?</label>
  <div class="panel-p">
    <p>Medications such as Wegovy and Mounjaro act to jumpstart your weight loss journey and gradually ease you into living a healthier lifestyle. There are a number of different medicine options on the program, each of which has been shown to facilitate weight loss.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title6" />
  <label for="title6">What prescription weight loss medications are available at Pharmacy Planet?</label>
  <div class="panel-p">
    <p>At Pharmacy Planet, we offer several medicines for medical weight loss journeys. This includes Wegovy (Semaglutide) and Mounjaro (Tirzepatide), which are both popular, weekly injectable options that have helped many patients lose weight. For individuals who do not like to use injectable options, there is Orlistat/Xenical, which is a capsule that can be taken with meals, which can block fat absorption that helping with weight loss. These medications are prescribed following an online consultation to ensure suitability and safety. </p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title7" />
  <label for="title7">How do these weight loss medications work?</label>
  <div class="panel-p">
    <p>Weight loss medicines like Wegovy and Mounjaro belong to a family of drugs known as GLP-1 receptor agonists. These medicines work by mimicking a hormone within the body that helps with regulating appetite and food intake, causing you to eat fewer calories and lose weight. These medicines are most effective when used alongside a healthy diet and a regular exercise plan.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title8" />
  <label for="title8">Who is eligible for prescription weight loss treatments?</label>
  <div class="panel-p">
    <p>You may be eligible to take prescription weight loss treatments if you are an adult with a body mass index (BMI) of 30 or higher, or 27 or higher if you have a weight-related co-morbidity like type 2 diabetes or high blood pressure. Your healthcare clinician will assess your medical history and any current conditions to ensure that this medication is appropriate for you. </p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title9" />
  <label for="title9">What are the potential side effects of these medications?</label>
  <div class="panel-p">
    <p>Some common side effects of using GLP-1s like Wegovy and Mounjaro for weight loss can include nausea, vomiting, diarrhoea, constipation and even symptoms related to acid reflux, like gassiness and sulphur burps. You should make sure to bring up any side effects to your clinician so they can give you the best advice to resolve any discomfort. </p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title10" />
  <label for="title10">Are these medications a substitute for diet and exercise?</label>
  <div class="panel-p">
    <p>No, medicine for weight loss, like Wegovy and Mounjaro, are not substitutes for diet and exercise. These medicines are tools designed to be used alongside a healthy diet and exercise to achieve optimal results.</p>
  </div>
</div>
</div>
</div>

<script>
        document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(checkbox => {
            checkbox.addEventListener('change', function () {
                if (this.checked) {
                    document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(otherCheckbox => {
                        if (otherCheckbox !== this) {
                            otherCheckbox.checked = false;
                        }
                    });
                }
            });
        });
    </script>

 
