<div class="included-section">
  <div class="container">
    <div class="h-title">What's included</div>
    <div class="subsection reveal1">
      <div class="h-title-4">Free Online Consultation</div>
      <div class="subsection-content">
        <img src="/media/wysiwyg/WLImage/audience-svgrepo-com.png" alt="Free Online Consultation">
        <p>Our clinicians will assess your consultation to ensure your health and safety is at the heart of your treatment plan. </p>
      </div>
    </div>
    <div class="subsection reveal1">
      <div class="h-title-4">Discreet & Speedy Delivery</div>
      <div class="subsection-content">
        <img src="/media/wysiwyg/WLImage/delivery-truck.png" alt="Discreet & Speedy Delivery">
        <p>Once approved, your medicine is shipped using 24-hour delivery. All our orders are dispatched in our plain and discreet packaging.</p>
      </div>
    </div>
    <div class="subsection reveal1">
      <div class="h-title-4">Continuous Care</div>
      <div class="subsection-content last">
        <img src="/media/wysiwyg/WLImage/continuous-care.png" alt="Continuous Care">
        <p>Throughout the program, our clinicians and coaches will be by your side to ensure you experience minimal side effects, find the perfect dosage for your needs, and address any questions you may have. </p>
      </div>
    </div>
    <div class="subsection reveal1">
      <div class="h-title-4">Pause Treatment Anytime</div>
      <div class="subsection-content last last2">
        <img src="/media/wysiwyg/WLImage/cancel-anytime.png" alt="Cancel anytime">
        <p>Whether you experience side effects you'd like to address or simply need a break, we empower you to take control of your journey.  We'll pick things back up when you're ready.</p>
      </div>
    </div>
  </div>
</div>
