<?php
use Mirasvit\Core\Service\CspService;
/** @var $block MSP\ReCaptcha\Block\Frontend\ReCaptcha */
$nonce = CspService::getNonce();
?>
<?php
$scopeId = $block->getData('scope_id') ?: 'msp-recaptcha';
?>
<div class="field-recaptcha" id="<?= $block->escapeHtml($scopeId); ?>-container" data-bind="scope:'<?= $block->escapeHtml($scopeId); ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init" <?php if ($nonce): ?> nonce="<?= $block->escapeHtml($nonce) ?>"<?php endif; ?>>
{
    "#<?= $block->escapeHtml($scopeId); ?>-container": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
    }
}
</script>
