<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<!-- data-mage-init='{"toggleAdvanced": {"toggleContainers": "#<?= $block->escapeHtmlAttr($block->getBlockCss()) ?>", "selectorsToggleClass": "active"}}'> -->
<div class="myaccount-menu">
      <input id="tab-r1" type="checkbox" name="tabr">
      <label for="tab-r1">My Account</label>
      <div class="tab-content">
<div class="block <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>">
    <div class="title <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>-title">
        <strong>
            <?php echo __('My Account'); ?>
        </strong>
    </div>
    <div class="content <?= $block->escapeHtmlAttr($block->getBlockCss()) ?>-content"
         id="<?= $block->escapeHtmlAttr($block->getBlockCss()) ?>">
        <?= $block->getChildHtml() ?>
    </div>
</div>

</div>
    </div>
