<!--  HTML GO HERE : MEET OUR TEAM  -->
<div class="meet-the-team meet-our-team-sec">
    <h1>Meet our team</h1>
    <div class="row">
        <div class="column meet-our-team-list" onclick="openModal();currentSlide(1)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/BOO-PROFILE-PIC.jpg" alt="Bhupinder (Boo) Dhaliwal" />
            </div>
            <h3>Bhupinder (Boo) Dhaliwal</h3>
            <h5>GPhC 2050963</h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>
        

        <div class="column meet-our-team-list" onclick="openModal();currentSlide(2)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/JAMES-PROFILE-PIC.jpg" alt="James Batson" />
            </div>
            <h3>James Batson</h3>
            <h5></h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>

        <div class="column meet-our-team-list last" onclick="openModal();currentSlide(3)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/JEN-PROFILE-PIC.jpg" alt="Jenomi Thuduwage" />
            </div>
            <h3>Jenomi Thuduwage</h3>
            <h5></h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>

        <div class="column meet-our-team-list" onclick="openModal();currentSlide(4)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/TAM-PROFILE-PIC.jpg" alt="Tamana Panesar" />
            </div>
            <h3>Tamana Panesar</h3>
            <h5></h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>

        <div class="column meet-our-team-list" onclick="openModal();currentSlide(5)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/ayesha.png" alt="Ayesha Patel" />
            </div>
            <h3>Ayesha Patel</h3>
           <h5>GPhC 2079407</h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>

        <div class="column meet-our-team-list last" onclick="openModal();currentSlide(6)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/HARMY-PROFILE-PIC.jpg" alt="Harminder ‘Harmy’ Kaur" />
            </div>
            <h3>Harminder ‘Harmy’ Kaur</h3>
            <h5>GPhC 2061107</h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>


        <div class="column meet-our-team-list" onclick="openModal();currentSlide(7)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/WLImage/gurdev-sehmi-img.jpg" alt="Gurdev Sehmi" />
            </div>
            <h3>Gurdev Sehmi</h3>
            <h5>GPhC 2050925</h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>

        <div class="column meet-our-team-list" onclick="openModal();currentSlide(8)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Manesha Thuduwage" />
            </div>
            <h3>Manesha Thuduwage</h3>
            <!-- <h5>Bsc.Pharm,PgDipIP, MRPharmS</h5> -->
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>

        <div class="column meet-our-team-list last" onclick="openModal();currentSlide(9)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Keshav ‘Kesh’ Sharma" />
            </div>
            <h3>Keshav ‘Kesh’ Sharma</h3>
            <h5>GPhC 2076168</h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>
 

        <div class="column meet-our-team-list" onclick="openModal();currentSlide(12)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Amardeep Sehmi" />
            </div>
            <h3>Amardeep Sehmi</h3>
            <h5>GPhC 2077030</h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>

        <div class="column meet-our-team-list" onclick="openModal();currentSlide(13)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Hardeep Sehmi" />
            </div>
            <h3>Hardeep Sehmi</h3>
            <h5>GPhC 2060875</h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>

        <div class="column meet-our-team-list" onclick="openModal();currentSlide(14)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Bez Hasanyan" />
            </div>
            <h3>Bez Hasanyan</h3>
            <h5>GPhC 2203291</h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>

        <div class="column meet-our-team-list last" onclick="openModal();currentSlide(15)">
            <div class="bio-img">
                <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Farook Ahmed" />
            </div>
            <h3>Farook Ahmed</h3>
            <h5>GPhC 2050941</h5>
            <p class="view-details-link"><a href="#" onclick="event.preventDefault();">View details</a></p>
        </div>

        
    </div>

    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close cursor" onclick="closeModal()"><img src="/pub/media/wysiwyg/close-icon-p.png" /></span>

            <div class="mySlides">
                <div class="numbertext">1 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/BOO-PROFILE-PIC.jpg" alt="Bhupinder (Boo) Dhaliwal" />
                </div>
                <div class="bio-details">
                    <h3>Bhupinder (Boo) Dhaliwal</h3>
                    <h4>GPhC 2050963</h4>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                            Boo's journey in pharmacy began with a strong foundation. He graduated with a degree in pharmacy from Aston University in 1999, followed by achieving registration as a pharmacist with the General Pharmaceutical Council. Fuelled by a desire to make a tangible impact on people's health, he didn't waste time acquiring his first independent community pharmacy. 
                        </p>

                        <p>
                            This marked the beginning of a successful venture. Today, Boo, alongside his partners, manages over 20 Pharmacies across England. This thriving network serves as a testament to his dedication to delivering exceptional in-person care to communities nationwide. 
                        </p>

                        <p>
                            Always one to embrace innovation, Boo recognised the potential of the digital age to further improve healthcare accessibility. This foresight led to the creation of Pharmacy Planet, an online pharmacy built upon the same principles of trust and expertise that have always defined his approach. 
                        </p>

                        <p>
                            While medications are his professional focus, Boo's commitment to well-being extends beyond the pharmacy counter. He prioritises a healthy lifestyle, balancing work with gym sessions and enjoying rounds of golf. This active approach reflects the holistic view he strives to embody in his work. 
                        </p>

                        <p>
                            Boo's extensive experience in both traditional and online pharmacy management allows him to lead the Pharmacy Planet team with a unique perspective. His leadership ensures patients receive consistent, high-quality care.
                        </p>
                    </div>
                </div>
            </div>


            <div class="mySlides">
                <div class="numbertext">2 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/JAMES-PROFILE-PIC.jpg" alt="James Batson" />
                </div>
                <div class="bio-details">
                    <h3>James Batson</h3>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                            James's passion for pharmacy blossomed early, taking root during his teenage years working in a small regional Australian pharmacy. These formative experiences instilled in him a profound understanding of the essence of patient care within the pharmacy setting. This early exposure wasn't a fleeting interest; it ignited a lifelong dedication that fuelled James's pursuit of extensive experience across diverse pharmacy environments.
                        </p>

                        <p>
                            His distinguished career stretches over decades, where he meticulously navigated the intricacies of retail, hospital, and community pharmacy settings. This breadth of experience has transformed him into a highly regarded authority figure. James possesses an unparalleled understanding of the multifaceted needs patients face and the distinct ways pharmacies can cater to them. 
                        </p>

                        <p>
                            Today, James leverages his vast knowledge and experience to serve as the central conductor of Pharmacy Planet's complex operations. He coordinates all aspects of the company, ensuring it runs like a well-oiled machine. Under his masterful leadership, Pharmacy Planet has earned a reputation for delivering exceptional service. This exceptional service is built upon a deep understanding of the nuances of pharmaceutical care, ensuring patients receive the precise level of attention and support they deserve. 
                        </p>
                    </div>
                </div>
            </div>


            <div class="mySlides">
                <div class="numbertext">3 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/JEN-PROFILE-PIC.jpg" alt="Jenomi Thuduwage" />
                </div>
                <div class="bio-details">
                    <h3>Jenomi Thuduwage</h3>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                            Jenomi has been with Pharmacy Planet since its pioneering days. She began with Pharmacy Planet as an operational assistant, where she meticulously prepared medications for patients and ensured their orders were packaged with the utmost care. This hands-on experience instilled in her an intimate understanding of the intricate processes required to safely supply medicine. 
                        </p>
                        <p>
                            Jenomi's dedication and talent didn't go unnoticed, and over time, her expertise and commitment to excellence propelled her through the ranks. Today, she leads Pharmacy Planet's customer service team, ensuring patients receive exceptional care and clear communication throughout their experience. Her deep understanding of operations, coupled with her unwavering focus on customer satisfaction, makes her an invaluable asset. Jenomi's leadership also extends to the weight loss clinic, where she plays a crucial role in its day-to-day operations, guaranteeing a seamless and supportive experience for patients on their wellness journeys. 
                        </p>
                    </div>
                </div>
            </div>



            <div class="mySlides">
                <div class="numbertext">4 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/TAM-PROFILE-PIC.jpg" alt="Tamana Panesar" />
                </div>
                <div class="bio-details">
                    <h3>Tamana Panesar</h3>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                            Tamana's journey in pharmacy began long before joining Pharmacy Planet in 2023. Her roots lie in the heart of the community, where she honed her skills working in a local pharmacy. This experience instilled in her a deep understanding of the unique needs and challenges faced by patients daily. In 2023, Tamana brought her passion and expertise to Pharmacy Planet's customer service team. 
                        </p>
                        <p>
                           Since then, Tamana has thrived in building strong relationships with patients. Her friendly and approachable demeanour creates a trusting environment where patients feel comfortable discussing their healthcare concerns. Tamana doesn't just answer questions; she goes the extra mile to truly understand each patient's situation. This dedication has allowed her to facilitate personalised solutions for thousands of patients, ensuring they receive the support and guidance they need. Her cheery disposition and willingness to go above and beyond are not just personality traits; they're the hallmarks of a trusted advisor who genuinely cares about patient well-being. This combination of expertise, empathy, and a commitment to exceptional service has made Tamana a highly valued member of the Pharmacy Planet team, someone patients can rely on for support and navigation through their healthcare journey. 
                        </p>
                    </div>
                </div>
            </div>


            <div class="mySlides">
                <div class="numbertext">5 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/ayesha.png" alt="Ayesha Patel" />
                </div>
                <div class="bio-details">
                    <h3>Ayesha Patel</h3>
                    <h3>MPharm (Hons), IPresc</h3>
                     <h4>GPhC 2079407</h4>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                            Ayesha Patel is a highly skilled and dedicated pharmacist with extensive experience in community pharmacy management. Registered with the General Pharmaceutical Council (GPhC), she has demonstrated her commitment to patient care and clinical excellence throughout her career. Ayesha holds a Master of Pharmacy (MPharm) degree from Portsmouth University, where she developed a strong foundation in pharmaceutical science, clinical therapeutics, and patient care. Her academic achievements reflect her dedication to mastering the complexities of pharmacy, from the precise science of medicine formulation to the compassionate delivery of healthcare services.
                        </p>

                        <p>
                            Building on this strong academic foundation, Ayesha pursued further professional development by completing her qualification as an Independent Prescriber in 2018 at Keele University. This prestigious qualification has significantly enhanced her ability to provide patient-centred care, empowering her to conduct focused consultations and develop individualised care plans tailored to each patient’s unique needs. Her experience working closely with other healthcare professionals has further refined her expertise in safe, evidence-based prescribing practices, including medication reviews, chronic disease management, and optimising patient outcomes.
                        </p>

                        <p>
                           Throughout her career, Ayesha has excelled in pharmacy management, where she has consistently led teams to deliver exceptional results. Her patient-focused approach, combined with her proactive leadership style, has consistently resulted in high levels of customer satisfaction and retention. Her ability to adapt to diverse and dynamic environments ensures that patients receive the highest standard of care.
                        </p>

                        <p>
                           Ayesha is fluent in English and Gujarati, which has proven invaluable in providing clear and compassionate care to patients from various backgrounds. Her dedication to patient well-being, combined with her clinical expertise as an Independent Prescriber, makes her a valuable asset to Pharmacy Planet’s clinical team, where she continues to deliver safe, effective, and personalised healthcare.
                        </p>
                    </div>
                </div>
            </div>


            <div class="mySlides">
                    <div class="numbertext">6 / 4</div>
                    <div class="bio-info-page">
                        <img src="/pub/media/wysiwyg/HARMY-PROFILE-PIC.jpg" alt="Harminder ‘Harmy’ Kaur" />
                    </div>
                    <div class="bio-details">
                        <h3>Harminder ‘Harmy’ Kaur</h3>
                        <h4>GPhC 2061107</h4>
                        <div class="sep-line"></div>
                        <div class="bio-details-cont">
                            <p>
                              Harmy stands out as a highly experienced pharmacist with a unique blend of expertise. She is both a seasoned community pharmacist and a clinical services pharmacist. This dual qualification allows her to bridge the gap between community settings and specialised clinical care, providing a holistic understanding of patient needs. 
                            </p>

                            <p>
                                Harmy's career has been driven by a particular interest in weight loss medicine. This passion has led her to work with patients across a wide array of healthcare settings, from community pharmacies to specialised clinics.This diverse experience has equipped her with an in-depth understanding of the challenges and opportunities associated with weight management.Moreover, it has fuelled her dedication to developing and implementing innovative new clinical and patient care services.Harmy is a recognised expert in creating programmes that empower patients on their weight loss journeys. 
                            </p>

                            <p>
                                Harmy brings her wealth of experience and innovative spirit to Pharmacy Planet's weight loss clinic. She leverages her clinical services expertise to provide patients with personalised guidance and support.Through her insightful consultations and advice, Harmy empowers patients to make informed decisions and achieve their weight loss goals.Her dedication fosters a trusting environment where patients feel comfortable discussing their concerns and receive the comprehensive support they deserve. 
                            </p>
                        </div>
                    </div>
                </div>


                <div class="mySlides">
                <div class="numbertext">7 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/WLImage/gurdev-sehmi-img.jpg" alt="Gurdev Sehmi" />
                </div>

                <div class="bio-details">
                    <h3>Gurdev Sehmi</h3>
                    <h4>GPhC 2050925</h4>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                            Gurdev's journey in pharmacy began with academic excellence. He graduated in 1999 from Aston University, laying a strong foundation for his future success. Following graduation, Gurdev embarked on a rewarding career path as a community pharmacist. For decades, he has diligently served patients, fostering a deep understanding of their needs and the vital role community pharmacies play in their well-being. This wealth of experience has positioned Gurdev as a respected leader within the pharmacy community. 
                        </p>
                        <p>
                            Gurdev's leadership extends far beyond his practice. He has drawn upon his experience to oversee the operations of the dozens of community pharmacies belonging to the Pharmacy group. This impressive network is a testament to his expertise and his dedication to fostering excellence within the industry. Gurdev's leadership has undoubtedly played a significant role in shaping the success of these pharmacies and ensuring they deliver exceptional patient care. 
                        </p>

                        <p>
                            Gurdev's commitment to the profession extends beyond managing pharmacies.  At Pharmacy Planet, he serves as the superintendent pharmacist. In this pivotal role, Gurdev spearheads the company's professional governance and carefully oversees all aspects of Pharmacy Planet's practice, ensuring strict adherence to the high standards set by professional regulatory bodies. Gurdev's unwavering commitment safeguards patient safety and fosters trust within the healthcare community. His leadership ensures Pharmacy Planet remains at the forefront of ethical and compliant practices. 
                        </p>

                        <p>
                            Gurdev's dedication to patient well-being is further amplified by his qualification as a Pharmacist Independent Prescriber. This advanced qualification allows him to take on a more prominent role in patient care, directly contributing to improved health outcomes. Gurdev's ability to prescribe medications independently empowers him to work collaboratively with other healthcare professionals, streamlining the treatment process and optimising patient care. 
                        </p>
                    </div>
                </div>
            </div>


            

            <div class="mySlides">
                <div class="numbertext">8 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Manesha Thuduwage" />
                </div>
                <div class="bio-details">
                    <h3>Manesha Thuduwage</h3>
                    <!-- <h4>Bsc.Pharm,PgDipIP, MRPharmS</h4> -->
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                            Manesha is a recognised authority within Pharmacy Planet, having been with the company since its very inception. Her experience stretches back to the company's birth, where she played a pivotal role in establishing the core processes and systems that revolutionised pharmaceutical healthcare delivery. Manesha wasn't simply present at the forefront of this innovation; she was instrumental in shaping it.Her fingerprints are on the foundational elements that allow Pharmacy Planet to deliver medication in entirely new ways. 
                        </p>
                        <p>
                            Through her dedication and tenure within Pharmacy Planet, Manesha has cultivated an unparalleled understanding of pharmacy service processes.Her expertise goes beyond mere familiarity; she possesses a keen eye for improvement and a deep understanding of how new technologies can empower better patient care.Manesha recognises the immense potential of the online space to cater to the vast and diverse needs of patients.This recognition fuels her constant drive to innovate and develop creative solutions. 
                        </p>

                        <p>
                            Manesha leverages her in-depth understanding of Pharmacy Planet's inner workings to spearhead the development of the company's website and internal systems. Under her leadership, these systems continuously evolve, adapting to the ever-changing needs of both patients and the healthcare industry as a whole. Manesha's expertise ensures that Pharmacy Planet remains at the forefront of innovation, consistently implementing creative solutions to address global patient challenges. 
                        </p>
                    </div>
                </div>
            </div>

            

            
            

            

            <div class="mySlides">
                <div class="numbertext">9 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Keshav ‘Kesh’ Sharma" />
                </div>
                <div class="bio-details">
                    <h3>Keshav ‘Kesh’ Sharma</h3>
                    <h4>GPhC 2076168</h4>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                           Kesh boasts over a decade of experience as a trusted community pharmacist. Throughout his career, he has honed his expertise in both NHS and private settings, giving him a well-rounded understanding of the diverse needs patients face. This extensive experience positions him perfectly to oversee Pharmacy Planet's dispensary operations, ensuring the highest standards of accuracy and efficiency. 
                        </p>

                        <p>
                            Kesh's dedication goes beyond technical expertise. He is driven by a genuine interest in health and fitness, which aligns perfectly with Pharmacy Planet's core mission: empowering patients to achieve optimal health. This passion fuels his commitment to ensuring every patient receives the medication and guidance they need to thrive. 
                        </p>

                        <p>
                            His meticulous nature and deep understanding of regulations are invaluable assets. He meticulously oversees Pharmacy Planet's dispensary operations, guaranteeing strict adherence to all relevant guidelines. This unwavering commitment to compliance fosters a safe and trustworthy environment for both patients and staff. 
                        </p>

                        <p>
                            Kesh's extensive experience allows him to anticipate potential challenges within the dispensary and implement proactive solutions. This foresight ensures a smooth and efficient medication dispensing process, minimising delays and maximising patient satisfaction. His approachable demeanour further strengthens trust with patients, creating a comfortable space for them to ask questions and receive clear guidance. 
                        </p>
                    </div>
                </div>
            </div>

            <div class="mySlides">
                <div class="numbertext">10 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Heather Ward" />
                </div>
                <div class="bio-details">
                    <h3>Heather Ward</h3>
                    <h4>GPhC 5105186</h4>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                            Heather's dedication to pharmacy began at a young age, embarking on her career path at the promising age of 19. This early foray into the field ignited a passion that has fueled her for many years. Her extensive
                            experience encompasses a diverse range of pharmacy environments, allowing her to develop a well-rounded understanding of the intricacies involved.
                        </p>

                        <p>
                            A significant portion of Heather's career has been dedicated to working within the demanding yet crucial environment of hospital dispensaries and laboratories. These settings require meticulous attention to
                            detail and a deep understanding of safe medication handling practices. Heather's years of experience in these high-pressure environments have honed her expertise in ensuring the utmost accuracy and safety in
                            medication dispensing.
                        </p>

                        <p>
                            Heather's commitment to excellence is further underscored by her qualification as a Pharmacy Technician. This rigorous training equips her with a comprehensive knowledge base and the skills necessary to navigate
                            the complexities of pharmacy operations. As a valued member of Pharmacy Planet's dispensary team, Heather uses her expertise to facilitate the safe and accurate supply of medications to our patients. Her
                            dedication plays a vital role in ensuring patients receive the precise medication they need, fostering trust and promoting optimal health outcomes.
                        </p>
                    </div>
                </div>
            </div>

            <div class="mySlides">
                <div class="numbertext">11 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Kiloran ‘Kiki’ Clark" />
                </div>
                <div class="bio-details">
                    <h3>Kiloran ‘Kiki’ Clark</h3>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                            Kiki's journey in pharmacy is a testament to her unwavering dedication to the field. Her experience in Pharmacy spans numerous years, and ultimately lead her to become a qualified dispenser. This qualification
                            signifies her in-depth understanding of safe medication handling and dispensing procedures, ensuring patients receive the correct medication in the prescribed manner.
                        </p>

                        <p>
                            Prior to returning to pharmacy with renewed zeal, Kiki spent a significant portion of her career honing her stock management skills within the demanding world of high-end retail. These years of experience
                            instilled in her a meticulous approach to organization and inventory control, skills that are highly transferable to the world of pharmacy dispensing. Kiki's ability to manage stock efficiently translates to a
                            smoother and more streamlined medication dispensing process for Pharmacy Planet.
                        </p>

                        <p>
                            After a hiatus from pharmacy, Kiki returned to the field with a newfound passion for dispensary operations. This renewed enthusiasm fuels her commitment to ensuring the safe and accurate supply of medications at
                            Pharmacy Planet. Her dedication plays a vital role in fostering trust with patients and guaranteeing they receive their medications without delays or errors. Kiki's combined experience and renewed zeal make her a
                            valuable asset to our dispensary team.
                        </p>
                    </div>
                </div>
            </div>

            <div class="mySlides">
                <div class="numbertext">12 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Amardeep Sehmi" />
                </div>
                <div class="bio-details">
                    <h3>Amardeep Sehmi</h3>
                    <h4>GPhC 2077030</h4>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                            Amardeep is a highly respected pharmacist with extensive experience honed within the demanding environment of hospital pharmacy. Amardeep graduated with a master's degree in pharmacy from Medway School of Pharmacy in 2010, solidifying her foundation in pharmaceutical knowledge. Her dedication to continuous learning is further evidenced by her diploma in clinical pharmacy in 2013 from Keele University. These years of experience have developed her clinical knowledge base thoroughly, equipping her with a deep understanding of complex medical conditions and medication interactions. This expertise positions her as a valuable asset within the healthcare field, particularly in situations requiring a meticulous and knowledgeable approach. 
                        </p>

                        <p>
                           Amardeep's dedication to patient well-being is most evident in her experience as an ICU pharmacist. In this critical setting, she plays a vital role in delivering effective patient outcomes for some of the sickest patients. Her keen eye for detail, combined with her in-depth clinical knowledge, allows her to optimise medication regimens and ensure patients receive the precise treatment they need to recover. Amardeep's unwavering commitment contributes significantly to improved patient outcomes within the ICU. 
                        </p>

                        <p>
                            AAmardeep's qualifications extend beyond her impressive hospital pharmacy experience.  Having achieved her qualification as a Pharmacist Independent Prescriber from the University of Herefordshire in 2022, this additional expertise empowers her to utilise her extensive clinical knowledge and experience to directly benefit Pharmacy Planet's patients. Amardeep's ability to independently prescribe medications allows for a more personalised approach to care, ensuring patients receive the most effective treatment plans possible. 
                        </p>
                    </div>
                </div>
            </div>

            <div class="mySlides">
                <div class="numbertext">13 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Hardeep Sehmi" />
                </div>
                <div class="bio-details">
                    <h3>Hardeep Sehmi</h3>
                    <h4>GPhC 2060875</h4>
                    <div class="sep-line"></div>
                    <div class="bio-details-cont">
                        <p>
                           Hardeep boasts an impressive two-decade career as an accomplished community pharmacist. He achieved his qualification as a pharmacist by graduating with a Master of Pharmacy from the London School of Pharmacy. This extensive experience has instilled in him a deep understanding of the intricacies of community pharmacy operations and the vital role it plays in patient well-being. Over the years, Hardeep has cultivated a reputation for exceptional service and has become a trusted resource for patients within his community. 
                        </p>

                        <p>
                            Hardeep's dedication extends beyond a general understanding of pharmacy practice. He has developed a particular interest and expertise in conditions affecting the ear, nose, and throat (ENT). This focused knowledge allows him to provide patients with more in-depth consultations and guidance on these prevalent concerns. Whether it's recommending over-the-counter medications or offering valuable insights, Hardeep's expertise empowers patients to manage their health effectively. 
                        </p>

                        <p>
                           Hardeep's commitment to patient well-being and dedication to continuous learning is further exemplified by his independent prescriber qualification from the University of Leicester in 2023. This additional expertise empowers him to utilise his extensive knowledge and experience to directly benefit his patients. This advanced qualification empowers him to take a more prominent role in patient care, particularly in situations involving ENT concerns. Hardeep can work collaboratively with all kinds of healthcare professionals to ensure patients receive the medications they need promptly and efficiently, minimising delays and fostering a smoother healthcare experience. 
                        </p>
                    </div>
                </div>
            </div>

            <div class="mySlides">
                <div class="numbertext">14 / 4</div>
                <div class="bio-info-page">
                    <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Bez Hasanyan" />
                </div>
                  <div class="bio-details">
                      <h3>Bez Hasanyan</h3>
                      <h4>GPhC 2203291</h4>
                      <div class="sep-line"></div>
                      <div class="bio-details-cont">
                          <p>
                             Bez Hasnyan is a respected clinical pharmacist with a deep commitment to patient-centred care. He holds a Master of Pharmacy degree from the Medway School of Pharmacy, graduating in 2016. Bez's dedication to ongoing learning and professional development is further evidenced by his achievement of the Independent Prescribing qualification in 2019.This additional expertise empowers him to take on a more prominent role in patient care, directly contributing to improved health outcomes. 
                          </p>
                          <p>
                              Bez's experience extends across a wide range of clinical specialities and disease processes. This breadth of knowledge allows him to approach patient cases with a comprehensive perspective, considering all potential factors that may be impacting their health. His ability to navigate complex medical situations fosters trust with patients and ensures they receive the most effective treatment plans possible.
                          </p>

                          <p>
                              Bez's qualification as a pharmacist independent prescriber positions him as a valuable asset to the Pharmacy Planet clinical team. This expertise allows him to leverage his clinical insights and perspectives to directly benefit patients. He can work collaboratively with doctors to ensure patients receive the medications they need promptly and efficiently, minimising delays and fostering a smoother healthcare experience. Bez's commitment to collaboration and his focus on patient-centred care make him a trusted advisor and a key player in optimising patient outcomes at Pharmacy Planet. 
                          </p>
                      </div>
                  </div>
            </div>

                <div class="mySlides">
                    <div class="numbertext">15 / 4</div>
                    <div class="bio-info-page">
                        <img src="/pub/media/wysiwyg/Unknown_person.jpg" alt="Farook Ahmed" />
                    </div>
                    <div class="bio-details">
                        <h3>Farook Ahmed</h3>
                        <h4>GPhC 2050941</h4>
                        <div class="sep-line"></div>
                        <div class="bio-details-cont">
                            <p>
                                Farook's journey in pharmacy began with a strong academic foundation. He graduated with a Bachelor of Pharmacy from the esteemed Aston University in 1999. This rigorous programme equipped him with the in-depth knowledge and practical skills necessary to excel in the demanding field of pharmacy. 
                            </p>

                            <p>
                                Farook's passion for patient care has fuelled his extensive career within the community pharmacy sector. For decades, he has diligently served a wide range of patients across the country.This wealth of experience has instilled in him a deep understanding of the diverse needs and challenges faced by patients, allowing him to provide exceptional care and guidance. 
                            </p>

                            <p>
                                Today, Farook draws upon his vast experience to play a pivotal role in Pharmacy Planet's operations. He is heavily involved in pharmaceutical procurement and supply chain management, working tirelessly to ensure a steady flow of medicine into the dispensary. Farook's meticulous approach and in-depth understanding of the complexities involved in supply chain management minimise disruptions and delays. This unwavering commitment guarantees patients have timely access to the medications they need to manage their health effectively
                            </p>

                            <p>
                                Farook's dedication extends far beyond technical expertise. His years of experience as a community pharmacist have fostered a deep empathy for patients' well-being. This translates into a commitment to ensuring a smooth and efficient medication supply chain, ultimately empowering patients to focus on their health journey without unnecessary hurdles. Farook's expertise and dedication make him a trusted resource and a pillar of reliability within Pharmacy Planet. 
                            </p>
                        </div>
                    </div>
                </div>

                

                 
            </div>
        </div>
    </div>
 
</div>

<script>
    function openModal() {
        document.getElementById("myModal").style.display = "block";
        document.body.className += "home";
    }

    function closeModal() {
        document.getElementById("myModal").style.display = "none";
        document.body.className = document.body.className.replace("home", "");
    }

    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides((slideIndex += n));
    }

    function currentSlide(n) {
        showSlides((slideIndex = n));
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("demo");
        var captionText = document.getElementById("caption");
        if (n > slides.length) {
            slideIndex = 1;
        }
        if (n < 1) {
            slideIndex = slides.length;
        }
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].className += " active";
        captionText.innerHTML = dots[slideIndex - 1].alt;
    }
</script>
 