<style> 
	@import url('https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap');
	@import url('https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap');
html {
	scroll-behavior: smooth;
}

body {
	font-family: 'Lato', sans-serif !important;
	background-color: transparent !important;
	max-width: 100% !important;
}

body.category-weight-loss.catalog-category-view {
	background: transparent !important;
}

span.wl-offer {
	line-height: 38px;
}

.header.content {
	padding: 0px !important;
}

.active:after {
	display: none;
}

.widget.block.block-static-block.mf-initial {
}

.video-section {
	margin-bottom: 78px;
}

.content-heading .title {
	font: normal normal normal 32px/36px Lato;
	letter-spacing: 0px;
	color: #101010;
	text-align: center;
	line-height: 36px;
	font-weight: 300;
}

.owl-carousel .owl-item .banner-item {
	margin: 0 10px;
}

.owl-carousel .owl-item .banner-image {
	padding: 0;
	margin: 0;
	max-width: 100%;
}

.owl-carousel .owl-item .banner-image img {
	height: 270px;
}

.custom-slider {
	margin-bottom: 25px;
}

.custom_content .subsection-content2 {
	text-align: left;
	margin-top: 148px;
	margin-left: -12px;
}

.subsection-content2 .h-title-6 {
	font: normal normal 900 15px Lato;
	letter-spacing: 0px;
}

.subsection-content2 p {
	font: normal normal normal 13px/20px Lato;
	letter-spacing: 0px;
}

.h-banner-btn {
	text-align: center;
	margin-bottom: 30px;
}

.how-it-works-section.mf-initial {
	border-top: 1px solid #ebebeb;
}

.owl-theme.owl-carousel .owl-controls .owl-dot span {
	background: #96D9F1;
	margin: 5px 4px;
}

.owl-theme.owl-carousel .owl-controls .owl-dot.active span {
	background: #074A5B;
}

.how-it-works-section {
	padding: 18px 0 45px 0;
}

@media screen and (max-width: 767px) {
	html, body {
		overflow-x: hidden;
	}

	body {
		width: 100%;
	}

	header .header.content {
		padding-top: 0px !important;
	}

	span.wl-offer {
		font: normal normal normal 12px / 18px Lato;
		padding: 12px;
		letter-spacing: 0.22px;
		color: #FFFFFF;
		text-transform: uppercase;
		text-align: center;
		justify-content: center;
		display: flex;
	}

	.minicart-wrapper.active {
		position: relative !important;
		top: 28px !important;
		right: -34px !important;
		margin-top: 0px;
	}

	.timeframe-subheading ul {
		display: none;
	}

	.block-static-block.widget {
		margin-bottom: 0px;
	}

	.rating-img {
		display: none !important;
	}

	.review-slide {
		margin: 3px 5% 10px 5% !important;
	}

	.work-c p {
		margin: 0 0 10px 10px;
	}

	.owl-carousel .owl-item .banner-image img {
		height: auto;
	}

	.owl-theme .owl-dots {
		bottom: -20px;
	}

	.h-banner-content .banner-left-c p {
		display: none;
	}

	.review-slide .dots:checked {
		background-color: #074A5B !important;
		outline-color: #074A5B !important;
	}

	.how-it-works-section .Works-1 img {
		margin-left: 15px;
		float: left;
	}

	.google-review-section.mobile {
		width: 100%;
	}
}

@media only screen and (min-width:992px) and (max-width:1024px) {
	.mf-initial .minicart-wrapper a {
		margin-right: 0px;
	}

	.h-banner-btn {
		margin-top: 20px;
	}

	.work-c p {
		width: 117% !important;
	}
}

@media only screen and (min-width:768px) and (max-width:991px) {
	.mf-initial .minicart-wrapper a {
		margin-right: 11px;
	}

	.included-section {
		padding-left: 20px !important;
	}

	.category-weight-loss.catalog-category-view .slider-wrapper.desk-review-slider .slide-arrow {
		top: 15% !important;
	}
}

@media screen and (min-width: 768px) {
	.homepage-banner-new-mobile {
		display: none;
	}

	.review-content-mobile {
		display: none;
	}

	.owl-theme .owl-dots {
		bottom: -24px;
	}

	.owl-theme.owl-carousel .owl-controls .owl-dot.active span {
	}
}

@media screen and (min-width: 768px) {
	.header.content {
		text-align: center;
	}

	.cms-index-index .page-header {
		position: relative !important;
	}

	.homepage-banner-new {
		width: 100%;
		float: left;
		padding: 0;
		margin: 0;
		background: url(/app/design/frontend/Custom/luma_weightloss/Magento_Theme/templates/images/main-banner.jpg) 90% 16% no-repeat;
		height: 675px;
		background-attachment: fixed;
		background-size: cover;
	}

	.banner-left-c {
		width: 295px;
		float: left;
	}

	.banner-right-c {
		width: 275px;
		float: right;
		margin-top: 25px;
	}

	.banner-icon {
		height: 43px;
	}

	.rating-header {
		width: auto;
		float: left;
		position: absolute;
		text-align: left;
		z-index: 999999;
		justify-content: center;
		align-items: center;
	}

	.rating-header img {
		float: left;
	}

	.rating-header p {
		float: left;
		margin-left: 10px;
		margin-top: 8px;
	}

	.offer.mf-initial {
		width: auto;
		height: 42px;
	}
}

.h-banner-content-sec {
	width: 660px;
	float: right;
	padding: 0;
	margin: 0;
}

.review-content {
	width: 680px;
	float: left;
	padding: 0;
	margin: 27px 0 0 0;
}

.review-content img {
	float: left;
	margin-right: 12px;
	margin-bottom: 10px;
}

.h-banner-content {
	width: 600px;
	float: right;
	padding: 30px;
	margin: 0;
	background: #FEECEC;
	border-radius: 8px;
	margin-top: 55px;
}

.h-banner-content h2 {
	width: auto;
	float: left;
	font-family: 'Lato', sans-serif;
	font-size: 42px;
	color: #000 !important;
	line-height: 46px;
	font-weight: 300 !important;
	text-align: left;
	padding: 0 0 10px 0;
	margin: 0;
}

.h-banner-content p {
	width: 100%;
	float: left;
	font-family: 'Lato', sans-serif;
	font-size: 15px;
	color: #000 !important;
	line-height: 20px;
	font-weight: 400 !important;
	text-align: center;
	padding: 0 0 15px 0;
	margin: 0;
}

.h-banner-content .banner-left-c p {
	text-align: left !important;
}

.h-banner-btn {
	width: 100%;
	float: left;
}

.h-banner-btn a, .h-banner-btn .start-const-btn button, .banner-left-c .start-const-btn button {
	width: 280px;
	display: inline-block;
	text-align: center;
	background: #EC3237;
	font-size: 13px;
	color: #fff;
	font-family: 'Lato', sans-serif;
	line-height: 55px;
	padding: 0 0px;
	font-weight: 400;
	border-radius: 30px;
	letter-spacing: 0.26px;
	height: auto;
	text-transform: uppercase;
}

.h-banner-btn a:hover, .h-banner-btn .start-const-btn button:hover, .banner-left-c .start-const-btn button:hover {
	background: #53CAF5 !important;
}

.how-it-works-section .h-banner-btn a {
	width: 285px !important;
	line-height: 66px !important;
	border-radius: 32px !important;
}

.banner-right-c ul {
	padding: 0;
	margin: 0;
}

.banner-right-c ul li {
	width: 135px;
	float: left;
	text-align: center;
	list-style-type: none;
	margin: 0;
	padding-bottom: 10px;
}

.banner-right-c ul li:nth-child(1) {
	border-right: 1px solid #eec9c9;
	border-bottom: 1px solid #eec9c9;
}

.banner-right-c ul li:nth-child(2) {
	border-bottom: 1px solid #eec9c9;
}

.banner-right-c ul li:nth-child(3) {
	border-right: 1px solid #eec9c9;
	padding-top: 25px;
}

.banner-right-c ul li:nth-child(4) {
	padding-top: 25px;
}

.weight-loss-journey {
	width: 100%;
	float: left;
	padding: 0;
	margin: 87px 0 86px 0;
	text-align: center;
}

.weight-loss-journey h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 45px 0;
	text-align: center;
	font-size: 38px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 46px;
	font-weight: 300;
}

.weight-loss-journey .timeframe-subheading {
	width: 345px;
	float: none;
	display: inline-block;
	vertical-align: top;
}

.timeframe-subheading h3 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 7px 0;
	font-size: 20px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 40px;
	font-weight: 700;
	text-align: left;
}

.timeframe-subheading h4 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 16px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 20px;
	font-weight: 700;
	text-align: left;
}

.timeframe-subheading ul {
	padding: 0 0 0 19px;
	margin: 0;
	float: left;
	width: 90%;
}

.timeframe-subheading ul li {
	padding: 0;
	margin: 0 0 5px 0;
	font-size: 13px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 17px;
	font-weight: 400;
	text-align: left;
}

.weight-loss1 {
	background: url(/pub/media/wysiwyg/WLImage/weight1.png) left top no-repeat;
}

.weight-loss2 {
	background: url(/pub/media/wysiwyg/WLImage/weight2.png) left top no-repeat;
}

.weight-loss3 {
	background: url(/pub/media/wysiwyg/WLImage/weight3.png) left top no-repeat;
}

.weight-loss-content {
	width: 94%;
	float: left;
	padding: 0 0 0 75px;
}

.home-testimonilas {
	width: 100%;
	display: inline-block;
	padding: 65px 0 95px 0;
	margin: 75px 0 0px 0 !important;
	background: #E7F2F4;
	text-align: center;
}

.home-testimonilas h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 30px 0;
	font-size: 38px;
	color: #101010;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
}

.home-testimonilas .google-review-container {
	width: 100%;
	float: left;
}

.how-it-works-section {
	width: 100%;
	display: inline-block;
	padding: 80px 0 100px 0;
	text-align: center;
}

.how-it-works-section h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
	color: #101010;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
	text-align: center;
}

.Works-1 {
	width: 334px;
	float: none;
	display: inline-block;
	vertical-align: top;
	position: relative;
	margin: 0 20px;
	margin-bottom: 34px;
}

.work-c {
	position: absolute;
	top: 32px;
	left: 129px;
}

.work-c h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 20px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 25px;
	font-weight: 700;
	text-align: left;
	letter-spacing: 0.5px;
	text-transform: uppercase;
}

.work-c p {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 13px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 18px;
	font-weight: 400;
	text-align: left;
}

.treatment-options {
	width: 100%;
	float: left;
	padding: 65px 0 87px 0;
	margin: 0;
	background: #96D8F0;
}

.treatment-options h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 35px 0;
	font-size: 38px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
	text-align: center;
}

.home-treatment-block {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0;
	text-align: center;
}

.home_block_1 {
	width: 298px;
	float: none;
	display: inline-block;
	margin: 0 0px;
	border-radius: 8px;
	vertical-align: top;
	background: #fff;
	padding: 40px 25px 0px 25px;
}

.home_block_img {
	height: 260px;
	overflow-y: hidden;
	margin-bottom: 30px;
}

.home_block_1 h3 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 20px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 30px;
	font-weight: 900;
	text-align: left;
}

.home_block_1 h3 a {
	color: #000;
}

.home_block_1 p {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 22px 0;
	font-size: 14px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 20px;
	font-weight: 400;
	text-align: left;
}

.home_block_1 .h-banner-btn a, .home_block_1 .h-banner-btn button {
	width: 145px;
	text-transform: uppercase;
	float: left;
}

.home_block_1 .h-banner-btn a, .home_block_1 .h-banner-btn button {
	width: 145px;
	display: inline-block;
	text-align: center;
	background: #EC3237;
	font-size: 13px;
	color: #fff;
	font-family: 'Lato', sans-serif;
	line-height: 55px;
	padding: 0 0px;
	font-weight: 400;
	border-radius: 30px;
	letter-spacing: 0.26px;
	border: 0;
	transition: all .35s;
}

.home_block_1 .h-banner-btn a:hover, .home_block_1 .h-banner-btn button:hover {
	background: #53CAF5 !important;
}

.included-section {
	width: 100%;
	float: left;
	padding: 75px 0 45px 0;
	margin: 0;
}

.included-section h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 35px 0;
	font-size: 38px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
	text-align: center;
}

.subsection {
	width: 50%;
	float: left;
}

.subsection h3 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 15px 0;
	font-size: 20px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 30px;
	font-weight: 900;
	text-align: left;
}

.subsection p {
	width: 80%;
	float: left;
	padding: 0;
	margin: 0 0 0px 15px;
	font-size: 15px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 22px;
	font-weight: 400;
	text-align: left;
}

.subsection-content {
	width: auto;
	float: left;
	margin-right: 30px;
	padding: 0 0 11px 0;
	margin-bottom: 32px;
	border-bottom: 1px solid #D3DEE1;
	min-height: 101px;
}

.subsection-content.last {
	border-bottom: 0 !important;
}

.subsection-content img {
	float: left;
}

.video-section {
	width: 100%;
	float: left;
	padding: 76px 0 46px 0;
	background: #E7F2F4;
	text-align: center;
}

.video-section h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 50px 0;
	font-size: 38px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
	text-align: center;
}

.video-section .subsection {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0;
	text-align: center;
}

.subsection-2 {
	width: 1028px;
	margin-left: auto;
	margin-right: auto;
	margin-top: 65px;
	display: inline-block;
}

.subsection-2 h3 {
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 55px;
	font-weight: 300;
	text-align: left;
}

.subsection-2 h3 strong {
	font-weight: 700;
}

.subsection-2 .h-banner-btn {
	width: auto;
	float: right;
}

.subsection-2 .h-banner-btn a {
	width: 220px !important;
}

.meet-team-section {
	width: 100%;
	float: left;
	padding: 80px 0;
	margin: 0;
	text-align: center;
}

.meet-team-section h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 30px 0;
	font-size: 38px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
	text-align: center;
}

.meet-team-section h3 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 5px 0;
	font-size: 20px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 30px;
	font-weight: 900;
	text-align: left;
}

.meet-team-section p {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 0px 0px;
	font-size: 14px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 20px;
	font-weight: 400;
	text-align: left;
}

.meet-team-section .team-1 {
	width: 332px;
	float: none;
	margin: 0 5px;
	display: inline-block;
}

.meet-team-section .subsection-content2 {
	margin-top: 175px;
	padding-left: 10px;
	padding-right: 10px;
}

button.plus-button {
	background: #FFFFFF 0% 0% no-repeat padding-box;
	display: inline-block;
	float: right;
	margin-top: -28px;
	margin-right: -34px;
	padding: 7px 12px;
	width: 40px;
	height: 40px;
	border: none;
	border-radius: 50%;
	font-size: 24px;
	text-align: center;
	cursor: pointer;
}

.meet-team-section2 {
	width: 100%;
	float: left;
	padding: 65px 0;
	margin: 66px 0px 0px 0px;
	background: #E7F2F4;
	text-align: center;
}

.team-2 {
	width: 321px;
	float: none;
	display: inline-block;
	background: #fff;
	margin: 0 12px;
	border-radius: 8px;
	padding: 44px 34px;
}

.team-2 img {
	float: left;
}

.team-2 h3 {
	padding: 0;
	margin: 0 0 0 20px;
	font-size: 18px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 22px;
	font-weight: 700;
	text-align: left;
	float: left;
	width: 175px;
}

.stories-section {
	width: 100%;
	float: left;
	padding: 65px 0;
	margin: 0;
	text-align: center;
}

.stories-section h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 30px 0;
	font-size: 38px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
	text-align: center;
}

.story-1 {
	width: 332px;
	float: none;
	display: inline-block;
	vertical-align: top;
	margin: 0 5px;
}

.story-1 .subsection-content {
	width: 100%;
	float: left;
	padding: 0;
	margin: 45px 0 0 0;
	border-bottom: 0 !important;
}

.story-1 img {
	border-radius: 8px;
}

.story-1 .subsection-content {
	position: relative;
}

.story-1 .subsection-content:before {
	width: 48px;
	height: 40px;
	display: inline-block;
	content: " " !important;
	background: url(/pub/media/wysiwyg/WLImage/quote-icon.png) 0 0 no-repeat;
	position: absolute;
	top: -70px;
	left: 0;
}

.story-1 .subsection-content p {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 13px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 20px;
	font-weight: 400;
	text-align: left;
}

.story-1 .subsection-content p strong {
	font-weight: 700;
}

.story-1 .subsection-content img {
	float: left;
	margin-bottom: 10px;
	border-radius: 0;
}

.faq-section {
	width: 100%;
	float: left;
	padding: 84px 0 104px 0;
	margin: 0;
	background: #E7F2F4;
}

.faq-section h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
	text-align: center;
}

.faq-content {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0;
}

.faq-list p.question {
	font-size: 16px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 30px;
	font-weight: 400;
	text-align: left;
	padding: 20px 0;
}

.blogs-section {
	width: 100%;
	float: left;
	padding: 65px 0;
	margin: 0;
	text-align: center;
}

.blogs-section h2, .blogs-section h3 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
	text-align: center;
}

.blog-c, .blogs-section .post-holder {
	width: 332px;
	float: none;
	display: inline-block;
	vertical-align: top;
	margin: 0 5px;
}

.blogs-section .post-title-holder {
	height: 67px;
	width: 100%;
	overflow-y: hidden;
	padding-bottom: 0;
	float: left;
	margin-bottom: 5px;
}

.blog-img, .blogs-section .post-holder .post-ftimg-hld {
	margin-bottom: 20px;
}

.blog-img img, .blogs-section .post-holder .post-ftimg-hld img {
	border-radius: 8px;
}

.blog-c h4, .blogs-section .post-holder .post-title a {
	width: 100%;
	float: left;
	font-size: 20px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 26px;
	font-weight: 900;
	text-align: left;
	padding: 0px 0 10px 0;
	margin: 0;
}

.blogs-section .post-holder .post-text-hld {
	min-height: auto !important;
	width: 100%;
	float: left;
}

.blog-c p, .blogs-section .post-holder .post-text-hld p {
	width: 100%;
	float: left;
	font-size: 13px;
	color: #101010;
	font-family: 'Lato', sans-serif;
	line-height: 20px;
	font-weight: 400;
	text-align: left;
	padding: 0px 0 5px 0;
	margin: 0;
}

.blogs-section .post-holder .post-posed-date {
	float: left;
}

.blog-c p span, .blogs-section .post-holder .post-posed-date span {
	font-size: 11px !important;
	color: #6B6B6B !important;
	font-family: 'Lato', sans-serif;
	line-height: 20px;
	font-weight: 400 !important;
	text-align: left;
	padding: 0px 0 0px 0;
	margin: 0;
	font-style: normal !important;
}

.google-review-section {
	width: 100%;
	float: left;
	padding: 65px 0 74px 0;
	margin: 0;
	background: #E6F0F3;
	text-align: center;
}

.google-review-section h2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 30px 0;
	font-size: 38px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
	text-align: center;
}

.rating-img {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	text-align: center;
	display: inline-block;
}

.rating-img img {
	float: none;
	display: inline-block;
}

.rating-img p {
	width: auto;
	float: none;
	display: inline-block;
	vertical-align: top;
	margin-top: 4px !important;
	margin-left: 10px !important;
}

.review-list-content {
	width: 100%;
	float: left;
	padding: 0;
	margin: 50px 0 0 0;
	text-align: center;
}

.review-list {
	width: 285px;
	float: none;
	display: inline-block;
	background: #fff;
	margin: 0 8px;
	padding: 40px 28px;
	border-radius: 8px;
	text-align: left;
}

.review-list .review-img {
	margin-bottom: 10px;
}

.review-list p {
	margin-bottom: 15px;
}

.author-c img {
	float: left;
	border-radius: 50px;
}

.author-c p {
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 14px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 50px;
	font-weight: 700;
	letter-spacing: 0.31px;
}

.footer-consultation .container h3 {
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
	color: #fff;
	font-family: 'Lato', sans-serif;
	line-height: 55px;
	font-weight: 300;
	text-align: left;
	background: none !important;
}

.footer-consultation .container h3 strong {
	font-weight: 700;
}

.footer-consultation .h-banner-btn {
	width: auto;
	float: right;
}

.footer-consultation .h-banner-btn a {
	width: 146px;
	margin-left: 10px;
}

.custom-menu-ul .view-all-treatment a, .custom-menu-ul .start-const-btn button {
	font-size: 13px;
	color: #fff;
	font-family: 'Lato', sans-serif;
	line-height: 52px;
	font-weight: 400;
	letter-spacing: 0.26px;
	background: #ED3237;
	padding: 0 28px;
	box-shadow: inset 0 0px 0 0 #ffffff, inset 0 0 0 0 rgba(204, 204, 204, 0);
	border-radius: 50px;
	transition: all 0.1s;
	border: 1px solid rgba(255, 255, 255, 0.5);
	position: relative;
	display: inline-block;
}

.custom-menu-ul .start-const-btn button {
	height: 54px;
}

.custom-menu-ul .view-all-treatment a:hover, .custom-menu-ul .start-const-btn button:hover {
	background: #53CAF5;
	text-decoration: none !important;
}

.customMenu li.view-all-treatment a {
	font-size: 13px;
	color: #fff;
	font-family: 'Lato', sans-serif;
	line-height: 52px;
	font-weight: 400;
	letter-spacing: 0.26px;
	background: #ED3237;
	padding: 0 28px;
	box-shadow: inset 0 0px 0 0 #ffffff, inset 0 0 0 0 rgba(204, 204, 204, 0);
	border-radius: 50px;
	transition: all 0.1s;
	border: 1px solid rgba(255, 255, 255, 0.5);
	position: relative;
	display: inline-block;
}

.customMenu li.view-all-treatment a:hover {
	background: #53CAF5;
	text-decoration: none !important;
}

.custom-menu-ul .btn-login-signup a {
	font-size: 13px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 52px;
	font-weight: 400;
	letter-spacing: 0.26px;
	text-transform: uppercase;
}

.customMenu .custom-menu-ul {
	margin-top: 10px;
}

.testimonials-list {
	width: 285px;
	float: none;
	display: inline-block;
	background: #fff;
	margin: 0 8px;
	padding: 60px 30px;
	border-radius: 8px;
	text-align: left;
}

.testimonials-list .rating-img-1 {
	margin-bottom: 10px;
}

.testimonials-list p {
	width: auto;
	float: left;
	padding: 0 0 10px 0;
	margin: 0;
	font-size: 14px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 20px;
	font-weight: 400;
	letter-spacing: 0.31px;
}

.testimonials-list p strong {
	font-weight: 700;
}

.footer-consultation .h-banner-btn a {
	background: #fff;
	font-size: 13px;
	color: #000;
	font-family: 'Ubuntu', sans-serif;
	line-height: 56px;
	border: 0;
	padding: 0 48px;
	font-weight: 400;
	border-radius: 50px;
	text-transform: uppercase;
	display: inline-block;
	text-decoration: none;
	-webkit-transition: all 0.1s;
	-moz-transition: all 0.1s;
	-o-transition: all 0.1s;
	transition: all 0.1s;
	border: 1px solid rgba(255, 255, 255, 0.5);
	position: relative;
	width: auto;
}

.footer-consultation .h-banner-btn a:hover {
	background: #ED3237;
	color: #fff;
}

@media screen and (min-width: 768px) {
	.page-header .header.content, .breadcrumbs, .container {
		max-width: 1260px !important;
	}

	.footer-left .accordion-tab label {
		width: 150px;
	}

	.footer-left .accordion-tab.footer-newsletter-1 {
		width: 600px;
	}

	.footer-left .accordion-tab.socila-media-tab {
		width: 220px;
		float: right;
	}

	.footer-left .accordion-tab label {
		width: 130px;
		float: left;
		margin-right: 35px;
	}

	.footer-left .accordion-tab .newsletter label, .block.newsletter .field.newsletter {
		width: 100% !important;
		max-width: 100% !important;
	}

	.footer.content .block.newsletter {
		border-radius: 27px;
		background: #1A1A1A 0% 0% no-repeat padding-box;
		opacity: 1;
	}

	.footer-left .accordion-tab.footer-newsletter-1 .tab-content {
		width: 410px;
		float: left;
	}

	.footer.content ul {
		padding-right: 0 !important;
	}

	.footer-left .social-tab ul li:before {
		font-size: 35px!important;
	}

	.footer-left .social-tab ul li {
		margin-right: 0 !important;
		margin-left: 25px !important;
	}

	.footer-right .footer-links {
		width: 500px;
		float: left;
	}

	.footer-right .right-img {
		width: auto;
		float: right;
		margin-top: 10px;
	}

	.footer-right .footer-links .leff-col ul li {
		width: 35%;
	}

	.page-main {
		max-width: 100% !important;
	}

	.category-section-2 .subsection-b {
		width: 17%;
		float: left;
	}

	.glp-work .subsection-content {
		height: 90px;
	}

	.faq-section .container {
		max-width: 670px !important;
	}

	.page-with-filter .category-cms {
		margin-top: 65px !important;
	}

	.included-section.glp-work .container, .included-section .container {
		max-width: 1005px !important;
	}

	.footer-link .container, .footer-consultation .container {
		max-width: 1090px !important;
	}

	.product-info-tab .tab-container {
		max-width: 1145px !important;
		margin: 0 auto;
	}

	.weightloss-journey .container {
		max-width: 1030px !important;
		display: block !important;
	}

	.blog-c, .blogs-section .post-holder {
		width: 332px !important;
	}

	.slider-wrapper.desk-review-slider .slide-arrow {
		top: -15% !important;
	}

	.offer.mf-initial {
		width: auto;
		height: 42px;
	}
}

@media screen and (max-width: 767px) {
	.category-weight-loss.catalog-category-view .footer-blog {
		padding-bottom: 10px !important;
	}

	.category-weight-loss.catalog-category-view .page-title-wrapper h1.page-title span {
		font-size: 26px !important;
		font-family: 'Ubuntu', sans-serif;
	}

	.video-section {
		margin-top: 20px;
	}

	.header.content .rating-header {
		display: none;
	}

	.h-banner-content-sec {
		width: 100% !important;
		float: left !important;
	}

	.video-section .subsection-2 {
		width: 100% !important;
	}

	.video-section .subsection-2, .h-banner-content-sec .review-content {
		width: 100% !important;
	}

	.h-banner-content {
		width: auto !important;
		float: left !important;
		margin-top: 0 !important;
		border-radius: 0;
	}

	.cms-index-index .page-main {
		padding-top: 0 !important;
	}

	.cms-index-index .page-header {
		margin-bottom: 0 !important;
	}

	.h-banner-btn a {
		width: 220px !important;
	}

	header .header.content {
		padding-bottom: 10px !important;
	}

	.h-banner-content h2 {
		font-size: 30px !important;
		line-height: 36px !important;
	}

	.h-banner-btn {
		margin-top: 10px;
	}

	.banner-left-c {
		margin-bottom: 30px;
		display: inline-block;
	}

	.banner-right-c ul li {
		width: 49% !important;
		padding-bottom: 0 !important;
		height: 100px;
	}

	.h-banner-content-sec .review-content {
		text-align: center;
	}

	.review-content img {
		float: none !important;
		margin-right: 15px;
		margin-bottom: 0 !important;
		width: 45% !important;
		vertical-align: top;
	}

	.weight-loss-journey {
		background: #fff;
		padding-top: 30px;
		padding-bottom: 40px;
		margin: 0;
	}

	.weight-loss-journey h2, .home-testimonilas h2, .google-review-section h2, .blogs-section h2, .faq-section h2, .stories-section h2, .meet-team-section h2, .video-section h2, .included-section h2, .treatment-options h2, .how-it-works-section h2 {
		font-size: 32px !important;
		line-height: 40px !important;
		text-align: left;
		padding-left: 15px;
		padding-right: 15px;
		width: auto !important;
	}

	.video-section h2 {
		margin-bottom: 30px !important;
	}

	.faq-section h2 br {
		display: none;
	}

	.weight-loss-journey .timeframe-subheading, .story-1 {
		width: auto !important;
		float: left;
		padding: 0 15px 20px 15px !important;
	}

	.included-section .subsection {
		width: 100% !important;
		padding: 0 15px;
	}

	.included-section .subsection-content {
		margin-right: 0 !important;
	}

	.included-section .subsection-content img {
		margin-top: -40px;
	}

	.included-section .subsection p {
		width: 70% !important;
	}

	.included-section .subsection-content.last {
		border-bottom: 1px solid #D3DEE1 !important;
	}

	.included-section .subsection-content.last.last2 {
		border-bottom: 0 !important;
		padding-bottom: 0 !important;
		margin-bottom: 0 !important;
	}

	.treatment-options .home_block_1 {
		margin-bottom: 20px !important;
	}

	.story-1 img {
		width: 100%;
	}

	.story-1 .subsection-content img {
		width: auto !important;
	}

	.meet-team-section .team-1 {
		width: 90% !important;
		margin: 0 0 25px 0 !important;
	}

	.cms-index-index .home-testimonilas.inner {
		margin-top: 0 !important;
		padding: 35px 0 !important;
	}

	.included-section {
		padding-top: 40px;
	}

	.cms-index-index .faq-section, .meet-team-section, .video-section, .treatment-options {
		padding: 35px 0 !important;
	}

	.cms-index-index .google-review-section {
		padding-bottom: 10px !important;
	}

	.how-it-works-section {
		background: #fff;
		padding-top: 45px !important;
		padding-bottom: 45px !important;
	}

	.how-it-works-section h2 {
		margin-bottom: 0 !important;
	}

	.how-it-works-section .work-c h2 {
		width: 100% !important;
		padding: 0 !important;
		font-size: 20px !important;
		font-family: 'Lato', sans-serif;
		line-height: 25px !important;
		margin-bottom: 10px !important;
	}

	.work-c {
		left: 140px !important;
		padding-right: 20px !important;
	}

	.Works-1 {
		width: 100% !important;
		margin: 0 !important;
	}

	.testimonials-list, .review-list {
		width: 90% !important;
		margin: 0 0px 20px 0px !important;
	}

	.testimonials-list {
		padding-top: 40px;
		padding-bottom: 40px;
	}

	.faq-content {
		width: 90% !important;
		padding: 0 15px !important;
	}

	.meet-team-section2, .stories-section {
		padding: 40px 0!important;
	}

	.blogs-section {
		padding: 10px 0 10px 0 !important;
	}

	.faq-section .container {
		width: 90%;
	}

	.faq-section button.accordion {
		padding-right: 20px !important;
		line-height: 22px !important;
	}

	.blog-c {
		margin: 0 15px 20px 15px !important;
	}

	.footer-left {
		border-bottom: 0 !important;
		padding-bottom: 0 !important;
	}

	.footer-link {
		padding: 0 15px;
	}

	.video-section .subsection-2 {
		margin-top: 15px !important;
	}

	.footer-consultation .container h3, .video-section .subsection-2 h3 {
		width: 100% !important;
		text-align: center !important;
		font-size: 25px !important;
	}

	.footer-consultation .h-banner-btn, .video-section .subsection-2 .h-banner-btn {
		width: 100% !important;
		float: left !important;
		margin-top: 10px;
	}

	.footer-right .right-img {
		float: left;
		width: 100%;
		margin-top: 30px;
	}

	.footer-right .right-img img {
		margin-right: 10px;
		margin-bottom: 10px;
	}

	.page-footer .copyright-panel p {
		margin-top: 0 !important;
	}

	.weight-loss-content {
		width: 95% !important;
		padding: 15px 0 15px 75px;
	}

	.home_block_img {
		height: auto !important;
		margin-bottom: 25px;
	}

	.video-section .subsection video {
		width: 90% !important;
		height: 250px !important;
	}

	.meet-team-section2 .team-2 {
		width: 90% !important;
		margin-bottom: 10px !important;
	}

	.home-treatment-block .home_block_1 {
		width: 90% !important;
	}

	.cms-index-index .page-header {
		padding-bottom: 0 !important;
	}

	.logo img {
		width: 158px !important;
		height: 90px !important;
	}

	.footer-link .footer-left {
		border-bottom: 0 !important;
		padding-bottom: 0 !important;
	}

	.footer-link .footer-right {
		padding-top: 0 !important;
	}

	.footer-left .social-tab {
		margin-bottom: 20px !important;
	}

	.cms-index-index .homepage-banner-new {
		display: none;
	}

	.homepage-banner-new-mobile {
		width: 100%;
		float: left;
		padding: 0 0 25px 0;
		margin: 0;
		background: url(/app/design/frontend/Custom/luma_weightloss/Magento_Theme/templates/images/weight-loss-main-banner.webp) 30% 16% no-repeat;
		height: auto;
		background-size: cover;
	}

	.cms-index-index .homepage-banner-new-mobile {
		padding-bottom: 15px !important;
		height: 478px;
		margin-bottom: 20px;
	}

	.homepage-banner-new-mobile .h-banner-content-sec h2 {
		font: normal normal 300 40px / 46px Lato;
		letter-spacing: 0px;
		margin-left: 167px;
		margin-right: 13px;
	}

	.homepage-banner-new-mobile .h-banner-content-sec .popup-button {
		width: 150px;
		display: inline-block;
		text-align: center;
		background: #EC3237;
		font-size: 13px;
		color: #fff;
		font-family: 'Lato', sans-serif;
		line-height: 55px;
		padding: 0 0px;
		font-weight: 400;
		border-radius: 30px;
		letter-spacing: 0.26px;
		height: auto;
		border: 0;
		margin-bottom: 0px;
		text-transform: uppercase;
		margin-left: 167px;
		margin-right: 13px;
	}

	.homepage-banner-new-mobile .banner-left-c {
		display: none;
	}

	.homepage-banner-new-mobile .h-banner-content p {
		font: normal normal normal 11px / 16px Lato;
		letter-spacing: 0px;
		padding: 0;
	}

	.homepage-banner-new-mobile .banner-right-c ul li {
		height: 86px;
	}

	.homepage-banner-new-mobile .banner-right-c ul li:nth-child(3) {
		padding-top: 15px;
	}

	.homepage-banner-new-mobile .banner-right-c ul li:nth-child(4) {
		padding-top: 10px;
	}

	.review-content-mobile {
		text-align: center;
		width: 100%;
		margin-bottom: 20px;
	}

	.review-content-mobile img {
		float: none !important;
		margin-bottom: 0 !important;
		width: 45% !important;
		vertical-align: top;
		margin: auto;
	}

	.offer.mf-initial {
		width: auto;
		height: 42px;
	}
}

.subsection-b {
	background: #FEECEC;
	border-radius: 8px;
	padding: 28px 35px;
	margin-right: 40px;
}

.subsection-b.last {
	margin-right: 0 !important;
}

.subsection-b h3 {
	font-size: 25px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 30px;
	font-weight: 700;
	padding: 0;
	margin: 0 0 30px 0;
}

.glp-work .subsection-content.last {
	margin-bottom: 0 !important;
	padding-bottom: 0 !important;
}

.glp-work {
	padding-bottom: 20px !important;
	padding-top: 85px !important;
}

.faq-content .faq-list {
	border-bottom: 1px solid #96D8F0;
}

.how-it-works-section.inner {
	background: #E7F2F4;
	margin-top: 40px;
}

.weightloss-journey {
	width: 100%;
	float: left;
	padding: 45px 0;
	margin: 0;
	background: #96D8F0;
}

.weightloss-journey .container h3 {
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 55px;
	font-weight: 300;
	text-align: left;
	background: none !important;
}

.weightloss-journey .container h3 strong {
	font-weight: 700;
}

.weightloss-journey .h-banner-btn {
	width: auto;
	float: right;
}

.weightloss-journey .h-banner-btn a {
	width: 220px;
	display: inline-block;
	text-align: center;
	background: #EC3237;
	font-size: 13px;
	color: #fff;
	font-family: 'Lato', sans-serif;
	line-height: 52px;
	padding: 0 0px;
	font-weight: 400;
	border-radius: 28px;
	letter-spacing: 0.26px;
}

.weightloss-journey .h-banner-btn a:hover {
	background: #53CAF5 !important;
}

.video-section.inner, .meet-team-section2.inner {
	background: #fff !important;
}

.meet-team-section2.inner {
	padding-top: 0 !important;
}

.meet-team-section2.inner .team-2 {
	background: #E7F2F4;
}

.home-testimonilas.inner {
	margin-top: 50px !important;
}

.included-section.inner {
	padding-bottom: 20px !important;
}

.cms-index-index .message.success {
	margin-top: 66px;
}

.block.newsletter .form.subscribe div.mage-error[generated] {
	font-size: 14px;
}

.faq-section .faq-list {
	border-bottom: 1px solid #96D8F0;
	padding-bottom: 12px;
}

.faq-section button.accordion {
	border: 0;
	border-bottom: 0px solid #96D8F0;
	box-shadow: none !important;
	background: transparent;
	font-size: 16px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 30px;
	font-weight: 400;
	text-align: left;
	padding: 20px 0 8px 0;
}

.faq-section .panel, .faq-section .panel p {
	font-size: 16px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 24px;
	font-weight: 400;
	text-align: left;
	padding: 0px 0;
}

.faq-section button.accordion:after {
	float: right;
	display: none;
}

.faq-section button.accordion {
	background: url(/pub/media/wysiwyg/WLImage/Poly.png) right 32px no-repeat;
}

a:hover {
	text-decoration: none;
}

@media only screen and (min-width:768px) and (max-width:991px) {
	.homepage-banner-new {
		height: 655px !important;
	}

	.weight-loss-content {
		width: 100% !important;
	}

	.weight-loss-journey .timeframe-subheading {
		width: 31% !important;
	}

	.video-section h2 {
		margin-bottom: 0 !important;
	}

	.slider-wrapper.desk-review-slider .slides-container {
		margin-left: 60px !important;
	}

	.slider-wrapper.desk-review-slider.google-review-section .demo-content {
		width: 27% !important;
	}

	.blogs-section .post-holder {
		width: 30% !important;
	}

	.subsection-2 {
		width: 95% !important;
		margin-top: 50px!important;
	}

	.subsection-2 h3, .footer-consultation .container h3 {
		font-size: 32px !important;
		line-height: 44px !important;
	}

	.header .rating-header {
		display: none;
	}

	.header .logo {
		width: auto !important;
		margin-left: 0px;
	}

	.header .logo img {
		margin: 0 !important;
	}

	.header.content .customMenu {
		margin-top: 0 !important;
	}

	.review-content {
		width: 100% !important;
		margin-left: -50px;
	}

	.h-banner-content {
		margin-right: 64px !important;
		width: 640px !important;
	}

	.review-content img {
		width: 48%;
	}

	.weight-loss-journey .timeframe-subheading {
		margin-bottom: 20px;
	}

	.testimonials-list {
		width: 230px !important;
		padding: 50px 20px !important;
	}

	.home_block_1 {
		width: 230px !important;
	}

	.home_block_img {
		height: 200px !important;
	}

	.cms-index-index .included-section.glp-work .container, .cms-index-index .included-section .container .footer-consultation .container {
		max-width: 100% !important;
	}

	.footer-link .container {
		max-width: 95% !important;
	}

	.included-section .subsection p {
		width: 70% !important;
	}

	.included-section .subsection {
		width: 44%;
		float: left;
		margin: 0 20px;
	}

	.included-section .subsection-content {
		margin-right: 0 !important;
	}

	.video-section, .meet-team-section {
		padding: 50px 0 !important;
	}

	.meet-team-section .team-1, .story-1, .blog-c {
		width: 240px!important;
	}

	.team-2 {
		width: 240px !important;
		margin: 0 5px !important;
		padding: 44px 20px !important;
	}

	.team-2 h3 {
		font-size: 15px !important;
		width: 122px !important;
	}

	.review-list {
		width: 200px !important;
		margin: 0 5px !important;
		padding: 40px 20px !important;
	}

	.footer-right .accordion-tab {
		width: 100% !important;
	}

	.footer-left .accordion-tab.footer-newsletter-1 {
		width: 500px !important;
	}

	.footer-left .accordion-tab.footer-newsletter-1 .tab-content {
		width: 320px !important;
	}

	.footer-right .footer-links {
		width: 270px !important;
	}

	.footer-right .right-img {
		width: 62% !important;
	}

	.footer-right .right-img img {
		width: 24%;
	}

	.footer-right .footer-links .leff-col ul li {
		width: 50% !important;
	}
}

@media only screen and (min-width:992px) and (max-width:1024px) {
	.category-weight-loss.catalog-category-view .slider-wrapper.desk-review-slider .slide-arrow {
		top: 30% !important;
	}

	.slider-wrapper.desk-review-slider .slides-container {
		margin-left: 70px !important;
	}

	.slider-wrapper.desk-review-slider.google-review-section .demo-content {
		width: 27% !important;
	}

	.blogs-section .post-holder {
		width: 31% !important;
	}

	.weight-loss-content {
		width: 90% !important;
	}

	.header .logo {
		width: auto !important;
		display: inline-block;
		margin: 20px 0 20px 0px !important;
	}

	.subsection-2 {
		width: 95% !important;
		margin-top: 50px!important;
	}

	.subsection-2 h3, .footer-consultation .container h3 {
		font-size: 35px !important;
		line-height: 50px !important;
	}

	.header.content .customMenu {
		margin-top: -11% !important;
	}

	.customMenu li.view-all-treatment a, .btn-login-signup a {
		padding: 0 15px !important;
	}

	.review-content {
		width: 100% !important;
	}

	.h-banner-content {
		margin-right: 20px !important;
		width: 640px !important;
	}

	.review-content img {
		width: 48%;
	}

	.weight-loss-journey .timeframe-subheading {
		margin-bottom: 20px;
		width: 327px !important;
	}

	.testimonials-list {
		width: 315px !important;
		padding: 50px 25px !important;
	}

	.home_block_1 {
		width: 31% !important;
	}

	.home_block_img {
		height: 250px !important;
	}

	.Works-1 {
		width: 300px !important;
		margin: 0 12px !important;
	}

	.cms-index-index .included-section.glp-work .container, .cms-index-index .included-section .container .footer-consultation .container {
		max-width: 100% !important;
	}

	.footer-link .container {
		max-width: 95% !important;
	}

	.included-section .subsection p {
		width: 70% !important;
	}

	.included-section .subsection {
		width: 45%;
		float: left;
		margin: 0 20px;
	}

	.included-section .subsection-content {
		margin-right: 0 !important;
	}

	.video-section, .meet-team-section {
		padding: 50px 0 !important;
	}

	.meet-team-section .team-1, .story-1, .blog-c {
		width: 320px!important;
	}

	.team-2 {
		width: 270px !important;
		margin: 10px 10px !important;
		padding: 44px 20px !important;
	}

	.team-2 h3 {
		font-size: 15px !important;
		width: 122px !important;
	}

	.review-list {
		width: 270px !important;
		margin: 0 10px !important;
		padding: 40px 20px !important;
	}

	.footer-right .footer-links {
		width: 360px !important;
	}

	.footer-right .right-img {
		width: 62% !important;
	}

	.footer-right .right-img img {
		width: 24%;
	}

	.footer-right .footer-links .leff-col ul li {
		width: 50% !important;
	}

	.category-weight-loss.catalog-category-view .slider-wrapper.desk-review-slider .slide-arrow {
		top: 30% !important;
	}

	.category-weight-loss.catalog-category-view .meet-team-section2 .team-2 {
		padding-left: 10px !important;
		padding-right: 10px !important;
		width: 305px !important;
	}

	.catalog-category-view .page-footer .footer-right {
		width: 56% !important;
	}
}

.customMenu .custom-menu-ul .amform-parent {
	float: left;
}

.faq-section button.accordion {
	width: 100%;
}

.reveal1 {
	position: relative;
	transform: translateY(0);
	opacity: 1;
	transition: 1s all ease !important;
}

.reveal1.active {
	transform: translateY(0);
	opacity: 1;
}

.amcform-button.-default:focus, .amcform-button.-error:focus {
	background-color: #53CAF5 !important;
	box-shadow: none !important;
}

.banner-left-c .start-const-btn button, .h-banner-btn .start-const-btn button, .home_block_1 .h-banner-btn a, .category-details .start-const-btn button, .weightloss-journey .h-banner-btn a, .footer-consultation .h-banner-btn a, .amcform-popup-block .amform-form .amcform-toolbar button, .product-order-now a button, .catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-options-bottom .box-tocart .action.tocart, .cart-container .continue-shopping, .checkout-cart-index .cart-summary .checkout-methods-items .action.primary.checkout, .popup-authentication.modal-popup .actions-toolbar .primary button.action, .osc-place-order-wrapper .place-order-primary button.primary.checkout {
	transition: all .35s !important;
	text-decoration: none !important;
}

.faq-section .accordion {
	font: var(--unnamed-font-style-normal) normal normal 18px/21px Roboto;
	letter-spacing: var(--unnamed-character-spacing-0);
	color: var(--unnamed-color-000000);
	text-align: left;
	font: normal normal normal 18px/21px Roboto;
	letter-spacing: 0px;
	color: #000000;
	opacity: 1;
	padding: 15px;
	width: 100%;
}

.faq-section .accordion:after {
	content: '\002B';
	/ Unicode character for plus sign / padding-left: 80px float: right;
}

.faq-section .panel {
	padding: 10px 0;
	display: none;
	overflow: hidden;
	font: var(--unnamed-font-style-normal) normal normal 18px/21px Roboto;
	letter-spacing: var(--unnamed-character-spacing-0);
	color: var(--unnamed-color-000000);
	text-align: left;
	font: normal normal normal 18px/21px Roboto;
	letter-spacing: 0px;
	color: #000000;
	opacity: 1;
}

.h-title-2 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 15px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 18px;
	font-weight: 700;
	text-align: left;
	letter-spacing: 0.5px;
	text-transform: uppercase;
}

.h-title-3 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 7px 0;
	font-size: 20px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 40px;
	font-weight: 700;
	text-align: left;
}

.subsection .h-title-4 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 15px 0;
	font-size: 20px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 30px;
	font-weight: 900;
	text-align: left;
}

.subsection-2 .h-title-5 {
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 55px;
	font-weight: 300;
	text-align: left;
}

.subsection-2 .h-title-5 strong {
	font-weight: 700;
}

.meet-team-section .h-title-6 {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 5px 0;
	font-size: 20px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 30px;
	font-weight: 900;
	text-align: left;
}

.team-2 .h-title-7 {
	padding: 0;
	margin: 0 0 0 20px;
	font-size: 18px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 22px;
	font-weight: 700;
	text-align: left;
	float: left;
	width: 175px;
}

.home_block_1 .h-product-title {
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 20px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 30px;
	font-weight: 900;
	text-align: left;
}

.footer-consultation .container .footer-title {
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
	color: #fff;
	font-family: 'Lato', sans-serif;
	line-height: 55px;
	font-weight: 300;
	text-align: left;
	background: none !important;
}

.footer-consultation .container .footer-title span {
	font-size: 15px;
	line-height: 22px !important;
	width: 100%;
	float: left;
}

@media screen and (min-width: 768px) {
	.h-title {
		width: 100%;
		float: left;
		padding: 0;
		margin: 0 0 22px 0;
		font-size: 38px;
		color: #101010;
		font-family: 'Lato', sans-serif;
		line-height: 48px;
		font-weight: 300;
		text-align: center;
	}

	.blogs-section .h-title {
		margin-bottom: 40px !important;
	}
}

@media only screen and (min-width:768px) and (max-width:991px) {
	.category-weight-loss.page-products.page-layout-1column.amform-body .products-grid .product-item.custom-col-category {
		width: 45% !important;
		margin: 5px 20px;
	}

	.video-section .subsection-2 .h-title-5, .footer-consultation .container .footer-title {
		font-size: 32px !important;
		line-height: 44px !important;
	}

	.team-2 .h-title-7 {
		font-size: 15px !important;
		width: 122px !important;
	}

	.offer.mf-initial {
		width: auto;
		height: 42px;
	}
}

@media only screen and (min-width:992px) and (max-width:1024px) {
	.team-2 {
		width: 310px !important;
	}

	.offer.mf-initial {
		width: auto;
		height: 42px;
	}
}

@media screen and (max-width: 767px) {
	.weight-loss-journey .h-title, .home-testimonilas .h-title, .google-review-section .h-title, .blogs-section .h-title, .faq-section .h-title, .stories-section .h-title, .meet-team-section .h-title, .video-section .h-title, .included-section .h-title, .treatment-options .h-title, .how-it-works-section .h-title {
		font-size: 32px !important;
		line-height: 40px !important;
		text-align: left;
		padding-left: 15px;
		padding-right: 15px;
		width: auto !important;
		font-weight: 300;
		margin: 0 0 45px 0;
	}

	.how-it-works-section .h-title {
		margin-bottom: 19px !important;
	}

	.faq-section .h-title {
		padding-left: 0 !important;
		padding-right: 0 !important;
		margin-bottom: 25px !important;
	}

	.how-it-works-section .work-c .h-title-2 {
		width: 100% !important;
		padding: 0 !important;
		font-size: 20px !important;
		font-family: 'Lato', sans-serif;
		line-height: 25px !important;
		margin-bottom: 10px !important;
	}

	.video-section .subsection-2 .h-title-5, .footer-consultation .container .footer-title {
		width: 100% !important;
		text-align: center !important;
		font-size: 25px !important;
	}
}

.home-treatment-block .home_block_1:after {
	display: none;
}

@media screen and (max-width: 767px) {
	.cms-index-index .weight-loss-journey .h-title {
		padding-right: 0 !important;
		padding-left: 0 !important;
		line-height: 36px !important;
	}

	.social-tab ul li.twitter-icon:before {
		content: " " !important;
		width: 20px;
		height: 30px;
		display: inline-block;
		background-size: 100%;
	}

	.cms-index-index .h-banner-content {
		margin-right: 15px;
		margin-left: 15px;
		margin-top: 15px !important;
		width: 199px !important;
		height: 207px;
		margin-left: 167px;
		margin-right: 13px;
		padding: 20px 10px;
	}

	.homepage-banner-new-mobile .banner-right-c ul li .banner-icon {
		height: 43px;
	}

	.cms-index-index .homepage-banner-new {
		padding-bottom: 15px !important;
	}

	.homepage-banner-new .h-banner-content h2 {
		font-size: 25px !important;
		line-height: 30px !important;
		font-weight: 400 !important;
	}

	.meet-team-section .team-1 {
		width: 43% !important;
		margin: 0 12px 25px 12px !important;
		float: none;
		vertical-align: top;
	}

	.meet-team-section .h-title-6 {
		font-size: 16px !important;
		line-height: 22px !important;
	}

	.meet-team-section .subsection-content2 {
		margin-top: 10px !important;
	}

	.story-1 .subsection-content {
		padding-bottom: 0 !important;
	}

	.stories-section {
		padding: 40px 0 10px 0 !important;
	}

	.cms-index-index .weight-loss-journey .h-title, .cms-index-index .home-testimonilas .h-title, .cms-index-index .google-review-section .h-title, .cms-index-index .blogs-section .h-title, .cms-index-index .faq-section .h-title, .cms-index-index .stories-section .h-title, .cms-index-index .meet-team-section .h-title, .cms-index-index .video-section .h-title, .cms-index-index .included-section .h-title, .cms-index-index .treatment-options .h-title, .cms-index-index .how-it-works-section .h-title {
		text-align: left;
		padding-left: 15px;
		padding-right: 15px;
		width: auto !important;
		font-weight: 300;
		margin: 0 0 25px 0;
		font: normal normal normal 32px/36px Lato;
		letter-spacing: 0px;
		color: #101010;
	}

	.work-c {
		top: 51px !important;
	}

	.how-it-works-section .work-c .h-title-2 br {
		display: none;
	}

	.how-it-works-section .work-c .h-title-2 {
		font-size: 15px !important;
		line-height: 20px !important;
	}

	.timeframe-subheading h4 {
		text-align: left;
		font: normal normal normal 16px/20px Lato;
		letter-spacing: 0px;
		font-weight: 500;
	}

	.blog-c h4, .blogs-section .post-holder .post-title a {
		font-weight: 500 !important;
	}

	.testimonials-list {
		padding-top: 20px !important;
		padding-bottom: 10px !important;
		padding-left: 20px !important;
		padding-right: 20px !important;
	}

	.home_block_1 .h-product-title {
		font-weight: 600 !important;
	}

	.home-treatment-block .home_block_1 {
		padding: 15px 15px 25px 15px !important;
	}

	.home_block_img {
		width: 100%;
		margin-bottom: 15px !important;
	}

	.home_block_img img {
		width: 70%;
	}

	.home_block_1 p {
		margin-bottom: 15px !important;
	}

	.home-treatment-block .home_block_1 {
		width: 80% !important;
	}

	.treatment-options, .meet-team-section {
		padding-bottom: 20px !important;
	}

	.review-name-header {
		text-align: left !important;
		padding-left: 15px !important;
		padding-right: 15px !important;
		width: auto !important;
		margin: 0 0 25px 0;
		font: normal normal normal 32px / 36px Lato !important;
		letter-spacing: 0px;
		color: #101010;
	}

	.cms-index-index .google-review-section {
		padding: 53px 0 40px 0 !important;
	}

	.blog-c h4, .blogs-section .post-holder .post-title a {
		font-size: 18px !important;
	}

	.meet-team-section2 .team-2 {
		padding: 20px 20px !important;
		margin-left: 0 !important;
		margin-right: 0 !important;
	}

	.team-2 .h-title-7 {
		width: 72% !important;
		font-size: 15px !important;
		line-height: 42px !important;
	}

	.meet-team-section p {
		font-size: 13px !important;
	}

	.subsection .h-title-4 {
		margin: 22px 0 10px 84px;
		font: normal normal 900 18px Lato;
		letter-spacing: 0px;
	}

	.included-section .subsection p {
		width: 75% !important;
		font-size: 14px !important;
	}

	.subsection-content {
		margin-bottom: 10px !important;
	}

	.faq-section button.accordion {
		font-size: 15px !important;
	}

	.faq-section .panel p {
		font-size: 14px !important;
		line-height: 22px !important;
	}
	.product-faq-section .container .faq-list label{
		background: url(/pub/media/wysiwyg/WLImage/Poly.png) right 20px center no-repeat !important;
	}
}

.meet-team-section2 .team-2:after, .weight-loss-journey .timeframe-subheading:after {
	display: none;
}

.faq-section button.accordion {
	font-weight: 700 !important;
}

.banner-left-c button {
	width: 120px;
	display: inline-block;
	text-align: center;
	background: #EC3237;
	font-size: 13px;
	color: #fff;
	font-family: 'Lato', sans-serif;
	line-height: 55px;
	padding: 0 0px;
	font-weight: 400;
	border-radius: 30px;
	letter-spacing: 0.26px;
	height: auto;
	border: 0;
	margin-bottom: 0px;
	text-transform: uppercase;
}

.banner-left-c button:hover {
	background: #53CAF5 !important;
}

.banner-left-c .popup-content h2 {
	width: 100%;
	display: inline-block;
	text-align: center;
	font-size: 22px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 56px;
	padding: 0 0px 10px 0;
	font-weight: 400 !important;
	text-transform: uppercase;
}

.banner-left-c .popup-content .container {
	width: 100%;
	display: inline-block;
}

.banner-left-c .popup-content label {
	width: 100%;
	display: inline-block;
	text-align: left;
	font-size: 14px;
	color: #000;
	font-family: 'Lato', sans-serif;
	line-height: 26px;
	padding: 0 0px 10px 0;
	font-weight: 400;
}

.banner-left-c .popup-content form input {
	border-radius: 34px;
	background-color: #F1F7F9 !important;
	border: 1px solid #D7E7EC;
	padding: 0 20px;
	height: 66px;
	margin-bottom: 20px;
}

.banner-left-c .popup-content {
	border-radius: 10px;
	background-color: #fff;
}

.banner-left-c .popup-content p {
	display: none;
}

.banner-left-c .popup {
	background-color: rgba(0, 0, 0, 0.9);
	z-index: 999999;
}

.banner-left-c .popup-content {
	position: relative;
}

.banner-left-c .popup-content .close {
	color: #fff;
	float: right;
	font-size: 80px;
	font-weight: 200;
	position: absolute;
	top: -90px;
	right: -50px;
}

.banner-left-c .popup-content .close:hover {
	color: #fff;
}

.banner-left-c .popup-content .col-md-6 {
	width: 100%;
	display: inline-block;
}

.banner-left-c .popup-content .col-md-6.popup-register {
	background-color: #E7F2F4;
	padding: 25px 0;
}

.banner-left-c .popup-content .col-md-6.popup-register, .banner-left-c .popup-content .col-md-6.popup-register h2 {
	text-align: center;
}

.banner-left-c .popup-content .col-md-6.popup-register h2 {
	width: 100%;
	line-height: 40px !important;
	padding-bottom: 5px !important;
}

.login-button-popup {
	width: 100%;
	display: inline-block;
}

.login-button-popup span {
	float: left;
	line-height: 56px;
	font-size: 14px;
	color: #000;
	font-family: 'Lato', sans-serif;
}

.banner-left-c .popup-content .col-md-6 form button {
	float: right;
}

.banner-left-c .popup-content .col-md-6.popup-register p {
	display: block !important;
	text-align: center !important;
	margin-bottom: 25px;
}

@media screen and (min-width: 768px) {
	.banner-left-c .popup-content {
		width: 60%;
		margin-top: 8%;
	}

	.banner-left-c .popup-content .col-md-6 h2 {
		width: auto;
	}

	.banner-left-c .popup-content .col-md-6 button {
		float: none;
	}

	.banner-left-c .popup-content .col-md-6 {
		width: 47%;
		float: left;
	}

	.banner-left-c .popup-content .col-md-6.popup-register {
		float: right;
		height: 58vh;
	}
}

@media screen and (max-width: 767px) {
	.banner-left-c .popup-content {
		width: 90% !important;
		margin-top: 20% !important;
	}

	.banner-left-c .popup-content .close {
		top: -95px !important;
		right: -10px !important;
	}

	.banner-left-c .popup-content h2 {
		font-size: 20px !important;
		margin-bottom: 10px;
		text-align: left !important;
	}

	.banner-left-c .popup-content .col-md-6.popup-register {
		margin-top: 30px;
	}

	.banner-left-c .popup-content .col-md-6.popup-register h2 {
		text-align: center !important;
		margin-bottom: 0 !important;
	}

	.banner-left-c .popup-content form input {
		margin-bottom: 10px !important;
		height: 46px !important;
	}

	.login-button-popup {
		margin-top: 10px;
	}

	.footer-consultation .h-banner-btn a {
		margin-top: 15px;
		width: 145px !important;
	}
}

@media only screen and (min-width:768px) and (max-width:991px) {
	.banner-left-c .popup-content {
		width: 85% !important;
	}

	.banner-left-c .popup-content .col-md-6.popup-register {
		height: 36vh;
	}
}

@media only screen and (min-width:992px) and (max-width:1024px) {
	.banner-left-c .popup-content {
		width: 80% !important;
	}
}

@media screen and (max-width: 767px) {
	.hm-meet-team .custom-slider .owl-carousel .owl-stage-outer {
		overflow: hidden;
	}

	.hm-meet-team .custom-slider .owl-carousel .custom_content .subsection-content2 {
		margin-top: 80px !important;
		margin-left: 0 !important;
	}

	.hm-meet-team .custom-slider .owl-carousel .banner-item .content_slider {
		left: 10px !important;
		width: 70% !important;
	}

	.hm-meet-team .custom-slider .subsection-content2 .h-title-6 {
		font-size: 14px !important;
		font-weight: 600 !important;
		height: 40px;
	}

	.hm-meet-team .custom-slider .owl-carousel .owl-item .banner-image {
		position: relative;
	}

	.hm-meet-team .custom-slider .owl-carousel .owl-item .banner-item .banner-image:before {
		background: linear-gradient(#00000000, #00000080), rgba(0, 0, 0, 0.1);
		content: " " !important;
		width: 100%;
		height: 100%;
		display: inline-block;
		opacity: 0.5;
		position: absolute;
		left: 0;
		top: 0;
		z-index: 99999;
	}

	.hm-meet-team .custom-slider .owl-carousel .banner-item .content_slider {
		z-index: 999999;
	}

	.hm-meet-team .custom-slider .owl-carousel .banner-item .content_slider button.plus-button {
		width: 30px !important;
		height: 30px !important;
		font-size: 19px !important;
		padding: 7px 10px !important;
	}

	.meet-the-team-popup .model-content-sec {
		width: 100% !important;
	}

	.treatment-options {
		margin-top: 50px !important;
	}
}

.page-header .offer1 {
	display: none !important;
}

@media only screen and (min-width:768px) and (max-width:991px) {
	.header .rating-header {
		width: 180px !important;
		left: 0 !important;
	}

	.header .rating-header p {
		margin-left: 0 !important;
	}

	.page-header .header.content .customMenu {
		width: 175px !important;
		margin-top: 40px !important;
	}

	.header.content .customMenu {
		margin-top: 40px !important;
		width: 430px !important;
	}

	.page-header .minicart-wrapper {
		top: 40px !important;
		right: 0 !important;
	}

	.homepage-banner-new .h-banner-content-sec {
		width: 87% !important;
		margin-right: 0 !important;
	}

	.homepage-banner-new .h-banner-content {
		margin-right: 20px !important;
	}

	.homepage-banner-new .review-content {
		margin-left: -7px !important;
	}

	.homepage-banner-new .review-content img {
		width: 46% !important;
	}

	.homepage-banner-new {
		background: url(/app/design/frontend/Custom/luma_weightloss/Magento_Theme/templates/images/main-banner.jpg) 44% 16% no-repeat !important;
	}

	.header .rating-header {
		margin-top: 45px !important;
	}

	.weight-loss-journey .container .timeframe-subheading {
		width: 33% !important;
	}

	.timeframe-subheading ul {
		width: 100% !important;
	}

	.reveal1 {
		position: relative;
		transform: none !important;
		opacity: 1 !important;
		transition: 1s all ease !important;
	}

	.slider-wrapper.desk-review-slider {
		display: block !important;
		width: 100% !important;
		padding-bottom: 15px !important;
	}

	.slider-wrapper.desk-review-slider .slide-arrow {
		top: 5% !important;
	}

	.how-it-works-section {
		width: 98% !important;
	}

	.weight-loss-journey {
		margin-top: 60px !important;
		margin-bottom: 0 !important;
	}

	.how-it-works-section {
		padding-top: 30px !important;
	}

	.treatment-options .container {
		width: 100% !important;
	}

	.treatment-options .home-treatment-block .home_block_1 {
		width: 31% !important;
		padding: 15px 15px 25px 15px !important;
		margin: 0 5px 20px 5px !important;
	}

	.home_block_1 p {
		font-size: 13px !important;
	}

	.home_block_1 .h-product-title {
		font-size: 17px !important;
		line-height: 27px !important;
	}

	.treatment-options .home-treatment-block .fixed-image {
		width: 45% !important;
	}

	.treatment-options .home-treatment-block.fixed-image .h-banner-btn {
		width: 100%;
	}

	.treatment-options .fixed-image .start-const-btn .amform-show-popup {
		padding: 20px 0 !important;
	}

	.treatment-options .fixed-image .h-banner-btn, .treatment-options .start-const-btn .amform-show-popup.amcform-button {
		width: 100%;
	}

	.page-main .how-it-works-section {
		border-top: 0px solid #ebebeb !important;
		padding-top: 25px !important;
	}

	.treatment-options .h-banner-btn {
		margin-bottom: 0 !important;
	}

	.hm-meet-team .content-heading h2 {
		width: 100%;
		display: inline-block;
	}

	.faq-section .container .h-title {
		font-size: 32px !important;
		line-height: 40px !important;
	}

	.blogs-section .post-holder {
		margin: 0 10px !important;
	}

	.cms-index-index .faq-section {
		margin-bottom: 0 !important;
	}
}

@media only screen and (min-width:992px) and (max-width:1024px) {
	.how-it-works-section .work-c {
		left: 110px !important;
		top: 40px !important;
	}

	.how-it-works-section .work-c .h-title-2 br {
		display: none;
	}

	.how-it-works-section .work-c .h-title-2 {
		font-size: 14px !important;
	}
}

@media only screen and (min-width:768px) and (max-width:1024px) {
	.page-header .logo {
		margin-left: 8% !important;
		float: left;
	}

	.header.content .customMenu {
		margin-top: 0% !important;
		width: 250px !important;
	}

	.header .rating-header {
		position: relative;
		left: 0px;
		margin-top: 53px;
		height: auto;
		display: block !important;
	}
}

@media screen and (min-width: 768px) {
	.cms-index-index .page-main .page.messages {
		top: 95px !important;
	}

	.slider-wrapper.desk-review-slider .demo-content {
		min-height: 245px !important;
	}

	.hm-meet-team .custom-slider .owl-carousel .owl-item .banner-item .banner-image {
		position: relative;
	}

	.hm-meet-team .custom-slider .owl-carousel .owl-item .banner-item .banner-image:before {
		background: linear-gradient(#00000000, #00000080), rgba(0, 0, 0, 0.1);
		content: " " !important;
		width: 100%;
		height: 100%;
		display: inline-block;
		opacity: 0.5;
		position: absolute;
		left: 0;
		top: 0;
		z-index: 99999;
	}

	.hm-meet-team .custom-slider .owl-carousel .banner-item .content_slider {
		z-index: 999999;
	}
}

@media screen and (max-width: 767px) {
	.page-main .how-it-works-section .Works-1 .work-c {
		top: 0px !important;
        left: 140px !important;
        padding-right: 8px !important;
        height: 190px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin-top: 0 !important;
        padding-right: 10px !important;
	}

	.how-it-works-section .Works-1:nth-child(2) .work-c {
		margin-top: 18px;
	}

	.homepage-banner-new-mobile .banner-right-c ul li:nth-child(3) .banner-icon {
		height: 38px;
	}
}

.btn-login-signup a:hover {
	color: #fff !important;
}

.btn-login-signup a, .h-banner-btn a, .h-banner-btn .start-const-btn button, .banner-left-c .start-const-btn button, .treatment-options .fixed-image .start-const-btn .amform-show-popup, .footer-consultation .h-banner-btn a {
	transition: all .35s !important;
}

.treatment-options .fixed-image .start-const-btn .amform-show-popup:hover {
	background: #EC3237 !important;
}

.cms-index-index .message.success {
	margin-top: 10px !important;
}

.cms-index-index .included-section.mf-initial {
	padding-top: 70px;
}

.cms-index-index .faq-section {
	margin-top: 50px;
}

.homepage-banner-new {
	animation: animatedBackground 30s linear alternate infinite;
	background-size: 110% !important;
}

@keyframes animatedBackground {
	0% {
		background-position: 0 0;
	}

	50% {
		background-position: 0 -20%;
	}

	100% {
		background-position: 0 20%;
	}
}

.category-weight-loss .page-header .view-treatment-btn {
	width: auto;
	float: left;
	margin-top: 45px;
}

.category-weight-loss .page-header .view-treatment-btn a, .category-weight-loss .page-header .view-treatment-btn button {
	width: 202px;
	display: inline-block;
	text-align: center;
	background: #EC3237;
	font-size: 13px;
	color: #fff;
	font-family: 'Lato', sans-serif;
	line-height: 52px;
	padding: 0 0px;
	font-weight: 400;
	border-radius: 30px;
	letter-spacing: 0.26px;
	height: auto;
	text-transform: uppercase;
	transition: all .35s !important;
}

.category-weight-loss .page-header .view-treatment-btn a:hover, .category-weight-loss .page-header .view-treatment-btn button:hover {
	background: #53CAF5 !important;
}

.category-weight-loss .page-header .btn-login-signup a {
	line-height: 50px;
	color: #fff !important;
}

.category-weight-loss .meet-the-team-section {
	width: 100%;
	float: left;
	padding: 50px 0 75px 0;
	margin: 0;
	background-color: #E7F2F4;
}

.category-weight-loss.catalog-category-view .breadcrumbs {
	display: none;
}

.category-weight-loss.catalog-category-view .homepage-banner-new {
	animation: none !important;
	background-position: 90% 20px !important;
	margin-top: 0px;
	background-size: cover !important;
}

.category-weight-loss .mob-consult-btn {
	display: none;
}

.category-weight-loss.catalog-category-view .slider-wrapper.desk-review-slider .demo-content .read-more-btn, .category-weight-loss.catalog-category-view .review-slide .content .read-more-btn {
	width: 100%;
	float: left;
	margin-bottom: 20px;
	color: #000 !important;
	text-align: left;
	font-weight: 400;
	font-size: 13px;
	box-shadow: none !important;
}

.category-weight-loss.catalog-category-view .slider-wrapper.desk-review-slider .demo-content .read-more-btn:hover, .category-weight-loss.catalog-category-view .slider-wrapper.desk-review-slider .demo-content .read-more-btn:focus, .category-weight-loss.catalog-category-view .review-slide .content .read-more-btn:hover {
	color: #EC3237 !important;
	text-decoration: underline;
	background: transparent;
	border: 0;
	box-shadow: none !important;
}

.category-weight-loss.catalog-category-view. slider-wrapper.desk-review-slider .demo-content .review-list p, .category-weight-loss.catalog-category-view .review-slide .content .review-list p {
	margin-bottom: 10px !important;
}

.category-weight-loss.catalog-category-view .how-it-works-section {
	border: 0!important;
}

.category-weight-loss.catalog-category-view .meet-the-team-section .owl-carousel .owl-item .banner-image img {
	height: auto;
}

.category-weight-loss.catalog-category-view .meet-the-team-section {
	width: 100%;
	display: inline-block;
	background-color: #E7F2F4;
	padding: 50px 0;
}

.category-weight-loss.catalog-category-view .meet-team-section2 {
	background-color: #fff !important;
	margin-top: 0;
}

.category-weight-loss.catalog-category-view .meet-team-section2 .team-2 {
	background-color: #E7F2F4;
}

.category-weight-loss.catalog-category-view .page-bottom {
	display: none;
}

.category-weight-loss.catalog-category-view .products-grid {
	background-color: #96D8F0;
	padding: 70px 0 20px 0;
}

.category-weight-loss .products ~ .toolbar-products {
	background-color: #96D8F0;
	padding: 0 0 70px 0;
}

.category-weight-loss .toolbar-products .pages a.page {
	border: 1px solid #fff;
	color: #333333;
	background-color: #fff;
}

.category-weight-loss .toolbar-products .pages .action.next, .category-weight-loss .toolbar-products .pages .action.previous {
	box-shadow: none;
}

.category-weight-loss .pages strong.page {
	background: #46C0EC !important;
}

.category-weight-loss .toolbar-products .pages strong.page {
	border: 1px solid #46C0EC !important;
}

.category-weight-loss .toolbar-products .pages a.page, .category-weight-loss .toolbar-products .pages strong.page, .category-weight-loss .toolbar-products .pages .action.next, .category-weight-loss .toolbar-products .pages .action.previous {
	width: 50px;
	height: 50px;
	line-height: 50px;
	font-size: 18px;
	border-radius: 50px;
}

.category-weight-loss .pages .action.next {
	margin-left: 0 !important;
}

.category-weight-loss .pages .item {
	margin-right: 8px;
	margin-left: 8px;
}

.category-weight-loss .hm-meet-team {
	width: 100%;
	display: inline-block;
}

.category-weight-loss .hm-meet-team h3 {
	display: none;
}

.category-weight-loss .footer-consultation .h-banner-btn {
	margin-bottom: 0 !important;
}

.category-weight-loss .category-cms .pages {
	background-color: #96D8F0;
	padding: 40px 0 70px 0;
	text-align: center;
}

.category-weight-loss .category-cms .pages a.page {
	border: 1px solid #fff;
	color: #333333;
	background-color: #fff;
}

.category-weight-loss .category-cms .pages .action.next, .category-weight-loss .category-cms .pages .action.previous {
	box-shadow: none;
}

.category-weight-loss .category-cms .pages strong.page {
	background: #46C0EC !important;
}

.category-weight-loss .category-cms .pages strong.page {
	border: 1px solid #46C0EC !important;
}

.category-weight-loss .category-cms .pages a.page, .category-weight-loss .category-cms .pages strong.page, .category-weight-loss .category-cms .pages .action.next, .category-weight-loss .category-cms .pages .action.previous {
	width: 50px;
	height: 50px;
	line-height: 50px;
	font-size: 18px;
	border-radius: 50px;
	text-align: center;
	padding: 0 !important;
}

.category-weight-loss .category-cms .pages .action.next {
	margin-left: 0 !important;
}

.category-weight-loss .category-cms .pages .item {
	margin-right: 8px;
	margin-left: 8px;
}

.category-weight-loss .product-item-info.custom-col-wrapper-category, .category-weight-loss .products-grid .product-item-info:hover, .category-weight-loss .products-grid .product-item-info.active {
	padding: 25px 25px 35px 25px;
}

.category-weight-loss.page-products.page-layout-1column .products-grid .product-item.custom-col-category {
	padding: 0;
}

.category-weight-loss.page-products .custom-row-category .product-image-container {
	width: 100% !important;
}

.category-weight-loss.page-products .custom-col-wrapper-category .product-item-name a {
	font-size: 18px !important;
}

.category-weight-loss.page-products .product-item-info.custom-col-wrapper-category .product-item-details {
	margin-top: 20px;
}

.category-weight-loss.page-products .custom-col-wrapper-category .simple-prod.start-from {
	padding: 17px 30px;
	border-radius: 26px;
	font-size: 12px !important;
}

.category-weight-loss.page-products .custom-col-wrapper-category .simple-prod.start-from.out-of-stock-p {
	min-width: auto;
}

@media screen and (min-width: 768px) {
	.category-weight-loss .page-header .view-all-treatment button {
		line-height: 50px;
	}

	.category-weight-loss .page-header .customMenu .custom-menu-ul {
		margin-top: 0 !important;
	}

	.category-weight-loss .page-header .rating-header {
		position: relative;
	}

	.category-weight-loss .page-header .logo {
		margin-top: 35px;
	}

	.category-weight-loss .page-header .logo img {
		float: left;
	}

	.category-weight-loss .page-header .rating-header {
		width: 175px;
		display: inline-block;
		text-align: center;
		margin-top: 35px;
	}

	.category-weight-loss .page-header .btn-login-signup a, .category-weight-loss .page-header .minicart-wrapper {
		margin-top: 35px;
	}

	.category-weight-loss .page-header .rating-header p {
		margin-left: 0 !important;
		margin-top: 0;
	}

	.category-weight-loss .page-header .rating-header img {
		float: none;
	}

	.category-weight-loss .page-header .custom-menu-ul li.trustpoilet {
		width: 300px;
		margin-top: 30px;
	}

	.category-weight-loss.catalog-category-view .slider-wrapper.desk-review-slider #slide-arrow-prev, .category-weight-loss.catalog-category-view .slider-wrapper.desk-review-slider #slide-arrow-next {
		height: 50px;
		width: 50px;
		border-radius: 50px !important;
		background-color: #fff;
		display: flex;
		align-items: center;
		justify-content: center;
		opacity: 1;
	}

	.category-weight-loss.catalog-category-view .slider-wrapper.desk-review-slider .slide-arrow {
		top: 35% !important;
	}

	.category-weight-loss .hm-meet-team .owl-carousel .owl-item .banner-item {
		height: 270px;
		overflow: hidden;
	}

	.category-weight-loss .hm-meet-team .owl-carousel .owl-item .banner-item .banner-image img {
		height: auto;
	}

	.category-weight-loss.catalog-category-view .footer-right .accordion-tab {
		float: left;
	}

	.category-weight-loss.page-products.page-layout-1column .products-grid .product-item.custom-col-category {
		width: 30% !important;
		margin: 5px 15px;
	}

	.category-weight-loss.page-products .product-item-info.custom-col-wrapper-category .product-item-details {
		text-align: left;
	}

	.category-weight-loss.catalog-category-view .how-it-works-section {
		padding: 40px 0 50px 0 !important;
	}
}

@media only screen and (max-width: 767px) {
	.category-weight-loss .h-banner-content {
		width: 88% !important;
		padding: 20px 10px;
	}

	.category-weight-loss .homepage-banner-new-mobile {
		margin-top: -20px;
		padding-bottom: 15% !important;
		margin-bottom: 20px;
	}

	.category-weight-loss .mob-consult-btn {
		display: block;
		position: fixed;
		bottom: 0;
		background-color: #FEECEC;
		margin: 0;
		padding: 14px 0px;
		z-index: 999999999;
		width: 100%;
		text-align: center;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new {
		display: none !important;
	}

	.category-weight-loss.catalog-category-view .page-main {
		padding-top: 0;
		padding-left: 0 !important;
		padding-right: 0 !important;
	}

	.category-weight-loss.catalog-category-view.page-layout-1column .category-cms {
		margin-top: 0px !important;
	}

	.category-weight-loss.catalog-category-view header .header.content {
		padding-bottom: 0px !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new-mobile .h-banner-content-sec h2 {
		font-size: 33px !important;
		line-height: 36px !important;
		margin-left: 0 !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new-mobile .h-banner-content-sec {
		width: 52% !important;
		float: right !important;
		margin-right: 25px !important;
	}

	.category-weight-loss.catalog-category-view .review-content-mobile {
		text-align: center;
		width: 100%;
		margin-bottom: 0;
		border-bottom: 1px solid #eee;
		padding-bottom: 18px;
	}

	.category-weight-loss .hm-meet-team .custom-slider .owl-carousel .banner-item .content_slider .buttons .custom_content {
		padding: 0 10px !important;
	}

	.category-weight-loss .product-faq-section .container {
		width: 90%;
	}

	.category-weight-loss .hm-meet-team .content-heading .title {
		text-align: left;
		margin-left: 10px;
		margin-top: 0;
	}

	.category-weight-loss .product-faq-section .h-title {
		font-size: 32px !important;
		line-height: 38px !important;
		text-align: left !important;
	}

	.category-weight-loss .footer-consultation .h-banner-btn a {
		width: auto !important;
		padding: 0 30px !important;
	}

	.category-weight-loss .footer-link .main-container {
		padding: 0 !important;
	}

	.category-weight-loss .timeframe-subheading ul {
		display: block !important;
	}

	.category-weight-loss .hm-meet-team .content-heading .title {
		margin-bottom: 5px;
	}

	.category-weight-loss .pages .item {
		position: relative;
	}

	.category-weight-loss.catalog-category-view .products-grid .product-items.custom-row-category {
		width: 90%;
	}

	.category-weight-loss.catalog-category-view .post-holder .post-header .post-info {
		padding: 0;
	}

	.category-weight-loss.catalog-category-view .products-grid .h-title {
		width: auto;
		float: left;
		padding: 0 15px;
		margin: 0 0 35px 0;
		font-size: 32px;
		color: #101010;
		font-family: 'Lato', sans-serif;
		line-height: 40px;
		font-weight: 300;
		text-align: left;
	}

	.category-weight-loss.catalog-category-view .products-grid {
		margin-top: 0 !important;
	}
}

@media only screen and (min-width:768px) and (max-width:1024px) {
	.category-weight-loss .page-header {
		padding: 0 10px;
	}

	.category-weight-loss .page-header .custom-menu-ul li.trustpoilet {
		display: none !important;
	}

	.category-weight-loss .page-header .header.content .customMenu {
		width: 460px !important;
	}

	.category-weight-loss .page-header .btn-login-signup a, .category-weight-loss .page-header .minicart-wrapper {
		margin-top: 0 !important;
	}

	.category-weight-loss .page-header .header.content .customMenu .view-all-treatment button {
		line-height: 52px !important;
	}

	.category-weight-loss .page-header .logo {
		margin-left: 0 !important;
	}

	.category-weight-loss .page-wrapper {
		margin: 0 !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new {
		background-position: 60% -40px !important;
		margin-top: 0px;
	}

	.category-weight-loss.catalog-category-view .h-banner-content {
		width: 84% !important;
		padding-left: 20px !important;
		padding-right: 20px !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new .h-banner-content h2 {
		font-size: 33px !important;
		line-height: 36px !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new .banner-left-c {
		width: 230px !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new .banner-right-c {
		width: 265px !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new .review-content img {
		width: 46% !important;
		margin-right: 20px !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new .banner-right-c ul li {
		width: 130px !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new .h-banner-btn a {
		width: 100% !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new .review-content {
		margin-left: 85px !important;
		width: auto !important;
	}

	.category-weight-loss.catalog-category-view .weight-loss-journey .container {
		width: 100%;
		text-align: left;
		display: inline-block;
	}

	.category-weight-loss.catalog-category-view .weight-loss-journey .h-title {
		font-size: 34px !important;
	}

	.category-weight-loss.catalog-category-view .custom_content .subsection-content2 {
		margin-top: 100px !important;
	}

	.category-weight-loss.page-products.page-layout-1column .products-grid .product-item.custom-col-category {
		margin-right: 15px !important;
		margin-left: 15px !important;
	}

	.category-weight-loss.catalog-category-view .products-grid .product-items.custom-row-category {
		width: 95% !important;
	}

	.category-weight-loss .custom-col-wrapper-category .simple-prod.start-from {
		padding-left: 20px !important;
		padding-right: 20px !important;
	}
}

@media only screen and (min-width:992px) and (max-width:1024px) {
	.category-weight-loss .page-header .header.content .customMenu, .category-weight-loss .page-header .minicart-wrapper {
		margin-top: 25px !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new {
		background-position: 60% 40px !important;
		margin-top: 30px;
	}
}

.category-weight-loss.catalog-category-view .category-view .category-description, .category-weight-loss.catalog-category-view .start-my-consultation-btn , .category-weight-loss.catalog-category-view .category-view .page-title-wrapper {
	margin-left: 5%;
}

@media only screen and (max-width: 767px) {
	.category-weight-loss.catalog-category-view .category-view .category-description, .category-weight-loss.catalog-category-view .start-my-consultation-btn, .category-weight-loss.catalog-category-view .category-view .page-title-wrapper {
		margin-left: 0 !important;
		padding: 0 15px;
	}

	.category-weight-loss.catalog-category-view .weight-loss-journey {
		margin-top: 50px;
	}
}

@media only screen and (min-width:1400px) and (max-width:1800px) {
	.category-weight-loss.catalog-category-view .category-view .category-description, .category-weight-loss.catalog-category-view .start-my-consultation-btn , .category-weight-loss.catalog-category-view .category-view .page-title-wrapper {
		margin-left: 13% !important;
	}

	.category-weight-loss.catalog-category-view .category-view .category-description, .category-weight-loss.catalog-category-view .category-view .page-title-wrapper {
		width: 51% !important;
	}

	.category-weight-loss.catalog-category-view .category-view .category-image {
		margin-right: 4% !important;
	}
}

@media only screen and (min-width:1800px) and (max-width:2000px) {
	.category-weight-loss.catalog-category-view .category-view .category-description, .category-weight-loss.catalog-category-view .start-my-consultation-btn , .category-weight-loss.catalog-category-view .category-view .page-title-wrapper {
		margin-left: 17% !important;
	}

	.category-weight-loss.catalog-category-view .category-view .category-description, .category-weight-loss.catalog-category-view .category-view .page-title-wrapper {
		width: 47% !important;
	}

	.category-weight-loss.catalog-category-view .category-view .category-image {
		margin-right: 6% !important;
	}
}

@media screen and (min-width: 1400px) {
	.catalog-category-view .meet-the-team-popup .model-content-sec {
		width: 550px !important;
		padding: 30px !important;
	}

	.catalog-category-view .meet-the-team-popup .modal-content p {
		font-size: 18px !important;
		line-height: 28px !important;
	}

	.catalog-category-view .meet-the-team-popup .modal-header {
		font-size: 24px !important;
	}
}

@media only screen and (max-width: 768px) {
	.catalog-category-view .blog-widget-recent p.h-title {
		font-size: 34px;
		font-weight: normal;
	}
}

.catalog-category-view .toolbar-products, .catalog-category-view.page-layout-1column .column.main {
	display: inline-block;
}

.page-products.catalog-category-view .columns {
	display: inline-block;
}

@media screen and (min-width: 1025px) {
	.catalog-category-view .page-footer .footer-right {
		width: 56% !important;
	}

	.catalog-category-view .footer-right .payment-icon img {
		margin-right: 12px !important;
	}

	.category-weight-loss.catalog-category-view .page-header .header.content, .category-weight-loss.catalog-category-view .homepage-banner-new .container {
		max-width: 1090px !important;
	}
}

@media only screen and (min-width: 768px) and (max-width: 991px) {
	.catalog-category-view .footer-link .container {
		max-width: 100% !important;
	}

	.category-weight-loss.catalog-category-view .footer-right .accordion-tab {
		float: left;
		max-width: 100%;
		width: 50% !important;
	}

	.category-weight-loss.catalog-category-view .footer-right .accordion-tab.socila-media-tab {
		float: left;
		max-width: 100%;
		width: 100% !important;
	}

	.category-weight-loss.catalog-category-view .meet-team-section2 .team-2 {
		width: 230px !important;
		margin: 0 5px !important;
		padding: 44px 10px !important;
	}

	.category-weight-loss.catalog-category-view .footer-blog {
		padding-bottom: 0 !important;
	}

	.category-weight-loss.catalog-category-view .how-it-works-section .Works-1 {
		margin: 0 10px !important;
	}

	.category-weight-loss.catalog-category-view .how-it-works-section .Works-1 .h-title-2 br {
		display: none;
	}

	.category-weight-loss.catalog-category-view .how-it-works-section {
		width: 100% !important;
	}

	.category-weight-loss.catalog-category-view .how-it-works-section .h-banner-btn {
		margin-top: 30px;
		margin-bottom: 0 !important;
	}

	.category-weight-loss.catalog-category-view .slider-wrapper.desk-review-slider .slide-arrow {
		top: 20% !important;
	}
}

@media only screen and (max-width: 768px) {
	.category-weight-loss.catalog-category-view .mob-consult-btn {
		display: block;
		position: fixed;
		bottom: 0;
		background-color: #FEECEC;
		margin: 0;
		padding: 14px 0px;
		z-index: 999999999;
		width: 100%;
		text-align: center;
	}

	.category-weight-loss.catalog-category-view .mob-consult-btn a {
		width: 90% !important;
		background-color: #ec3237;
		color: #ffffff;
		padding: 19px 17px 17px 17px;
		display: inline-block;
		text-transform: uppercase;
		border-radius: 30px;
	}
}

.category-weight-loss.catalog-category-view .category-view .page-title-wrapper, .category-weight-loss.catalog-category-view .category-view .category-description, .category-weight-loss.catalog-category-view .category-view .category-image, .category-weight-loss.catalog-category-view .start-my-consultation-btn {
	display: none !important;
}

.category-weight-loss.catalog-category-view .page-wrapper .page-main {
	margin-top: 30px;
}

@media screen and (max-width: 767px) {
	.category-weight-loss.catalog-category-view .category-view .page-title-wrapper, .category-weight-loss.catalog-category-view .category-view .category-description, .category-weight-loss.catalog-category-view .category-view .category-image, .category-weight-loss.catalog-category-view .start-my-consultation-btn, .category-weight-loss.catalog-category-view.amform-body .category-view .category-description.main-cat-desc {
		display: none !important;
	}

	.catalog-category-view.category-weight-loss .custom-col-wrapper-category .price-box {
		margin-top: 0;
	}
}

.category-weight-loss.page-products .custom-col-wrapper-category .simple-prod.start-from.out-of-stock-p {
	background: #EBEBEB;
	display: inline-block;
	border-radius: 26px;
	padding: 16px 0px !important;
	min-width: 151px !important;
	text-align: center;
	font-size: 13px !important;
	font-weight: 400 !important;
	font-family: 'Ubuntu', sans-serif !important;
	color: #ed3237;
	text-transform: uppercase;
}

.category-weight-loss.page-products .product-item-info.custom-col-wrapper-category .product-item-details {
	margin-top: 0;
}

@media screen and (min-width: 768px) {
	.category-weight-loss.page-products .product-item-info.custom-col-wrapper-category .product-item-name-wrapper {
		height: 70px;
	}

	.catalog-category-view.category-weight-loss .products-grid .product-items.custom-row-category .price-box, .category-weight-loss.page-products .custom-col-wrapper-category .start-from.out-of-stock-p, .category-weight-loss.page-products .custom-col-wrapper-category .simple-prod.start-from.out-of-stock-p {
		float: left;
		margin: 0;
	}
}

.catalog-category-view.category-weight-loss .product-item-info.custom-col-wrapper-category .price-box span.normal-price {
	padding: 15px 25px;
	border-radius: 26px;
	font-size: 13px !important;
	font-weight: 400 !important;
	font-family: 'Ubuntu', sans-serif !important;
	color: #fff;
	display: inline-block;
}

.catalog-category-view.category-weight-loss .custom-col-wrapper-category .price-box .price-label, .catalog-category-view.category-weight-loss .product-item-info.custom-col-wrapper-category .price-box span.normal-price span span.price {
	font-size: 13px !important;
	font-weight: 400 !important;
	font-family: 'Ubuntu', sans-serif !important;
	color: #fff;
}

.category-weight-loss.page-products .custom-col-wrapper-category .start-from.out-of-stock-p, .category-weight-loss.page-products .custom-col-wrapper-category .simple-prod.start-from.out-of-stock-p {
	font-size: 13px !important;
	font-weight: 400 !important;
	font-family: 'Ubuntu', sans-serif !important;
	padding: 16px 0 !important;
	min-width: 151px;
}

.category-weight-loss.page-products .product-item-info.custom-col-wrapper-category .product-item-price {
	margin-top: 15px;
}

.catalog-category-view.category-weight-loss .page-wrapper > .breadcrumbs {
	display: none;
}

.category-weight-loss.catalog-category-view .category-cms .pages .item.pages-item-next, .category-weight-loss.catalog-category-view .category-cms .pages .item.pages-item-previous {
	display: none;
}

.h-banner-content-sec .review-content img, .category-weight-loss.page-products.page-layout-1column .products-grid .product-item.custom-col-category {
	transition: transform .2s;
}

.category-weight-loss.page-products.page-layout-1column .products-grid .product-item.custom-col-category:hover {
	transform: scale(1.03);
}

.h-banner-content-sec .review-content img:hover {
	transform: scale(1.05);
	box-shadow: 0 1px 10px 1px rgb(0, 0, 0, 15%);
}

@media screen and (min-width: 1025px) {
	.header.content .customMenu {
		width: 74% !important;
	}

	.custom-menu-ul .trustpilot-widget {
		margin-top: 15px;
	}

	.category-weight-loss .google_translate-section {
		margin-bottom: 0;
	}
}

.category-weight-loss .hm-meet-team h3 {
	display: block !important;
	padding: 0;
	margin: 20px 0 20px 0;
	font-size: 38px;
	color: #101010;
	font-family: 'Lato', sans-serif;
	line-height: 48px;
	font-weight: 300;
	text-align: center;
}

@media screen and (max-width: 767px) {
	.category-weight-loss .hm-meet-team h3 {
		font-size: 32px;
		color: #101010;
		font-family: 'Lato', sans-serif;
		line-height: 42px;
		font-weight: 300;
		text-align: left !important;
		margin-left: 10px;
		margin-bottom: 0 !important;
	}

	.catalog-category-view.category-weight-loss .page-wrapper > .breadcrumbs {
		display: none !important;
	}
}

@media screen and (max-width: 767px) {
	.category-weight-loss .footer-link {
		padding: 0 10px;
	}

	.category-weight-loss .product-faq-section .h-title {
		font-weight: 300 !important;
	}
}

@media screen and (min-width: 768px) {
	.category-weight-loss .google_translate-section .container {
		max-width: 1090px !important;
	}
}

@media screen and (min-width: 768px) {
	.category-weight-loss.catalog-category-view .homepage-banner-new {
		width: 100%;
		float: left;
		padding: 0;
		margin: 0;
        /*background: url('https://www.pharmacyplanet.com/pub/media/weight-loss-banner-n.jpg') 0% 0 no-repeat !important;*/
		background-attachment: scroll !important;
		background-size: cover !important;
	}
}

@media screen and (min-width: 1800px) {
	.category-weight-loss.catalog-category-view .homepage-banner-new {
		height: 1120px !important;
	}
    


 @	media screen and (max-width: 767px) {
		.category-weight-loss .homepage-banner-new-mobile{
		background: url('https://www.pharmacyplanet.com/pub/media/weight-loss-banner-mobile.jpg') 0% 0 no-repeat !important;
		height: 370px;
		background-attachment: scroll !important;
		background-size: cover !important;
	}

	.category-weight-loss.catalog-category-view .homepage-banner-new-mobile .h-banner-content-sec h2 {
		color: #000 !important;
	}
}

@media screen and (max-width: 767px) {
	
	.category-weight-loss .slider-wrapper.desk-review-slider.google-review-section,
	.category-weight-loss .google-review-section.mobile {
		display: none;
	}

	.category-weight-loss.catalog-category-view .weight-loss-journey {
		margin-top: 0 !important;
	}
}

.trustpilot-widget {
	width: 100%;
	display: inline-block;
	margin-top: 20px;
}

@media screen and (min-width: 1025px) {
	.catalog-category-view.category-weight-loss .page-footer .footer-right {
		width: 56% !important;
	}
}

@media only screen and (min-width: 992px) and (max-width: 1024px) {
	.catalog-category-view.category-weight-loss  .page-footer .footer-right {
		width: 56% !important;
	}
}

.category-weight-loss .product-item-info.custom-col-wrapper-category, 
.category-weight-loss .products-grid .product-item-info:hover, 
.category-weight-loss .products-grid .product-item-info.active {
	height: auto;
}



</style>