 
<style>

.product-faq-section .faq-list input {
    display: none;
}

.product-faq-section .faq-list label {
    text-align: left;
    letter-spacing: 0px;
    color: #000000;
    opacity: 1;
    padding: 20px 0 8px 0;
    width: 100%; 
    border: none;
    outline: none;
    transition: 0.4s;
    box-shadow: none !important;
    font-family: 'Lato', sans-serif;
    font-size: 18px;
    font-weight: 700;
    line-height: 28px;
    transition: ease .5s;
    display: inline-block;
    background: url(/pub/media/wysiwyg/WLImage/Poly.png) right 32px no-repeat !important;

}

.product-faq-section .faq-list label:hover,
.product-faq-section .faq-list label:focus{
    background: url(/pub/media/wysiwyg/WLImage/Poly.png) right 32px no-repeat !important;
}

.product-faq-section .faq-list .panel-p {
    text-align: left;
    letter-spacing: 0px;
    font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 24px;
    font-weight: 400;
    text-align: left;
    padding: 0px 0;
    padding: 0 0;  
    background: transparent;
    overflow: hidden;
      max-height: 0px;
      transition: max-height 0.5s ease;
}
.product-faq-section .faq-list .panel-p:target{
      max-height: 150px;
}
.product-faq-section .faq-list .panel-p p{
    font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 24px;
    font-weight: 400;
    text-align: left;
    padding: 0px 0 15px 0;
    margin: 0;
}

.product-faq-section .faq-list input + label + .panel-p { 
    overflow: hidden;
      max-height: 0px;
      transition: max-height 0.3s ease-out;
}

.product-faq-section .faq-list input:checked + label + .panel-p { 
    max-height: 165px;
}


.product-faq-section{
    width: 100%;
    float: left;
    padding: 80px 0 80px 0;
    margin: 0;
    background: #E7F2F4;
}
.product-faq-section .h-title {
        width: 100%;
        float: left;
        padding: 0;
        margin: 0 0 22px 0;
        font-size: 38px;
        color: #101010;
        font-family: 'Lato', sans-serif;
        line-height: 48px;
        font-weight: 300;
        text-align: center;
}
.product-faq-section .faq-list {
    border-bottom: 1px solid #96D8F0;
    padding-bottom: 12px;
    width: 100%;
    display: inline-block;
}

@media screen and (min-width: 768px) {
    .product-faq-section .container {
        max-width: 670px !important;
        margin: 0 auto;
    }
    .product-faq-section .faq-list label{
        cursor: pointer;
    }
}

@media screen and (max-width: 767px) {
    .product-faq-section .h-title{
        text-align: left;
        padding-left: 15px;
        padding-right: 15px;
        width: auto !important;
        font-weight: 300;
        margin: 0 0 25px 0;
        font-size: 32px;
        color: #000;
        font-family: 'Lato', sans-serif;
        line-height: 36px;
        font-weight: 400;
        text-align: left;
        padding: 0px 0;
        letter-spacing: 0px;
    }
    .product-faq-section .container{
        width: 90%;
    }
    .product-faq-section .faq-list label{
        font-size: 15px !important;
        padding-left: 0 !important;
        padding-right: 20px !important;
        line-height: 22px;
    }
     
    .product-faq-section .faq-list .panel-p p{
        font-size: 14px !important;
        line-height: 22px !important;
    }
}

</style>


<div class="product-faq-section">
<div class="container reveal1">
<div class="h-title">Weight Loss everything you need to know</div>


<div class="faq-list">
  <input type="checkbox" id="title1" />
  <label for="title1">What is Pharmacy Planet’s Weight Loss Clinic?</label>
  <div class="panel-p">
    <p>Pharmacy Planet’s Weight Loss Clinic is an online pharmacy dedicated to facilitating weight loss through clinical means. Our team includes UK registered clinicians, weight loss experts, and a supportive customer service team that aims to help you reach the very pinnacle of your weight loss goals.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title2" />
  <label for="title2">What do I get with Pharmacy Planet’s weight loss program?</label>
  <div class="panel-p">
    <p>Our approach to weight loss is simple: A healthier lifestyle partnered with scientifically backed treatment. This combined approach will tackle both the physical and mental aspects of losing weight, helping you not only to look good but feel good as well. We not only offer support from a weight related angle but from a clinical perspective. So, if you feel like the medication you have requested isn’t quite working for you, our helpful team of clinicians will be able to get down to the root of the problem and provide an unparalleled level of help.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title3" />
  <label for="title3">What can I expect in the online clinical consultation form?</label>
  <div class="panel-p">
    <p>Our clinical consultation form will cover questions regarding your height, weight, medical history, and lifestyle. Our team of clinicians will assess your order to see whether the treatment is suitable for you. This should take you a few minutes to fill in.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title4" />
  <label for="title4">What results can I achieve from joining Pharmacy Planet’s Weight Loss Clinic?</label>
  <div class="panel-p">
    <p>Everyone’s response to clinical weight loss varies, so results can differ from person to person. With all suggested weight loss medicines accompanied by a healthier lifestyle, you can expect to lose up to as much as 15% of your body weight over a 6-month period. It’s important to set realistic milestones and ensure that you are putting just as much effort into maintaining exercise and dieting habits as you are into consistently taking the medication.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title5" />
  <label for="title5">Where is Pharmacy Planet’s Weight Loss Clinic based?</label>
  <div class="panel-p">
    <p>Pharmacy Planet’s Weight Loss Clinic is based in the UK, with all weight loss medicines being sourced only from UK accredited suppliers.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title6" />
  <label for="title6">What is the role of medication in Pharmacy Planet’s weight loss program?</label>
  <div class="panel-p">
    <p>Medications such as Wegovy and Mounjaro act to jumpstart your weight loss journey and gradually ease you into living a healthier lifestyle. There are a number of different medicine options on the program, each of which has been shown to facilitate weight loss.</p>
  </div>
</div>

<div class="faq-list">
  <input type="checkbox" id="title7" />
  <label for="title7">How can I get in touch with Pharmacy Planet’s Weight Loss Clinic?</label>
  <div class="panel-p">
    <p>You can get in touch with our helpful Pharmacy Planet team via our email: headoffice@pharmacyplanet.com, or alternatively you can call us on 0800 978 8956. Our friendly customer service team will be happy to assist you.</p>
  </div>
</div>


</div>
</div>

<script>
        document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(checkbox => {
            checkbox.addEventListener('change', function () {
                if (this.checked) {
                    document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(otherCheckbox => {
                        if (otherCheckbox !== this) {
                            otherCheckbox.checked = false;
                        }
                    });
                }
            });
        });
    </script>

 
