 <!-- Experience Stories -->
 <div class="stories-section">
    <div class="container">
      <div class="h-title">Experience stories</div>
      <div class="story-1 reveal1">
        <img src="/media/wysiwyg/WLImage/fatty.png" alt="fatty">
        <div class="subsection-content">
          <img src="/media/wysiwyg/WLImage/Groupstar.png" alt="star image">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer rhoncus odio et leo lobortis faucibus sed quis sapien. In ut diam id dui commodo feu.</p>
          <p>
            <strong>EMMI</strong>
          </p>
        </div>
      </div>
      <div class="story-1 reveal1">
        <img src="/media/wysiwyg/WLImage/slim.png" alt="slim">
        <div class="subsection-content">
          <img src="/media/wysiwyg/WLImage/Groupstar.png" alt="star image">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer rhoncus odio et leo lobortis faucibus sed quis sapien. In ut diam id dui commodo feu.</p>
          <p>
            <strong>EMMI</strong>
          </p>
        </div>
      </div>
      <div class="story-1 reveal1">
        <img src="/media/wysiwyg/WLImage/black.png" alt="black">
        <div class="subsection-content">
          <img src="/media/wysiwyg/WLImage/Groupstar.png" alt="star image">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer rhoncus odio et leo lobortis faucibus sed quis sapien. In ut diam id dui commodo feu.</p>
          <p>
            <strong>EMMI</strong>
          </p>
        </div>
      </div>
    </div>
  </div>

