<!-- Our testimonials -->

<div class="home-testimonilas inner">
    <div class="container">
    <div class="h-title">Our testimonials</div>
    <div class="testimonials-list reveal1">
        <div class="rating-img-1"><img src="/media/wysiwyg/WLImage/Groupstar.png" alt="star image"></div>
         
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer rhoncus odio et leo lobortis faucibus sed quis sapien. In ut diam id dui commodo feu.</p>
            <p><strong>EMMI</strong></p>
         
    </div>

    <div class="testimonials-list reveal1">
        <div class="rating-img-1"><img src="/media/wysiwyg/WLImage/Groupstar.png" alt="star image"></div>
         
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer rhoncus odio et leo lobortis faucibus sed quis sapien. In ut diam id dui commodo feu.</p>
           <p><strong>EMMI</strong></p>
       
    </div>

    <div class="testimonials-list reveal1">
        <div class="rating-img-1"><img src="/media/wysiwyg/WLImage/Groupstar.png" alt="star image"></div>
         
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer rhoncus odio et leo lobortis faucibus sed quis sapien. In ut diam id dui commodo feu.</p>
            <p><strong>EMMI</strong></p>
        
    </div>

  </div>

</div>