<?php $collection = $block->getCollection() ?>
    <div class="category-slider">
        <div class="slick-slider">
            <?php foreach ($collection->getData() as $item) :?>
                <div class="item">
                    <?php $imagePath = $block->getImagePath($item['category_id']); ?>
                        <img src="<?= $imagePath ?>" alt="<?= $item['title'] ?>" />
                        <p>
                            <?= $item['name'] ?>
                        </p>
                </div>
                <?php endforeach ;?>
        </div>
    </div>











<h2>Medication and Treatment Categories</h2>
<?php $categories = array_chunk($collection->getData(), 4);?>
<div class="row">
    <?php foreach ($categories as $categories_chunks) : ?>
        <div class="column">
            <ul>
                <?php  foreach ($categories_chunks as $item) : ?>
                    <?php $url = '/advice/post/view?id='. $item['entity_id']; ?>
                   <li> 
                    <a href="<?= $url ?>" > <?= $item['name'] ?></a>
                </li>
                <?php endforeach ;?>
            </ul>
        </div>
    <?php endforeach; ?>    
</div>    





<style type="text/css">
  .row {
    display: flex;
  }

  .column {
    padding: 0px 30px;
  }
</style>








    <script type="text/javascript">
        require(['jquery', 'jquery/ui', 'slick'], function($){
    $(document).ready(function() {
        $('.slick-slider').slick({
            dots: true,
            infinite: false,
            slidesToShow: 4,
            slidesToScroll: 4,
            autoplay: false
        });
    });
});
    </script>

    <style>
        .category-slider {
            
        }
        
        .item img {
            height: 300px;
            width: 300px;
        }
    </style>