
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": "https://magento-1584919-6629151.cloudwaysapps.com/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "<?php echo $this->getProduct()->getName(); ?>",
      "item": "<?php echo $this->getProduct()->getProductUrl(); ?>"
    }
  ]
}
    </script>