<div class="need-help-section">
  <div class="container">
    <h2>Need Help?</h2>
    <div class="new-two-column">
      <div class="left-column reveal-l"><img src="<?php echo $this->getBaseUrl();?>media/wysiwyg/WLImage/need-help.png" alt="question mark"></div>
      <div class="right-column revealr">
        <div class="content-title">
          Do you have a question about weight loss treatment?
        </div>
        <p>Start your weight loss journey heading in the right direction. Our team are here to help. Whether you’re unsure about which medicine is right for you or need help navigating the world of weight loss drugs, our team are on hand to help you make the right decision. We can put you in touch with one of our experienced weight loss clinicians so you can be sure you’re making the best decision with the most accurate information.</p>
        <p>To get in touch, contact our Customer Service team on <a href="tel:08009788956">0800 978 8956</a> or email <a href="mailto:headoffice@pharmacyplanet.com">headoffice@pharmacyplanet.com</a>.</p>
      </div>
    </div>
  </div>
</div>

