<!-- <div class="product-info-cont-1">
<div class="info-cont-1">
<p>UK licenced medication</p>     
</div>

<div class="info-cont-2">
<p>Cancel any time</p>     
</div>

<div class="info-cont-3">
<p>100% Discretion & Confidentiality</p>     
</div>

<div class="info-cont-4">
<p>TrustScore 4.8</p>     
</div>

</div> -->




<div class="product-info-cont-1 product-mhra-section">

    <div class="info-mhra-logo-sec">
        <div class="img-1-n">
        <a href="https://uk.trustpilot.com/review/magento-1584919-6629151.cloudwaysapps.com" target="_blank" rel="noreferrer"><img src="<?php echo $this->getViewFileUrl('images/trustpilot-logo-info.png'); ?>" alt="Trustpilot"  /></a></div>
        <div class="img-1-n">
        <img src="/static/frontend/Custom/luma_child/en_GB/images/mhra.svg" data-original="<?php echo $this->getViewFileUrl('images/mhra.svg'); ?>" alt="MHRA"  /></div>
        <div class="img-1-n">
        <img src="/static/frontend/Custom/luma_child/en_GB/images/sagepay-logo1.png" data-original="<?php echo $this->getViewFileUrl('images/pharmacy-logo.svg'); ?>" alt=""  /></div>
        <div class="img-2-n">
        <img src="/static/frontend/Custom/luma_child/en_GB/images/pharmacy-logo.svg" data-original="<?php echo $this->getViewFileUrl('images/sagepay-logo1.png'); ?>" alt="Sagepay"  /></div>

    </div>

    <div class="product-cont-right">
    <div class="info-cont-1">
        <p>UK licenced<br> medication</p>     
    </div> 
    <div class="info-cont-3">
        <p>100% Discretion<br> & Confidentiality</p>     
    </div>
    <div class="info-cont-2">
        <p>Cancel any<br> time</p>     
    </div>
    
    <!-- <div class="info-cont-4">
        <p>TrustScore 4.8</p>     
    </div> -->
</div>
</div>