<?php 
    $_product = $block->getProduct();
     $proCustopt = $_product->getOptions();
    $productDesc = $_product->getData('short_description');
    $prodPrice = $_product->getPriceInfo()->getPrice('final_price')->getValue();
    $prodStock = $_product->isSaleable();
?>

<div class="prod-desprection">
    <?php if($productDesc != ""){ ?>
    <div id="short-desc">
        <!--SHORT DESCRIPTIONS -->
        
        <?php echo implode(' ', array_slice(explode(' ', $productDesc), 0, 20))."\n"; ?>
        
        <span id="product-view-dots">...</span>
    </div>

    <!--FULL DESCRIPTIONS -->
    <span id="product-view-full-desc" style="display: none;">
        <?php /* @escapeNotVerified */ echo $productDesc; ?>
    </span>

    <!--READ MORE FUNCTION -->
    <a onclick="readLessReadMore()" id="product-view-desc-hh">Read full description</a>

    <?php }if($prodStock){ ?>
    <span class="select-custoption">Please make a selection</span>
    <?php } ?>
</div>

<?php
if(!($_product->isSaleable())){
?>
<div class="config-price">
<span class="price-label">Starts at</span>
<span class="price"><?php echo "£".$prodPrice; ?></span>
</div>
<?php } ?>
<script>
    function readLessReadMore() {
        var dots = document.getElementById("product-view-dots");
        var moreText = document.getElementById("product-view-full-desc");
        var btnText = document.getElementById("product-view-desc-hh");      

        if (dots.style.display === "none") {
            dots.style.display = "inline";
            btnText.innerHTML = "Read full description"; 
            moreText.style.display = "none";
            document.getElementById("short-desc").style.display = "block";
            
        } else {
            dots.style.display = "none";
            btnText.innerHTML = "Read less description"; 
            moreText.style.display = "inline";
            document.getElementById("short-desc").style.display = "none";
        }
    }
</script>