<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog tag claud sidebar template
 *
 * @var \Magefan\Blog\Block\Sidebar\TagClaud $block
 * @var \Magefan\Community\Api\SecureHtmlRendererInterface $mfSecureRenderer
 * @var \Magento\Framework\Escaper $escaper
 */

if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>
<?php $tags = $block->getTags(); ?>

<?php if (count($tags)) { ?>
<div class="widget block block-tagclaud" data-bind="scope: 'tagclaud'">
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('Tags')) ?></strong>
    </div>

    <div id="blogSidebarCloudCanvasContainer">
        <canvas style="width:100%" height="<?= $escaper->escapeHtml($block->getCloudHeight()) ?>" id="blogSidebarCloudCanvas">
            <div class="tagclaud-hld">
                <?php foreach ($tags as $tag) { ?>
                    <?php $title = $tag->getTitle() ?>
                    <span class="<?= $escaper->escapeHtml($block->getTagClass($tag)) ?>">
                        <a href="<?= $escaper->escapeUrl($tag->getTagUrl()) ?>" title="<?= $escaper->escapeHtml($title) ?>">
                            <?= $escaper->escapeHtml($title) ?>
                         </a>
                    </span>
                <?php } ?>
            </div>
        </canvas>
    </div>
</div>

<script type="text/javascript" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Magefan_Blog::js/tagcanvas.min.js')) ?>" ></script>
    <?php $script = "
    document.addEventListener('DOMContentLoaded', function() {
        try {
            TagCanvas.Start('blogSidebarCloudCanvas', null, " . /*@noEscape*/ $block->getAnimationConfig() . ");
        } catch (e) {
            /* something went wrong, hide the canvas container */
            document.getElementById('blogSidebarCloudCanvasContainer').style.display = 'none';
        }
    });
"; ?>
    <?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
<?php } ?>
