<style> 
@media screen and (min-width: 1025px) {
	.one-step-checkout-wrapper .col-mp.mp-4 {
		width: 27.333333% !important;
		margin-right: 18px;
		padding-top: 22px !important;
	}

	.one-step-checkout-wrapper .col-mp.mp-4:nth-last-child(2) { 
		padding: 22px 33px 0px 33px !important;
		width: 41.333333% !important; 
	} 
	.checkout-cart-index .form-cart,
	.checkout-cart-index .cart-discount{
		width: 65% !important;
		padding-right: 2% !important;
	}
}

.one-step-checkout-wrapper .col-mp.mp-4{
	padding: 0 10px !important;
}
.row-mp{
	margin: 0;
}
.qty-wrapper {
	padding: 0px 12px;
	min-width: auto !important;
	height: 44px !important;
	float: left;
	border-radius: 50px;
	background: #f1f7f9;
}
.qty-wrapper .qty-wrap .input-text.update {
	background: none !important;
	border: 0 !important;
	line-height: 43px;
	color: #000;
	font-family: 'Ubuntu', sans-serif;
	font-size: 13px;
	top: 0 !important; 
	width: 100% !important;
}

.remove-wrapper .button-action.remove {
	background: #ED3237 !important;
}
.opc-block-summary .minicart-items-wrapper{
	max-height: none !important;
}
.opc-block-summary .table-totals{
	padding-top: 0 !important;
}

.osc-place-order-wrapper .place-order-primary button.primary.checkout{
	background-color: #ED3237 !important;
	border-color: #ED3237 !important;
	border-radius: 0 !important;
	-webkit-transition: all 0.1s;
    -moz-transition: all 0.1s;
    -o-transition: all 0.1s;
    transition: all 0.1s;
}
.osc-place-order-wrapper .osc-multi-address-checkout{
	display: none;
}
.onestepcheckout-index-index .checkout-agreement.field.choice{
	display: flex !important;
}

.osc-trust-seal{
	margin: 0 !important;
}

@media screen and (min-width: 1200px) { 

	.account.page-layout-2columns-left .column.main {
		width: 65.7% !important; 
	}
	.block-minicart .block-content > .actions > .secondary .action.viewcart{
		line-height: 21px;
	}
	.header-container .header.content{
		padding-left: 0 !important;
		padding-right: 0 !important;
	}

}

@media screen and (min-width: 768px) {
	.searchbar .block-search { 
		margin-bottom: 0 !important;
	}

    header.page-header .custom-menu-ul .trustpilot-widget{
        margin-top: 5px !important;
    }
}


@media only screen and (max-width: 767px) {
.cms-index-index .page-main .header.searchbar {
		position: relative;
		top: -80px !important;
		padding-top: 5px;
	}

	.cms-index-index .homepage-main-banner-slider {
		margin-top: 70px;
	}
	.amcform-popup-block .amcform-popup, .categoryquest-index-index {
        background: #fff !important;
    }
    .page-layout-1column.start_consultation .product-det .product-img{
    	width: auto;
    	margin-right: 20px;
    }
    .checkout-index-index .osc-cms-block{
    	padding-top: 25px 10px;
    }
    .onestepcheckout-index-index .field.choice.checkout-agreement input:after{
    	top: 10px !important;
    	left: 0 !important;
    }
    .onestepcheckout-index-index .field.choice.checkout-agreement input{
    	top: -5px !important;
    }

}

.osc-payment-after-methods .opc-payment-additional .field .control{
	width: 65% !important;
}

.blog-page .widget.blog-search{
	background: transparent !important;
	margin: 0 !important;
	padding: 0 !important;
}
.blog-page .widget.blog-search input {
    border-radius: 0 !important;
    font-size: 14px;
    border: 0 !important;
    background: transparent !important;
    padding: 0 !important;
    height: auto;
}

.blog-post-view .post-text-hld table{
	margin-bottom: 20px;
}
.blog-post-view .post-text-hld table > thead > tr > th{
	font-weight: 700;
}
.blog-post-view .post-text-hld table > thead > tr > th,
.blog-post-view .post-text-hld table > tbody > tr > td{
  padding: 10px;
  color: #000;
}

</style>