<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        if($_category->getMagetimCategoryImageAlt()) {
            $img_alt = $_category->getMagetimCategoryImageAlt();
        } else {
            $img_alt = $_category->getName();
        }
       $_imgHtmlImag = '<img src="' . $_imgUrl . '" alt="' . $block->escapeHtml($img_alt) . '" title="' . $block->escapeHtml($_category->getName()) . '" class="image" />';
        $_imgHtmlImag = '<img src="/' . ltrim(ltrim($_imgUrl, "/pub"), "/") . '" alt="' . $block->escapeHtml($img_alt) . '" title="' . $block->escapeHtml($_category->getName()) . '" class="image" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtmlImag, 'image');
        echo '<div class="category-image hello">';
        /* @escapeNotVerified */ echo $_imgHtml;
        echo '</div>';
    }
?>
