<div class="logo-sec-top">
  
    <!-- <h2 style="color: #333;">FAST, RELIABLE, AND APPROVED</h2>
    <h1 style="color: #007bff;">Lose Weight Effectively with Wegovy</h1>
    <h2 style="color: #555;">Get Wegovy Delivered Safely and Quickly from Pharmacy Planet</h2>
    <a href="#" class="button" style="display: inline-block; padding: 10px 20px; background: #007bff; color: #fff; text-decoration: none; border-radius: 5px; margin-top: 10px;">Start Your Consultation</a> -->
   
      <div class="logo-img-1 trust-pilot-i">
       <!-- TrustBox widget - Mini -->
        <div class="trustpilot-widget" data-locale="en-GB" data-template-id="53aa8807dec7e10d38f59f32" data-businessunit-id="62de404543cebd829464951e" data-style-height="150px" data-style-width="100%">
          <a href="https://uk.trustpilot.com/review/magento-1584919-6629151.cloudwaysapps.com" target="_blank" rel="noopener">Trustpilot</a>
        </div>
      <!-- End TrustBox widget -->
      </div>
      <div class="logo-img-1">
        <img src="/media/wysiwyg/mhra.svg" alt="Web Verification Logo" >
        
      </div>
      <div class="logo-img-1">
        <img src="/media/wysiwyg/pharmacy-logo.svg" alt="Web Verification Logo" >
      </div>
</div>
 
 
