<div class="logo-sec" >
  <div class="box">
    <div class="box-img-1"><img src="/media/theme_template/delivery-shipping-shop-svgrepo-com.svg" alt="Truck Icon"></div>
    <p>Fast Delivery to your Door</p>
    <!-- <p>Experience the convenience of having your items delivered quickly and efficiently.</p> -->
  </div>
  <div class="box">
    <div class="box-img-1"><img src="/media/theme_template/star-svgrepo-com.svg" alt="Quality Icon"></div>
    <p>Quality Products Guaranteed</p>
    <!-- <p>We ensure that all our products meet the highest standards of quality.</p> -->
  </div>
  <div class="box">
    <div class="box-img-1"><img src="/media/theme_template/Mask Group 3.png" alt="Support Icon"></div>
    <p>24/7 Customer Support</p>
   <!--  <p>Our team is here to assist you anytime you need help.</p> -->
  </div>
  <div class="box">
    <div class="box-img-1"><img src="/media/theme_template/Path 3245.svg" alt="Support Icon" ></div>
    <p>24/7 Customer Support</p>
    <!-- <p>Our team is here to assist you anytime you need help.</p> -->
  </div>
</div>