<div class="custom-section-2 temp2">
    <div class="container">
        <div class="logo-sec2">
            <div class="logo-2">
                <div class="logo-img-2"><img src="media/wysiwyg/online-const-i.png" alt=""></div>
                <p>Easy Online Consultation</p>
            </div>
            <div class="logo-2">
                <div class="logo-img-2"><img src="media/wysiwyg/star-svgrepo-com.png" alt=""></div>
                <p>Trusted Online Pharmacy</p>
            </div>
            <div class="logo-2">
                <div class="logo-img-2"> <img src="media/wysiwyg/uk-i.png" alt=""></div>
                <p>UK Medical Professionals</p>
            </div>
        </div>
        <div class="logo-3">
            <img src="/media/wysiwyg/mhra.svg" alt="Web Verification Logo">

            <img src="/media/wysiwyg/pharmacy-logo.svg" alt="Web Verification Logo">
        </div>


    </div>

</div>