<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list lazyload template
 *
 * @var \Magefan\Blog\Block\Post\PostList\Toolbar\Pager $block
 * @var \Magento\Framework\Escaper $escaper
 */

if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>
<?php if ($block->useLazyload()) { ?>
    <?php
        $config = $block->getLazyloadConfig([
            'trigger_element' => '.mbblog-lazyload-trigger'
        ]);
    ?>
    <div class="mfblog-autoloader">
        <button class="mbblog-lazyload-trigger mfblog-hide-onload action primary"
                title="<?= $escaper->escapeHtml(__('See more')) ?>"
                type="button">
            <span><?= $escaper->escapeHtml(__('See more')) ?></span>
        </button>
        <div class="mfblog-show-onload" style="display: none;">
            <img class="posts-loader"
                 src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-2.gif')) ?>"
                 alt="<?= $escaper->escapeHtml(__('Posts loader')) ?>" />
        </div>
    </div>
    <?=  /* @noEscape */ $block->getLayout()->createBlock(\Magefan\Community\Block\JsScript::class)->setMethod('ajax')->toHtml() ?>
    <?php $script = "
        (function () {
            function initMfPostLazyLoad() {
                var script = document.createElement('script');
                script.src = '" . $escaper->escapeUrl($block->getViewFileUrl($block->getLazyloadJs() . '.js')) . "';
                script.addEventListener('load', () => window.mfPostLazyLoad(" . /*@noEscape*/ $config . "));
                document.head.append(script);
            };

            document.body.addEventListener('touchstart', initMfPostLazyLoad, {once: true});
            document.body.addEventListener('mouseover', initMfPostLazyLoad, {once: true});
        })();
    "; ?>
    <?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
<?php } ?>