<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Register $block */
?>

<?php
    $registerSuccessHelper = $this->helper(\Nilesh\Theme\Helper\RegisterSuccess::class);
?>

<div class="custom-block-customer-register">
    <div class="reg-header">
        <h2><?php echo __("Create an Account"); ?></h2>
        <div class="login-text">
        <p><?php echo __("Already registered?"); ?> <a href="<?php echo $block->getBaseUrl(); ?>customer/account/login">Login Here</a></p>
        </div>

    </div>


    <?= $block->getChildHtml('form_fields_before') ?>
    <?php /* Extensions placeholder */ ?>
    <?= $block->getChildHtml('customer.form.register.extra') ?>
    <form class="form create account form-create-account custom-form" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
        <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
        <div class="basic-registration-elements">
            <fieldset class="fieldset create info">
                <fieldset class="small-header">
                    <legend class="legend"><?= $block->escapeHtml(__('Create an account and make your checkout fast and easy')) ?></legend>
                </fieldset>
                <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
                <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
                <?php
                    if($registerSuccessHelper->getRefBack() == "cart" || $block->getFormData()->getRefback() == 'yes'){
                        ?>
                        <input type="hidden" name="refback" value="yes">
                        <?php
                    }else{
                        ?>
                        <input type="hidden" name="refback" value="no">
                        <?php
                    }
                ?>

                <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>


                <div class="custom-row row-phone-dob">
                    <div class="dob">
                        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
                        <?php if ($_dob->isEnabled()) : ?>
                            <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                        <?php endif ?>
                    </div>
                    <?php if ($block->getShowAddressFields()) : ?>
                        <?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
                        <?php if ($_telephone->isEnabled()) : ?>
                            <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
                        <?php endif ?>
                    <?php endif ?>
                </div>


                <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
                <?php if ($_taxvat->isEnabled()) : ?>
                    <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
                <?php endif ?>

                <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
                <?php if ($_gender->isEnabled()) : ?>
                    <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                <?php endif ?>



            </fieldset>
            <?php if ($block->getShowAddressFields()) : ?>
                <fieldset class="fieldset address">
                    <fieldset class="small-header">
                        <legend class="legend"><?= $block->escapeHtml(__('Address Information')) ?></legend>
                    </fieldset>
                    <input type="hidden" name="create_address" value="1" />

                    <?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
                    <?php if ($_company->isEnabled()) : ?>
                        <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
                    <?php endif ?>

                    <?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
                    <?php if ($_fax->isEnabled()) : ?>
                        <?= $_fax->setFax($block->getFormData()->getFax())->toHtml() ?>
                    <?php endif ?>
                    <?php //phpcs:disable ?>
                    <?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>
                    <?php //phpcs:enable ?>
                    <div class="field street required">
                        <label for="street_1" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
                        <div class="control">
                            <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>" id="street_1" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                            <div class="nested">
                                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                                <?php //phpcs:disable ?>
                                <?php for ($_i = 2, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i <= $_n; $_i++) : ?>
                                <?php //phpcs:enable ?>
                                    <div class="field additional">
                                        <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                            <span><?= $block->escapeHtml(__('Address')) ?></span>
                                        </label>
                                        <div class="control">
                                            <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                        </div>
                                    </div>
                                <?php endfor; ?>
                            </div>
                        </div>
                    </div>

                    <div class="reg-form-grouped">


                        <div class="field region required">
                            <!-- <label for="region_id" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label> -->
                            <label for="region_id" class="label"><span><?= /* @noEscape */ __('County') ?></span></label>
                            <div class="control">
                                <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" style="display:none;">
                                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                                </select>
                                <?php //phpcs:disable ?>
                                <input type="text" id="region" name="region" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>" style="display:none;">
                                <?php //phpcs:enable ?>
                            </div>
                        </div>

                        <div class="field required">
                            <label for="city" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
                            <div class="control">
                                <?php //phpcs:disable ?>
                                <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="city">
                                <?php //phpcs:enable ?>
                            </div>
                        </div>

                    </div>

                    <div class="reg-form-grouped">

                        <div class="field country required">
                            <label for="country" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
                            <div class="control">
                                <?= $block->getCountryHtmlSelect() ?>
                            </div>
                        </div>

                        <div class="field zip required">
                            <label for="zip" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
                            <div class="control">
                                <?php //phpcs:disable ?>
                                <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
                                <?php //phpcs:enable ?>
                            </div>
                        </div>
                    </div>

                    <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                    <?php if ($addressAttributes) : ?>
                        <?php $addressAttributes->setEntityType('customer_address'); ?>
                        <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                        <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                        <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
                    <?php endif;?>
                    <input type="hidden" name="default_billing" value="1">
                    <input type="hidden" name="default_shipping" value="1">
                </fieldset>

            <?php endif; ?>
            <fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <fieldset class="small-header">
                    <legend class="legend"><?= $block->escapeHtml(__('Sign-in Information')) ?></legend><br>
                </fieldset>
                <div class="reg-form-grouped">

                <div class="field required">
                    <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input type="email" name="email" autocomplete="email" id="email_address" value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                        <div style="display:none; color:#e02b27;" id="email_address-custom-error">This email address is already in use by other user</div>
                    </div>
                </div>
                <div class="field password required">
                    <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input type="password" name="password" id="password"
                            title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                            class="input-text"
                            data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                            data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                            data-validate="{required:true, 'validate-customer-password':true}"
                            autocomplete="off">
                            <button class="btn btn-link" id="showpassword" type="button"><i class="fa fa-eye" aria-hidden="true"></i></button>
                            <input type="hidden" name="password_confirmation" id="password_confirmation">
                        <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                            <div id="password-strength-meter" class="password-strength-meter">
                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                    <?= $block->escapeHtml(__('No Password')) ?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                </div>
                <!-- <div class="field confirmation required">
                    <label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
                    <div class="control">
                        <input type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                    </div>
                </div> -->

                <!-- GENERAL QUESTION -->
                    <!-- Display Div -->
                    <div class="general-question-regpage-div">
                        <input type="hidden" id="general_question" name="general_question" value="<?php echo !empty($block->getFormData()->getQuestionOne())?$block->getFormData()->getQuestionOne():0; ?>">
                        <div class="general-question-regpage-text">
                            <h5>General Health Questions</h5>
                            <h6>Would you like to fill in your General Health Questions now?</h6>
                            <p>Please note: You can update/edit this information later in the my account section, after registration.</p>
                        </div>
                        <div class="general-question-regpage-btn">
                            <button type="button" class="btn btn-primary" id="general_question_btn">General questions</button>
                        </div>


                    </div>
                <!-- GENERAL QUESTION -->

                <?php echo $block->getChildHtml('form_additional_info') ?>

                    <div class="temsCondition">
                        <input type="checkbox" value="1" name="accept_term_condition" class="required-entry">
                        <label class="accept-and-go">
                            <span>By ticking this box you confirm you have read, understood and accept our <a href="/terms-and-conditions" target="_blank" rel="noopener noreferrer">Terms & Conditions</a> and <a href="/privacy-policy" target="_blank" rel="noopener noreferrer">Privacy Policy</a></span>
                        </label>
                        <div for="accept_term_condition" generated="true" class="mage-error" style="display:none" id="accept_term_condition-error">This is a required field.</div>
                    </div>

                    <?php
                /* Newsletter */
                if ($block->isNewsletterEnabled()) : ?>
                    <div class="field choice newsletter">
                        <input type="checkbox" name="is_subscribed" title="<?= $block->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()) : ?> checked="checked"<?php endif; ?> class="checkbox">
                        <label for="is_subscribed" class="label"><span><?= $block->escapeHtml(__('Keep me informed of new product and promotions.')) ?></span></label>
                    </div>
                    <?php /* Extensions placeholder */ ?>
                    <?= $block->getChildHtml('customer.form.register.newsletter') ?>
                <?php endif ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></button>
                </div>
                <div class="secondary">
                    <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
                </div>
            </div>
        </div>

        <!-- General Question Popup -->
        <div class="general-question-elements">
            <div class="general-question-fixed">
                <!-- <span class="floating-general-question general_question_btn_cancel">X</span> -->
                <div class="main-container">
                    <div class="question-wrapper">
                        <div class="general-question-title-wrapper">
                            <div class="title">
                                <h3 class="general-question-title"><?php echo __("General Health Questions"); ?></h3>
                                <p class="general-question-text">To assess the suitability of the item you have ordered we’re going to have to ask you some brief questions regarding your general health</p>
                            </div>
                            <div class="back-to-register">
                                <span class="floating-general-question general_question_btn_cancel">< back to registration</span>
                            </div>
                        </div>
                        <div class="questiondiv">
                            <?php
                                $gq = array();
                                $gq['suffer_diagnosed'] = $block->getFormData()->getSufferDiagnosed();
                                $gq['suffer_diagnosed_yes'] = $block->getFormData()->getSufferDiagnosedYes();
                                $gq['other_medication'] = $block->getFormData()->getOtherMedication();
                                $gq['other_medication_yes'] = $block->getFormData()->getOtherMedicationYes();
                                $gq['have_allergies'] = $block->getFormData()->getHaveAllergies();
                                $gq['have_allergies_yes'] = $block->getFormData()->getHaveAllergiesYes();
                                $gq['registered_gp'] = $block->getFormData()->getRegisteredGp();
                                $gq['registered_gp_permission'] = $block->getFormData()->getRegisteredGpPermission();
                                $gq['registered_gp_surgery'] = $block->getFormData()->getRegisteredGpSurgery();
                                $gq['upload_documents_prescriber'] = $block->getFormData()->getUploadDocumentsPrescriber();
                                $gq['upload_documents_prescriber_yes'] = $block->getFormData()->getUploadDocumentsPrescriberYes();
                                $gq['prescriber_to_know'] = $block->getFormData()->getPrescriberToKnow();
                                $gq['prescriber_to_know_yes'] = $block->getFormData()->getPrescriberToKnowYes();
                            ?>
                            <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setGq($gq)->setTemplate("Nilesh_GeneralQuestions::general/fields.phtml")->toHtml() ?>
                        </div>
                        <div class="general-question-submit">
                            <div class="button">
                                <button type="button" class="btn btn-primary" id="general_question_submit">Submit</button>
                            </div>
                            <div class="back-to-register">
                                <span class="floating-general-question general_question_btn_cancel">< back to registration</span>
                            </div>
                        </div>
                    </div>
                    <div class="text-wrapper">
                        <p>Don’t forget, only our qualified prescribers see the answers you provide.</p>
                        <div class="img-wrapper">
                            <a href="https://medicine-seller-register.mhra.gov.uk/search-registry/386" rel="noreferrer">
                                <img src="<?php echo $this->getViewFileUrl('images/mhra-logo.jpg'); ?>" alt="">
                            </a>
                            <a href="https://www.pharmacyregulation.org/registers/pharmacy/registrationnumber/1035466" rel="noreferrer">
                                <img src="<?php echo $this->getViewFileUrl('images/pharmacy-img.jpg'); ?>" alt="">
                            </a>
                        </div>
                        <div class="img-wrapper">
                            <div class="trustpilot-widget" data-locale="en-GB" data-template-id="5419b6ffb0d04a076446a9af" data-businessunit-id="5b55f778afee7a0001b505dc" data-style-height="20px" data-style-width="100%" data-theme="light">
                                <a href="https://uk.trustpilot.com/review/pharmacyplanet.co.uk" target="_blank" rel="noopener">Trustpilot</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- General Question Popup -->
    </form>
</div>
<script>
require([
    'jquery',
    'mage/storage',
    'mage/mage'
], function($,storage){

    var dataForm = $('#form-validate');
    var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()) : ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else : ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

    // Open General Question Section
    $("#general_question_btn").click(function (e) {
        e.preventDefault();
        $('.basic-registration-elements').addClass('hide');
        $('.custom-block-customer-register .reg-header').addClass('hide');
        window.scrollTo(0, 0);
        $(".general-question-fixed").addClass("active");
    });

    // Close General Question
    $(".general_question_btn_cancel").click(function (e) {
        e.preventDefault();
        if(dataForm.validation('isValid')){
            $("#general_question").val(1);
        }else{
            var r = confirm("Are you sure you want to leave? \r\nGeneral Questions will not be submitted");
            if (r == true) {
                $('.basic-registration-elements').removeClass('hide');
                $('.custom-block-customer-register .reg-header').removeClass('hide');
                $("#general_question").val(0);
                $(".general-question-fixed").removeClass("active");
                var genQuestionPosition = $('.general-question-regpage-div').offset();
                window.scrollTo(0, genQuestionPosition.top);
            }
        }
    });

    // Submit of Genral Question
    $('#general_question_submit').click( function() {

        if(dataForm.validation('isValid')){
            $("#general_question").val(1);
            $('.basic-registration-elements').removeClass('hide');
            $('.custom-block-customer-register .reg-header').removeClass('hide');
            $(".general-question-fixed").removeClass("active");
            var genQuestionPosition = $('.general-question-regpage-div').offset();
            window.scrollTo(0, genQuestionPosition.top);
        }
    });

    var returnNe = false;

    $("#email_address").change(function (e) {
        e.preventDefault();
        var emailVal = $(this).val();
        var emailError = $("#email_address-custom-error");
        /*
            *this is for email availability
        */
        storage.post(
            BASE_URL+'/rest/V1/customers/isEmailAvailable',
            JSON.stringify({
                customerEmail: emailVal
            }),
            false
        ).done(function (isEmailAvailable) {
            console.log(isEmailAvailable);
            if (isEmailAvailable) {
                emailError.hide();
                returnNe = true;
            }else{
                emailError.html("This email address is already in use by other user");
                emailError.show();
                returnNe = false;
            }
        });
    });

    // Removing re-enter password
    $("#form-validate").submit(function (e) {
        /*
        *This is use for prevent revalidation
        */
        var pass = $("#password").val();
        $("#password_confirmation").val(pass);

        if(returnNe == false){
            e.preventDefault();
        }
    });

    // Add hide show password
    $("#showpassword").click(function (e) {
        e.preventDefault();
        var x = document.getElementById("password");
        if (x.type === "password") {
            x.type = "text";
            $(this).html(`<i class="fa fa-eye-slash" aria-hidden="true"></i>`);
        } else {
            x.type = "password";
            $(this).html(`<i class="fa fa-eye" aria-hidden="true"></i>`);
        }
    });

    // this is for DOB
    $('.dob-day').keyup(function(){
        if($(this).val().length >= 2){
            $(".dob-month").focus();
        }
    });

    $('.dob-month').keyup(function(){
        if($(this).val().length >= 2){
            $(".dob-year").focus();
        }
    });
});
</script>

<?php if ($block->getShowAddressFields()) : ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                <?php //phpcs:disable ?>
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                <?php //phpcs:enable ?>
                "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                <?php //phpcs:disable ?>
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
                <?php //phpcs:enable ?>
            }
        }
    }
</script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>
