<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post media gallery images template for Fancybox 2.x
 * Use this template for porto theme. Copy this file to your porto theme as
 * app/design/frontend/Smartwave/theme-name/Magefan_Blog/templates/post/view/gallery.phtml
 *
 * @var \Magefan\Blog\Block\Post\View\Gallery $block
 * @var \Magefan\Community\Api\SecureHtmlRendererInterface $mfSecureRenderer
 * @var \Magento\Framework\Escaper $escaper
 */

if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>

<?php
    $post = $block->getPost();
    $galleryImages = $post->getGalleryImages();
?>

<?php if (count($galleryImages)) { ?>
    <div class="post-gallery clearfix">
        <?php foreach ($galleryImages as $image) { ?>
            <a class="gallery-image-hld fancybox-thumb"
               href="<?= $escaper->escapeUrl($image) ?>"
               rel="fancybox-thumb">
                <?php
                    $featuredImage = $image->resize(200, null, true);
                    $imageWidthAndHeight = $featuredImage->getWidthAndHeight();
                    $addWH = !empty($imageWidthAndHeight);
                ?>
                <img class="gallery-image" src="<?= $escaper->escapeUrl($featuredImage) ?>" alt="" <?= $addWH ? 'width="' . $imageWidthAndHeight['width'] . '" height="' . $imageWidthAndHeight['height'] . '"' : '' ?>/>
            </a>
        <?php } ?>
    </div>
    <?php $script = "
    require(['jquery', 'domReady!'], function($){
        require(['fancybox/js/jquery.fancybox'], function(){
            $(document).ready(function() {
                $('.gallery-image-hld').fancybox();
            });
        });
    });
    "; ?>
    <?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
<?php } ?>
