<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post next and prev post links
 *
 * @var \Magefan\Blog\Block\Post\View\NextPrev $block
 * @var \Magento\Framework\Escaper $escaper
 */

if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>

<?php if ($block->displayLinks()) { ?>
    <?php
        $prevPost = $block->getPrevPost();
        $nextPost = $block->getNextPost();
    ?>
    <?php if ($prevPost || $nextPost) { ?>
        <div class="post-nextprev-hld clearfix">
            <?php if ($prevPost) { ?>
                <?php $title = $escaper->escapeHtml($prevPost->getTitle()) ?>
                <a class="nextprev-link prev-link"
                   href="<?= $escaper->escapeUrl($prevPost->getPostUrl()) ?>"
                   title="<?= $escaper->escapeHtml(__('Read %1', $title)) ?>">
                    <?= $escaper->escapeHtml(__('&larr; Previous')) ?>
                </a>
            <?php } ?>
            <?php if ($nextPost) { ?>
                <?php $title = $escaper->escapeHtml($nextPost->getTitle()) ?>
                <a class="nextprev-link next-link"
                   href="<?= $escaper->escapeUrl($nextPost->getPostUrl()) ?>"
                   title="<?= $escaper->escapeHtml(__('Read %1', $title)) ?>">
                    <?= $escaper->escapeHtml(__('Next &rarr;')) ?>
                </a>
            <?php } ?>
        </div>
    <?php } ?>
<?php } ?>
