<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post og:tags
 *
 * @var \Magefan\Blog\Block\Post\View\Opengraph $block
 * @var \Magento\Framework\Escaper $escaper
 */

if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>

<meta property="og:type" content="<?= $escaper->escapeHtml($block->getType()); ?>" />
<meta property="og:title" content="<?= $escaper->escapeHtml($block->getTitle()); ?>" />
<meta property="og:description" content="<?= $escaper->escapeHtml($block->getDescription()); ?>" />
<meta property="og:url" content="<?= $escaper->escapeHtml($block->getPageUrl()); ?>" />
<?php if ($image = $block->getImage()) { ?>
<meta property="og:image" content="<?= $escaper->escapeHtml($image); ?>" />
<?php } ?>