<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var \Magefan\Blog\Block\Post\View\RelatedPosts $block
 * @var \Magefan\Blog\Block\Catalog\Product\RelatedPosts $block
 * @var \Magento\Framework\Escaper $escaper
 */

if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>

<?php if ($block->displayPosts()) { ?>
    <?php $postCollection = $block->getPostCollection(); ?>
    <?php if (count($postCollection)) { ?>
    <div class="mfblog-related-posts-block block related">
        <?php if (!$block->getHideTitle()) { ?>
        <div class="block-title title">
            <strong id="block-relatedposts-heading" role="heading" aria-level="2">
                <?= $escaper->escapeHtml(__('Related Posts')) ?>
            </strong>
        </div>
        <?php } ?>
        <ol class="block-content">
            <?php foreach ($postCollection as $post) { ?>
                <li class="item">
                    <a class="post-item-link" title="<?= $escaper->escapeHtml($post->getTitle()) ?>"
                       href="<?= $escaper->escapeUrl($post->getPostUrl()) ?>">
                        <?= $escaper->escapeHtml($post->getTitle()) ?>
                    </a>
                </li>
            <?php } ?>
        </ol>
    </div>
    <?php } ?>
<?php } ?>

