<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

/**
 * @var \Magefan\Blog\Block\ViewsCount $block
 * @var \Magefan\Community\Api\SecureHtmlRendererInterface $mfSecureRenderer
 */
?>
<?= $block->getLayout()->createBlock(\Magefan\Community\Block\JsScript::class)->setMethod('sendBeacon')->toHtml() ?>
<?php $script = "
    require(['domReady!'], function(){
        setTimeout(function(){
            MagefanJs.sendBeacon({
                url: atob( '" . base64_encode($block->getCounterUrl()) . "'),
                data: {}
            });
        }, 5000);
    });
"; ?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>

