<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */

/**
 * @var $block \Magento\Catalog\Block\Adminhtml\Category\Edit
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div data-id="information-dialog-category" class="messages">
    <div class="message message-notice">
        <div><?= $block->escapeHtml(__('This operation can take a long time')) ?></div>
    </div>
</div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag('display: none;', 'div[data-id="information-dialog-category"]') ?>

<script type="text/x-magento-init">
    {
        "*": {
            "categoryForm": {"refreshUrl": "<?= $block->escapeJs($block->escapeUrl( $this->getUrl('blog/*/refreshPath', ['_current' => true]))) ?>"}
        }
    }
</script>
