<?php
/** @var \Mirasvit\Helpdesk\Block\Ticket\View\Message\Rate $block */
?>
<?php
$message = $block->getMessage();

if ($message->getTriggeredBy() != \Mirasvit\Helpdesk\Model\Config::USER) {
    return;
}
$rateUrl = $block->getRateImageUrl();
?>

<?php if ($rateUrl): ?>
    <div class="hdmx__ticket-message-rate-satisfaction">
        <div class="comment">
            <?= $block->escapeHtml($block->getSatisfactionComment(), $message->getAllowedTags()); ?>
        </div>

        <div class="rate">
            <img src="<?= $block->escapeUrl($rateUrl); ?>" alt="<?= $block->escapeHtml(__('Rate')) ?>"/>
        </div>
    </div>
<?php else: ?>
    <div class="hdmx__ticket-message-rate">
        <a href="<?= $block->escapeUrl($block->getSatisfactionUrl(1)); ?>" target="_blank">
            <img src="<?= $block->escapeUrl($block->getRateImages()[1]) ?>" alt="Bad">
            <span><?= $block->escapeHtml(__('Bad')) ?></span>
        </a>

        <a href="<?= $block->escapeUrl($block->getSatisfactionUrl(2)); ?>" target="_blank">
            <img src="<?= $block->escapeUrl($block->getRateImages()[2]) ?>" alt="Ok">
            <span><?= $block->escapeHtml(__('Ok')) ?></span>
        </a>

        <a href="<?= $block->escapeUrl($block->getSatisfactionUrl(3)); ?>" target="_blank">
            <img src="<?= $block->escapeUrl($block->getRateImages()[3]) ?>" alt="Great">
            <span><?= $block->escapeHtml(__('Great')) ?></span>
        </a>
    </div>
<?php endif ?>
