<?php
/*
 * This software is the confidential and proprietary information of Autify Digital Ltd.
 * Unauthorized use, reproduction, or distribution of this software, in whole or in part, is strictly prohibited.
 * Copyright (c) 2020-Present Autify Digital Ltd.
 * This work is protected under applicable copyright and intellectual property laws.
 * All rights reserved. Distribution and disclosure are permitted only in accordance with
 * the terms of a valid written agreement with Autify Digital Ltd.
 */
/** @var \AutifyDigital\LloydscardnetPayment\Block\Config $block */
?>
<script>
    window.googlepayConfig = <?= /* @noEscape */ $block->getJsonEncode($block->getConfig()) ?>;
    window.baseUrl = <?= /* @noEscape */ $block->getJsonEncode($block->getBaseUrl()) ?>;
    window.applePayConfig = <?= /* @noEscape  */ $block->getJsonEncode($block->getApplePayConfig()) ?>;
</script>
