<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog feedback button
 *
 * @var \Magento\Backend\Block\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */

if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>
<?php
$reviewProductUrl = 'https://magefan.com/magento2-blog-extension/reviews';
$contactUrl = 'https://magefan.com/contact';
?>
<?php if (\Magefan\Community\Model\UrlChecker::showUrl($block->getUrl())) { ?>
<div id="blog-feedback-block">
    <div class="blog-leave-feedback blog-leave-review">
        <img  src="<?= $escaper->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/feedback-ico.png')) ?>" />
        <a target="_blank"
           href="<?= $escaper->escapeUrl($reviewProductUrl); ?>">
            <?= $escaper->escapeHtml(__('Leave a review about the blog extension')) ?>
        </a>
    </div>
    <div class="blog-leave-feedback blog-leave-suggest">
        <img  src="<?= $escaper->escapeUrl($block->getViewFileUrl('Magefan_Blog::images/add-feature-ico.png')) ?>" />
        <a target="_blank"
           href="<?= $escaper->escapeUrl($contactUrl); ?>">
            <?= $escaper->escapeHtml(__('Need a new blog feature?')) ?>
        </a>
    </div>
</div>

<style>
    .blog-leave-feedback {display:inline-block;padding: 15px 15px 0 0}
    .blog-leave-feedback a {color:#000;text-decoration:underline}
    .blog-leave-feedback img {float:left; margin-right: 10px; height:20px}
</style>
<?php } ?>
