<div id="custom-selected-option">
  <div class="custom-cont">
<div class="custom-selected-option-sec">
 <h2> Selected Medication </h2>
    <div id="simple-product-name"></div>
</div>
</div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'Magento_ConfigurableProduct/js/configurable'
    ], function ($) {
        $(document).ready(function () {
            // console.clear();
            $('#custom-selected-option').insertAfter('#product-options-wrapper');
            console.log('element added')
            
            var productOptionsWrapper = $('.product-options-wrapper');
        var configurableFields = productOptionsWrapper.find('.field.configurable');

        // Get the length of configurable fields
        var length = configurableFields.length;
            console.log('get ready is called ');
        // Loop based on the length and create <div> structure
        for (var i = 0; i < length; i++) {
            let selectelement = configurableFields[i];
            let selectelementObj = $(selectelement).find('select.super-attribute-select');

            let attributeId = selectelementObj.attr('id');
            let labelText = $('label[for="' + attributeId + '"]').text().trim();
            var div = $('<div class="custom-opt-t">');
            var labelSpan = $('<p>').addClass('label '+ attributeId).text(labelText + ' : ');
            var valueSpan = $('<span>').addClass('selected_option ' + attributeId).text(' ');

            div.append(labelSpan).append(valueSpan);

            $('#simple-product-name').append(div);
        }





        // Observe changes in the selected options
        $('.super-attribute-select').on('change', function () {
          console.log('select element is changed')
          let optionValue = $(this).val();
          console.log($(this).attr('id'));

          var selectedSpan = $('span.selected_option.' + $(this).attr('id'));

          if (optionValue !== "") {
              var optionElement = $('option[value="' + optionValue + '"]');
          }else {
            var optionElement = ' ';
            selectedSpan.text(' ');
          }
          
          if (optionElement.length > 0) {
                  
            if (optionElement.attr('value') !== "") {
              selectedSpan.text(optionElement.text())
            }  else {
              selectedSpan.text('');
            }
          } else {
            console.log("Option with value '" + dynamicValue + "' not found.");
          }
        });
      });
    });
</script>




<style type="text/css">
    
    #custom-selected-option{
        width: 665px;
        float: left;
        padding: 0 30px;
        margin: 0;
        background-color: #F1F7F9;
    }
    .custom-selected-option-sec{
        width: 635px;
        padding: 10px 15px;
        display: inline-block;
        background-color: #E6EDEF;
        margin-bottom: 30px;
    }
    .start_consultation .product-info-main .custom-selected-option-sec h2{
        font-size: 13px;
        color: #000;
        font-family: 'Lato', sans-serif;
        line-height: 26px;
        font-weight: 700;
        text-align: left;
        padding:0;
        margin: 0 0 7px 0;
    }


    .custom-opt-t:nth-child(1){
      width: 100%;
      float: left;
    }
    .custom-opt-t:nth-child(2){
      width: auto;
      float: left;
      margin-right: 5%;
    }
    .custom-opt-t:nth-child(3){
      width: auto;
      float: left;
    }
    .custom-opt-t p{
      font-weight: 600 !important;
    }
    .custom-opt-t p,
    .custom-opt-t .selected_option{
      width: auto;
      float: left;
      padding: 0;
      margin: 0 10px 0 0;
      font-size: 12px;
        color: #000;
        font-family: 'Lato', sans-serif;
        line-height: 23px;
        font-weight: 400;
        text-align: left;
    }
    .catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-config-price .price-wrapper{
      top: 2px !important;
    }
    .page-layout-1column.start_consultation .product-info-main .product-config-price .price-wrapper:before{
      margin-bottom: 10px !important;
    }

    @media only screen and (max-width: 767px) {

      .page-layout-1column.start_consultation .product-det .product-name{
        line-height: 32px;
      }
      .catalog-product-view.page-layout-1column.start_consultation .field.configurable:nth-child(2),
      .catalog-product-view.page-layout-1column.start_consultation .field.configurable:nth-child(3){
        margin-bottom: 20px;
        width: 100%;
      }

      .catalog-product-view.page-layout-1column.start_consultation .field.configurable:nth-child(1),
      .catalog-product-view.page-layout-1column.start_consultation .field.configurable:nth-child(2),
      .catalog-product-view.page-layout-1column.start_consultation .field.configurable:nth-child(3){
        margin-right: 0 !important;
      }
      #custom-selected-option,
      .custom-selected-option-sec{
        width: 100% !important;
        padding:15px 0 !important;
      }

      .custom-selected-option-sec .custom-opt-t{
        width:100% !important;
      }
      div#product-options-wrapper{
        background-color: #E6EDEF;
      }
      .catalog-product-view.page-layout-1column.start_consultation .product-options-wrapper .fieldset {
        height: auto !important;
        padding-bottom: 0px !important;
      }
      .custom-selected-option-sec #simple-product-name,
      .start_consultation .product-info-main .custom-selected-option-sec h2{
        padding: 0 20px;
        display: inline-block;
      }
      .start_consultation .product-info-main .custom-selected-option-sec h2{
        width: 88% !important;
      }

      .page-layout-1column.start_consultation .product-info-main .product-config-price{
        padding-top: 0 !important;
        border-top: 0 !important;
      }
      .catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-config-price,
      .catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-options-bottom{
        width: 100% !important;
        padding-bottom: 15px !important;
      }
      .catalog-product-view.page-layout-1column.start_consultation .product-info-main .price-box{
        float: left !important;
      }
      .catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-options-bottom{
        padding-top: 15px !important;
      }
      .custom-selected-option-se{
        margin-bottom: 10px !important;
      }

      #custom-selected-option .custom-cont{
        margin: 0 20px;
      }
      .catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-det {
        padding: 25px 20px;
        width: 88%;
    }

    }





.page-layout-1column.start_consultation .product-det.mf-initial .product-desc .product-img{
  float: left !important;
}

.page-layout-1column.start_consultation .product-det .product-name{
  color: #000 !important;
}
.page-layout-1column.start_consultation .product-info-main .product-config-price {
    bottom: 0 !important;
    left: 0 !important;
}
.page-layout-1column.start_consultation .product-info-main .product-config-price .price-wrapper{
  position: relative !important;
  top: 0 !important;
}

.page-layout-1column.start_consultation .product-info-main .price-box{
  float: right !important;
  width: 200px !important; 
}

.page-layout-1column.start_consultation .product-info-main .product-config-price{
  width: 100% !important;
  background: #F1F7F9;
  display: inline-block;
  padding-bottom: 30px;
  padding-top: 30px;
  border-top: 1px solid #e7e9eb;
  float: right;
}

@media screen and (min-width: 768px) {
.catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-config-price{
  width: 50% !important;
  padding-top: 20px !important;
}
.catalog-product-view.page-layout-1column.start_consultation .product-options-bottom{
  width: 50% !important;
  padding-bottom: 15px;
  padding-top: 25px;
}
}

@media only screen and (max-width: 767px) {
  .product-options-bottom .box-tocart .actions #product-addtocart-button{
    padding-left: 30px !important;
    padding-right: 30px !important;
  }
  .page-layout-1column.start_consultation .product-info-main .price-box{
    width: 150px !important;
  }
  .page-product-configurable.catalog-product-view.page-layout-1column.start_consultation .product-options-wrapper .fieldset {
        padding-bottom: 20px !important;
    }
  .page-layout-1column.start_consultation .product-info-main .product-config-price .price-container .price {
    font-size: 35px !important;
  }
  .page-layout-1column.start_consultation .product-info-main .product-config-price .price-wrapper:before{
    margin-bottom: 10px !important;
  }

}


@media only screen and (min-width:768px) and (max-width:1024px) {

  .catalog-product-view.page-layout-1column.start_consultation .product-options-wrapper .fieldset{
    padding-left: 20px !important;
  }
  #custom-selected-option{
    padding: 0 20px !important;
    width: 100% !important;
  }
  .catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-options-bottom .box-tocart .action.tocart{
    margin-left: 20px !important;
  }
  .custom-selected-option-sec{
    width: 88% !important;
  }

}


@media only screen and (min-width:992px) and (max-width:1024px) {

  
  #custom-selected-option{
    padding: 0 20px !important;
    width: 95% !important;
  }
 
  .custom-selected-option-sec{
    width: 90% !important;
  }

}

</style>