<?php
/** @var \Mirasvit\Helpdesk\Block\Ticket\Listing\Column\DefaultColumn $block */
/** @var \Mirasvit\Helpdesk\Model\Ticket $ticket */
$ticket = $block->getItem();
$column = $block->getColumn();
?>

    <a href="<?= $block->escapeUrl($ticket->getUrl(false)) ?>" aria-label="<?= $block->escapeHtml(__('View ticket: %1', $ticket->getSubject())) ?>"><?= $block->escapeHtml($ticket->getSubject()) ?></a>
<?php if (!$ticket->getLastMessage()->getIsRead()): ?>
    <span class="unread"></span>
<?php endif ?>