<?php
// Receive from email var
$order_id = $this->getOrder();
// get Order instance
$_order = $block->getItemList($order_id);
// get Order Item
$orderItems = $_order->getAllVisibleItems();

$orderCustomerName = $_order->getCustomerName();

$orderStoreId = $_order->getStoreId();

$orderBaseUrl = $block->getStoreBaseUrl($orderStoreId);

// echo $orderCustomerName;

foreach ($orderItems as $item) {
    $product_id = $item->getProductId();
    $_product = $block->getProductUrl($product_id);
    $_productUrl = $_product->setStoreId($orderStoreId)->getProductUrl();
    $imageUrl = $block->getProductImage($_product);
    if($_productUrl){
        ?>
        <div class="order_item_grid" style="float: left;
    width: 100%; margin-bottom: 20px; border-top: 1px solid #ddd;
    padding-bottom: 20px; padding-top: 25px;">
            <div class="single_product" style="text-align: center;">
                <div class="product-image" style="float: left; border: 2px solid #ddd; margin-bottom: 20px; margin-right: 15px;">
                        <img style="width: 100px; height: 100px;" src="<?php echo $imageUrl ?>" alt="">
                </div>
                <div class="product-content" style="width: auto; float: left; margin-top: 0px; margin-left: 0px;">
                    <p class="product_name" style="width: 100%; float: left; margin-right: 20px; line-height: 24px; text-align: left; font-weight: 700;
    color: #53caf5;"><?php echo $_product->getName(); ?></p>
                    <a style="background: #53caf5; border-radius: 50px; padding: 0px 10px;  color: #FFF; font-size: 12px; margin-top: 0; height: 25px; text-decoration: none !important; line-height: 25px; float: left; -webkit-box-shadow: 1px 3px 3px 1px rgba(0, 0, 0, 0.15) !important;
-moz-box-shadow: 1px 3px 3px 1px rgba(0, 0, 0, 0.15) !important;
box-shadow: 1px 3px 3px 1px rgba(0, 0, 0, 0.15) !important; " class="reorder_icon" href="<?php echo $orderBaseUrl."reorder/index/index/referer/".base64_encode($_productUrl); ?>">
                        Reorder Now
                        <!-- <img src="https://magento24.hhhosting.co.uk/pub/media/wysiwyg/reorder-button.png" alt="Reorder" title="Reorder" /> -->
                    </a>
                </div>
            </div>
        </div>
        <?php
    }
}