<?php
/**
 * Lloyds Cardnet payment form for admin order creation
 */
/** @var \AutifyDigital\LloydscardnetPayment\Block\Form\Lcnetredirect $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="admin__field payment-method-lcnetredirect">
    <div class="admin__field-control checkout-payment-method">
        <p><?= $escaper->escapeHtml(__('Order will be placed and redirected to Lloyds Cardnet payment gateway.')) ?></p>
    </div>
</div>
