<?php
$connectId = @$_GET['connect_id'];
if(!empty($connectId)):
?>
<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document).ready(function () {
            var setterInterval = setInterval(function() {
                let getConnectId = "<?= @$connectId; ?>",
                    nameConnectId = $('input[name="connect_id"]');
                if(nameConnectId.length > 0 && nameConnectId.val() !== ""){
                        clearInterval(setterInterval);
                }
                nameConnectId.val(getConnectId).change();
            }, 1000)
        });
    });
</script>
<?php endif; ?>
