<?php /**  @var $block \Magento\Checkout\Block\Cart\Grid */ ?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= /* @escapeNotVerified */
$block->getUrl('checkout/cart/updatePost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'
      class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                 data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?></div>
        <?php endif ?>
        <section id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <!-- <caption role="heading" aria-level="2" class="table-caption"><?= /* @escapeNotVerified */
                __('Shopping Cart Items') ?></caption> -->
            
            <?php foreach ($block->getItems() as $_item): ?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </section>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                 data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?></div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= /* @escapeNotVerified */
                    __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                class="action clear" id="empty_cart_button">
            <span><?= /* @escapeNotVerified */
                __('Clear Shopping Cart') ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

<?php  
    $backLinkCart = $this->helper(\Nilesh\Theme\Helper\BackLinkCart::class);
    $isSessionSet = $backLinkCart->getBackProductId();
    // echo "Haarty-".$isSessionSet;
    if(!empty($isSessionSet)){
        $backCart = $backLinkCart->lastCartItem();
        $item_id = $backCart['item_id'];
        $product_id = $backCart['product_id'];
    }
?>
<script type="text/javascript">
    require(['jquery', 'CartQtyUpdate'], function ($) {
        <?php if(!empty($isSessionSet)): ?>
        if (window.history && window.history.pushState) {
            window.history.pushState('forward', null, null);
            $(window).on('popstate', function () {
                window.location.href = BASE_URL+'checkout/cart/configure/id/<?php echo $item_id; ?>/product_id/<?php echo $product_id; ?>#editconsultation';
            });
        }
        <?php endif; ?>
    });
</script>
<?php $backLinkCart->unSetBackProductId(); ?>