<?php
/*
 * This software is the confidential and proprietary information of Autify Digital Ltd.
 * Unauthorized use, reproduction, or distribution of this software, in whole or in part, is strictly prohibited.
 * Copyright (c) 2020-Present Autify Digital Ltd.
 * This work is protected under applicable copyright and intellectual property laws.
 * All rights reserved. Distribution and disclosure are permitted only in accordance with
 * the terms of a valid written agreement with Autify Digital Ltd.
 */

/** @var \AutifyDigital\LloydscardnetPayment\Block\Applepay\Minicart $block */
$helper = $block->getHelper();
$orderTotal = $block->getBaseGrandTotal();
?>
<?php if ($helper->displayMiniCartApplePay($orderTotal) &&
$helper->getApplepayPaymentMethodInteration() == 'onsite'):?>
    <div id="cardnet-applepay-minicart-btn"
        class="apple-pay-button-container-<?= $escaper->escapeHtmlAttr($block->getExtraClassname()); ?>"
        data-mage-init='{
             "AutifyDigital_LloydscardnetPayment/js/view/minicart-applepay": {
                 "storeName": "<?= $escaper->escapeJs($block->getStoreName()); ?>",
                 "grandTotal": "<?= $escaper->escapeJs($block->getBaseGrandTotal()); ?>",
                 "storeCountry": "<?= $escaper->escapeJs($block->getStoreCountry()); ?>",
                 "storeCurrency": "<?= $escaper->escapeJs($block->getStoreCurrency()); ?>"
             }
        }'
        style="display:none;"></div>
<?php endif; ?>
