<style>
    body.adlanding-index-index {
        background: #F4F8FB !important;
    }

    .weightloss-login-sec .container {
        max-width: 1050px;
        margin: 0 auto;
    }

    .weightloss-login-sec .card {
        background: #fff;
        border: 1px solid #B3D2DD;
        border-radius: 20px;
        padding: 40px 40px;
        margin-bottom: 30px;
    }

    .weightloss-login-sec .card h2 {
        color: #000;
        font-family: Lato;
        font-size: 26px;
        font-style: normal;
        font-weight: 700;
        line-height: 33px;
        margin: 0 0 7px 0;
    }

    .weightloss-login-sec .card p {
        color: #000;
        font-family: Lato;
        font-size: 16px;
        font-style: normal;
        font-weight: 400;
        line-height: 23px;
        margin-bottom: 25px;
    }

    .weightloss-login-sec .start-const-btn button.amcform-button {
        background: #000;
        color: #FFF;
        font-family: Lato;
        font-size: 13px;
        font-style: normal;
        font-weight: 700;
        line-height: normal;
        letter-spacing: 0.26px;
        text-transform: uppercase;
        border-radius: 28px;
        width: 256px;
        height: 52px;
    }

    .weightloss-login-sec .start-const-btn button.amcform-button:hover {
        background: #EC3237;
    }

    .weightloss-login-sec .card a.btn.btn-secondary {
        background: #EC3237;
        color: #FFF;
        font-family: Lato;
        font-size: 13px;
        font-style: normal;
        font-weight: 700;
        line-height: normal;
        letter-spacing: 0.26px;
        text-transform: uppercase;
        border-radius: 28px;
        width: 256px;
        display: block;
        padding: 10px;
        line-height: 32px;
        text-align: center;
        text-decoration: none;
    }

    .weightloss-login-sec .card a.btn.btn-secondary:hover {
        background: #000;
    }


    @media (max-width: 767px) {
        .weightloss-login-sec .card {
            padding: 20px 20px;
        }

        .weightloss-login-sec .card h2 {
            font-size: 26px;
        }

        .weightloss-login-sec .card p {
            font-size: 15px;
        }

        .adlanding-index-index .header .logo {
            width: 100% !important;
        }

        .adlanding-index-index .header .logo img {
            float: none !important;
        }

        .adlanding-index-index .page-header .header.content {
            border: 0 !important;
        }

        .adlanding-index-index .page-header,
        .adlanding-index-index .column.main {
            background: transparent !important;
        }

        .weightloss-login-sec .container {
            width: 94% !important;
        }

        .weightloss-login-inner {
            padding: 25px 0;
        }

        .adlanding-index-index .wl-question-sec h2 {
            font-size: 27px !important;
            width: 70%;
            line-height: 33px !important;
            text-align: left !important;
        }

        .adlanding-index-index .amcform-popup-block .amform-form {
            margin-top: -10px;
        }

        .adlanding-index-index .rendered-form .wl-question-sec .fieldset .fields .field.form-group.am-customform-depend .amform-text.error-msg {
            margin-right: 10px;
        }

    }

    @media screen and (min-width: 768px) {
        .weightloss-login-inner {
            width: 510px;
            margin: 0 auto;
        }

        .adlanding-index-index.amform-poup-opened .amcform-popup-block .amform-form {
            max-width: 600px !important;
        }

        .adlanding-index-index.amform-poup-opened .amcform-popup-block .amcform-button.-close-popup {
            right: 18%;
        }
    }

    .adlanding-index-index .page-header .header.content .rating-header,
    .adlanding-index-index .logo-login-signup-mobile,
    .adlanding-index-index .header.content .customMenu,
    .adlanding-index-index .minicart-wrapper {
        display: none !important;
    }

    .adlanding-index-index .logo {
        margin-left: 0 !important;
        float: left !important;
    }

    .adlanding-index-index .logo img {
        margin: 0 !important;
    }

    .adlanding-index-index .weightloss-login-sec {
        padding: 2% 0;
    }

    .adlanding-index-index .wl-question-sec {
        box-shadow: none !important;
    }

    .adlanding-index-index .wl-question-sec h2 {
        color: #101010;
        text-align: center;
        font-family: Lato;
        font-size: 38px;
        font-style: normal;
        font-weight: 300;
        line-height: 40px;
        margin-bottom: 25px !important;
    }

    .adlanding-index-index .rendered-form .fieldset .fields .field.form-group .checkbox-group .amform-groupv2 {
        margin-right: 5px !important;
    }

    .adlanding-index-index .wl-question-sec .field.required.control.amcform-gdpr {
        background-color: #fff;
        margin: -10px 0 0 0;
        padding: 0 30px;
    }

    .adlanding-index-index .default.amform-form .fields .amform-layout-one {
        margin-right: 0 !important;
    }

    .adlanding-index-index .amform-parent .amcform-popup .rendered-form .fieldset .fields .field.fb-checkbox.form-group label.amform-versiontwo-label {
        padding-left: 15px !important;
        max-width: 440px !important;
    }

    .adlanding-index-index .rendered-form .fieldset .fields .field.fb-radio.form-group.registered_gp_fieldset {
        padding-bottom: 20px;
    }

    .adlanding-index-index .amform-parent .amcform-popup .rendered-form .fieldset .fields .field.form-group label.amform-versiontwo-label {
        max-width: 330px !important;
    }

    .adlanding-index-index .rendered-form .wl-question-sec .fieldset .fields .field.form-group.am-customform-depend {
        background-color: #fff;
    }

    .adlanding-index-index .rendered-form .wl-question-sec .fieldset .fields .field.form-group.am-customform-depend .amform-text.error-msg {
        margin-left: 15px;
    }

    .adlanding-index-index .rendered-form .wl-question-sec .fieldset .fields .field.fb-radio.form-group.registered_gp_surgery_fieldset {
        padding: 0;
    }

    .adlanding-index-index .rendered-form .wl-question-sec .fieldset .fields .field.fb-radio.form-group.registered_gp_surgery_fieldset {
        .adlanding-index-index .rendered-form .wl-question-sec .fieldset .fields .field.fb-radio.form-group.registered_gp_surgery_fieldset #clear_gp_search {
            right: -10px;
        }
</style>

<?php
$redirectUrl = $block->getUrl('adlanding/product/questionnaire');
$referer = base64_encode($redirectUrl);
$loginUrl = $block->getUrl('customer/account/login') . 'referer/' . $referer;
?>

<div class="weightloss-login-sec">
    <div class="container">

        <div class="weightloss-login-inner">
            <div class="card">
                <h2>New to Pharmacy Planet?</h2>
                <p>Click the button below to begin your weight loss consultation</p>
                <?php
                /** @var \Kdi\AdLanding\Block\Index\Index $block */
                $questionnaireId = $block->getNewCustomerQuestionnaire();
                ?>
                <?= $this->helper("Amasty\Customform\Helper\Data")->renderForm($questionnaireId) ?>
            </div>

            <div class="card">
                <h2>Existing Customers</h2>
                <p>Login to save time completing your assessment</p>

                <a href="<?= $escaper->escapeUrl($loginUrl) ?>" class="btn btn-secondary">
                    Click Here To Login
                </a>
            </div>
        </div>

    </div>
</div>