<style>
.x-mas-mailer {
    width: 740px;
    float: none;
    margin: 0 auto;
}

.order-update-shipping {
    width: auto;
    float: left;
    padding: 55px 50px;
    margin: 40px 0;
    background: url(/pub/media/wysiwyg/order-update-bg.jpg) 0 0 no-repeat !important;
}

.order-update-shipping .order-update-shipping-title {
    width: 100%;
    float: left;
    font-size: 22px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 30px;
    font-weight: 700;
    text-align: left;
    padding: 0px 0 12px 0;
    margin: 0;
    text-align: center;
}

.order-update-shipping p {
    width: 100%;
    float: left;
    font-size: 15px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 21px;
    font-weight: 400;
    text-align: left;
    padding: 0px 0 13px 0;
    text-align: center;
    margin: 0;
}

.order-update-shipping p a{
    color: #fff !important;
}

.order-update-shipping p span {
    color: #A7F5E6 !important;
    font-size: 16px !important;
    font-weight: 700 !important;
}

@media only screen and (max-width: 767px) {
    .x-mas-mailer .order-update-shipping {
        width: auto;
        float: left;
        padding: 55px 25px 50px 25px;
        background: url(/pub/media/wysiwyg/order-update-bg-m2.jpg) 0 0 no-repeat !important;
        background-size: 100% !important;
        margin: 50px 15px;
    }
    .x-mas-mailer {
        width: 100% !important;
    }
    .order-update-shipping .order-update-shipping-title {
        font-size: 16px !important;
        line-height: 20px !important;
    }
    .order-update-shipping p {
        font-size: 12px !important;
        line-height: 17px !important;
        padding-bottom: 8px !important;
    }
    .order-update-shipping p span {
        font-size: 13px !important;
    }
}

@media only screen and (min-width:380px) and (max-width:395px) {
    .x-mas-mailer .order-update-shipping {
        padding-bottom: 55px !important;
        padding-bottom: 70px;
    }
    .order-update-shipping p {
        line-height: 20px !important;
    }
}

@media only screen and (min-width:400px) and (max-width:450px) {
    .x-mas-mailer .order-update-shipping p {
        font-size: 15px !important;
        line-height: 21px !important;
    }
    .x-mas-mailer .order-update-shipping p span {
        font-size: 15px !important;
    }
    .x-mas-mailer .order-update-shipping {
        padding-left: 35px !important;
        padding-right: 35px !important;
        padding-bottom: 60px !important;
    }
}



@media only screen and (min-width:451px) and (max-width:480px) {
    .x-mas-mailer .order-update-shipping p {
        font-size: 15px !important;
        line-height: 21px !important;
        margin-bottom: 10px;
    }
    .x-mas-mailer .order-update-shipping p span {
        font-size: 15px !important;
    }
    .x-mas-mailer .order-update-shipping {
        padding-left: 35px !important;
        padding-right: 35px !important;
        padding-bottom: 60px !important;
    }
    .order-update-shipping .order-update-shipping-title {
        font-size: 18px !important;
        line-height: 28px !important;
        margin-top: 35px;
    }
}

.x-msg {
    width: 100%;
    float: left;
}
</style>
<div class="x-msg">
    <div class="x-mas-mailer">
        <div class="order-update-shipping">
            <div class="order-update-shipping-title">Holiday Order Update - Important Shipping Information</div>
            <p>Thank you for placing your order with us during this festive period! We're excited to help you with your purchase. Please note that any orders placed between 23rd and 28th December will be dispatched on Monday, 29th December, if your order is approved during this time.</p>
            <p>We appreciate your understanding and patience as we ensure your order reaches you as soon as possible after the holiday break. </p>
            <p>If you have any questions about your order, please email us at <a href="mailto:headoffice@pharmacyplanet.com">headoffice@pharmacyplanet.com</a> or call us at <a href="tel:+448009788956">+44 (0)800 978 8956</a>. </p>
            <p><span>Wishing you a joyful and peaceful festive season!</span></p>
        </div>
    </div>
</div>