<style>
@import url('https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap');

html {
  scroll-behavior: smooth;
}

body{
	font-family: 'Lato', sans-serif !important;
	background-color: transparent !important;
	max-width: 100% !important;
}

body.cms-index-index{
	background-color: transparent !important;
}


 @media screen and (min-width: 768px) {

	/*.minicart-wrapper,
	.custom-menu-ul li.trustpoilet,
	.view-all-treatment-menu,
	.mppromobanner-style{
		display: none !important;
	}*/

	.header.content{
		text-align: center;
	}
	.logo{
		float: none;
		display: inline-block;
		width: 100%;
		max-width: 100%;
    	text-align: center;
    	margin-bottom: 25px;
	}

	.logo img{
		margin: 0 auto;
		width: 232px !important;
    	height: 97px !important;
	}
	.header.content .customMenu {
	    width: 450px;
	    display: inline-block;
	    float: right;
	    margin-top: -9%;
	    z-index: 999999;
	    position: relative;
	}
	.cms-index-index .page-header{
		position: relative !important;
	}
	.homepage-banner-new{
		width: 100%;
		float: left;
		padding: 0;
		margin: 0;
        background:url(/app/design/frontend/Custom/luma_weightloss/Magento_Theme/templates/images/weight-loss-homepage-banner.webp) 90% 16% no-repeat;
		/* background: url(../images/weight-loss-homepage-banner.webp) 90% 16% no-repeat; */
		height: 745px;
		background-attachment: fixed;
		background-size: cover;
	}

	.banner-left-c{
		width: 295px;
		float: left;
	}
	.banner-right-c{
		width: 275px;
		float: right;
		margin-top: 25px;
	}
	.banner-icon{
		height: 43px;
	}
	.rating-header{
		width: auto;
	    float: left;
	    position: absolute;
	    text-align: left;
	    z-index: 999999;
	    display: flex;
	    height: 97px;
	    justify-content: center;
	    align-items: center;
	}
	.rating-header img{
		float: left;
	}
	.rating-header p{
		float: left;
	    margin-left: 10px;
	    margin-top: 8px;
	}
}


.h-banner-content-sec{
	width: 660px;
	float: right;
	padding: 0;
	margin: 0;
}
.review-content{
	width: 670px;
	float: left;
	padding: 0;
	margin:27px 0 0 0;
}
.review-content img{
	float: left;
	margin-right: 15px;
	margin-bottom: 10px;
}
.review-content img:last-child{
	margin-right: 0 !important;
}
.h-banner-content{
	width: 660px;
	float: right;
	padding: 30px;
	margin: 0;
	background: #FEECEC;
	border-radius: 8px;
	margin-top: 55px;
}
.h-banner-content h2{
	width: auto;
    float: left;
    font-family: 'Lato', sans-serif;
    font-size: 42px;
    color: #000 !important;
    line-height: 46px;
    font-weight: 300 !important;
    text-align: left;
    padding: 0 0 10px 0;
    margin: 0;
}
.h-banner-content p{
	width: 100%;
    float: left;
    font-family: 'Lato', sans-serif;
    font-size: 15px;
    color: #000 !important;
    line-height: 20px;
    font-weight: 400 !important;
    text-align: center;
    padding: 0 0 15px 0;
    margin: 0;
}

.h-banner-content .banner-left-c p{
	text-align: left !important;
}

.h-banner-btn{
	width: 100%;
	float: left;
}
.h-banner-btn a,
.h-banner-btn .start-const-btn button,
.banner-left-c .start-const-btn button{
	width: 280px;
	display: inline-block;
	text-align: center;
	background: #EC3237;
    font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 55px; 
    padding: 0 0px;
    font-weight: 400;
    border-radius: 30px;
    letter-spacing: 0.26px;
    height: auto;
     
}
.h-banner-btn a:hover,
.h-banner-btn .start-const-btn button:hover,
.banner-left-c .start-const-btn button:hover{
	background: #53CAF5 !important;
}

.how-it-works-section .h-banner-btn a{
	width: 285px !important;
	line-height: 66px !important;
	border-radius: 32px !important;
}
.banner-right-c ul{
	padding: 0;
	margin: 0;
}

.banner-right-c ul li{
	width: 135px;
	float: left;
	text-align: center;
	list-style-type: none;
	margin: 0;
	padding-bottom: 10px;

}

.banner-right-c ul li:nth-child(1){
	border-right: 1px solid #eec9c9;
    border-bottom: 1px solid #eec9c9;
}
.banner-right-c ul li:nth-child(2){ 
    border-bottom: 1px solid #eec9c9;
}
.banner-right-c ul li:nth-child(3){
	border-right: 1px solid #eec9c9; 
	padding-top: 25px;
}
.banner-right-c ul li:nth-child(4){ 
	padding-top: 25px;
}

.weight-loss-journey{
	width: 100%;
	float: left;
	padding: 0;
	margin: 87px 0 0 0;
	text-align: center;
}
.weight-loss-journey h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 45px 0;
	text-align: center;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 46px; 
    font-weight: 300;
}

.weight-loss-journey .timeframe-subheading{
	width: 345px;
	float: none;
	display: inline-block;
	vertical-align: top;
}



.timeframe-subheading h3{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 7px 0;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 40px; 
    font-weight: 700;
    text-align: left;
}

.timeframe-subheading h4{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 20px; 
    font-weight: 700;
    text-align: left;
}

.timeframe-subheading ul{
	padding: 0 0 0 17px;
	margin: 0;
	float: left;
	width: 90%;
}
.timeframe-subheading ul li{ 
	padding: 0;
	margin: 0 0 5px 0;
	font-size: 13px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 18px; 
    font-weight: 400; 
    text-align: left;
}

.weight-loss1{
	background: url(/pub/media/wysiwyg/WLImage/weight1.png) left top no-repeat;
}
.weight-loss2{
	background: url(/pub/media/wysiwyg/WLImage/weight2.png) left top no-repeat;
}
.weight-loss3{
	background: url(/pub/media/wysiwyg/WLImage/weight3.png) left top no-repeat;
}


.weight-loss-content{
	width: 74%;
	float: left;
	padding: 0 0 0 75px;
} 

.home-testimonilas{
	width: 100%;
	display: inline-block;
	padding:65px 0 95px 0;
	margin: 75px 0 0px 0 !important;
	background: #E7F2F4;
	text-align: center;
}

.home-testimonilas h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 30px 0;
	font-size: 38px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
}

.home-testimonilas .google-review-container{
	width: 100%;
	float: left;
}

.how-it-works-section{
	width: 100%;
	display: inline-block;
	padding:70px 0 100px 0;
	text-align: center;
}
.how-it-works-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.Works-1{
	width: 315px;
	float: none;
	display: inline-block;
	vertical-align: top;
	position: relative;
	margin: 0 20px;
	margin-bottom: 15px;
}

.work-c{
	position: absolute;
	top: 70px;
	left: 120px;
}
.work-c h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 25px; 
    font-weight: 700; 
    text-align: left;
    letter-spacing: 0.5px;
    text-transform: uppercase;
}

 
.work-c p{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 18px; 
    font-weight: 400; 
    text-align: left; 
}


.treatment-options{
	width: 100%;
	float: left;
	padding:65px 0 87px 0;
	margin: 0;
	background: #96D8F0;
}
.treatment-options h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 35px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.home-treatment-block{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0;
	text-align: center;
}
.home_block_1{
	width: 290px;
	float: none;
	display: inline-block;
	margin: 0 8px;
	border-radius: 8px;
	vertical-align: top;
	background: #fff;
	padding: 40px 25px;
}
.home_block_img{
	height: 260px;
	overflow-y: hidden;
}

.home_block_1 h3{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px; 
    font-weight: 900; 
    text-align: left;
}
.home_block_1 h3 a{
	color: #000;
}

.home_block_1 p{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 30px 0;
	font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 20px; 
    font-weight: 400; 
    text-align: left;
}


.home_block_1 .h-banner-btn a,
.home_block_1 .h-banner-btn button{
	width: 145px;
	text-transform: uppercase;
	float: left;
}
.home_block_1 .h-banner-btn a,
.home_block_1 .h-banner-btn button{
    width: 145px;
    display: inline-block;
    text-align: center;
    background: #EC3237;
    font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 55px;
    padding: 0 0px;
    font-weight: 400;
    border-radius: 30px;
    letter-spacing: 0.26px;
}
.home_block_1 .h-banner-btn a:hover,
.home_block_1 .h-banner-btn button:hover{
    background: #53CAF5 !important;
}

.included-section{
	width: 100%;
	float: left;
	padding:75px 0 20px 0;
	margin: 0;
}

.included-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 35px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.subsection{
	width: 50%;
	float: left;
}

.subsection h3{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 15px 0;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px; 
    font-weight: 900; 
    text-align: left;
}

.subsection p{
	width: 80%;
	float: left;
	padding: 0;
	margin: 0 0 0px 15px;
	font-size: 15px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 400; 
    text-align: left;
}

.subsection-content{
	width: auto;
	float: left;
	margin-right: 30px;
	padding: 0 0 40px 0;
	margin-bottom: 40px;
	border-bottom: 1px solid #D3DEE1;
}

.subsection-content.last{
	border-bottom: 0 !important;
}
.subsection-content img{
	float: left;
}
 

.video-section{
	width: 100%;
	float: left;
	padding: 80px 0;
	background: #E7F2F4;
	text-align: center;
}

.video-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 50px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.video-section .subsection{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0;
	text-align: center;
}

.subsection-2{
	width: 1028px;
	margin-left: auto;
	margin-right: auto;
	margin-top: 65px;
	display: inline-block;
}
.subsection-2 h3{
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 55px; 
    font-weight: 300; 
    text-align: left;
}

.subsection-2 h3 strong{
	font-weight: 700;
}

.subsection-2 .h-banner-btn{
	width: auto;
	float: right;
}
.subsection-2 .h-banner-btn a{
	width: 220px !important;
}

.meet-team-section{
	width: 100%;
	float: left;
	padding:80px 0;
	margin: 0;
	text-align: center;
}
.meet-team-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 30px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.meet-team-section h3{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 5px 0;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px; 
    font-weight: 900; 
    text-align: left;
}

.meet-team-section p{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 0px 0px;
	font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 20px; 
    font-weight: 400; 
    text-align: left;
}

.meet-team-section .team-1{
	width: 332px;
	float: none;
	margin: 0 5px;
	display: inline-block;
}

.meet-team-section .subsection-content2{
	margin-top: 20px;
}
 

.meet-team-section2{
	width: 100%;
	float: left;
	padding:65px 0;
	margin: 0;
	background: #E7F2F4;
	text-align: center;
}
.team-2{
	width: 321px;
	float: none;
	display: inline-block;
	background: #fff;
	margin: 0 12px;
	border-radius: 8px;
	padding: 44px 34px;
}
.team-2 img{
	float: left;
}

.team-2 h3{
	padding: 0;
	margin:0 0 0 20px;
	font-size: 18px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 700; 
    text-align: left;
    float: left;
    width: 175px;
}

.stories-section{
	width: 100%;
	float: left;
	padding: 65px 0;
	margin: 0;
	text-align: center;
}
.stories-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 30px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.story-1{
	width: 332px;
	float: none;
	display: inline-block;
	vertical-align: top;
	margin: 0 5px;
}


.story-1 .subsection-content{
	width: 100%;
	float: left;
	padding: 0;
	margin:45px 0 0 0;
	border-bottom: 0 !important;
}
.story-1 img{
	border-radius: 8px;
}
.story-1 .subsection-content{
	position: relative;
}
.story-1 .subsection-content:before{
	width: 48px;
	height: 40px;
	display: inline-block;
	content: " " !important;
	background: url(/pub/media/wysiwyg/WLImage/quote-icon.png) 0 0 no-repeat; 
	position: absolute;
	top: -70px;
	left: 0;
}
.story-1 .subsection-content p{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 13px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 20px; 
    font-weight: 400; 
    text-align: left;
}

.story-1 .subsection-content p strong{
	font-weight: 700;
}



.story-1 .subsection-content img{
	float: left;
	margin-bottom: 10px;
	border-radius: 0;
}

.faq-section{
	width: 100%;
	float: left;
	padding:65px 0;
	margin: 0;
	background: #E7F2F4;
}

.faq-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.faq-content{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0;
}
.faq-list p.question{
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px; 
    font-weight: 400; 
    text-align: left;
    padding: 20px 0;
}

.blogs-section{
	width: 100%;
	float: left;
	padding:65px 0;
	margin: 0;
	text-align: center;
}

.blogs-section h2,
.blogs-section h3{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.blog-c,
.blogs-section .post-holder{
	width: 332px;
	float: none;
	display: inline-block;
	vertical-align: top;
	margin: 0 5px;
}

.blogs-section .post-title-holder{
	height: 67px;
    width: 100%;
    overflow-y: hidden;
    padding-bottom: 0;
    float: left;
    margin-bottom: 5px;
}

.blog-img,
.blogs-section .post-holder .post-ftimg-hld{
	margin-bottom: 20px;
}
.blog-img img,
.blogs-section .post-holder .post-ftimg-hld img{
	border-radius: 8px;
}

.blog-c h4,
.blogs-section .post-holder .post-title a{
	width: 100%;
	float: left;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 26px; 
    font-weight: 900; 
    text-align: left;
    padding: 0px 0 10px 0;
    margin: 0;
}

.blogs-section .post-holder .post-text-hld{
	min-height: auto !important;
	width: 100%;
	float: left;
}
.blog-c p,
.blogs-section .post-holder .post-text-hld p{
	width: 100%;
	float: left;
	font-size: 13px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 20px; 
    font-weight: 400; 
    text-align: left;
    padding: 0px 0 5px 0;
    margin: 0;
}

.blogs-section .post-holder .post-posed-date{
	float: left;
}
.blog-c p span,
.blogs-section .post-holder .post-posed-date span{
	font-size: 11px !important; 
    color: #6B6B6B !important;
    font-family: 'Lato', sans-serif;
    line-height: 20px; 
    font-weight: 400 !important; 
    text-align: left;
    padding: 0px 0 0px 0;
    margin: 0;
    font-style: normal !important;
}

.google-review-section{
	width: 100%;
	float: left;
	padding:65px 0;
	margin: 0;
	background: #E6F0F3;
	text-align: center;
}
.google-review-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 30px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}
.rating-img{
	width: 100%;
    float: left;
    padding: 0;
    margin: 0 0 40px 0;
    text-align: center;
    display: inline-block;
}
.rating-img img{
	float: none;
    display: inline-block;
}
.rating-img p{
	width: auto;
    float: none;
    display: inline-block;
    vertical-align: top;
    margin-top: 4px !important;
    margin-left: 10px !important;
}

.review-list-content{
	width: 100%;
	float: left;
	padding: 0;
	margin:50px 0 0 0;
	text-align: center;
}

.review-list{
	width: 285px;
	float: none;
	display: inline-block;
	background: #fff;
	margin: 0 8px;
	padding: 40px 28px;
	border-radius: 8px;
	text-align: left;
}
.review-list .review-img{
	margin-bottom: 10px;
}

.review-list p{
	margin-bottom: 20px;
}
.author-c img{
	float: left;
	border-radius: 50px;
}

.author-c p{
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 50px; 
    font-weight: 700; 
    letter-spacing: 0.31px;
}

.footer-consultation .container h3{
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 55px; 
    font-weight: 300; 
    text-align: left;
    background: none !important;
}

.footer-consultation .container h3 strong{
	font-weight: 700;
}

.footer-consultation .h-banner-btn {
	width: auto;
	float: right;
}

.footer-consultation .h-banner-btn a{
	width: 220px;
}
 
.custom-menu-ul .view-all-treatment a,
.custom-menu-ul .start-const-btn button{
	font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 52px; 
    font-weight: 400; 
    letter-spacing: 0.26px;
    background: #ED3237;
    padding: 0 28px;
    box-shadow: inset 0 0px 0 0 #ffffff, inset 0 0 0 0 rgba(204, 204, 204, 0);
    border-radius: 50px;
    transition: all 0.1s;
    border: 1px solid rgba(255, 255, 255, 0.5);
    position: relative;
    display: inline-block;
}

.custom-menu-ul .start-const-btn button{
	height: 54px;
}
 

.custom-menu-ul .view-all-treatment a:hover,
.custom-menu-ul .start-const-btn button:hover{
    background: #53CAF5;
    text-decoration: none !important;
}

.customMenu li.view-all-treatment a{
	font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 52px; 
    font-weight: 400; 
    letter-spacing: 0.26px;
    background: #ED3237;
    padding: 0 28px;
    box-shadow: inset 0 0px 0 0 #ffffff, inset 0 0 0 0 rgba(204, 204, 204, 0);
    border-radius: 50px;
    transition: all 0.1s;
    border: 1px solid rgba(255, 255, 255, 0.5);
    position: relative;
    display: inline-block;
}
 

.customMenu li.view-all-treatment a:hover {
    background: #53CAF5;
    text-decoration: none !important;
}

.custom-menu-ul .btn-login-signup a{
	font-size: 13px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 52px; 
    font-weight: 400; 
    letter-spacing: 0.26px;
    text-transform: uppercase;
}

.customMenu .custom-menu-ul{
	margin-top: 10px;
}
.testimonials-list{
    width: 285px;
    float: none;
    display: inline-block;
    background: #fff;
    margin: 0 8px;
    padding: 60px 30px;
    border-radius: 8px;
    text-align: left;
}
.testimonials-list .rating-img-1 {
    margin-bottom: 10px;
}
 
.testimonials-list p {
    width: auto;
    float: left;
    padding: 0 0 10px 0;
    margin: 0;
    font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 20px;
    font-weight: 400;
    letter-spacing: 0.31px;
}

.testimonials-list p strong{
	font-weight: 700;
}

.footer-left,
.footer-right{
	width: 100% !important;
	border-left: 0 !important;
	border-bottom: 1px solid rgba(255, 255, 255, 0.44);
}

.footer-left{
	padding-bottom: 20px !important;
}
.footer-right{
	padding: 30px 0 35px 0 !important;
}

.footer-left .social-tab{
	padding: 0;
	margin:10px 0 0 0;
	border: 0 !important;
}

.footer-right .footer-links h5{
	width: 100%;
	float: left;
	padding: 0 0 10px 0;
	margin: 0;
	font-size: 18px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 28px; 
    font-weight: 400; 
}

.copyright-panel{
	border-top: 0 !important;
}

.page-footer .copyright-panel p{
	width: 100%;
	float: left;
	text-align: center;
	font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 28px; 
    font-weight: 400; 

}
.page-footer .copyright-panel p a{
	color: #fff;
}

footer.page-footer{
	padding-bottom: 0 !important;
}




 @media screen and (min-width: 768px) {
 	.page-header .header.content,
 	.breadcrumbs,
 	.container{
 		max-width: 1260px !important;
 	}
 	 

 	.footer-left .accordion-tab label{
 		width: 150px;
 	}
 	.footer-left .accordion-tab.footer-newsletter-1{
 		width: 600px;
 	}
 	.footer-left .accordion-tab.socila-media-tab {
	    width: 220px;
	    float: right;
	}

 	.footer-left .accordion-tab label{
 		width: 130px;
 		float: left;
 		margin-right: 35px;
 	}

 	.footer-left .accordion-tab .newsletter label,
 	.block.newsletter .field.newsletter{
 		width: 100% !important;
 		max-width: 100% !important;
 	}

 	.footer-left .accordion-tab.footer-newsletter-1 .tab-content{
 		width: 410px;
 		float: left;
 	}
 	.footer.content ul {
	    padding-right: 0 !important;
	}

	.footer-left .social-tab ul li:before{
		font-size: 35px!important;
	}

	.footer-left .social-tab ul li{
		margin-right: 0 !important;
		margin-left: 25px !important;
	}

	.footer-right .footer-links{
		width: 500px;
		float: left;
	}
	.footer-right .right-img{
		width: auto;
		float: right;
		margin-top: 10px;
	}

	.footer-right .footer-links .leff-col ul li{
		width: 35%;
	}

	.page-main{
		max-width: 100% !important;
	}

	.category-section-2 .subsection-b{
		width: 17%;
		float: left; 
	}

	.glp-work .subsection-content{
		height: 90px;
	}

	.faq-section .container{
		max-width: 670px !important;
	}
	.page-with-filter .category-cms {
	    margin-top: 65px !important;
	}

	.included-section.glp-work .container,
	.included-section .container{
		max-width: 1005px !important;

	}
	.footer-link .container,
	.footer-consultation .container{
		max-width: 1090px !important;

	}

	.product-info-tab .tab-container{
		max-width: 1145px !important;
		margin: 0 auto;
	}

	.weightloss-journey .container{
		max-width: 1030px !important;
		display: block !important;
	}

	.blog-c,
	.blogs-section .post-holder{
		width: 332px !important; 
	}

	.slider-wrapper.desk-review-slider .slide-arrow{
		top: 25% !important;
	}

	

 }

 
 


 @media screen and (max-width: 767px) {

 	.header.content .rating-header{
 		display: none;
 	}
 	.h-banner-content-sec{
 		width: 100% !important;
 		float: left !important;
 	}
 	.video-section .subsection-2{
 		width: 100% !important;
 	}

 	.video-section .subsection-2,
 	.h-banner-content-sec .review-content{
 		width: 100% !important;
 		
 	}
 	.h-banner-content{
 		width: auto !important;
 		float: left !important;
 		margin-top: 0 !important;
 	}
 	.cms-index-index .page-main {
	    padding-top: 0 !important;
	}
	.cms-index-index .page-header{
		margin-bottom: 0 !important;
	}

	.h-banner-btn a{
		width: 220px !important;
	}
	.header.content{
		padding-bottom: 20px !important;
	}

	.h-banner-content h2{
		font-size: 30px !important;
		line-height: 36px !important;
	}
	.h-banner-btn{
		margin-top: 10px;
	}

	.banner-left-c{
		margin-bottom: 30px;
		display: inline-block;
	}
	.banner-right-c ul li{
		width: 49% !important;
		padding-bottom: 0 !important;
		height: 100px;
	}

	.h-banner-content-sec .review-content{
		text-align: center;
	}
	.review-content img {
	    float: none !important;
	    margin-right: 15px;
	    margin-bottom: 0 !important;
	    width: 45% !important;
	    vertical-align: top;
	}

	.weight-loss-journey{
		background: #fff;
		padding-top: 25px;
		padding-bottom: 25px;
	}
	.weight-loss-journey h2,
	.home-testimonilas h2,
	.google-review-section h2,
	.blogs-section h2,
	.faq-section h2,
	.stories-section h2,
	.meet-team-section h2,
	.video-section h2,
	.included-section h2,
	.treatment-options h2,
	.how-it-works-section h2{
		font-size: 32px !important;
		line-height: 40px !important;
		text-align: left;
		padding-left: 15px;
		padding-right: 15px;
		width: auto !important;
	}

	

	.video-section h2{
		margin-bottom: 30px !important;
	}
	.faq-section h2 br{
		display: none;
	}
	.weight-loss-journey .timeframe-subheading,
	.story-1{
	    width: auto !important;
	    float: left;
	    padding: 0 15px 20px 15px !important;
	}

	.included-section .subsection{
		width: 90% !important;
		padding: 0 15px;
	}

	.included-section .subsection-content{
		margin-right: 0 !important;
	}
	.included-section .subsection p{
		width: 70% !important;
	}

	.included-section .subsection-content.last {
	    border-bottom: 1px solid #D3DEE1 !important;
	}
	.included-section .subsection-content.last.last2 {
	    border-bottom: 0 !important;
	    padding-bottom: 0 !important;
	    margin-bottom: 0 !important;
	}
	.treatment-options .home_block_1{
		margin-bottom: 20px !important;
	}
	.story-1 img{
		width: 100%;
	}

	.story-1 .subsection-content img{
		width: auto !important;
	}

	.meet-team-section .team-1{
		width: 90% !important;
		margin: 0 0 25px 0 !important;
	}

	.cms-index-index .home-testimonilas{
		margin-top: 0 !important;
		padding: 35px 0 !important;
	}

	.cms-index-index .google-review-section,
	.cms-index-index .faq-section,
	.meet-team-section,
	.video-section,
	.treatment-options{
		padding: 35px 0 !important;
	}

	.how-it-works-section{
		background: #fff;
		padding-top: 45px !important;
		padding-bottom: 45px !important;
	}
	.how-it-works-section h2{
		margin-bottom: 0 !important;
	}
	.how-it-works-section .work-c h2{
		width: 100% !important; 
	    padding: 0 !important; 
	    font-size: 20px !important; 
	    font-family: 'Lato', sans-serif;
	    line-height: 25px !important; 
	    margin-bottom: 10px !important;
	}
	.work-c { 
	    left: 150px !important;
	    padding-right: 20px !important;
	}

	.Works-1{
		width: 100% !important;
		margin: 0 !important;
	}

	.testimonials-list,
	.review-list{
		width: 90% !important;
		margin: 0 0px 20px 0px !important;
	}

	.testimonials-list{
		padding-top: 40px;
		padding-bottom: 40px;
	}

	.faq-content{
		width: 90% !important;
		padding: 0 15px !important;
	}

	.meet-team-section2,
	.stories-section{
		padding: 40px 0!important;
	}

	.blogs-section{
		padding: 40px 0 10px 0 !important;
	}

	.faq-section .container{
		width: 90%;
	}
	.faq-section button.accordion{
		padding-right: 20px !important;
		line-height: 26px !important;
	}

	.blog-c{ 
		margin: 0 15px 20px 15px !important;
	}

	.footer-left{
		border-bottom: 0 !important;
		padding-bottom: 0 !important;
	}
	.footer-link{
		padding: 0 15px;
	}


	.video-section .subsection-2{
		margin-top: 15px !important;
	}
	.footer-consultation .container h3,
	.video-section .subsection-2 h3{
		width: 100% !important;
		text-align: center !important;
		font-size: 25px !important;
	}
	.footer-consultation .h-banner-btn,
	.video-section .subsection-2 .h-banner-btn{
	    width: 100% !important;
	    float: left !important;
	    margin-top: 10px;
	}
	.footer-right .right-img{
		float: left;
	    width: 100%;
	    margin-top: 30px; 
	}

	.footer-right .right-img img{
		margin-right: 10px;
		margin-bottom: 10px;
	}
	.page-footer .copyright-panel p{
		margin-top: 0 !important;
	}
	.weight-loss-content{
		width: 95% !important;
	}
	.home_block_img{
		height: auto !important;
		margin-bottom: 25px;
	}
	.video-section .subsection video{
		width: 100% !important;
		height: 250px !important;
	}
	.meet-team-section2 .team-2{
		width: 90% !important;
		margin-bottom: 10px !important;
	}
	.home-treatment-block .home_block_1{
		width: 90% !important;
	}
	.cms-index-index .page-header{
		padding-bottom: 0  !important;
	}

	.review-name-header{
		font-size: 25px !important;
	}
	.review-slide{
		height: 380px !important;
	}
	.logo img {
	    width: 220px !important;
	    height: 90px !important;
	}

	.footer-link .footer-left{
		border-bottom: 0 !important;
		padding-bottom: 0 !important;
	}
	.footer-link .footer-right{
		padding-top: 0 !important;
	}
	.footer-left .social-tab{
		margin-bottom: 20px !important;
	}

 }

 
.subsection-b{
	background: #FEECEC;
	border-radius: 8px;
	padding:28px 35px;
	margin-right: 40px;
}

.subsection-b.last{
	margin-right: 0 !important;
}

.subsection-b h3{
	font-size: 25px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px; 
    font-weight: 700; 
    padding: 0;
    margin: 0 0 30px 0;
}

.glp-work .subsection-content.last{
	margin-bottom: 0 !important;
	padding-bottom: 0 !important;
}

.glp-work{
	padding-bottom: 20px !important;
	padding-top: 85px !important;
}

.faq-content .faq-list{
	border-bottom: 1px solid #96D8F0
}

 


.how-it-works-section.inner {
	background: #E7F2F4;
	margin-top: 40px;
}

 

.weightloss-journey{
    width: 100%;
    float: left;
    padding: 45px 0;
    margin: 0;
    background: #96D8F0;
}

.weightloss-journey .container h3{
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 55px; 
    font-weight: 300; 
    text-align: left;
    background: none !important;
}

.weightloss-journey .container h3 strong{
	font-weight: 700;
}

.weightloss-journey .h-banner-btn {
	width: auto;
	float: right;
}

.weightloss-journey .h-banner-btn a{
	width: 220px;
	display: inline-block;
	text-align: center;
	background: #EC3237;
    font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 52px; 
    padding: 0 0px;
    font-weight: 400;
    border-radius: 28px;
    letter-spacing: 0.26px;
     
}
.weightloss-journey .h-banner-btn a:hover{
	background: #53CAF5 !important;
}


.video-section.inner,
.meet-team-section2.inner{
	background: #fff !important;
}

.meet-team-section2.inner{
	padding-top: 0 !important;
}

.meet-team-section2.inner .team-2{
	background: #E7F2F4;
}

.home-testimonilas.inner{
	margin-top: 50px !important;
}
 


 
 

.included-section.inner{
	padding-bottom: 20px !important;
}

 

.cms-index-index .message.success {
    margin-top: 66px;
}
.block.newsletter .form.subscribe div.mage-error[generated]{
	font-size: 14px;
}


.faq-section button.accordion{
	border: 0;
	border-bottom: 1px solid #96D8F0;
	box-shadow:none !important;
	background: transparent;
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px;
    font-weight: 400;
    text-align: left;
    padding: 20px 0;
}

.faq-section .panel,
.faq-section .panel p{
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px;
    font-weight: 400;
    text-align: left;
    padding: 10px 0;
}

.faq-section button.accordion:after{
	float: right; 
	display: none;
}
.faq-section button.accordion{ 
	background: url(/pub/media/wysiwyg/WLImage/Poly.png) right 32px no-repeat; 
}

a:hover{
	text-decoration: none;
}




@media only screen and (min-width:768px) and (max-width:991px){

.subsection-2{
	width: 95% !important;
	margin-top: 50px!important;
}
.subsection-2 h3,
.footer-consultation .container h3{
	font-size: 35px !important;
	line-height: 50px !important;
}
.header .rating-header{
	display: none;
}
.header .logo{
	width: auto !important;
}
.header .logo img{
	margin: 0 !important;
}
.header.content .customMenu{
	margin-top: 0 !important;
}
.review-content{
	width: 100% !important;
}
.h-banner-content{
	margin-right: 20px !important;
	width: 580px !important;
}
.review-content img{
	width: 48%;
}
.weight-loss-journey .timeframe-subheading{
	margin-bottom: 20px;
}

.testimonials-list{
	width: 195px !important;
	padding: 50px 20px !important;
}
.home_block_1{
	width: 180px !important;
}
.home_block_img{
	height: 200px !important;
}
.cms-index-index .included-section.glp-work .container, 
.cms-index-index .included-section .container
.footer-consultation .container{
    max-width: 100% !important;
}
.footer-link .container{
    max-width: 95% !important;
}

.included-section .subsection p{
	width: 70% !important;
}
.included-section .subsection {
    width: 44%;
    float: left;
    margin: 0 20px;
}
.included-section .subsection-content{
	margin-right: 0 !important;
}
.video-section,
.meet-team-section{
	padding: 50px 0 !important;
}

.meet-team-section .team-1,
.story-1,
.blog-c{
	width: 240px!important;
}

.team-2 {
    width: 200px !important; 
    margin: 0 5px !important;  
    padding: 44px 20px !important;
}
.team-2 h3{
	font-size: 15px !important;
	width: 122px !important;
}
.review-list {
    width: 200px !important; 
    margin: 0 5px !important;
    padding: 40px 20px !important; 
}

.footer-right .accordion-tab{
	width: 100% !important;
}
.footer-left .accordion-tab.footer-newsletter-1 {
    width: 500px !important;
}
.footer-left .accordion-tab.footer-newsletter-1 .tab-content{
	width: 320px !important;
}

.footer-right .footer-links{
	width: 270px !important;
}
.footer-right .right-img{
	width: 62% !important;
}
.footer-right .right-img img{
	width: 24%;
}
.footer-right .footer-links .leff-col ul li{
	width: 50% !important;
}

}



@media only screen and (min-width:992px) and (max-width:1024px){

.subsection-2{
	width: 95% !important;
	margin-top: 50px!important;
}
.subsection-2 h3,
.footer-consultation .container h3{
	font-size: 35px !important;
	line-height: 50px !important;
}

.header.content .customMenu{
	margin-top: -11% !important;
}
.customMenu li.view-all-treatment a,
.btn-login-signup a {
    padding: 0 15px !important;
}
.review-content{
	width: 100% !important;
}
.h-banner-content{
	margin-right: 20px !important;
	width: 580px !important;
}
.review-content img{
	width: 48%;
}
.weight-loss-journey .timeframe-subheading{
	margin-bottom: 20px;
	width: 320px !important;
}

.testimonials-list{
	width: 265px !important;
	padding: 50px 25px !important;
}
.home_block_1{
	width: 265px !important;
}
.home_block_img{
	height: 250px !important;
}
.Works-1{
	width: 300px !important;
	margin: 0 15px !important;
}
.cms-index-index .included-section.glp-work .container, 
.cms-index-index .included-section .container
.footer-consultation .container{
    max-width: 100% !important;
}
.footer-link .container{
    max-width: 95% !important;
}

.included-section .subsection p{
	width: 70% !important;
}
.included-section .subsection {
    width: 46%;
    float: left;
    margin: 0 20px;
}
.included-section .subsection-content{
	margin-right: 0 !important;
}
.video-section,
.meet-team-section{
	padding: 50px 0 !important;
}

.meet-team-section .team-1,
.story-1,
.blog-c{
	width: 320px!important;
}

.team-2 {
    width: 270px !important; 
    margin: 0 10px !important;  
    padding: 44px 20px !important;
}
.team-2 h3{
	font-size: 15px !important;
	width: 122px !important;
}
.review-list {
    width: 270px !important; 
    margin: 0 10px !important;
    padding: 40px 20px !important; 
}

 

.footer-right .footer-links{
	width: 360px !important;
}
.footer-right .right-img{
	width: 62% !important;
}
.footer-right .right-img img{
	width: 24%;
}
.footer-right .footer-links .leff-col ul li{
	width: 50% !important;
}

}

.footer-right .accordion-tab{
	width: 100% !important;
}

.customMenu .custom-menu-ul .amform-parent{
	float: left;
}

.faq-section button.accordion{
	width: 100%;
}


/*
.banner-left-c .start-const-btn button{
  position: relative;
  transition: all .35s;
}

.banner-left-c .start-const-btn button:before,
.banner-left-c .start-const-btn button:after{
  position: absolute;
  content: "";
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  background: seagreen;
  z-index: -1;
  transition: all .35s;
}

.banner-left-c .start-const-btn button:before{
  opacity: .5;
}

.banner-left-c .start-const-btn button:after{
  transition-delay: .2s;
}

.banner-left-c .start-const-btn button:hover{
  color: #fff;
}

.banner-left-c .start-const-btn button:hover:before,
.banner-left-c .start-const-btn button:hover:after{
  top: 0;
}*/



.reveal1{
  position: relative;
  transform: translateY(150px);
  opacity: 0;
  transition: 1s all ease !important;
}

.reveal1.active{
  transform: translateY(0);
  opacity: 1;
}

.amcform-button.-default:focus, .amcform-button.-error:focus {
    background-color: #53CAF5 !important;
    box-shadow: none !important;
}

.banner-left-c .start-const-btn button,
.h-banner-btn .start-const-btn button,
.home_block_1 .h-banner-btn a,
.category-details .start-const-btn button,
.weightloss-journey .h-banner-btn a,
.footer-consultation .h-banner-btn a,
.amcform-popup-block .amform-form .amcform-toolbar button,
.product-order-now a button,
.catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-options-bottom .box-tocart .action.tocart,
.cart-container .continue-shopping,
.checkout-cart-index .cart-summary .checkout-methods-items .action.primary.checkout,
.popup-authentication.modal-popup .actions-toolbar .primary button.action,
.osc-place-order-wrapper .place-order-primary button.primary.checkout{ 
	transition: all .35s;
	text-decoration: none !important;
}

/*.banner-left-c .start-const-btn button{
	position: relative;
	z-index: 2; 
}
.banner-left-c .start-const-btn button:after { 
  content: "";
  height: 100%; 
  left: 0; 
  top: 0; 
  width: 0px;  
  position: absolute; 
  transition: all 0.3s ease 0s; 
  -webkit-transition: all 0.3s ease 0s; 
  z-index: -1;
  border-radius: 30px;
}

.banner-left-c .start-const-btn button:hover:after{ width: 100%; }
.banner-left-c .start-const-btn button:after{ background: #53CAF5; }*/

</style>