<!doctype html>

<html>

<head>
<meta charset="utf-8">
<title>CSS Accordion</title>

<style>

.product-faq-section .faq-list input {
    display: none;
}

.product-faq-section .faq-list label {
    text-align: left;
    letter-spacing: 0px;
    color: #000000;
    opacity: 1;
    padding: 20px 0 8px 0;
    width: 100%; 
    border: none;
    outline: none;
    transition: 0.4s;
    box-shadow: none !important;
    font-family: 'Lato', sans-serif;
    font-size: 18px;
    font-weight: 700;
    line-height: 28px;
    transition: ease .5s;
    display: inline-block;
    background: url(/pub/media/wysiwyg/WLImage/Poly.png) right 32px no-repeat !important;

}

.product-faq-section .faq-list label:hover,
.product-faq-section .faq-list label:focus{
    background: url(/pub/media/wysiwyg/WLImage/Poly.png) right 32px no-repeat !important;
}

.product-faq-section .faq-list .panel-p {
    text-align: left;
    letter-spacing: 0px;
    font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 24px;
    font-weight: 400;
    text-align: left;
    padding: 0px 0;
    padding: 0 0;  
    background: transparent;
    overflow: hidden;
      max-height: 0px;
      transition: max-height 0.5s ease;
}
.product-faq-section .faq-list .panel-p:target{
      max-height: 150px;
}
.product-faq-section .faq-list .panel-p p{
    font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 24px;
    font-weight: 400;
    text-align: left;
    padding: 0px 0 15px 0;
    margin: 0;
}

.product-faq-section .faq-list input + label + .panel-p { 
    overflow: hidden;
      max-height: 0px;
      transition: max-height 0.3s ease-out;
}

.product-faq-section .faq-list input:checked + label + .panel-p { 
    max-height: 165px;
}


.product-faq-section{
    width: 100%;
    float: left;
    padding: 80px 0 80px 0;
    margin: 0;
    background: #E7F2F4;
}
.product-faq-section .h-title {
        width: 100%;
        float: left;
        padding: 0;
        margin: 0 0 22px 0;
        font-size: 38px;
        color: #101010;
        font-family: 'Lato', sans-serif;
        line-height: 48px;
        font-weight: 300;
        text-align: center;
}
.product-faq-section .faq-list {
    border-bottom: 1px solid #96D8F0;
    padding-bottom: 12px;
    width: 100%;
    display: inline-block;
}

@media screen and (min-width: 768px) {
    .product-faq-section .container {
        max-width: 670px !important;
        margin: 0 auto;
    }
    .product-faq-section .faq-list label{
        cursor: pointer;
    }
}

@media screen and (max-width: 767px) {
    .product-faq-section .h-title{
        text-align: left;
        padding-left: 15px;
        padding-right: 15px;
        width: auto !important;
        font-weight: 300;
        margin: 0 0 25px 0;
        font-size: 32px;
        color: #000;
        font-family: 'Lato', sans-serif;
        line-height: 36px;
        font-weight: 400;
        text-align: left;
        padding: 0px 0;
        letter-spacing: 0px;
    }
    .product-faq-section .container{
        width: 90%;
    }
    .product-faq-section .faq-list label{
        font-size: 15px !important;
        padding-left: 0 !important;
        padding-right: 20px !important;
        line-height: 22px;
    }
     
    .product-faq-section .faq-list .panel-p p{
        font-size: 14px !important;
        line-height: 22px !important;
    }
}

</style>

</head>

<div class="product-faq-section">
<div class="container reveal1">
<div class="h-title" data-was-processed="true">Weight Loss everything you need to know</div>

<div class="faq-list">
<input type="checkbox" id="title1" />
<label for="title1">What is Saxenda, and how does it work?</label>
<div class="panel-p">
<p>Saxenda is a prescription medicine that comes in pre-filled injection pens for self-administration at home once a day. It contains liraglutide, which belongs to a class of medications called GLP-1 receptor agonists. Saxenda works by mimicking the hormone GLP-1, which helps regulate blood sugar levels and induces a feeling of fullness, leading to weight loss.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title2" />
<label for="title2">How effective is Saxenda?</label>
<div class="panel-p">
<p>Saxenda is considered one of the most effective weight loss medications available. Studies have shown that patients can expect to lose up to 8% of their body weight on average over 56 weeks when combined with diet and exercise.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title3" />
<label for="title3">Who is eligible for Saxenda?</label>
<div class="panel-p">
<p>Saxenda is suitable for adults with a BMI of 30 or greater, or a BMI of 27 or greater with weight-related conditions such as high blood pressure, diabetes, or high cholesterol.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title4" />
<label for="title4">How do I use Saxenda?</label>
<div class="panel-p">
<p>Saxenda is injected once daily, at any time of day, independently of meals. The injection is administered subcutaneously (under the skin) in the abdomen, thigh, or upper arm. Detailed instructions on how to use the injection pen are provided in the Saxenda package.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title5" />
<label for="title5">How does dosing work with Saxenda?</label>
<div class="panel-p">
<p>Treatment typically starts with a low dose and gradually increases over time. The dose is increased weekly until the maintenance dose is reached. Healthcare providers may adjust the dose based on individual response and tolerability.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title6" />
<label for="title6">What are the potential side effects of Saxenda?</label>
<div class="panel-p">
<p>Like all medications, Saxenda can cause side effects. Common side effects include nausea, diarrhea, constipation, vomiting, and low blood sugar (especially when used with other medications that lower blood sugar). These side effects usually improve over time.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title7" />
<label for="title7">Is Saxenda suitable for me?</label>
<div class="panel-p">
<p>Saxenda may be prescribed for adults with a BMI of 30 or greater, or a BMI of 27 or greater with weight-related conditions. It is not suitable for everyone, including those with a history of pancreatitis or thyroid cancer. Your healthcare provider will assess your eligibility for Saxenda and discuss the risks and benefits with you.</p>
</div>
</div>

</div>
</div>


</html>



<script>
        document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(checkbox => {
            checkbox.addEventListener('change', function () {
                if (this.checked) {
                    document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(otherCheckbox => {
                        if (otherCheckbox !== this) {
                            otherCheckbox.checked = false;
                        }
                    });
                }
            });
        });
    </script>