<!doctype html>

<html>

<head>
<meta charset="utf-8">
<title>CSS Accordion</title>

<style>

.product-faq-section .faq-list input {
    display: none;
}

.product-faq-section .faq-list label {
    text-align: left;
    letter-spacing: 0px;
    color: #000000;
    opacity: 1;
    padding: 20px 0 8px 0;
    width: 100%; 
    border: none;
    outline: none;
    transition: 0.4s;
    box-shadow: none !important;
    font-family: 'Lato', sans-serif;
    font-size: 18px;
    font-weight: 700;
    line-height: 28px;
    transition: ease .5s;
    display: inline-block;
    background: url(/pub/media/wysiwyg/WLImage/Poly.png) right 32px no-repeat !important;

}

.product-faq-section .faq-list label:hover,
.product-faq-section .faq-list label:focus{
    background: url(/pub/media/wysiwyg/WLImage/Poly.png) right 32px no-repeat !important;
}

.product-faq-section .faq-list .panel-p {
    text-align: left;
    letter-spacing: 0px;
    font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 24px;
    font-weight: 400;
    text-align: left;
    padding: 0px 0;
    padding: 0 0;  
    background: transparent;
    overflow: hidden;
      max-height: 0px;
      transition: max-height 0.5s ease;
}
.product-faq-section .faq-list .panel-p:target{
      max-height: 150px;
}
.product-faq-section .faq-list .panel-p p{
    font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 24px;
    font-weight: 400;
    text-align: left;
    padding: 0px 0 15px 0;
    margin: 0;
}

.product-faq-section .faq-list input + label + .panel-p { 
    overflow: hidden;
      max-height: 0px;
      transition: max-height 0.3s ease-out;
}

.product-faq-section .faq-list input:checked + label + .panel-p { 
    max-height: 165px;
}


.product-faq-section{
    width: 100%;
    float: left;
    padding: 80px 0 80px 0;
    margin: 0;
    background: #E7F2F4;
}
.product-faq-section .h-title {
        width: 100%;
        float: left;
        padding: 0;
        margin: 0 0 22px 0;
        font-size: 38px;
        color: #101010;
        font-family: 'Lato', sans-serif;
        line-height: 48px;
        font-weight: 300;
        text-align: center;
}
.product-faq-section .faq-list {
    border-bottom: 1px solid #96D8F0;
    padding-bottom: 12px;
    width: 100%;
    display: inline-block;
}

@media screen and (min-width: 768px) {
    .product-faq-section .container {
        max-width: 670px !important;
        margin: 0 auto;
    }
    .product-faq-section .faq-list label{
        cursor: pointer;
    }
}

@media screen and (max-width: 767px) {
    .product-faq-section .h-title{
        text-align: left;
        padding-left: 15px;
        padding-right: 15px;
        width: auto !important;
        font-weight: 300;
        margin: 0 0 25px 0;
        font-size: 32px;
        color: #000;
        font-family: 'Lato', sans-serif;
        line-height: 36px;
        font-weight: 400;
        text-align: left;
        padding: 0px 0;
        letter-spacing: 0px;
    }
    .product-faq-section .container{
        width: 90%;
    }
    .product-faq-section .faq-list label{
        font-size: 15px !important;
        padding-left: 0 !important;
        padding-right: 20px !important;
        line-height: 22px;
    }
     
    .product-faq-section .faq-list .panel-p p{
        font-size: 14px !important;
        line-height: 22px !important;
    }
}

</style>

</head>


<div class="product-faq-section">
<div class="container reveal1">
<div class="h-title" data-was-processed="true">Weight Loss everything you need to know</div>

<div class="faq-list">
<input type="checkbox" id="title1" />
<label for="title1">What is Wegovy, and how does it work?</label>
<div class="panel-p">
<p>Wegovy belongs to a group of treatments known as GLP-1 medicines, which are administered via pre-filled injection pens for self-administration at home once a week. These treatments mimic a natural gut hormone, regulating blood sugar levels and inducing a sense of fullness, leading to weight loss nearly twice as much as some other popular medications.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title2" />
<label for="title2">How effective are treatments like Wegovy?</label>
<div class="panel-p">
<p>Wegovy is among the most effective weight loss medications available. Patients can expect to lose up to 20.9% body weight on average over 36 weeks and 25.3% body weight on average over 88 weeks.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title3" />
<label for="title3">Who is eligible for Wegovy?</label>
<div class="panel-p">
<p>Injectable weight loss treatments like Wegovy are suitable for individuals with a BMI over 30. Those with weight-related health concerns may be eligible with a BMI over 27, including conditions like high blood pressure, diabetes, heart disease, and raised cholesterol.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title4" />
<label for="title4">How do I use injectable pens like Wegovy?</label>
<div class="panel-p">
<p>Wegovy is administered once weekly, on the same day, using a pre-filled pen. The process is straightforward, with the needles being small, making it relatively pain-free and easy to adapt to. Inside your box of Wegovy, there are detailed instructions that show you exactly how and where to administer your injection.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title5" />
<label for="title5">How does dosing work with injectable treatments?</label>
<div class="panel-p">
<p>Treatment starts at the lowest dose and increases every four weeks until reaching the recommended maintenance dose. Adjustments to your dose are typically made every four weeks but this is based on a number of factors including your level of weight loss and your experience with side effects.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title6" />
<label for="title6">What are the potential side effects of Wegovy?</label>
<div class="panel-p">
<p>Like all medicines, injectable GLP-1 treatments can cause side effects such as nausea, vomiting, constipation, and diarrhea. These side effects typically diminish over time, but severe or persistent symptoms should be reported to a healthcare provider immediately.</p>
</div>
</div>


<div class="faq-list">
<input type="checkbox" id="title7" />
<label for="title7">Is Wegovy suitable for me?</label>
<div class="panel-p">
<p>Wegovy can be prescribed for adults with a BMI over 30, or a BMI over 27 with weight-related conditions. It is not suitable for pregnant individuals or those allergic to any of its ingredients. One of our clinicians will help to determine your suitability for treatment and discuss your options.</p>
</div>
</div>


</div>
</div>

</html>


<script>
        document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(checkbox => {
            checkbox.addEventListener('change', function () {
                if (this.checked) {
                    document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(otherCheckbox => {
                        if (otherCheckbox !== this) {
                            otherCheckbox.checked = false;
                        }
                    });
                }
            });
        });
    </script>