
<div class="product-faq-section">
   <div class="container reveal1">
      <div class="h-title">Frequently asked questions</div>
      <div class="faq-list">
         <input type="checkbox" id="title1" />
         <label for="title1">What is Orlistat?</label>
         <div class="panel-p">
            <p>Orlistat is a medicine used to treat obesity. It acts on your digestive system avoiding digesting about a third of the fat contained in the food you eat. Orlistat binds to enzymes in your digestive system (lipases), preventing them from hydrolyzing part of the fats that have ingested during food. The undigested fat cannot be absorbed and is eliminated by your body. Orlistat is indicated for the treatment of obesity, along with a reduced calorie diet.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title2" />
         <label for="title2">How does it work?</label>
         <div class="panel-p">
            <p>Orlistat is a powerful, specific, and long-acting inhibitor of gastrointestinal lipases. It exercises its therapeutic activity in the lumen of the stomach and small intestine by bonding covalent with the active serine site of gastric and pancreatic lipases. The inactivated enzyme is not available to hydrolyze dietary fat, in the form of triglycerides, to absorbable free fatty acids and Monoglycerides.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title3" />
         <label for="title3">What are the benefits of taking it?</label>
         <div class="panel-p">
            <p>Orlistat is a weight loss pill. This medication is normally part of a complete weight loss program, which includes diet and exercise. When taken with meals, it works by altering the way the body processes the fats that are consumed.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title4" />
         <label for="title4">How do I use it and its dosage?</label>
         <div class="panel-p">
            <p>Always use this effective weight loss medication exactly as your doctor or pharmacist has told you. If in doubt, consult your doctor or pharmacist again.</p>
            <p>The recommended dose is one 120 mg capsule taken with each of the three main meals of the day. It can be taken immediately before, during, or up to an hour after food. The capsule must be ingested with water.</p>
            <p>Orlistat should be taken with a calorie-controlled diet, well balanced, rich in fruits and vegetables, and containing an average of 30% of calories from fat. Your daily intake of fats, carbohydrates, and protein should be spread over three meals. This means that you will usually take one capsule for breakfast, one for lunch and one for dinner. For optimal benefits, avoid eating fat-containing foods between meals, such as cookies, chocolate, or salty snacks.</p>
            <p>Orlistat works only in the presence of dietary fats. Therefore, you do not need to take orlistat if you do not have a main meal or a meal that does not contain fat.</p>
            <p>If for any reason you have not taken your medicine exactly as it was prescribed, tell your doctor. Otherwise, your doctor may think that this medicine was not effective or well tolerated and you can change your treatment without it.</p>
            <p>Your doctor will stop orlistat treatment if after 12 weeks you have not lost at least 5% of your weight at the start of treatment. Orlistat has been studied in clinical trials of up to 4 years in duration.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title5" />
         <label for="title5">Side effects & precautions</label>
         <div class="panel-p">
            <p>Like all medicines, this weight loss treatment medication can cause side effects, although not everybody gets them.</p>
            <p>If you are not feeling well while you are taking orlistat, tell your doctor or pharmacist as soon as possible.</p>
            <p>Most of the unwanted effects related to the use of orlistat result from its local action on the digestive system. These symptoms are generally moderate, occur at the beginning of treatment, and occur especially after meals that have high levels of fat.</p>
            <p>These symptoms usually disappear if you continue treatment and follow the recommended diet.</p>
            <p>The following section details the known Orlistat side effects and their frequency.</p>
            <p>Very common side effects (affect more than 1 in 10 patients)</p>
            <ul>
               <li>Headache, abdominal pain or discomfort, urgency or increased need to defecate, flatulence (gas) with fecal incontinence, oily stool incontinence, oily or fatty stools, liquid stools, low blood sugar levels (experienced by some patients with type diabetes two)</li>
            </ul>
            <p>Common side effects (affects 1 to 10 users in 100)</p>
            <ul>
               <li>Rectal pain or discomfort, loose stools, incontinence (fecal), swelling (experienced by some patients with type 2 diabetes), tooth and gum abnormalities, irregular menstrual cycle, fatigue.</li>
            </ul>
            <p>The following Orlistat side effects have also been reported but their frequencies cannot be estimated from the available data:</p>
            <p>Allergic reactions. The main symptoms are itching, skin rash, hives (slightly raised areas of skin that itch and are paler or reddened than the surrounding skin), great difficulty breathing, nausea, vomiting, and feeling sick. Blisters on the skin (includes blisters that explode). Diverticulitis. Rectal bleeding. Increases in liver enzyme levels can be detected in blood tests. Hepatitis (inflammation of the liver). Symptoms may include yellowing of the skin and eyes, itching, dark-colored urine, stomach pain, and liver tenderness (indicated by pain under the front of the rib cage on the right side), sometimes with loss of appetite Stop taking orlistat tablets if these symptoms appear and inform your doctor. Gallstones. Pancreatitis (inflammation of the pancreas). Oxalate nephropathy (developed by calcium oxalate that can cause kidney stones).</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title6" />
         <label for="title6">Buying Orlistat online</label>
         <div class="panel-p">
            <p>You can buy Orlistat online through one of the UK’s leading online pharmacies, Pharmacy Planet. It's easy and convenient. You will need to fill out a short assessment and the item will be delivered directly to your door. If you want to buy the orlistat Superdrug online, use Pharmacy Planet, a UK pharmacy you can trust.</p>
         </div>
      </div>
   </div>
</div>
<script>
   document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(checkbox => {
       checkbox.addEventListener('change', function () {
           if (this.checked) {
               document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(otherCheckbox => {
                   if (otherCheckbox !== this) {
                       otherCheckbox.checked = false;
                   }
               });
           }
       });
   });
</script>