 
<div class="product-faq-section">
   <div class="container reveal1">
      <div class="h-title">Frequently asked questions</div>
      <div class="faq-list">
         <input type="checkbox" id="title1" />
         <label for="title1">Is Retatrutide the same as Semaglutide?</label>
         <div class="panel-p">
            <p>No, Retatrutide is not the same as Semaglutide. While both medications are used to manage type 2 diabetes and work as GLP-1 receptor agonists, they have different mechanisms of action and clinical profiles.</p>
            <table style="border-collapse: collapse; width: 100%; height: 90px;" border="1">
               <tbody>
                  <tr style="height: 18px;">
                     <td style="width: 33.3333%; height: 18px;">&nbsp;</td>
                     <td style="width: 33.3333%; height: 18px;">Retatrutide</td>
                     <td style="width: 33.3333%; height: 18px;">Semaglutide</td>
                  </tr>
                  <tr style="height: 18px;">
                     <td style="width: 33.3333%; height: 18px;">Mechanism of Action</td>
                     <td style="width: 33.3333%; height: 18px;">GLP-1 Agonist, GIP Agonist and Glucagon Agonist</td>
                     <td style="width: 33.3333%; height: 18px;">GLP-1 Agonist</td>
                  </tr>
                  <tr style="height: 18px;">
                     <td style="width: 33.3333%; height: 18px;">Primary Function</td>
                     <td style="width: 33.3333%; height: 18px;">
                        <p>It stimulates insulin release and curbs glucagon output</p>
                        <p>Also affects gastric emptying and i<span style="font-family: Verdana, Arial, Helvetica, sans-serif; color: #000000;">mpacts the incretin system</span></p>
                     </td>
                     <td style="width: 33.3333%; height: 18px;">
                        <p>It stimulates insulin release and controls the glucagon output.</p>
                        <p>It lowers the plasma glucose concentrations</p>
                     </td>
                  </tr>
                  <tr style="height: 18px;">
                     <td style="width: 33.3333%; height: 18px;">Efficacy</td>
                     <td style="width: 33.3333%; height: 18px;">
                        <p>More effective in reducing fasting plasma glucose levels and LDL cholesterol</p>
                        <p>Higher benefits for glycemic control</p>
                     </td>
                     <td style="width: 33.3333%; height: 18px;">
                        <p>More effective in reducing fasting plasma glucose levels.</p>
                        <p>Cardio vascular benefitsr</p>
                     </td>
                  </tr>
                  <tr style="height: 18px;">
                     <td style="width: 33.3333%; height: 18px;">Clinical Indications</td>
                     <td style="width: 33.3333%; height: 18px;">Comprehensive metabolic health management</td>
                     <td style="width: 33.3333%; height: 18px;">
                        <p>Glycemic control</p>
                        Reduction in Cardiovascular-related risks
                     </td>
                  </tr>
               </tbody>
            </table>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title2" />
         <label for="title2">What is the difference between Retatrutide vs Tirzepatide?</label>
         <div class="panel-p">
            <p>Tirzepatide acts within two pathways, by mimicking the naturally occurring hormones GLP-1 and GIP, which are responsible for regulating the appetite and insulin secretion in response to meals. Meanwhile ,Retatrutide acts in three pathways i.e. GLP-1 Agonist, GIP and Glucagon Agonist which provides additional benefits of increased metabolic rate and suppressing appetite more effectively. This makes Retatrutide a comprehensive treatment option for managing both type 2 diabetes and obesity.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title3" />
         <label for="title3">What are the side effects of Retatrutide?</label>
         <div class="panel-p">
            <p>Though Retatrutide improves blood pressure and blood sugar levels, like other weight loss medications, Retatrutide can cause some side effects which may more likely be associated with gastrointestinal symptoms such as nausea, constipation, vomiting and diarrhoea. It remains uncertain if Retatrutide would cause the above side effects or severe health conditions as it is still in its testing phases.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title4" />
         <label for="title4">What are the doses for Retatrutide?</label>
         <div class="panel-p">
            <p>The dose of Retatrutide has not been finalised since it is still in its development phase. Usually a dosage chart will be followed with every medication to ensure maximum potential of the dosage is attained and also to minimize the side effects. In Phase 2 of <a href="https://www.nejm.org/doi/full/10.1056/NEJMoa2301972" target="_blank" rel="noopener">clinical trials</a> , Participants were given following doses subcutaneously to understand the effects of the medication.</p>
            <table style="border-collapse: collapse; width: 100%; height: 287px;" border="1">
               <tbody>
                  <tr style="height: 18px;">
                     <td style="width: 20%; height: 18px; text-align: center;">
                        <p><strong>Group</strong></p>
                     </td>
                     <td style="width: 20%; height: 18px; text-align: center;">
                        <p><strong>Dose</strong></p>
                     </td>
                     <td style="width: 20%; height: 18px; text-align: center;">
                        <p><strong>Initial Dose</strong></p>
                     </td>
                     <td style="width: 20.0237%; height: 18px; text-align: center;">
                        <p><strong>Number of Participants</strong></p>
                     </td>
                     <td style="width: 20%; height: 18px; text-align: center;">
                        <p><strong>Duration</strong></p>
                     </td>
                  </tr>
                  <tr style="height: 17px;">
                     <td style="width: 20%; height: 17px; text-align: center;">
                        <p><strong>Retatrutide 1 mg</strong></p>
                     </td>
                     <td style="width: 20%; height: 17px; text-align: center;">1 mg</td>
                     <td style="width: 20%; height: 17px; text-align: center;">-</td>
                     <td style="width: 20.0237%; text-align: center;">
                        <p>1/10 of total participants</p>
                     </td>
                     <td style="width: 20%; text-align: center;">
                        <p>48 weeks</p>
                     </td>
                  </tr>
                  <tr style="height: 18px;">
                     <td style="width: 20%; height: 18px; text-align: center;">
                        <p><strong>Retatrutide 4 mg (Group 1)</strong></p>
                     </td>
                     <td style="width: 20%; height: 18px; text-align: center;">4 mg</td>
                     <td style="width: 20%; height: 18px; text-align: center;">2 mg</td>
                     <td style="width: 20.0237%; text-align: center;">
                        <p>1/10 of total participants</p>
                     </td>
                     <td style="width: 20%; text-align: center;">
                        <p>48 weeks</p>
                     </td>
                  </tr>
                  <tr style="height: 64px;">
                     <td style="width: 20%; height: 64px; text-align: center;">
                        <p><strong>Retatrutide 4 mg (Group 2)</strong></p>
                     </td>
                     <td style="width: 20%; height: 64px; text-align: center;">4 mg</td>
                     <td style="width: 20%; height: 64px; text-align: center;" width="72">
                        <p>4 mg</p>
                     </td>
                     <td style="width: 20.0237%; text-align: center;">
                        <p>1/10 of total participants</p>
                     </td>
                     <td style="width: 20%; text-align: center;">
                        <p>48 weeks</p>
                     </td>
                  </tr>
                  <tr style="height: 64px;">
                     <td style="width: 20%; height: 64px; text-align: center;">
                        <p><strong>Retatrutide 8 mg (Group 1)</strong></p>
                     </td>
                     <td style="width: 20%; height: 64px; text-align: center;" width="53">
                        <p>8 mg</p>
                     </td>
                     <td style="width: 20%; height: 64px; text-align: center;" width="72">
                        <p>2 mg</p>
                     </td>
                     <td style="width: 20.0237%; text-align: center;">
                        <p>1/10 of total participants</p>
                     </td>
                     <td style="width: 20%; text-align: center;">
                        <p>48 weeks</p>
                     </td>
                  </tr>
                  <tr style="height: 18px;">
                     <td style="width: 20%; height: 18px; text-align: center;"><strong>Retatrutide 8 mg (Group 2)</strong></td>
                     <td style="width: 20%; height: 18px; text-align: center;" width="53">
                        <p>8 mg</p>
                     </td>
                     <td style="width: 20%; height: 18px; text-align: center;" width="72">
                        <p>4 mg</p>
                     </td>
                     <td style="width: 20.0237%; text-align: center;">
                        <p>1/10 of total participants</p>
                     </td>
                     <td style="width: 20%; text-align: center;">
                        <p>48 weeks</p>
                     </td>
                  </tr>
                  <tr style="height: 44px;">
                     <td style="width: 20%; height: 44px; text-align: center;">
                        <p><strong>Retatrutide 12 mg</strong></p>
                     </td>
                     <td style="width: 20%; height: 44px; text-align: center;" width="53">
                        <p>12 mg</p>
                     </td>
                     <td style="width: 20%; height: 44px; text-align: center;" width="72">
                        <p>2 mg</p>
                     </td>
                     <td style="width: 20.0237%; text-align: center;">
                        <p>2/10 of total participants</p>
                     </td>
                     <td style="width: 20%; text-align: center;">
                        <p>48 weeks</p>
                     </td>
                  </tr>
                  <tr style="height: 44px;">
                     <td style="width: 20%; height: 44px; text-align: center;">
                        <p><strong>Placebo</strong></p>
                     </td>
                     <td style="width: 20%; height: 44px; text-align: center;">-</td>
                     <td style="width: 20%; height: 44px; text-align: center;">-</td>
                     <td style="width: 20.0237%; text-align: center;">
                        <p>2/10 of total participants</p>
                     </td>
                     <td style="width: 20%; text-align: center;">
                        <p>48 weeks</p>
                     </td>
                  </tr>
               </tbody>
            </table>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title5" />
         <label for="title5">Is Retatrutide for diabetes?</label>
         <div class="panel-p">
            <p>Since Retataturtide acts in three pathways and activates the GIP, GLP-1 and glucagon receptors, it is likely to be an effective treatment for the following conditions:</p>
            <ul>
               <li>Type 2 Diabetes</li>
               <li>Obesity</li>
               <li>Fatty Liver Disease</li>
               <li>High Blood Pressure</li>
            </ul>
         </div>
      </div>
   </div>
</div>
<script>
   document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(checkbox => {
       checkbox.addEventListener('change', function () {
           if (this.checked) {
               document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(otherCheckbox => {
                   if (otherCheckbox !== this) {
                       otherCheckbox.checked = false;
                   }
               });
           }
       });
   });
</script>