<div class="product-faq-section">
   <div class="container reveal1">
      <div class="h-title">Frequently asked questions</div>
      <div class="faq-list">
         <input type="checkbox" id="title1" />
         <label for="title1">What Is Rybelsus (Semaglutide)?</label>
         <div class="panel-p">
            <p>Rybelsus (semaglutide) is a prescription medication used to improve glycemic control in adults with type 2 diabetes. It belongs to a class of drugs called glucagon-like peptide-1 (GLP-1) receptor agonists, which work by increasing the amount of insulin released by the pancreas in response to high blood sugar levels, and by decreasing the amount of glucose produced by the liver.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title2" />
         <label for="title2">How Does Rybelsus (Semaglutide) Work?</label>
         <div class="panel-p">
            <p>Rybelsus works by mimicking the effects of GLP-1, a hormone that regulates insulin and glucose in the body. When Rybelsus is taken, it binds to GLP-1 receptors in the pancreas, which stimulates the release of insulin and suppresses the release of glucagon (a hormone that raises blood sugar levels). This helps to lower blood sugar levels and improve glucose control in people with type 2 diabetes.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title3" />
         <label for="title3">What Are The Benefits Of Taking Rybelsus (Semaglutide)?</label>
         <div class="panel-p">
            <p>Some benefits of taking Rybelsus include improved glycemic control, weight loss, and reduced risk of cardiovascular events. It may also improve beta cell function and reduce the risk of hypoglycemia (low blood sugar).</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title4" />
         <label for="title4">How Do I Use Rybelsus (Semaglutide)?</label>
         <div class="panel-p">
            <p>Rybelsus is a once-daily tablet that is usually taken in the morning. The dosage may be adjusted by a healthcare provider based on an individual's blood sugar levels and response to treatment. It is important to follow the dosing instructions provided by a healthcare provider.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title5" />
         <label for="title5">Rybelsus (Semaglutide) Dosage Precautions and Side Effects</label>
         <div class="panel-p">
            <p>The recommended starting dose of Rybelsus is 3 mg once daily, with the option to increase to 7 mg or 14 mg once daily based on efficacy and tolerability. The most common side effects of Rybelsus include nausea, diarrhea, constipation, and vomiting. It may also cause low blood sugar, especially when taken with other diabetes medications. It is important to inform a healthcare provider of any other medications being taken and any medical conditions, as Rybelsus may not be suitable for everyone.</p>
            <p>The most common side effects of Rybelsus (semaglutide) include:</p>
            <ul>
            <li>Nausea
            <li>
            <li>Diarrhea
            <li>
            <li>Constipation
            <li>
            <li>Vomiting
            <li>
            <li>Headache
            <li>
            <li>Low blood sugar (hypoglycemia)
            <li>
            <li>Injection site reactions (redness, itching, swelling)
            <li>
            <li>Dizziness</li>
            <li>Fatigue
            <li>
            <li>Abdominal pain</li>
            <li>Gastrointestinal symptoms (such as stomach discomfort)
            <li>
            </li>
            <p>It's also worth mentioning that Rybelsus may cause weight loss and may cause a decrease in appetite, which can lead to weight loss and malnutrition.</p>
            <p>It's important to note that this is not an exhaustive list, and you should always consult with your healthcare provider if you experience any side effects while taking Rybelsus. Also, it's important to mention that Rybelsus may not be suitable for everyone and you should inform your healthcare provider of any medical conditions and any other medications you are taking before starting treatment with Rybelsus.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title5" />
         <label for="title5">Buying Rybelsus online</label>
         <div class="panel-p">
            <p>You can buy Rybelsus (semaglutide) online through one of the UK’s leading online pharmacies, Pharmacy Planet. It's easy and convenient. You will need to fill out a short assessment and the item will be delivered directly to your door. If you want to buy Azopt online, use Pharmacy Planet, a UK pharmacy you can trust.</p>
         </div>
      </div>
   </div>
</div>
<script>
   document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(checkbox => {
       checkbox.addEventListener('change', function () {
           if (this.checked) {
               document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(otherCheckbox => {
                   if (otherCheckbox !== this) {
                       otherCheckbox.checked = false;
                   }
               });
           }
       });
   });
</script>