
<div class="product-faq-section">
   <div class="container reveal1">
      <div class="h-title">Frequently asked questions</div>
      <div class="faq-list">
         <input type="checkbox" id="title1" />
         <label for="title1">Why am I not losing weight on Wegovy?</label>
         <div class="panel-p">
            <p>If you're not losing weight on Wegovy after six months, there could be several factors that might be affecting your weight loss progress. Wegovy may not be effective if you eat high-calorie foods such as desserts, sweets, fast foods, etc. poor hydration, lack of exercise, and inadequate sleep. Adjusting your diet with more vegetables and low-calorie foods, exercising regularly, and taking the medication consistently will help you reduce weight. If you have any underlying medical conditions like hypothyroidism or type 2 diabetes then it is advised to consult your healthcare physician for further assistance.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title2" />
         <label for="title2">Is Wegovy Approved for weight loss?</label>
         <div class="panel-p">
            <p>Yes, Wegovy (semaglutide) is one of the approved weight loss medications, alongside Saxenda and Orlistat. It is a weekly injectable prescription-only medication recommended for those with a BMI above 30, or 27 for those with weight-related conditions like hypertension. Wegovy is very effective when used along with a reduced-calorie diet and regular physical exercise provider.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title3" />
         <label for="title3">Is Wegovy the same as Ozempic?</label>
         <div class="panel-p">
            <p>Wegovy and Ozempic are both prescription medications exist under different brand names that contain the same active ingredient, semaglutide. The key difference is Wegovy is specifically approved for weight loss and is used in weight management for obesity, while Ozempic is licensed to treat type 2 diabetes because it effectively controls blood sugar levels. </p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title4" />
         <label for="title4">Can you inject Wegovy cold?</label>
         <div class="panel-p">
            <p>Yes, Wegovy can be taken when it is cold. After opening, it should be kept inside the refrigerator between 2°C to 8°C. Avoid placing it in the direct sunlight and above 30°C. Make sure you use the Wegovy Pen within 6 weeks from the date of opening.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title5" />
         <label for="title5">Will I gain weight if I stop using Wegovy?</label>
         <div class="panel-p">
            <p>Yes, in some cases, weight regain can occur after you stop taking Wegovy as your appetite is expected to return to normal within a week. However, certain metabolic benefits, such as improved blood sugar control, may still be retained in the body. To maintain the weight loss achieved during treatment, it's essential to follow a healthy diet and engage in regular physical exercise.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title6" />
         <label for="title6">Who cannot take Wegovy?</label>
         <div class="panel-p">
            <p><strong>You must not take Wegovy if:</strong></p>
            <ul>
               <li>You are below 18 years old</li>
               <li>You are pregnant</li>
               <li>You are breast feeding</li>
               <li>You have or had any hereditary history of Medullary Thyroid Carcinoma or hypothyrodisim or MENS 2 or any other thyroid conditions.</li>
               <li>You are allergic to the active ingredient semaglutide or any other ingredient found in the drug.</li>
            </ul>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title7" />
         <label for="title7">How much weight do you lose in a month with Wegovy?</label>
         <div class="panel-p">
            <p>If you started taking wegovy (Semaglutide), you can expect losing up to 5% of your body weight in the first month. Some may experience immediate results of losing 2 pounds of weight per week which is around 8 pounds in a month. In Clinical trials it has been found that patients can lose 15% of their body weight with long term use i.e. over a year with lifestyle interventions. The results of weight loss differs between individuals depending on several factors such as medication dosage, age, diet, exercise etc.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title8" />
         <label for="title8">Where can I get wegovy in the UK?</label>
         <div class="panel-p">
            <p>You can buy Wegovy weight loss injections online from Pharmacy Planet by filling out a clinical consultation questionnaire available on our website. Our in-house team of prescribers will assess your responses and prescribe you the medication if it is suitable for you.</p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title9" />
         <label for="title9">Links and Related Information</label>
         <div class="panel-p">
            <p><a href="https://www.pharmacyplanet.com/blog/post/ozempic-vs-wegovy">Ozempic Vs Wegovy</a></p>
            <p><a href="https://www.pharmacyplanet.com/blog/post/what-is-semaglutide">What is Semaglutide?</a></p>
            <p><a href="https://www.pharmacyplanet.com/blog/post/ozempic-hollywoods-favourite-weight-loss-drug">Ozempic: Hollywoods Favourite Weight Loss Drug</a></p>
            <p><a href="https://www.pharmacyplanet.com/blog/post/everything-you-need-to-know-about-wegovy">Everything You Need To Know About Wegovy</a></p>
            <p><a href="https://www.pharmacyplanet.com/blog/post/wegovy-vs-other-weight-loss-solutions">Wegovy vs. Other Weight Loss Solutions</a></p>
            <p><a href="https://www.pharmacyplanet.com/blog/post/when-will-wegovy-be-available-exploring-prices-and-cost-effectiveness">When Will Wegovy Be Available? Exploring Prices and Cost Effectiveness</a></p>
            <p><a href="https://www.pharmacyplanet.com/blog/post/wegovy-weight-loss-results-how-much-weight-can-you-expect-to-lose">Wegovy Weight Loss Results: How Much Weight Can You Expect To Lose?</a></p>
            <p><a href="https://www.pharmacyplanet.com/blog/post/mastering-the-art-of-injecting-wegovy-tips-techniques-and-key-differences-from-ozempic">Mastering The Art Of Injecting Wegovy: Tips, Techniques, And Key Differences From Ozempic</a></p>
            <p><a href="https://www.pharmacyplanet.com/blog/post/the-truth-about-wegovy-and-that-side-effect">The Truth About Wegovy And That Side Effect</a></p>
            <p><a href="https://www.pharmacyplanet.com/blog/post/wegovy-and-emotional-well-being-the-psychological-impact-of-weight-loss">Wegovy And Emotional Well-Being: The Psychological Impact Of Weight Loss</a></p>
         </div>
      </div>
      <div class="faq-list">
         <input type="checkbox" id="title10" />
         <label for="title10">PATIENT INFORMATION LEAFLET (PIL)</label>
         <div class="panel-p">
            <p>Please read the important safety precautions carefully and other info about Wegovy provided in the patient information leaflet. This can be found in the medication box, or you can use the link provided for a <a href="https://www.medicines.org.uk/emc/files/pil.13801.pdf" target="_blank" rel="noopener">digital copy</a>.</p>
         </div>
      </div>
   </div>
</div>
<script>
   document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(checkbox => {
       checkbox.addEventListener('change', function () {
           if (this.checked) {
               document.querySelectorAll('.product-faq-section .faq-list input[type="checkbox"]').forEach(otherCheckbox => {
                   if (otherCheckbox !== this) {
                       otherCheckbox.checked = false;
                   }
               });
           }
       });
   });
</script>