<section class="slider-wrapper desk-review-slider google-review-section">
	 
<!-- <div class="h-title">What our patients are saying?</div> -->
  <!-- TrustBox widget - Carousel -->
  <div class="trustpilot-widget" data-locale="en-GB" data-template-id="53aa8912dec7e10d38f59f36" data-businessunit-id="62de404543cebd829464951e" data-style-height="140px" data-style-width="100%" data-stars="5" data-review-languages="en">
    <a href="https://uk.trustpilot.com/review/magento-1584919-6629151.cloudwaysapps.com" target="_blank" rel="noopener">Trustpilot</a>
  </div>
 
  <!-- End TrustBox widget -->
</section>
