<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($_description = $block->getCurrentCategory()->getDescription()) :?>
    <div class="category-description main-cat-desc">
        <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
            $block->getCurrentCategory(),
            $_description,
            'description'
        ) ?>
    </div>
    <button class="main-cat-btn btn btn-primary" type="button">
        <span class="readmore">Read More</span>
        <span class="icona"><i class="fa fa-caret-down" aria-hidden="true"></i></span>
    </button>

    <script>
        require(['jquery'], function($){

            var descHtml = `<?php echo /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute($block->getCurrentCategory(),$_description,'description'); ?>`;

            $(".main-cat-desc").each(function () {
                if (descHtml.length > 300) {
                    $(this).html(descHtml.substr(0, descHtml.lastIndexOf(' ', 297)) + ' ..');
                    $(".main-cat-btn").addClass('active');
                }
            });

            $(".main-cat-btn").click(function (e) {
                e.preventDefault();
                if($(this).hasClass('active-read')){
                    $(this).find('span.icona').html('<i class="fa fa-caret-down" aria-hidden="true"></i>');
                    $(this).find('.readmore').html('Read More');
                    $(this).removeClass('active-read');
                    $(".main-cat-desc").html(descHtml.substr(0, descHtml.lastIndexOf(' ', 297)) + ' ..');
                    $('html, body').animate({
                    scrollTop: $('.page-title-wrapper').offset().top
                }, 500);
                }else{
                    $(this).find('span.icona').html('<i class="fa fa-caret-up" aria-hidden="true"></i>');
                    $(this).find('.readmore').html('Read less');
                    $(this).addClass('active-read');
                    $(".main-cat-desc").html(descHtml);
                    $('html, body').animate({
                    scrollTop: $('.page-title-wrapper').offset().top
                }, 500);
                }
            });
        });
    </script>

<?php endif; ?>