<div class="weight-loss-journey mf-initial" data-was-processed="true">
  <div class="container mf-initial" data-was-processed="true">
  <div class="h-title" data-was-processed="true"></div>
    <div class="timeframe-subheading reveal1 mf-initial" data-was-processed="true">
      <div class="medicine-icon-content weight-loss1 mf-initial" data-was-processed="true">
        <h4>ANSWER THE CLINICAL QUESTIONNAIRE</h4>
        <ul>
          <li>This helps our clinical team to ensure the treatment is suitable for you.</li>
        </ul>
      </div>
    </div>
    <div class="timeframe-subheading reveal1 mf-initial" data-was-processed="true">
      <div class="docter-icon-content weight-loss2 mf-initial" data-was-processed="true">
        <h4>CHOOSE YOUR TREATMENT</h4>
        <ul>
          <li>Next, select your treatment from the list.</li>
        </ul>
      </div>
    </div>
    <div class="timeframe-subheading reveal1 mf-initial" data-was-processed="true">
      <div class="delivery-icon-content weight-loss3 mf-initial" data-was-processed="true">
        <h4>CHECKOUT AND DELIVERY</h4>
        <ul>
          <li>Complete the checkout and our clinical team will get started on your order. Keep an eye on your inbox for updates.</li>
        </ul>
      </div>
    </div>
  </div>
</div>
