<div class="meet-team-section2 inner">
    <div class="container">
        <div class="team-2 reveal1">
            <img src="<?php echo  $this->getBaseUrl(); ?>media/wysiwyg/WLImage/uk.png" alt="UK Registered pharmacy">
            <h3>UK Registered pharmacy</h3>
        </div>

        <div class="team-2 reveal1">
            <img src="<?php echo $this->getBaseUrl(); ?>media/wysiwyg/WLImage/Mhra.png" alt="MHRA authorised">
            <h3>MHRA authorised medications</h3>
        </div>

        <div class="team-2 reveal1">
            <img src="<?php echo $this->getBaseUrl(); ?>media/wysiwyg/WLImage/myfitnesspal-svgrepo-com.png" alt="Over 10 years experience">
            <h3>Over 10 years experience</h3>
        </div>
    </div>
</div>