<?php
/**
 * Webkul Software
 *
 * @category    Webkul
 * @package     Webkul_OutOfStockNotification
 * @author      Webkul
 * @copyright   Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license     https://store.webkul.com/license.html
 */
?>

<div class="wk-loading-mask-outer wk-display-none">
        <div class="wk-loader"></div>
    </div>
    <div class="wk-container wk-display-none">
        <div class="wk-oosn-container">
            <div class="wk-oosn-notificationcontainer">
                <div class="wk-loading-mask wk-display-none">
                    <div class="wk-loader"></div>
                </div>
                <p class="test-product test-new" onclick="myFunction()">Notify me once available</p>
                <div id="wk-notification-container" style="display: none">
                    <label>Enter your email id</label>
                    <div class="wk-oosn-emailBox" data-bind="scope: 'section'">
                        <input type="text" name='email' id="oosn_email" placeholder="Enter Your Email Id" data-bind="value: customer().email" />
                    </div>
                    <button type="button" title="<?= $block->escapeHtml(__("Notify Me")) ?>" 
                    class="action primary tocart" id="wk-oosn-button">
                        <span><?=$block->escapeHtml(__("Notify Me")); ?></span>
                    </button>
                </div>
            </div>
        </div>
        <div id="wk-oosn-warning" class="message"></div>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "section": {
                        "component": "Webkul_OutOfStockNotification/js/section"
                    }
                }
            }
        }
    }
</script>
<!-- 24 | WARNING | Unescaped output detected.
 26 | WARNING | Unescaped output detected.
 27 | WARNING | Unescaped output detected. -->
<script type="text/javascript">
function myFunction(){
       // $("#wk-notification-container").toggle();
var x = document.getElementById("wk-notification-container");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}

require(['jquery', 'jquery/ui'], function($){  
  $(document).ready( function() {
    if($('.test-product').length > 1) {
  //console.log('yes, more than one element exist');
  $('.test-product.test-new').hide();
  
}else{
    $('.test-product.test-new').show();
    // $('#wk-notification-container').show();
}

});


});
</script>