<h2>Hii hello</h2>
<?= $this->helper("Amasty\Customform\Helper\Data")->renderForm("6") ?>
<div class="product-question-right">
    <div class="info-1">
        <div class="info-img"><img class="" src="/static/frontend/Custom/luma_child/en_GB/images/manesha-img.jpg" alt="Manesha"></div>
        <div class="info_details_1 question-text">
            <h3>You’re almost there!</h3>
            <p>It is the prescribers duty to ensure that the medicine is being used safely and appropriately. please answer a few questions about yourself to help us process your request.</p>
        </div>
        <h3>- Manesha</h3>
        <p>Customer Service Team</p>
    </div>
    <div class="info-1 info_list">
        <h2 class="info_title_1">Confidentiality &amp; Authenticity Assured</h2>
        <ul>
            <li>Fully Regulated UK Pharmacy</li>
            <li>Authentic UK sourced medicines only.</li>
            <li>Trading for more than 10 years.</li>
            <li>Information Governance lead ensures all data is confidential</li>
        </ul>
    </div>
    <div class="info-1 info_list info_2">
        <h2 class="info_title_2">Need Help With Your Questionnaire?</h2>
        <p>Our customer service team is on hand Monday-Friday to help you with your queries.</p>
        <p>Please call us on <strong><a class="tel-link" href="tel:08009788956">08009788956</a></strong> or<br>email us at: <a href="mailto:headoffice@pharmacyplanet.com"><strong>headoffice@pharmacyplanet.com</strong></a></p>
    </div>
</div>