<div class="product-details-sec-new desktop-cont-tab">
   <div class="container">
      <div class="product-details">
         <nav class="section-nav">
            <p class="links-sec">LINKS</p>
            <ul>
               <li>
                  <a href="#about-survodutide">About Survodutide</a>
               </li>
               <li>
                  <a href="#side-effects-survodutide">Side effects of Survodutide</a>
               </li>
               <li>
                  <a href="#is-survodutide-available-in-stock-the-uk">Is Survodutide available in stock in the UK?</a>
               </li>
               <li>
                  <a href="#are-there-any-alternative-treatments-for-weight-loss">Are there any alternative treatments for weight loss?</a>
               </li>
               <li>
                  <a href="#be-the-first-know">Be the first to know</a>
               </li>
            </ul>
         </nav>
         <div class="tab-content-right-sec">
            <section id="about-survodutide">
               <h2>About Survodutide</h2>
               <div class="tab-content-sec">
                  <p>Unlike other dual GLP-1/glucagon dual agonists, it is an glucagon analog rather than an analog of oxyntomodulin. It means that survodutide is based on the properties of glucagon, a hormone involved in regulating blood sugar levels, rather than oxyntomodulin, another hormone with similar effects on metabolism. This distinction may impact the specific mechanisms of action and result in potential therapeutic effects of Survodutide compared to other dual agonists.</p>
               </div>
            </section>
            <section id="side-effects-survodutide">
               <h2>Side effects of Survodutide</h2>
               <div class="tab-content-sec">
                  <p>The safety analysis of the trial showed that there arwe no unexpected safety concerns or issues with tolerability, including with the 6.0 mg dose.</p>
               </div>
            </section>
            <section id="is-survodutide-available-in-stock-the-uk">
               <h2>Is Survodutide available in stock in the UK?</h2>
               <div class="tab-content-sec">
                  <p>Survodutide has not yet been approved or released for purchase in the UK. It is still in developmental phase and as soon as it becomes available, you can buy online in Pharmacy planet for the lowest price in the UK for weight loss treatment.</p>
               </div>
            </section>
            <section id="are-there-any-alternative-treatments-for-weight-loss">
               <h2>Are there any alternative treatments for weight loss?</h2>
               <div class="tab-content-sec">
                  <p>Yes, there are other drugs such as <a tabindex="0" href="https://www.pharmacyplanet.com/mounjaro.html" >Mounjaro</a> , <a tabindex="0" href="https://www.pharmacyplanet.com/ozempic.html" >Ozempic</a> and <a tabindex="0" href="https://www.pharmacyplanet.com/wegovy.html">Wegovy</a> are available for treating weight loss or obesity. Your healthcare provider can help you figuring out the right medicine for you. Alternatively, you can opt for an online medical consultation with us, where our clinicians will guide you towards the most appropriate solution.</p>
               </div>
            </section>
            <section id="be-the-first-know">
               <h2>Be the first to know</h2>
               <div class="tab-content-sec">
                  <p>Sign up to be the first to know when Survodutide becomes available by clicking the 'Notify me once available' button above and enter your email. We'll keep you up to date with the latest developments concerning Survodutide and let you know as soon as it becomes available in the UK.</p>
               </div>
            </section>
         </div>
      </div>
   </div>
</div>
<div class="mobile-cont-tab">
   <div class="faq-section-new">
      <div class="container reveal1">
         <div class="h-title">
            LINKS
         </div>
         <div class="faq-list">
            <button class="accordion-p">About Survodutide</button>
            <div class="panel-p">
               <p>Unlike other dual GLP-1/glucagon dual agonists, it is an glucagon analog rather than an analog of oxyntomodulin. It means that survodutide is based on the properties of glucagon, a hormone involved in regulating blood sugar levels, rather than oxyntomodulin, another hormone with similar effects on metabolism. This distinction may impact the specific mechanisms of action and result in potential therapeutic effects of Survodutide compared to other dual agonists.</p>
            </div>
         </div>
         <div class="faq-list">
            <button class="accordion-p">Side effects of Survodutide</button>
            <div class="panel-p">
               <p>The safety analysis of the trial showed that there arwe no unexpected safety concerns or issues with tolerability, including with the 6.0 mg dose.</p>
            </div>
         </div>
         <div class="faq-list">
            <button class="accordion-p">Is Survodutide available in stock in the UK?</button>
            <div class="panel-p">
               <p>Survodutide has not yet been approved or released for purchase in the UK. It is still in developmental phase and as soon as it becomes available, you can buy online in Pharmacy planet for the lowest price in the UK for weight loss treatment.</p>
            </div>
         </div>
         <div class="faq-list">
            <button class="accordion-p">Are there any alternative treatments for weight loss?</button>
            <div class="panel-p">
               <p>Yes, there are other drugs such as <a tabindex="0" href="https://www.pharmacyplanet.com/mounjaro.html">Mounjaro</a> , <a tabindex="0" href="https://www.pharmacyplanet.com/ozempic.html">Ozempic</a> and <a tabindex="0" href="https://www.pharmacyplanet.com/wegovy.html">Wegovy</a> are available for treating weight loss or obesity. Your healthcare provider can help you figuring out the right medicine for you. Alternatively, you can opt for an online medical consultation with us, where our clinicians will guide you towards the most appropriate solution.</p>
            </div>
         </div>
         <div class="faq-list">
            <button class="accordion-p">Be the first to know</button>
            <div class="panel-p">
               <p>Sign up to be the first to know when Survodutide becomes available by clicking the 'Notify me once available' button above and enter your email. We'll keep you up to date with the latest developments concerning Survodutide and let you know as soon as it becomes available in the UK.</p>
            </div>
         </div>
      </div>
   </div>
</div>