<div class="container">
  <h1 class="title">Viagra and Alzheimer's Disease</h1>
  <div class="image">
    <h3>IMAGE HERE</h3>
  </div>
  <div class="cta">
    <button>Start Your Consultation</button>
  </div>
  <div class="footer">
    <div class="footer-item">
      <img src="media/theme_template/Path 3245.svg" alt="Easy Access" width="50" height="50">
      <span>Easy Access</span>
    </div>
    <div class="footer-item">
      <img src="/media/theme_template/star-svgrepo-com.svg" alt="Expert Advice" width="50" height="50">
      <span>Expert Advice</span>
    </div>
    <div class="footer-item">
      <img src="/media/theme_template/Mask Group 3.png" alt="24/7 Support" width="50" height="50">
      <span>24/7 Support</span>
    </div>
    <div class="footer-item">
      <img src="https://magento-1195784-4216081.cloudwaysapps.com/media/wysiwyg/mhra.svg" alt="mhra logo" width="50" height="50">
      <span>24/7 Support</span>
    </div>
    <div class="footer-item">
      <img src="https://magento-1195784-4216081.cloudwaysapps.com/media/wysiwyg/pharmacy-logo.svg" alt="pharmacy-logo" width="50" height="50">
      <span>24/7 Support</span>
    </div>

  </div>
</div>