<style>

@import url('https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap');

html {
  scroll-behavior: smooth;
}

body{
	font-family: 'Lato', sans-serif !important;
}


.slider-wrapper.desk-review-slider .demo-content {min-height: 245px;}


 @media screen and (min-width: 768px) {

 	body{
 		overflow-x: hidden;
 	}
 	.page-product-configurable.catalog-product-view .page-main {
	    max-width: 100% !important;
	}

	.page-product-configurable.catalog-product-view .stories-section .container,
	.page-product-configurable.catalog-product-view .home-testimonilas.inner .container{
		max-width: 1260px !important;
	}
 	.page-products.catalog-category-view.amform-body .category-view .category-image{
 		margin-top: 50px !important;
 	}
	.custom-menu-ul li.trustpoilet,
	.view-all-treatment-menu,
	.mppromobanner-style{
		display: none !important;
	}

	.header.content{
		text-align: center;
	}
	.logo{
		float: none;
		display: inline-block;
		width: 100%;
		max-width: 100%;
    	text-align: center;
	}

	.logo img{
		margin: 0 auto;
		width: 232px !important;
    	height: 97px !important;
	}
	.header.content .customMenu {
	    width: 450px;
	    display: inline-block;
	    float: right;
	    margin-top: -9%;
	    z-index: 999999;
	    position: relative;
	}
	 

	 
	.banner-icon{
		height: 43px;
	}
	.rating-header{
		width: auto;
	    float: left;
	    position: absolute;
	    text-align: left;
	    z-index: 999999;
	    display: flex;
	    height: 97px;
	    justify-content: center;
	    align-items: center;
	}
	.rating-header img{
		float: left;
	}
	.rating-header p{
		float: left;
	    margin-left: 10px;
	    margin-top: 8px;
	}
}

.home-testimonilas{
	width: 100%;
	display: inline-block;
	padding:65px 0;
	margin: 75px 0 0px 0 !important;
	background: #E7F2F4;
	text-align: center;
}

.home-testimonilas h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
}

.home-testimonilas .google-review-container{
	width: 100%;
	float: left;
}

.how-it-works-section{
	width: 100%;
	display: inline-block;
	padding:65px 0 40px 0;
	text-align: center;
}
.how-it-works-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 22px 0;
	font-size: 38px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.Works-1{
	width: 315px;
	float: none;
	display: inline-block;
	vertical-align: top;
	position: relative;
	margin: 0 20px;
	margin-bottom: 15px;
}

.work-c{
	position: absolute;
	top: 70px;
	left: 120px;
}
.work-c h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 25px; 
    font-weight: 700; 
    text-align: left;
    letter-spacing: 0.5px;
    text-transform: uppercase;
}

.page-product-configurable .how-it-works-section.inner .work-c h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 25px; 
    font-weight: 700; 
    text-align: left;
    letter-spacing: 0.5px;
    text-transform: uppercase;
}
.work-c p{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 18px; 
    font-weight: 400; 
    text-align: left; 
}


.treatment-options{
	width: 100%;
	float: left;
	padding:65px 0 87px 0;
	margin: 0;
	background: #96D8F0;
}
.treatment-options h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 35px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.home-treatment-block{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0;
	text-align: center;
}
.home_block_1, .fixed-image{
	width: 243px;
	float: none;
	display: inline-block;
	margin: 0 0px;
	border-radius: 8px;
	vertical-align: top;
	background: #fff;
	padding: 40px 25px 0px 25px;
}
.home_block_img{
	height: 260px;
	overflow-y: hidden;
	margin-bottom: 30px;
}

.home_block_1 h3{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px; 
    font-weight: 900; 
    text-align: left;
}
.home_block_1 h3 a{
	color: #000;
}

.home_block_1 p{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 22px 0;
	font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 20px; 
    font-weight: 400; 
    text-align: left;
    min-height: 61px;
}

.home_block_1 .h-banner-btn a,
.home_block_1 .h-banner-btn button{
	width: 145px;
	text-transform: uppercase;
	float: left;
}
.home_block_1 .h-banner-btn a,
.home_block_1 .h-banner-btn button{
    width: 145px;
    display: inline-block;
    text-align: center;
    background: #EC3237;
    font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 55px;
    padding: 0 0px;
    font-weight: 400;
    border-radius: 30px;
    letter-spacing: 0.26px;
    border: 0;
    transition: all .35s;
}
.home_block_1 .h-banner-btn a:hover,
.home_block_1 .h-banner-btn button:hover{
    background: #53CAF5 !important;
}
.footer-consultation .h-banner-btn a{
    width: 280px;
    display: inline-block;
    text-align: center;
    background: #EC3237;
    font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 55px;
    padding: 0 0px;
    font-weight: 400;
    border-radius: 30px;
    letter-spacing: 0.26px;
}
.footer-consultation .h-banner-btn a:hover {
    background: #53CAF5 !important;
}

.included-section{
	width: 100%;
	float: left;
	padding:70px 0;
	margin: 0;
}

.included-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.subsection{
	width: 50%;
	float: left;
}

.subsection h3{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 20px 0;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px; 
    font-weight: 900; 
    text-align: left;
}

.subsection p{
	width: 80%;
	float: left;
	padding: 0;
	margin: 0 0 0px 15px;
	font-size: 15px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 400; 
    text-align: left;
}

.subsection-content{
	width: auto;
	float: left;
	margin-right: 30px;
	padding: 0 0 40px 0;
	margin-bottom: 40px;
	border-bottom: 1px solid #D3DEE1;
}

.subsection-content.last{
	border-bottom: 0 !important;
}
.subsection-content img{
	float: left;
}
 

.video-section{
	width: 100%;
	float: left;
	padding: 80px 0;
	background: #E7F2F4;
	text-align: center;
}

.video-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 50px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.video-section .subsection{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0;
	text-align: center;
}

.subsection-2{
	width: 1028px;
	margin-left: auto;
	margin-right: auto;
	margin-top: 65px;
	display: inline-block;
}
.subsection-2 h3{
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 55px; 
    font-weight: 300; 
    text-align: left;
}

.subsection-2 h3 strong{
	font-weight: 700;
}

.subsection-2 .h-banner-btn{
	width: auto;
	float: right;
}
.subsection-2 .h-banner-btn a{
	width: 220px !important;
}

.meet-team-section2{
	width: 100%;
	float: left;
	padding:65px 0;
	margin: 0;
	background: #E7F2F4;
	text-align: center;
}
.team-2{
	width: 321px;
	float: none;
	display: inline-block;
	background: #fff;
	margin: 0 12px;
	border-radius: 8px;
	padding: 44px 34px;
}
.team-2 img{
	float: left;
}

.team-2 h3{
	padding: 0;
	margin:0 0 0 20px;
	font-size: 18px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 700; 
    text-align: left;
    float: left;
    width: 175px;
}

.stories-section{
	width: 100%;
	float: left;
	padding: 65px 0;
	margin: 0;
	text-align: center;
}
.stories-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.story-1{
	width: 332px;
	float: none;
	display: inline-block;
	vertical-align: top;
	margin: 0 5px;
}


.story-1 .subsection-content{
	width: 100%;
	float: left;
	padding: 0;
	margin:45px 0 0 0;
	border-bottom: 0 !important;
}
.story-1 img{
	border-radius: 8px;
}
.story-1 .subsection-content{
	position: relative;
}
.story-1 .subsection-content:before{
	width: 48px;
	height: 40px;
	display: inline-block;
	content: " " !important;
	background: url(/pub/media/wysiwyg/WLImage/quote-icon.png) 0 0 no-repeat; 
	position: absolute;
	top: -70px;
	left: 0;
}
.story-1 .subsection-content p{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 13px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 20px; 
    font-weight: 400; 
    text-align: left;
}

.story-1 .subsection-content p strong{
	font-weight: 700;
}



.story-1 .subsection-content img{
	float: left;
	margin-bottom: 10px;
	border-radius: 0;
}

.faq-section{
	width: 100%;
	float: left;
	padding:65px 0 92px 0;
	margin: 0;
	background: #E7F2F4;
}

.faq-section h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.faq-content{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0;
}
.faq-list p.question{
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px; 
    font-weight: 400; 
    text-align: left;
    padding: 20px 0 8px 0;
}
 
 

.footer-consultation .container h3{
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 55px; 
    font-weight: 300; 
    text-align: left;
    background: none !important;
}

.footer-consultation .container h3 strong{
	font-weight: 700;
}

.footer-consultation .h-banner-btn {
	width: auto;
	float: right;
}

.footer-consultation .h-banner-btn a{
	width: 146px;
	margin-left: 10px;
}

 
.custom-menu-ul .view-all-treatment a,
.custom-menu-ul .start-const-btn button{
	font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 52px; 
    font-weight: 400; 
    letter-spacing: 0.26px;
    background: #ED3237;
    padding: 0 28px;
    box-shadow: inset 0 0px 0 0 #ffffff, inset 0 0 0 0 rgba(204, 204, 204, 0);
    border-radius: 50px;
    transition: all 0.1s;
    border: 1px solid rgba(255, 255, 255, 0.5);
    position: relative;
    display: inline-block;
}

.custom-menu-ul .start-const-btn button{
	height: 54px;
}
 

.custom-menu-ul .view-all-treatment a:hover,
.custom-menu-ul .start-const-btn button:hover{
    background: #53CAF5;
    text-decoration: none !important;
}

.custom-menu-ul .btn-login-signup a{
	font-size: 13px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 52px; 
    font-weight: 400; 
    letter-spacing: 0.26px;
    text-transform: uppercase;
}

.customMenu .custom-menu-ul{
	margin-top: 10px;
}
.testimonials-list{
    width: 285px;
    float: none;
    display: inline-block;
    background: #fff;
    margin: 0 8px;
    padding: 60px 30px;
    border-radius: 8px;
    text-align: left;
}
.testimonials-list .rating-img-1 {
    margin-bottom: 10px;
}
 
.testimonials-list p {
    width: auto;
    float: left;
    padding: 0 0 10px 0;
    margin: 0;
    font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 20px;
    font-weight: 400;
    letter-spacing: 0.31px;
}

.testimonials-list p strong{
	font-weight: 700;
}

.footer-left,
.footer-right{
	width: 100% !important;
	border-left: 0 !important;
	border-bottom: 1px solid rgba(255, 255, 255, 0.44);
}

.footer-left{
	padding-bottom: 20px !important;
}
.footer-right{
	padding: 30px 0 35px 0 !important;
}

.footer-left .social-tab{
	padding: 0;
	margin:10px 0 0 0;
	border: 0 !important;
}

.footer-right .footer-links h5{
	width: 100%;
	float: left;
	padding: 0 0 10px 0;
	margin: 0;
	font-size: 18px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 28px; 
    font-weight: 400; 
}

.copyright-panel{
	border-top: 0 !important;
}

.page-footer .copyright-panel p{
	width: 100%;
	float: left;
	text-align: center;
	font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 28px; 
    font-weight: 400; 

}
.page-footer .copyright-panel p a{
	color: #fff;
}

footer.page-footer{
	padding-bottom: 0 !important;
}




 @media screen and (min-width: 768px) {
 	.page-header .header.content,
 	.breadcrumbs,
 	.category-view .category-description.main-cat-desc .container,
 	.container{
 		max-width: 1260px !important;
 	}
 	 

 	.footer-left .accordion-tab label{
 		width: 150px;
 	}
 	.footer-left .accordion-tab.footer-newsletter-1{
 		width: 600px;
 	}
 	.footer-left .accordion-tab.socila-media-tab {
	    width: 220px;
	    float: right;
	}

 	.footer-left .accordion-tab label{
 		width: 130px;
 		float: left;
 		margin-right: 35px;
 	}

 	.footer-left .accordion-tab .newsletter label,
 	.block.newsletter .field.newsletter{
 		width: 100% !important;
 		max-width: 100% !important;
 	}

 	.footer-left .accordion-tab.footer-newsletter-1 .tab-content{
 		width: 410px;
 		float: left;
 	}
 	.footer.content ul {
	    padding-right: 0 !important;
	}

	.footer-left .social-tab ul li:before{
		font-size: 35px!important;
	}

	.footer-left .social-tab ul li{
		margin-right: 0 !important;
		margin-left: 25px !important;
	}

	.footer-right .footer-links{
		width: 500px;
		float: left;
	}
	.footer-right .right-img{
		width: auto;
		float: right;
		margin-top: 10px;
	}

	.footer-right .footer-links .leff-col ul li{
		width: 35%;
	}

	.page-main{
		max-width: 100% !important;
	}

	.category-section-2 .subsection-b{
		width: 17%;
		float: left; 
	}

	.glp-work .subsection-content{
		height: 90px;
	}

	.faq-section .container{
		max-width: 670px !important;
	}
	.page-with-filter .category-cms {
	    margin-top: 65px !important;
	}
	.page-with-filter.page-products .category-cms{
		margin-top: 0 !important;
	}

	.included-section.glp-work .container,
	.included-section .container{
		max-width: 1005px !important;

	}
	.footer-link .container,
	.footer-consultation .container{
		max-width: 1090px !important;

	}

	.product-info-tab .tab-container{
		max-width: 1145px !important;
		margin: 0 auto;
	}

	.weightloss-journey .container{
		max-width: 1030px !important;
		display: block !important;
	}

	.cart-container{
		width: 1260px;
		margin: 0 auto;
	}
	.popup-authentication.modal-popup._inner-scroll .modal-inner-wrap{
		width: 42% !important;
		border-radius: 12px !important;
		max-width: 580px !important;
		padding: 15px 40px !important;
		margin: 7rem auto !important;
	}
	.checkout-index-index .page-main {
	    max-width: 1090px !important; 
	    margin-top: 25px;
	}

 }

 
 


 @media screen and (max-width: 767px) {


 	.product-info-tab .tab button.tablinks{
 		font-size: 16px !important;
 	}

 	.header.content .rating-header{
 		display: none;
 	}
 	 
 	.video-section .subsection-2{
 		width: 100% !important;
 	}

 	.video-section .subsection-2{
 		width: 100% !important;
 		
 	}
 	 
	header .header.content{
		padding-bottom: 10px !important;
		padding-top: 20px !important;
	}

	 
	 
	.home-testimonilas h2,
	.google-review-section h2,
	.blogs-section h2,
	.faq-section h2,
	.stories-section h2, 
	.video-section h2,
	.included-section h2,
	.treatment-options h2{
		font-size: 32px !important;
		line-height: 40px !important;
		text-align: left;
		padding-left: 15px;
		padding-right: 15px;
		width: auto !important;
	}

	.video-section h2{
		margin-bottom: 30px !important;
	}
	.faq-section h2 br{
		display: none;
	}
	 
	.story-1{
	    width: auto !important;
	    float: left;
	    padding: 0 15px 20px 15px !important;
	}

	.included-section .subsection{
		width: 90% !important;
		padding: 0 15px;
	}

	.included-section .subsection-content{
		margin-right: 0 !important;
	}
	.included-section .subsection p{
		width: 70% !important;
	}

	.included-section .subsection-content.last {
	    border-bottom: 1px solid #D3DEE1 !important;
	}
	.included-section .subsection-content.last.last2 {
	    border-bottom: 0 !important;
	    padding-bottom: 0 !important;
	    margin-bottom: 0 !important;
	}
	.treatment-options .home_block_1{
		margin-bottom: 20px !important;
	}
	.story-1 img{
		width: 100%;
	}

	.story-1 .subsection-content img{
		width: auto !important;
	}

	 

	 
	.video-section,
	.treatment-options{
		padding: 35px 0 !important;
	}

	.how-it-works-section{
		background: #fff;
	}
	.work-c { 
	    left: 150px !important;
	    padding-right: 20px !important;
	}

	.Works-1{
		width: 100% !important;
		margin: 0 !important;
	}

	.testimonials-list,
	.review-list{
		width: 78% !important;
		margin: 0 15px 20px 15px !important;
	}

	.faq-content{
		width: 90% !important;
		padding: 0 15px !important;
	}

	.blog-c{ 
		margin: 0 15px 20px 15px !important;
	}

	.footer-link{
		padding: 0 15px;
	}


	.video-section .subsection-2{
		margin-top: 15px !important;
	}
	.footer-consultation .container h3,
	.video-section .subsection-2 h3{
		width: 100% !important;
		text-align: center !important;
		font-size: 25px !important;
	}
	.footer-consultation .h-banner-btn,
	.video-section .subsection-2 .h-banner-btn{
	    width: 100% !important;
	    float: left !important;
	    margin-top: 10px;
	}
	.footer-right .right-img{
		float: left;
	    width: 100%;
	    margin-top: 30px; 
	}

	.footer-right .right-img img{
		margin-right: 10px;
		margin-bottom: 10px;
	}
	.page-footer .copyright-panel p{
		margin-top: 0 !important;
	}
	
	.category-details .start-const-btn a{
		width: 100% !important;
	}
	.category-details .start-const-btn button{
		width: 80% !important;
	}
	.tab-cont{
		width: 80% !important;
	}
	.category-details .price-s{
		width: 81% !important;
		padding: 0 35px !important;
	}

	.result-list{
		width: 80% !important;
		margin-right: 0 !important;
		margin-bottom: 20px;
	}
	.category-c{
		padding:0 20px !important;
	}
	.category-description.main-cat-desc .category-details h2,
	.category-description.main-cat-desc .category-details .wl-product-name,
	.category-description.main-cat-desc .category-details p.wl-product-name,
	.category-description.main-cat-desc .category-details h1.wl-product-name{
		width: 100% !important;
		font-size: 40px !important;
		line-height: 46px !important;
	}

	.category-view .category-description.main-cat-desc .category-image{
		width: 100% !important;
		height: 100% !important;
		background: transparent !important;
	}
	.subsection-b{
		margin-right: 0 !important;
		margin-bottom: 20px;
		display: flex;
	    flex-direction: column;
	    align-items: center;
	}
	.subsection-b h3,
	.subsection-b p.text-2{
		order: 2;
		width: 100%;
		text-align: center;
		font-size: 22px!important;
	}
	.subsection-b h3 br,
	.subsection-b p.text-2 br{
		display: none;
	}
	.category-s-i{
		order: 1;
		margin-bottom: 10px;
	}
	.included-section.glp-work{
		padding-top: 35px !important;
	}

	.our-results h2,
	.our-results.our-results-2 h3,
	.our-results.our-results-2 .result-number{
		font-size: 32px !important;
		line-height: 38px !important;
		margin-bottom: 40px !important
	}
	.our-results{
		padding: 50px 0 30px 0 !important;
	}
	.result-list h3{
		font-size: 60px !important;
		line-height: 70px !important;
	}
	.result-list{
		margin-bottom: 20px !important;
		margin-left: auto !important;
	    margin-right: auto !important;
	    float: none !important;
	    display: grid;
	}
	.our-results .result-list.last{
		margin-left: auto !important;
	    margin-right: auto !important;
	}
	.category-view .category-description.main-cat-desc{
		padding-top: 20px;
	}
	.subsection-content{
		padding-bottom: 30px !important;
		margin-bottom: 25px !important;
	}
	.included-section.glp-work .subsection-content.last {
	    margin-bottom: 25px !important;
	    padding-bottom: 30px !important;
	}
	.product-info-tab{
		padding-bottom: 50px !important;
	}
	.how-it-works-section.inner{
		margin-top: 40px !important;
		padding-top: 40px !important;
	}
	.how-it-works-section h2{
		margin-bottom: 10px !important;
	}
	.product-info-tab h2{
		margin-bottom: 30px !important;
	}
	.weightloss-journey .h-banner-btn {
	    width: 100% !important;
	    text-align: left;
	    margin-top: 10px;
		padding: 20px 20px;
	}
	.weightloss-journey{
		padding: 25px 0 45px 0 !important;
	}
	.catalog-category-view .page-main{
		padding-left: 0 !important;
		padding-right: 0 !important;
	}

	.home-testimonilas.inner .testimonials-list{
		margin-left: 0 !important;
		margin-right: 0 !important;
	}
	.category-details .price-s{
		float: none;
		margin: 0 auto !important;
		display: block !important;
	}
	.category-section-2{
		padding: 0 15px;
	}
	.tab-cont{
		width: 100% !important;
		padding: 35px 0 !important;
	}
	.tab-cont .tab{
	    width: 90%;
	    display: block; 
	    margin-left: auto;
	    margin-right: auto;
	    float: none;
	}
	.tab-cont .tabcontent{
		padding: 0 20px;
	}

	.amform-parent .amcform-popup-block {
	    /*top: 215px !important;
	    position: absolute;*/
	    padding-bottom: 30px;
	    margin-top: 140px;
	}
	.header.content{
		border-bottom: 1px solid #ddd;
	}
	.included-section.inner{
		padding-top: 40px;
	}
	.custom-row-category .product-item.custom-col-category{
		margin-right: 0 !important;
		margin-bottom: 30px !important;
	}
	.categoryquestwl-index-index .column.main .content .select-product .custom-col-category h2{
		width: 85% !important;
		height: auto !important;
	}
	.weightloss-treatment-comparison{
		width: 92% !important; 
		margin-right: 15px !important;
		margin-left: 15px !important;
		display: inline-block;
	}

	.weightloss-treatment-comparison h2{
		font-size: 32px !important;
		line-height: 38px !important;
		margin-top: 0px !important;
	}

	.weightloss-treatment-comparison .weight-loss-com{ 
	    overflow-x: auto; 
	    margin-bottom: 40px;
	}
    .weightloss-treatment-comparison .weight-loss-com::-webkit-scrollbar {
	  width: 7px;
	  background-color: rgba(255, 255, 255, 0.1);
	}
	.weightloss-treatment-comparison .weight-loss-com::-webkit-scrollbar-thumb {
	  border-radius: 0px;
	  border: 0px solid white;
	  background-color: rgba(230, 241, 243, 1);
	}

	.categoryquestwl-index-index .column.main .content{
		padding-bottom: 0 !important;
	}

	.page-product-configurable.page-layout-1column.start_consultation .included-section.glp-work,
	.page-product-configurable.page-layout-1column.start_consultation .how-it-works-section.inner,
	.page-product-configurable.page-layout-1column.start_consultation .our-results,
	.page-product-configurable.page-layout-1column.start_consultation .product-info-tab,
	.page-product-configurable.page-layout-1column.start_consultation .weightloss-journey,
	.page-product-configurable.page-layout-1column.start_consultation .video-section.inner,
	.page-product-configurable.page-layout-1column.start_consultation .meet-team-section2.inner,
	.page-product-configurable.page-layout-1column.start_consultation .treatment-options,
	.page-product-configurable.page-layout-1column.start_consultation .stories-section,
	.page-product-configurable.page-layout-1column.start_consultation .home-testimonilas.inner{
		display: none;
	}

	.page-product-configurable.page-layout-1column.start_consultation .columns{
		flex-direction: column;
		display: flex;
	}
	.page-product-configurable.page-layout-1column.start_consultation .column.main{
		order: 1;
	}
	.page-product-configurable.page-layout-1column.start_consultation .category-section-2{
		order: 2;
		padding: 0 !important;
	}
	.custom-login-actions-toolbar .secondary{
		margin-left: 0 !important;
	}
	.modal-popup.modal-slide._inner-scroll .modal-inner-wrap{
		width: 92% !important;
	}

	.checkout-index-index .columns{
		display: inline-block;
	}

	.included-section.glp-work .subsection:nth-child(5) .subsection-content,
	.included-section.inner .subsection:nth-child(5) .subsection-content{
		border-bottom: 0 !important;
		margin-bottom: 0 !important;
		padding-bottom: 10px !important;
	}
	.catalog-category-view .stories-section{
		padding-bottom: 0 !important;
	}
	.catalog-category-view .home-testimonilas.inner {
	    margin-top: 0px !important;
	}
	.story-1 .subsection-content{
		margin-bottom: 0 !important;
	}
	/*.page-layout-1column.amform-body .amcform-popup-block{
		height: 300vh;

	}*/

	.categoryquestwl-index-index .columns{
		display: flex;
		flex-direction: column;
	}
	.categoryquestwl-index-index .column.main{
		order: 1;
	}

	.categoryquestwl-index-index .included-section.inner{
		order: 2;
	}
	.category-section-2 .subsection-b{
		margin-right: 15px !important;
		margin-left: 15px;
	}
	.popup-authentication.modal-popup._inner-scroll .modal-inner-wrap{
		width: 90% !important;
	}
	.onestepcheckout-index-index .page-title-wrapper{
		margin-top: 20px !important;
	}
	.onestepcheckout-index-index .field.choice.checkout-agreement input:after{
		left: 0  !important;
	}
	.onestepcheckout-index-index .field.choice.checkout-agreement input{
		margin-right: 15px !important;
	}
	.one-step-checkout-wrapper{
		margin-top: 10px !important;
	}
	.fieldset.login .actions-toolbar .primary button.action{
		margin-right: 20px;
	}
	.minicart-wrapper .block-minicart {
	    z-index: 999999999 !important;
	}

	.our-results.our-results-2 .result-list,
	.catalog-category-view .our-results.our-results-2 .result-list.result-2{
		/*background-size: 100% !important;*/
	}
	.our-results.our-results-2 .result-list{
		height: 320px !important;
	}
	.custom-block-customer-register .temsCondition input{
		margin-bottom: 30px !important;
	}
	.form-create-account .gender{
		margin-bottom: 30px !important;
	}
	.forgot-password-block .actions-toolbar .primary button.action{
		margin-right: 20px;
	}

	.footer-link .footer-left{
		border-bottom: 0 !important;
		padding-bottom: 0 !important;
	}
	.footer-link .footer-right{
		padding-top: 0 !important;
	}
	.footer-left .social-tab{
		margin-bottom: 20px !important;
	}




 }


.catalog-category-view{
	background-image: none !important;
}

.category-description.main-cat-desc .category-details{
	background: #fff;
	border-radius: 8px;
	width: 495px;
	float: left;
	margin-top: 50px;
	margin-bottom: 50px;
	padding: 35px 0;
}

.category-c{
	padding: 0 35px;
	margin-bottom: 40px;
}

.category-view .category-image{
	display: none;
}

.category-view .category-description.main-cat-desc .category-image{
	display: block !important;
} 


.category-weightloss-sub .breadcrumbs,
.category-weightloss-sub .category-view .page-title-wrapper{
	display: none !important;
 }

 .category-view .category-description.main-cat-desc{
 	width: 100% !important;
 	background: #E8F3F5;
 }


.category-description.main-cat-desc .category-details h2,
.category-description.main-cat-desc .category-details .wl-product-name
.category-description.main-cat-desc .category-details p.wl-product-name,
.category-description.main-cat-desc .category-details h1.wl-product-name{
	font-size: 60px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 66px; 
    font-weight: 300; 
    width: 100%;
    padding: 0;
    margin: 0 0 20px 0;
}
.category-description.main-cat-desc .category-details p{
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 400; 
    width: 100%;
    padding: 0;
    margin: 0 0 20px 0;
}

.category-description.main-cat-desc .category-details ul{
	padding: 0;
	margin: 0 0 15px 0px;
}
.category-description.main-cat-desc .category-details ul li{
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 700; 
    width: 100%;
    padding: 0;
    margin: 0 0 8px 0;
    list-style-type: none;
}

.category-description.main-cat-desc .category-details ul li:before{
	content: " " !important;
	width: 15px;
	height: 17px;
	float: left;
	background: url(/pub/media/wysiwyg/WLImage/tick-img.png) left 7px no-repeat;
	margin-right: 10px;
}

.category-details .price-s{
	width: 425px;
	display: inline-block;
	padding: 0 35px;
	margin: 0;
	background: #96D8F0;
	font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 92px; 
    font-weight: 700; 
}

.category-details .price-s span{
	float: right;
	font-size: 50px;
	line-height: 92px;
}

.category-details .price-s span.m-text{
	font-size: 18px !important;
	font-weight: 400 !important;
	line-height: 30px;
	margin-top: 43px;
}

.category-view .category-description.main-cat-desc .category-image{
	width: 635px;
    height: auto;
    border-radius: 100%;
    background: #96D8F0;
    text-align: center;
    align-items: center;
    display: flex !important;
}

.category-s-i{
	float: right;
}
.subsection-b{
	background: #FEECEC;
	border-radius: 8px;
	padding:28px 35px;
	margin-right: 40px;
}

.subsection-b.last{
	margin-right: 0 !important;
}

.subsection-b h3,
.subsection-b p.text-2{
	font-size: 25px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px; 
    font-weight: 700; 
    padding: 0;
    margin: 0 0 30px 0;
}

.glp-work .subsection-content.last{
	margin-bottom: 0 !important;
	padding-bottom: 0 !important;
}

.glp-work{
	padding-bottom: 20px !important;
	padding-top: 85px !important;
}

.faq-content .faq-list{
	border-bottom: 1px solid #96D8F0;
	padding-bottom: 12px;
}


.faq-content .faq-list .answer{
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px;
    font-weight: 400;
    text-align: left;
    padding: 0;
}

.faq-content .faq-list .opener{
	transform: none !important;
}


.category-details .start-const-btn{
	margin-top: 28px;
	text-align: center;
}
.category-details .start-const-btn a,
.category-details .start-const-btn button{
	width: 280px;
	display: inline-block;
	text-align: center;
	background: #EC3237;
    font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 60px; 
    height: 60px;
    padding: 0 0px;
    font-weight: 400;
    border-radius: 30px;
    letter-spacing: 0.26px; 
    transition: all .35s !important
     
}
.category-details .start-const-btn a:hover,
.category-details .start-const-btn button:hover{
	background: #53CAF5 !important;
	text-decoration: none;
}

.category-details .start-const-btn button:focus{
	background: #53CAF5 !important;
	box-shadow:none !important;
}


.how-it-works-section.inner {
	background: #E7F2F4;
	margin-top: 40px;
}


.our-results{
	width: 100%;
	float: left;
	padding:100px 0;
	margin: 0;
}
.our-results h2,
.our-results.our-results-2 h3,
.our-results.our-results-2 .result-number{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 60px 0;
	font-size: 38px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.result-list{
	width: 326px;
	float: left;
	padding: 35px 30px;
	margin: 0 50px 0 0;
	background: #FEECEC;
	border-radius: 8px;
}

.result-list.last{
	margin-right: 0 !important;
}

.result-list h3{
	width: 92%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 86px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 90px; 
    font-weight: 300; 
    text-align: left;
}
.result-list p{
	width: 94%;
	float: left;
	padding: 0;
	margin: 0 0 12px 0;
	font-size: 15px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 400; 
    text-align: left;
}

.result-list p span{
	font-size: 20px !important;
	font-weight: 700 !important;
}

.product-info-tab{
	width: 100%;
	float: left;
	padding:0 0 100px 0;
	margin: 0;
}
.product-info-tab h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 55px 0;
	font-size: 38px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.page-product-configurable.start_consultation .product-info-tab h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 55px 0;
	font-size: 38px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.tab-cont{
	background: #E7F2F4;
	padding: 35px;
	display: inline-block;
	width: 1075px;
}

.tab{
	width: 100%;
	display: inline-block;
	margin-bottom: 30px;
}
.tab button.tablinks{
	font-size: 19px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 55px; 
    font-weight: 700; 
    text-align: center;
    padding: 0 25px;
    border: 0 !important;
    background: transparent;
    box-shadow:none;
}

.tablinks.active{
	background: #96D8F0 !important;
	border-radius: 28px;
}

/*.tab span{ 
	border-right: 1px solid #96D8F0;
	height: 40px;
	display: inline-block;

}*/

.tabcontent h3{
	display: none;
}

.tabcontent p{
	width: 100%;
	float: left;
	padding: 0 0 20px 0;
	margin: 0;
	font-size: 15px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 24px; 
    font-weight: 400; 
    text-align: left;
}

.weightloss-journey{
    width: 100%;
    float: left;
    padding: 45px 0;
    margin: 0;
    background: #96D8F0;
}

.weightloss-journey .container h3{
	width: auto;
	float: left;
	padding: 0;
	margin: 0;
	font-size: 42px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 55px; 
    font-weight: 300; 
    text-align: left;
    background: none !important;
}

.weightloss-journey .container h3 strong{
	font-weight: 700;
	font: normal normal bold 40px/48px Lato;
}

.weightloss-journey .h-banner-btn {
	width: auto;
	float: right;
}

.weightloss-journey .h-banner-btn a{
	width: 220px;
	display: inline-block;
	text-align: center;
	background: #EC3237;
    font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 52px; 
    padding: 0 0px;
    font-weight: 400;
    border-radius: 28px;
    letter-spacing: 0.26px;
     
}
.weightloss-journey .h-banner-btn a:hover{
	background: #53CAF5 !important;
}


.video-section.inner,
.meet-team-section2.inner{
	background: #fff !important;
}

.meet-team-section2.inner{
	padding-top: 0 !important;
}

.meet-team-section2.inner .team-2{
	background: #E7F2F4;
}

.home-testimonilas.inner{
	margin-top: 50px !important;
}

.page-layout-1column.page-with-filter .page-bottom{
	display: none;
}

.page-with-filter.page-products .columns {
    margin-top: 50px !important;
}

.amform-parent .amcform-popup-block{
	/*top: 145px;
	position: absolute;*/
	margin-top: 0;
	z-index: 999999;
}
.amform-parent .amcform-popup-block .amcform-popup {
    background: #E7F2F4 !important;
    padding-bottom: 5%;
}
.page-layout-1column.amform-body .amform-parent .product-question-right{
	display: none !important;
}


@media screen and (min-width: 768px) {
	.amcform-popup-block .amform-form{
		max-width: 515px !important;
		float: none !important;
	}
	.content .select-product,
	.weightloss-treatment-comparison .container{
		width: 1120px;
	}
	.categoryquest-index-index.page-layout-1column .products-grid .product-item,
	.categoryquestwl-index-index.page-layout-1column .products-grid .product-item {
	    width: 31.5%;
	    margin-right: 10px;
	    margin-left: 10px;
	    background: #fff;
	}
	.categoryquest-index-index.page-layout-1column .products-grid .product-item:last-child,
	.categoryquestwl-index-index.page-layout-1column .products-grid .product-item:last-child{
	    margin-right: 0 !important;
	}
	.breadcrumbs{
		max-width: 100% !important; 
		background: #fff;
		padding: 15px 0 !important;
	}
	.breadcrumbs .items{
		max-width: 1260px !important;
		margin: 0 auto;
	}
	.customer-account-login footer.page-footer,
	.customer-account-create footer.page-footer,
	.customer-account-forgotpassword footer.page-footer{
		margin-top: 70px;
	}
	.cms-index-index footer.page-footer{
		margin-top: 0px !important;
	}
	.blog-page .page-main,
	.cms-page-view .page-main{
		max-width: 1260px !important;
	}
	.blog-page-list .post-holder .item-post-list{
		width: 340px !important;
	}
}

.rendered-form .fieldset .fields .field.fb-radio.form-group,
.rendered-form .fieldset .fields .field.fb-text.form-group,
.rendered-form .fieldset .fields .field.fb-undefined.form-group,
.rendered-form .fieldset .fields .field.fb-file.form-group,
.rendered-form .fieldset .fields .field.fb-checkbox.form-group,
.rendered-form .fieldset .fields .field.fb-number.form-group{
	background: #fff;
	padding: 0 30px;
}

.rendered-form .fieldset .fields .field.fb-checkbox.form-group{
	margin-bottom: 0 !important;
	padding-bottom: 15px;
}

.rendered-form .fieldset .fields .field.fb-file.form-group,
.rendered-form .fieldset .fields .field.fb-number.form-group{
	padding-top: 20px;
}
.rendered-form .fieldset .fields .field.fb-file.form-group p,
.rendered-form .fieldset .fields .field.fb-radio.form-group p{
	margin-bottom: 15px !important;
	font-weight: 700;
	padding-left: 0;
    padding-right: 0;
}
.rendered-form .fieldset .fields .field.fb-file.form-group ul,
.rendered-form .fieldset .fields .field.fb-radio.form-group ul{
	padding: 0;
	margin: 0 0 15px 0px;
	width: 100%;
}

.rendered-form .fieldset .fields .field.fb-file.form-group ul li,
.rendered-form .fieldset .fields .field.fb-radio.form-group ul li{
	border-top: 0 !important;
    margin-top: 5px !important;
    font-size: 14px !important;
    color: #000;
    font-family: 'Lato', sans-serif !important;
    line-height: 22px;
    font-weight: 400;
    text-align: left;
    margin-left: 17px;
}

.rendered-form .fieldset .fields .field.fb-number.form-group label.label{
	border-top: 0 !important;
	margin-top: 5px !important;
	font-size: 14px !important;
    color: #000;
    font-family: 'Lato', sans-serif !important;
    line-height: 22px; 
    font-weight: 400;
    text-align: left;
}

.cms-home-repeat.amform-body .rendered-form .fieldset .fields .field.form-group .control input[type=file]:before,
.amform-poup-opened.amform-body .rendered-form .fieldset .fields .field.form-group .control input[type=file]:before{
	margin-left: -18px;
	font-weight: 400;
}
.amform-parent .amcform-popup .rendered-form .fieldset .fields .field.form-group label.amform-versiontwo-label{
	border: 1px solid #E7F2F4;
}

.cms-home-repeat.amform-body .rendered-form .fieldset .fields .field.form-group input[type="checkbox"]:checked+label {
    /*background: #fff !important;*/
    color: #000;
}

.cms-home-repeat.amform-body .rendered-form .fieldset .fields .field.form-group .control .radio-group .amform-groupv2{
	margin-right: 0px !important;
}

.categoryquest-index-index .column.main .content,
.categoryquestwl-index-index .column.main .content{
	background: #e7f2f4;
	width: 100%;
	float: left;
	padding-top: 20px;
	padding-bottom: 70px;
}

.categoryquest-index-index .column.main .content .select-product h2,
.categoryquestwl-index-index .column.main .content .select-product h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.categoryquestwl-index-index .column.main .content .select-product .custom-col-category h2{
	font-size: 26px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 38px; 
    font-weight: 700; 
    height: 40px;
    text-align: left;
    width: auto;
    padding: 0 25px;
    margin-bottom: 20px;
}

.categoryquestwl-index-index .column.main .content .select-product .custom-col-category ul {list-style: none;
    display: inline-block; width: auto; padding: 0 25px 21px 25px;}
.categoryquestwl-index-index .column.main .content .select-product .custom-col-category ul li {margin-bottom: 15px;}
.categoryquestwl-index-index .column.main .content .select-product .custom-col-category ul li img {margin-right: 8px; vertical-align: middle;}

.categoryquestwl-index-index .column.main .content .select-product .custom-col-category .product-image{
	margin-bottom: 5px;
}

.categoryquest-index-index.page-layout-1column .products-grid .product-item,
.categoryquestwl-index-index.page-layout-1column .products-grid .product-item{
	border-top: 0 !important;
	padding: 30px 0;
}

.categoryquest-index-index.page-layout-1column .products-grid .product-item .product-image img,
.categoryquestwl-index-index.page-layout-1column .products-grid .product-item .product-image img{
	width: 100%;
}


.select-product h2.product-name{
	font-size: 30px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 38px; 
    font-weight: 700; 
    height: 90px;
    text-align: center;
    width: auto;
    padding: 0 25px;
}

.custom-col-wrapper-category{
	padding: 20px 0 !important;
}

.custom-row-category .product-item.custom-col-category{
	background: #fff !important;
	border-top: 0 !important;
	margin-right: 20px;
}

.custom-col-wrapper-category .select-price{
	display: inline-block;
    background: #96D8F0;
    padding: 18px 25px;
    text-align: center;
    width: 86%;
}

.custom-col-wrapper-category .product-price{
	font-size: 50px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 52px; 
    font-weight: 700;  
    text-align: center;
    width: 100%;
}

.custom-col-wrapper-category .product-price span{
	font-size: 18px !important;
	font-weight: 400 !important;
	padding-right: 5px;
}

.custom-col-wrapper-category .select-price p{
	width: auto;
	display: inline-block;
	padding: 0 10px;
	background: #E7F2F4;
	font-size: 15px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 400;  
    text-align: center;
    float: none;
    margin: 0;
}

.custom-col-wrapper-category .select-btn{
	padding: 35px 25px;
}

.custom-col-wrapper-category .product-order-now {
    float: left;
}

.custom-col-wrapper-category .select-btn img{
	float: right;
}

.custom-col-wrapper-category .product-item-desc{
	width: 87%;
	padding: 0 25px 30px 25px;
	display: inline-block;
}




.custom-col-wrapper-category .product-item-desc ul{
	padding: 0;
	margin: 0 0 15px 0px;
}

.custom-col-wrapper-category .product-item-desc ul li{
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 700; 
    width: 100%;
    padding: 0;
    margin: 0 0 8px 0;
    list-style-type: none;
}


.custom-col-wrapper-category .product-item-desc ul li:before{
	content: " " !important;
	width: 15px;
	height: 17px;
	float: left;
	background: url(/pub/media/wysiwyg/WLImage/tick-img.png) left 7px no-repeat;
	margin-right: 10px;
}


.weightloss-treatment-comparison{
	width: 100%;
	float: left;
	padding: 80px 0;
	margin: 0;
}
.weightloss-treatment-comparison h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.weight-loss-com table td{
	padding: 0;
}

.weight-loss-com table td.weight-d-2,
.weight-loss-com table td.weight-d-3{ 
    border-radius: 8px;
    padding: 5px !important;
    border: 5px solid #fff;
}

.weight-loss-com table td.weight-d-2{
	background: #FEECEC; 
}
.weight-loss-com table td.weight-d-3{
	background: #E7F2F4; 
}

.weight-cont{
	background: #fff;
    border-radius: 8px;
    padding:25px 10px 20px 10px;
    text-align: center;
    margin-bottom: 20px;
}

.weight-cont h3{
	font-size: 20px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 30px; 
    font-weight: 700; 
    text-align: left;
    padding: 0 0px;
}

.weight-d-1{
	height: 268px;
	width: 215px;
}

.weight-d-1 table td{
	font-size: 16px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 700; 
    text-align: left;
    padding: 22px 10px;
}

.weight-loss-com table td.l-space{
	font-size: 16px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 20px; 
    font-weight: 400; 
    text-align: left;
    padding: 22px 5px;
    height: 40px;
}

.weight-loss-com table td.weight-d-3 td.l-space{
	border-bottom: 1px solid #dde8ea;
}
.weight-loss-com table td.weight-d-2 td.l-space{
	border-bottom: 1px solid #fff;
}

.weight-cont .weight-i{
	height: 175px;
}


.l-space.last{
	border-bottom: 0 !important;
}

.weightloss-treatment-comparison p{
	font-size: 16px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 400; 
    text-align: left;
    width: 100%;
    display: inline-block;
}

.weight-loss-com{
	width: 100%;
	float: left;
	padding: 0;
	margin-bottom: 20px;
}

.before-footer .myaccount-bottom{
	display: none;
}

.included-section.inner{
	padding-bottom: 20px !important;
}


.amcform-popup-block .amform-form .amform-text-message{
	display: none;
}

.amform-text{
	font-size: 14px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 400; 
    text-align: center;
    margin-bottom: 18px;
}
.amcform-popup-block .amform-form h1.amform-hone{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 20px 0;
	font-size: 38px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.rendered-form .fieldset .fields .field.form-group label.fb-radio-group-label{
	border-top: 0 !important;
	margin-top: 5px !important;
	font-size: 14px !important;
    color: #000;
    font-family: 'Lato', sans-serif !important;
    line-height: 22px; 
    font-weight: 400;
    text-align: left;
}
.rendered-form .fieldset .fields .field.form-group{
	text-align: left;
}

.amcform-popup-block .amcform-button.-close-popup{
	float: left;
}


.page-layout-1column.amform-poup-opened .rendered-form .fieldset .fields .field.fb-file.form-group{
	padding-top: 27px;
}
.page-layout-1column.amform-poup-opened .rendered-form .fieldset .fields .field.fb-checkbox.form-group.field-checkboxtwo-1720096920041{
	padding-top: 15px;
}
.page-layout-1column.amform-poup-opened .rendered-form .fieldset .fields .field.fb-text.form-group.field-textinput-1719248480071 .fb-text-label{
	margin-top: 15px;
}
.page-layout-1column.amform-poup-opened .rendered-form .fieldset .fields .field.form-group.field-radiotwo-1719247930886 label.fb-radio-group-label{
	margin-top: 0 !important;
}
.rendered-form .fieldset .fields .field.fb-checkbox.form-group.am-customform-depend{
	padding-top: 23px;
	padding-bottom: 0;
}
.rendered-form .fieldset .fields .field.fb-text.form-group,
.rendered-form .fieldset .fields .field.fb-file.form-group,
.rendered-form .fieldset .fields .field.fb-checkbox.form-group{
	padding-bottom: 7px;
}
.rendered-form .fieldset .fields .field.fb-text.form-group .fb-text-label,
.rendered-form .fieldset .fields .field.form-group .fb-textarea-label{
	font-size: 14px !important;
    color: #000;
    font-family: 'Lato', sans-serif !important;
    line-height: 22px; 
    font-weight: 400 !important;
    margin-top: 20px;
}


.rendered-form .fieldset .fields .field.form-group label.amform-versiontwo-label{
	border-radius: 0 !important;
}
.rendered-form .fieldset .fields .field.form-group .amform-groupv2 {
    margin-right: 0 !important; 
}
.amform-parent .amcform-popup .rendered-form .fieldset .fields .field.form-group label.amform-versiontwo-label{
	min-width: 70px !important;
	padding: 10px 15px !important;
	background: #E7F2F4;
	border-radius: 3px;
}

.rendered-form .fieldset .fields .field.form-group input[type="radio"]:checked+label {
    background: #ffffff !important;
    color: #000 !important;
    box-shadow: 1px 1px 2px #00000029;
}

.rendered-form .fieldset .fields .field.form-group .amform-groupv2 {
    margin-right: 0 !important;
    background: #E7F2F4;
    padding: 0px;
    position: relative;
}
.rendered-form .fieldset .fields .field.form-group input[type="radio"]{
	z-index: 9;
}

.rendered-form .fieldset .fields .field.form-group input{
	/*width: 75px !important;*/
	border-radius: 3px !important;
	background: #E7F2F4 !important;
	height: 48px;
}

.rendered-form .fieldset .fields .field div.mage-error[generated]{
	width: 100%;
	float: left;
}

.amcform-popup-block .amform-form .amcform-toolbar {
    padding-top: 10px;
    background: #fff;
    width: 100%;
    text-align: left;
    padding-bottom: 50px;
}

.amcform-popup-block .amform-form .amcform-toolbar button{
	margin-left: 30px;
}


.page-product-configurable.start_consultation .category-section-2 .container,
.page-product-configurable.start_consultation .included-section.glp-work .container,
.page-product-configurable.start_consultation .our-results .container,
.page-product-configurable.start_consultation .weightloss-journey .container,
.page-product-configurable.start_consultation .video-section.inner .container,
.page-product-configurable.start_consultation .meet-team-section2.inner .container,
.page-product-configurable.start_consultation .treatment-options .container,
.page-product-configurable.start_consultation .stories-section .container,
.page-product-configurable.start_consultation .home-testimonilas.inner .container{
	display: block !important;
}

.page-product-configurable.start_consultation .category-section-2{
	width: 100%;
	float: left;
}

.page-product-configurable.page-layout-1column.start_consultation .product.media{
	display: none;
}

.page-product-configurable.page-layout-1column.start_consultation h2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 40px 0;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 48px; 
    font-weight: 300; 
    text-align: center;
}

.page-product-configurable.start_consultation .question-text.clinical-consultation h2{
	text-align: left;
	margin-bottom: 0;
}

.page-layout-1column.start_consultation .product-info-main .p-description{
	margin-bottom: 0 !important;
}

.checkout-cart-index .page-bottom{
	display: none;
}

.checkout-cart-index .cart-discount{
	margin-bottom: 50px;
}

.popup-authentication.modal-popup .modal-inner-wrap #block-customer-login-heading{
	font-size: 28px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 44px; 
    font-weight: 300; 
    text-align: center;
    padding: 0;
    margin: 0;
}

.popup-authentication.modal-popup .modal-inner-wrap .small-header legend{
	font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 24px; 
    font-weight: 400; 
    text-align: center;
    padding: 0;
    margin: 0;
}

.small-header{
	border: 0 !important;
}

.popup-authentication .block[class]{
	padding-right: 0 !important;
}

.popup-authentication.modal-popup .custom-login-actions-toolbar .secondary a{
	font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 24px; 
    font-weight: 700; 
    text-decoration: underline;
}

.popup-authentication.modal-popup .actions-toolbar .primary button.action{
	text-transform: uppercase;
	line-height: 62px;
	padding: 0;
	width: 150px;
}

.popup-authentication.modal-popup .custom-login-actions-toolbar .field.choice input{
  float: left;
  margin-bottom: 20px;
  margin-right: 10px;
  margin-top: 2px;
}
.popup-authentication.modal-popup .custom-login-actions-toolbar .field.choice input:after {
  content: '';
  display: inline-block;
  background-color: #fff;
  border: 1px solid #707070;
  border-radius:0;
  cursor: pointer;
  height: 16px;
  line-height: 16px;
  left: -1px;
  position: relative;
  top: -2px;
  width: 16px;
  text-align: center;
}

.popup-authentication.modal-popup .custom-login-actions-toolbar .field.choice input[type="checkbox"]:checked:after {
  background-color: #53CAF5;
  border-color: #53CAF5;
  content: '\2714';
  color: white;
}

.popup-authentication.modal-popup .custom-login-actions-toolbar .field.choice input[type="checkbox"]:checked:after {
  opacity: 1;
}

.register-text p{
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 24px; 
    font-weight: 400; 
}
.register-text p a{
	font-weight: 700 !important;
}

.popup-authentication.modal-popup .custom-form {
    border-bottom: 1px solid #e1e1e1 !important;
}

.popup-authentication.modal-popup._inner-scroll,
.modal-popup._inner-scroll{
    background-color: rgba(0, 0, 0, 0.90) !important;
}

.popup-authentication.modal-popup._inner-scroll .action-close{
	padding: 0 !important;
	margin: 0 !important;
}

.popup-authentication.modal-popup .modal-header{
	position: absolute;
	top: -35px;
	right: -50px;
}

.popup-authentication.modal-popup .action-close:before{
    font-size: 37px !important;
    line-height: 37px !important;
    color: #fff !important;
}


.checkout-index-index .page-title{
	margin-bottom: 10px !important;
}
.checkout-index-index .page-title,
.checkout-index-index .page-title span{
	width: 100%;
	float: left;
	font-size: 38px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 46px; 
    font-weight: 300; 
}
.checkout-index-index p.checkout-description{
	width: 100%;
	float: left;
	font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 22px; 
    font-weight: 400; 
}


.checkout-index-index .one-step-checkout-wrapper{
	background: #E7F2F4;
}
.checkout-index-index .checkout-container button:not(.primary):not(.action-show):not(.action-close):not(.edit-address-link):not(.ui-datepicker-trigger){
	background: #96D8F0 !important;
	color: #000 !important;
}

.checkout-index-index .opc-wrapper .shipping-address-item.selected-item:after{
	background-color: #00B67A !important;
}
.checkout-payment-method .payment-method-title {
    padding: 15px 0 0 !important;
}

.opc-wrapper .step-title{
	font-weight: 400 !important;
	letter-spacing: 0.48px;
	font-family: 'Lato', sans-serif !important;
}

 
.one-step-checkout-wrapper .minicart-items .product-item-detail .product-item-name{
	font-family: 'Lato', sans-serif !important;
	font-size: 20px;
	font-weight: 700;
}

.opc-block-summary .product-item .price{
	font-family: 'Lato', sans-serif !important;
	font-size: 20px;
	font-weight: 400 !important;
}

.opc-block-summary .table-totals tbody .mark, 
.opc-block-summary .table-totals tfoot .mark,
.opc-block-summary .table-totals tbody .amount, 
.opc-block-summary .table-totals tfoot .amount,
.opc-block-summary .table-totals .grand .mark,
.cart-totals .grand strong, 
.opc-block-summary .table-totals .grand strong,
.onestepcheckout-index-index .field.choice{
	font-family: 'Lato', sans-serif !important;
}

#checkout-review-table tbody{
	margin-bottom: 35px !important;
}

.onestepcheckout-index-index .field.choice.col-mp input[type="checkbox"]{
	margin-bottom: 8px !important;
}

.osc-place-order-wrapper .place-order-primary button.primary.checkout{
	font-family: 'Lato', sans-serif !important;
	font-weight: 400 !important;
}

.payment-methods input[type="radio"]{
	margin-bottom: 5px !important;
}

.cms-index-index .message.success {
    margin-top: 66px;
}
.block.newsletter .form.subscribe div.mage-error[generated]{
	font-size: 14px;
}


.product-order-now a button:hover{
	background: #53CAF5;
    text-decoration: none !important;
}

.myaccount-bottom{
	display: none !important;
}

.blog-page .post-list-wrapper .post-holder .post-content .post-description .post-text-hld p,
.blog-page .sidebar .widget.block .block-title,
.blog-page .sidebar .widget.block-categories li a,
.blog-page .sidebar .widget.block-list-posts .block-content .item a,
.blog-page.blog-post-view .post-holder .post-content .post-description .post-text-hld p,
.blog-page.blog-post-view .post-holder .post-content .post-description .post-text-hld p span{
	font-family: 'Lato', sans-serif !important;
}

.block.comments .c-replyform button{
	font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 52px;
    font-weight: 400;
    letter-spacing: 0.26px;
    background: #ED3237;
    padding: 0 28px;
    box-shadow: inset 0 0px 0 0 #ffffff, inset 0 0 0 0 rgba(204, 204, 204, 0);
    border-radius: 50px;
    transition: all 0.1s;
    border: 1px solid rgba(255, 255, 255, 0.5);
    position: relative;
    display: inline-block; 
}

.block.comments .c-replyform button:hover{
	background: #53CAF5;
    text-decoration: none !important;
}
.blog-page .post-holder .post-content .post-description .post-text-hld p a{
	color: #ec3237 !important;
}


.actions-toolbar .secondary a.action{
    margin-top: 0px !important;
    color: #000;
    font-weight: 700;
    font-family: 'Lato', sans-serif;
    font-size: 14px;
}

 

.our-results.our-results-2 .result-list{
	background-color: transparent !important;
	background: url(/pub/media/wysiwyg/WLImage/Group2939.png) left center no-repeat; 
	width: 386px;
	height: 386px;
	display: flex;
    padding: 0;
    flex-direction: column;
    align-items: center;
    justify-content: center;

}

.our-results.our-results-2 .result-list.result-2{ 
	background: url(/pub/media/wysiwyg/WLImage/Group-2940.svg) left center no-repeat !important; 

}

.our-results.our-results-2 .result-list h3,
.our-results.our-results-2 .result-list .result-number{
	text-align: left;
	margin-bottom: 3px !important;
	font-size: 80px;
	color: #28B556;
	line-height: 90px;
}
.our-results.our-results-2 .result-list.result-2 h3,
.our-results.our-results-2 .result-list.result-2 .result-number{
	color: #EE2227 !important;
}
.our-results.our-results-2 .result-list p{
	width: auto;
	padding:0 55px;
	text-align: center;
}


@media only screen and (min-width:768px) and (max-width:991px){


.page-layout-1column.start_consultation .product-info-main .product-add-form .price-box{
	margin-top: 0 !important;
}
.page-layout-1column.start_consultation .product-info-main .product-add-form .product-config-price  .price-wrapper {
    top: 0px !important;
}
.video-section h2{
	margin-bottom: 0 !important;
}
.stories-section .story-1{
    width: 230px !important;
}
.catalog-category-view.amform-body .category-view .category-image {
    margin-top: 50px !important;
}
.category-details .price-s span { 
    font-size: 40px !important;
    line-height: 90px;
}
.category-details .price-s span.m-text{
	margin-top: 40px !important;
}
.category-view .category-description.main-cat-desc .container, .container {
    max-width: 95% !important;
}
.catalog-category-view .category-view .main-cat-desc .category-image img {
    width: 230px !important;
}
.page-wrapper{
	margin: 0 !important;
}
.product-info-tab .tab-container{
	max-width: 100% !important;
}
.tab-cont{
	width: 90.2% !important;
}
.tab button.tablinks{
	font-size: 13px !important;
	padding: 0 15px !important;
}
.category-view .category-description.main-cat-desc .category-image{
	width: 50% !important;
	height: 385px !important;
}
.category-description.main-cat-desc .category-details{
	width: 45% !important;
}
.category-description.main-cat-desc .category-details h2,
.category-description.main-cat-desc .category-details .wl-product-name
.category-description.main-cat-desc .category-details p.wl-product-name,
.category-description.main-cat-desc .category-details h1.wl-product-name{
	font-size: 45px !important;
	line-height: 55px !important;
}
.category-details .price-s{
	width: 260px !important;
}
.category-details .start-const-btn a, .category-details .start-const-btn button{
	width: 300px !important;
}
.category-section-2{
	margin: 0 15px;
}

.subsection-b{
	width: 17% !important;
	padding: 28px 22px !important;
    margin-right: 15px !important;
}
.subsection-b h3,
.subsection-b p.text-2{
	font-size: 16px !important;
	line-height: 22px !important;
}

.included-section.glp-work .subsection p{
	height: 155px;
}

.subsection h3{
	font-size: 16px !important;
}
.glp-work .subsection-content{
	height: auto !important; 
}

.how-it-works-section.inner{
	margin-top: 0 !important;
}

.our-results.our-results-2 .result-list,
.our-results.our-results-2 .result-list.result-2{
	background-size: 100% !important;
	width: 210px !important;
	height: 222px !important;
	margin-left: 10px !important;
	margin-right: 10px !important;
}
.our-results.our-results-2 h2{
	margin-bottom: 25px !important;
}

.our-results.our-results-2 .result-list p br{
	display: none;
}
.our-results.our-results-2 .result-list p{
	padding: 0 30px !important;
	margin-bottom: 5px !important;
}
.our-results.our-results-2 .result-list h3,
.our-results.our-results-2 .result-list .result-number{
	font-size: 45px !important;
	line-height: 50px !important;
}

.result-list p span{
	font-size: 16px !important;
}
.weightloss-journey .container h3{
	font-size: 30px !important;
	line-height: 40px !important;
}
.weightloss-journey .container{
	width: 95% !important;
}
.home-testimonilas.inner {
    margin-top: 0px !important;
}
.footer-consultation .container h3{
	font-size: 30px !important;
	line-height: 40px !important;
}
.custom-menu-ul .trustpilot-widget{
	display: none;
}
.subsection-2{
	width: 95% !important;
	margin-top: 50px!important;
}
 
.header .rating-header{
	display: none;
}
.header .logo{
	width: auto !important;
}
.header .logo img{
	margin: 0 !important;
}
.header.content .customMenu{
	margin-top: 0 !important;
}
.review-content{
	width: 100% !important;
}
.h-banner-content{
	margin-right: 20px !important;
	width: 580px !important;
}
.review-content img{
	width: 48%;
}
.weight-loss-journey .timeframe-subheading{
	margin-bottom: 20px;
}

.testimonials-list{
	width: 185px !important;
	padding: 50px 20px !important;
}
.home_block_1{
	width: 170px !important;
}
.home_block_img{
	height: 200px !important;
}
.cms-index-index .included-section.glp-work .container, 
.cms-index-index .included-section .container
.footer-consultation .container{
    max-width: 100% !important;
}
.footer-link .container{
    max-width: 95% !important;
}

.included-section .subsection p{
	width: 70% !important;
}
.included-section .subsection {
    width: 44%;
    float: left;
    margin: 0 20px;
}
.included-section .subsection-content{
	margin-right: 0 !important;
}
.video-section,
.meet-team-section{
	padding: 50px 0 !important;
}

.meet-team-section .team-1,
.story-1,
.blog-c{
	width: 240px!important;
}

.team-2 {
    width: 205px !important; 
    margin: 0 5px !important;  
    padding: 44px 10px !important;
}
.team-2 h3{
	font-size: 15px !important;
	width: 122px !important;
}
.review-list {
    width: 200px !important; 
    margin: 0 5px !important;
    padding: 40px 20px !important; 
}

.footer-right .accordion-tab{
	width: 100% !important;
}
.footer-left .accordion-tab.footer-newsletter-1 {
    width: 500px !important;
}
.footer-left .accordion-tab.footer-newsletter-1 .tab-content{
	width: 320px !important;
}

.footer-right .footer-links{
	width: 270px !important;
}
.footer-right .right-img{
	width: 62% !important;
}
.footer-right .right-img img{
	width: 24%;
}
.footer-right .footer-links .leff-col ul li{
	width: 50% !important;
}

.content .select-product, .weightloss-treatment-comparison .container {
    width: 95% !important;
}
.categoryquestwl-index-index.page-layout-1column .products-grid .product-item{
	width: 31% !important;
	display: inline-block;
	margin-right: 25px !important;
}
.categoryquestwl-index-index .page-main .column.main .content .select-product .custom-col-category h2{
	font-size: 20px !important;
	line-height: 30px !important;
	height: 60px !important;
}

.custom-col-wrapper-category .product-price{
	font-size: 25px !important;
}
.custom-col-wrapper-category .select-price{
	padding: 18px 10px !important;
}
.custom-col-wrapper-category .select-price p{
	padding: 5px 10px !important;
}
.product-order-now a button{
	font-size: 11px !important;
	padding: 0 12px !important;
}
.custom-col-wrapper-category .select-btn{
	padding: 35px 15px !important;
}
.weight-loss-com table td.l-space{
	font-size: 13px !important;
	padding: 20px 7px !important;
}
.weight-cont h3{
	font-size: 17px !important;
	line-height: 26px !important;
}
.page-bottom{
	display: none;
}

.page-product-configurable.page-layout-1column.start_consultation button.before-start-consultation.question-text {
    top: 300px !important;
}
.page-layout-1column.catalog-product-view .question-text.clinical-consultation{
	padding: 0 15px;
}
.page-product-configurable.start_consultation .category-section-2{
	width: 96% !important;
}
.page-product-configurable.start_consultation .tab-cont {
    width: 90.7% !important;
}

.catalog-product-view.page-layout-1column.start_consultation .product-options-bottom{
	width: 100% !important;
}
.catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-options-bottom .box-tocart .action.tocart{
	margin-left: 25px;
}
.cart-container,
.breadcrumbs .items{
	width: 95% !important;
}
.one-step-checkout-wrapper .actions-toolbar {
    margin: 0 -15px !important;
}
.account.page-layout-2columns-left .sidebar-main{
	margin-left: 2%;
}

}



@media only screen and (min-width:992px) and (max-width:1024px){


.page-layout-1column.start_consultation .product-det .product-name{
	width: 80% !important;
}
.page-layout-1column.start_consultation .product-info-main .product-add-form .product-config-price .price-wrapper {
    top: 25px !important;
}
.page-layout-1column.start_consultation .product-info-main .product-add-form .price-box{
	margin-top: 0 !important;
}
.catalog-category-view.amform-body .category-view .category-image {
    margin-top: 50px !important;
}
.category-details .price-s span { 
    font-size: 40px !important;
    line-height: 90px;
}
.category-details .price-s span.m-text{
	margin-top: 40px !important;
}
.page-with-filter.catalog-category-view .category-view .category-cms .category-description.main-cat-desc .container {
    max-width: 95% !important;
}
.page-wrapper{
	margin: 0 !important;
}
.product-info-tab .tab-container{
	max-width: 100% !important;
	text-align: center;
}
.tab-cont{
	width: 93.2% !important;
}
.tab button.tablinks{
	font-size: 13px !important;
	padding: 0 15px !important;
}
.category-view .category-description.main-cat-desc .category-image{
	width: 50% !important;
	height: 512px !important;
}
.category-description.main-cat-desc .category-details{
	width: 45% !important;
}
 
.category-details .price-s{
	width: 370px !important;
}
.category-details .start-const-btn a, .category-details .start-const-btn button{
	width: 400px !important;
}
.category-section-2{
	margin: 0 0px;
}

.subsection-b{
	width: 17% !important;
	padding: 28px 33px !important;
    margin-right: 15px !important;
}
.subsection-b h3,
.subsection-b p.text-2{
	font-size: 16px !important;
	line-height: 22px !important;
}

.header .rating-header{
	display: none;
}
.header .logo img{
	margin: 0 !important;
}
.header .logo{
	width: auto !important;
	display: block;
	margin: 0 0 0 20px !important;
}
/*.header .logo img{
	margin: 0 !important;
}
.header.content .customMenu{
	margin-top: 0 !important;
}*/

.included-section.glp-work .subsection p{
	height: 155px;
}

.subsection h3{
	font-size: 16px !important;
}
.glp-work .subsection-content{
	height: auto !important; 
}

.how-it-works-section.inner{
	margin-top: 0 !important;
}

.our-results.our-results-2 .result-list,
.our-results.our-results-2 .result-list.result-2{
	background-size: 100% !important;
	width: 310px !important;
	height: 310px !important;
	margin-left: 15px !important;
	margin-right: 15px !important;
}

.our-results.our-results-2 .result-list p br{
	display: none;
}
.our-results.our-results-2 .result-list p{
	padding: 0 30px !important;
	margin-bottom: 5px !important;
}
.our-results.our-results-2 .result-list h3,
.our-results.our-results-2 .result-list .result-number{
	font-size: 45px !important;
	line-height: 50px !important;
}

.result-list p span{
	font-size: 16px !important;
}

.weightloss-journey .container{
	width: 95% !important;
}
.home-testimonilas.inner {
    margin-top: 0px !important;
}
 
.subsection-2{
	width: 95% !important;
	margin-top: 50px!important;
}
.subsection-2 h3{
	font-size: 35px !important;
	line-height: 50px !important;
}

.header.content .customMenu{
	margin-top: -8% !important;
}
.btn-login-signup a.btn-login-logout{
	padding: 0 !important;
}
.customMenu li.view-all-treatment a,
.btn-login-signup a {
    padding: 0 15px !important;
}
.review-content{
	width: 100% !important;
}
.h-banner-content{
	margin-right: 20px !important;
	width: 580px !important;
}
.review-content img{
	width: 48%;
}
.weight-loss-journey .timeframe-subheading{
	margin-bottom: 20px;
	width: 320px !important;
}

.testimonials-list{
	width: 265px !important;
	padding: 50px 25px !important;
}
.home_block_1{
	width: 265px !important;
}
.home_block_img{
	height: 250px !important;
}
.Works-1{
	width: 300px !important;
	margin: 0 15px !important;
}
.cms-index-index .included-section.glp-work .container, 
.cms-index-index .included-section .container
.footer-consultation .container{
    max-width: 100% !important;
}
.footer-link .container{
    max-width: 95% !important;
}

.included-section .subsection p{
	width: 70% !important;
}
.included-section .subsection {
    width: 46%;
    float: left;
    margin: 0 20px;
}
.included-section .subsection-content{
	margin-right: 0 !important;
}
.video-section,
.meet-team-section{
	padding: 50px 0 !important;
}

.meet-team-section .team-1,
.story-1,
.blog-c{
	width: 320px!important;
}

.team-2 {
    width: 270px !important; 
    margin: 0 10px !important;  
    padding: 44px 20px !important;
}
.team-2 h3{
	font-size: 15px !important;
	width: 122px !important;
}
.review-list {
    width: 270px !important; 
    margin: 0 10px !important;
    padding: 40px 20px !important; 
}

 

.footer-right .footer-links{
	width: 360px !important;
}
.footer-right .right-img{
	width: 62% !important;
}
.footer-right .right-img img{
	width: 24%;
}
.footer-right .footer-links .leff-col ul li{
	width: 50% !important;
}



.content .select-product, .weightloss-treatment-comparison .container {
    width: 95% !important;
}
.categoryquestwl-index-index.page-layout-1column .products-grid .product-item{
	width: 30.5% !important;
	display: inline-block;
	margin-right: 17px !important;
}
.categoryquestwl-index-index .column.main .content .select-product .custom-col-category h2{
	font-size: 20px !important;
	line-height: 30px !important;
	height: 60px !important;
}

.custom-col-wrapper-category .product-price{
	font-size: 25px !important;
}
.custom-col-wrapper-category .select-price{
	padding: 18px 10px !important;
}
.custom-col-wrapper-category .select-price p{
	padding: 5px 10px !important;
}
.product-order-now a button{
	font-size: 13px !important;
	padding: 0 30px !important;
}
.custom-col-wrapper-category .select-btn{
	padding: 35px 15px !important;
}
.weight-loss-com table td.l-space{
	font-size: 13px !important;
	padding: 20px 7px !important;
}
.weight-cont h3{
	font-size: 17px !important;
	line-height: 26px !important;
}
.page-bottom{
	display: none;
}

.page-product-configurable.page-layout-1column.start_consultation button.before-start-consultation.question-text {
    top: 300px !important;
}
.page-layout-1column.catalog-product-view .question-text.clinical-consultation{
	padding: 0 15px;
}
.page-product-configurable.start_consultation .category-section-2{
	width: 96% !important;
}
.page-product-configurable.start_consultation .tab-cont {
    width: 90.7% !important;
}

.catalog-product-view.page-layout-1column.start_consultation .product-options-bottom{
	width: 100% !important;
}
.catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-options-bottom .box-tocart .action.tocart{
	margin-left: 25px;
}.cart-container,
.breadcrumbs .items{
	width: 95% !important;
}


.cart-container,
.breadcrumbs .items{
	width: 95% !important;
}
.one-step-checkout-wrapper .actions-toolbar {
    margin: 0 -33px !important;
}
.account.page-layout-2columns-left .sidebar-main{
	margin-left: 2%;
}


}


.custom-block-customer-register .temsCondition input, 
.custom-block-customer-register .newsletter input{
	margin-right: 15px !important;
}
.custom-block-customer-register .temsCondition{
	width: 100%;
	float: left;
	margin-bottom: 10px !important;
	margin-top: 20px;
}
.custom-block-customer-register .newsletter{
	width: 100%;
	float: left;
	margin-bottom: 30px !important;
}

.block-customer-login.custom-block-customer-login .fieldset>.field>.control input,
.custom-block-customer-register .temsCondition input,
.custom-block-customer-register .newsletter input{
  float: left;
  margin-bottom: 10px;
  margin-right: 10px;
  margin-top: 2px;
}
.block-customer-login.custom-block-customer-login .fieldset>.field>.control input:after,
.custom-block-customer-register .temsCondition input:after,
.custom-block-customer-register .newsletter input:after {
  content: '';
  display: inline-block;
  background-color: #fff;
  border: 1px solid #707070;
  border-radius:0;
  cursor: pointer;
  height: 16px;
  line-height: 16px;
  left: 0px;
  position: relative;
  top: -2px;
  width: 16px;
  text-align: center;
}

.block-customer-login.custom-block-customer-login .fieldset>.field>.control input[type="checkbox"]:checked:after,
.custom-block-customer-register .temsCondition input[type="checkbox"]:checked:after,
.custom-block-customer-register .newsletter input[type="checkbox"]:checked:after{
  background-color: #53CAF5;
  border-color: #53CAF5;
  content: '\2714';
  color: white;
  opacity: 1;
}

.custom-block-customer-register .small-header legend.legend{
	font-weight: 500 !important;
	font-size: 18px !important;
}

.account.page-layout-2columns-left .page-bottom .myaccount-bottom{
	display: none !important;
}



 
.checkout-bottom{
	width: auto;
	float: right;
	border-bottom: 0 !important;
	margin-bottom: 0 !important;
}
.checkout-footer-logo{
	width: 440px;
	float: right;
	text-align: center;
}
.checkout-footer-logo .card-img{
	display: inline-block;
	float: none;
    margin: 0 10px;
    width: 155px;
}
.checkout-footer-logo .trut-pilot-2{
	border: 0 !important;
	padding-left: 0 !important;
	padding-right: 0 !important;
	margin-right: 10px !important;
	margin-left: 10px	 !important;
	display: inline-block;
	float: none;
	vertical-align: top;
    margin-top: 10px;
} 
.checkout-index-index .osc-cms-block{
	margin-top: 0;
}


.category-section-2.checkout-footer-sec{
	width: 100%;
	display: inline-block;
	margin-bottom: 40px;
}
@media screen and (min-width: 768px) {
	.category-section-2.checkout-footer-sec .subsection-b{
		/*width: 17.2% !important;*/
		margin-right: 0px !important;
		margin-left: 75px;
	}
	.category-section-2.checkout-footer-sec .subsection-b.last{
		margin-right: 0 !important;
	}
	.catalog-category-view .category-view .category-description{
		margin-bottom: 0;
	}
	.page-with-filter.catalog-category-view .category-view .category-cms .category-description.main-cat-desc{
		margin-bottom: 85px;
	}
	.page-with-filter.catalog-category-view .category-description.main-cat-desc{
		display: none;
	}
	.page-with-filter.catalog-category-view .category-view .category-cms .category-description.main-cat-desc{
		display: inline-block;
	}
	.page-product-configurable.catalog-product-view.page-layout-1column.start_consultation{
		padding-top: 0;
	}
	.page-wrapper > .breadcrumbs{
		margin-top: 0;
	}
	.catalog-category-view .category-view .main-cat-desc .category-image img{
		width: 400px;
		max-height:400px;
	}
}


@media only screen and (min-width:768px) and (max-width:991px){
.category-section-2.checkout-footer-sec .subsection-b{
	width: 15% !important;
	margin-right: 25px !important;
}

}

@media only screen and (min-width:992px) and (max-width:1024px){
.category-section-2.checkout-footer-sec .subsection-b{
	width: 16% !important;
	margin-right: 30px !important;
}

}

@media screen and (max-width: 767px) {
	.category-section-2.checkout-footer-sec{
		padding: 0 !important;
		margin-top: 50px;
		margin-bottom: 20px !important;
	}

	.logo img {
	    width: 158px !important;
	    height: 90px !important;
	}
	.custom-menu-ul li.trustpoilet,
	.view-all-treatment-menu,
	.mppromobanner-style{
		display: none !important;
	}
	.page-layout-1column.amform-body .amcform-popup-block{
		padding-bottom: 0 !important;
	}
	.amcform-popup-block .amform-form h1.amform-hone{
		margin-top: 25px;
	}
	.faq-section .container {
	    width: 90%;
	}
	.faq-section button.accordion {
	    padding-right: 20px !important;
	    line-height: 26px !important;
	}
	.faq-section h2{
		padding-left: 0 !important;
		padding-right: 0 !important;
	}
	.faq-section{
		margin-top: 20px;
		padding: 35px 0!important;
	}
	.faq-section h2{
		margin-bottom: 25px !important;
	}
	.product-body .product-image{
		text-align: center;
	}
	.product-order-now {
	    float: left;
	    margin-top: 25px;
	}
	.select-btn .product-order-now{
		margin-top: 0 !important;
	}
	.header.searchbar{
		display: none;
	}
	.breadcrumbs .items{
		padding-top: 10px !important;
	}
	.amcform-popup-block .amform-form .amcform-toolbar{
		margin-bottom: 70px;
	}
	.amcform-popup-block .amform-form{
		padding-bottom: 50px;
	}
	.checkout-footer-logo{
		width: 100% !important;
	}
	.checkout-footer-logo .card-img,
	.osc-cms-block .checkout-footer-logo .trut-pilot-2{
		margin: 0 !important;
	}
	.onestepcheckout-index-index .checkout-bottom{
		width: 100% !important;
		float: left !important;
		padding-bottom: 0 !important;
	}
	.category-section-2 .subsection-b.last{
		margin-right: 15px !important; padding-right: 30px;
	}
	.page-with-filter.catalog-category-view.amform-body .category-view .category-description.main-cat-desc{
		display: none !important;
	}
	.page-with-filter.catalog-category-view.amform-body .category-view .category-cms .category-description.main-cat-desc{
		display: inline-block !important;
		margin-bottom: 30px;  padding-bottom: 68px;
	}
	.page-with-filter.catalog-category-view.amform-body .category-view .category-cms{
		margin-top: 0 !important;
	}

	.page-with-filter.catalog-category-view.amform-body .page-main{
		padding-top: 0 !important;
	}
	.page-product-configurable.catalog-product-view.page-layout-1column.start_consultation button.before-start-consultation.question-text {
	    top: 38px !important;
	}
	.catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-options-bottom .box-tocart .action.tocart{
		margin-left: 20px;
	}
	.custom-col-wrapper-category .select-btn .info-tooltip{
		width: 195px !important;
	}
	.our-results.our-results-2 .result-list{
		margin-right: auto !important;
	}
	.meet-team-section2.inner .team-2{
		width: auto !important;
		margin: 0 !important;
	}
	.video-section.inner video{
		height: auto !important;
	}
	.catalog-category-view .home-testimonilas.inner{
		padding: 45px 0 !important;
	}
	.page-with-filter.catalog-category-view .amcform-popup-block .amform-form .amcform-toolbar{
		margin-bottom: 0 !important;
	}
	.custom-col-wrapper-category .select-btn .product-order-now a button{
		padding: 0 35px !important;
	}

	.amform-body .rendered-form .fieldset .fields .field.fb-file.form-group  label{
		width: 100%;
	}


}


.footer-right .accordion-tab{
	width: 100% !important;
}

/*.catalog-product-view.page-layout-1column.start_consultation .category-section-2,
.catalog-product-view.page-layout-1column.start_consultation .included-section.glp-work,
.catalog-product-view.page-layout-1column.start_consultation .how-it-works-section.inner,
.catalog-product-view.page-layout-1column.start_consultation .our-results.our-results-2,
.catalog-product-view.page-layout-1column.start_consultation .product-info-tab,
.catalog-product-view.page-layout-1column.start_consultation .weightloss-journey,
.catalog-product-view.page-layout-1column.start_consultation .video-section.inner,
.catalog-product-view.page-layout-1column.start_consultation .meet-team-section2.inner,
.catalog-product-view.page-layout-1column.start_consultation .treatment-options,
.catalog-product-view.page-layout-1column.start_consultation .stories-section,
.catalog-product-view.page-layout-1column.start_consultation .home-testimonilas.inner{
	display: none;
}*/

 @media screen and (min-width: 768px) {
	.page-product-configurable.catalog-product-view.page-layout-1column.start_consultation button.before-start-consultation.question-text{
		top: 35px !important;
	}
	.catalog-product-view .page-main {
	    max-width: 1260px !important;
	}
	.page-layout-1column.start_consultation .product-det .product-name{
		width: 71%;
	}
	.page-layout-1column.start_consultation .product-info-main .product-config-price .price-wrapper{
		/* top: -65px !important; */
		top: 65px !important;

	}
	.page-layout-1column.start_consultation .product-det{
		padding-bottom: 22px !important;
	}
	.catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-options-bottom .box-tocart .action.tocart{
		margin-left: 30px;
	}
	.catalog-product-view.page-layout-1column.start_consultation .stories-section{
		padding: 30px 0 !important;
	}

}

.catalog-product-view.page-layout-1column.start_consultation .product-options-bottom {
    width: 100%;
    border-top: 1px solid #ddd;
    padding-top: 20px;
    margin-top: 0 !important;
    background: #F1F7F9 !important;
}
.page-product-configurable.catalog-product-view.page-layout-1column.start_consultation .product-options-wrapper .fieldset{
	margin-bottom: 0 !important;
}


.customMenu .custom-menu-ul .amform-parent{
	float: left;
}

.faq-section button.accordion{
	width: 100%;
}

.faq-section button.accordion{
	border: 0;
	border-bottom: 1px solid #96D8F0;
	box-shadow:none !important;
	background: transparent;
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px;
    font-weight: 400;
    text-align: left;
    padding: 20px 0;
}

.faq-section .panel,
.faq-section .panel p{
	font-size: 16px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 24px;
    font-weight: 400;
    text-align: left;
    padding: 10px 0 5px 0;
    margin-bottom: 0;
}

.faq-section button.accordion:after{
	float: right; 
	display: none;
}
.faq-section button.accordion{ 
	background: url(/pub/media/wysiwyg/WLImage/Poly.png) right 32px no-repeat; 
}

.reveal1{
  position: relative;
  transform: translateY(150px);
  opacity: 0;
  transition: 1s all ease !important;
}

.reveal1.active{
  transform: translateY(0);
  opacity: 1;
}

.banner-left-c .start-const-btn button,
.h-banner-btn .start-const-btn button,
.home_block_1 .h-banner-btn a,
.category-details .start-const-btn button,
.weightloss-journey .h-banner-btn a,
.footer-consultation .h-banner-btn a,
.amcform-popup-block .amform-form .amcform-toolbar button,
.product-order-now a button,
.catalog-product-view.page-layout-1column.start_consultation .product-info-main .product-options-bottom .box-tocart .action.tocart,
.cart-container .continue-shopping,
.checkout-cart-index .cart-summary .checkout-methods-items .action.primary.checkout,
.popup-authentication.modal-popup .actions-toolbar .primary button.action,
.osc-place-order-wrapper .place-order-primary button.primary.checkout{ 
	transition: all .35s !important;
	text-decoration: none !important;
}


.custom-col-wrapper-category .select-btn{
	position: relative;
}
.custom-col-wrapper-category .select-btn .info-tooltip{ 
    position: absolute;
    left: 10px;
    width: 220px;
    background: #96d8f0;
    padding: 10px 15px;
    top: 31px;
    box-shadow: 1px 1px 2px #00000029;
    border-radius: 10px;
    transition: all .35s !important;
    font-family: 'Lato', sans-serif;
    color: #000;
    font-size: 13px;
    line-height: 18px;
}
.custom-col-wrapper-category .select-btn .info-tooltip::after {
    content: "";
    position: absolute;
    top: 50%;
    left: 100%;
    margin-top: -15px;
    border-width: 10px;
    border-style: solid;
    border-color: transparent transparent transparent #96d8f0;
}
.custom-col-wrapper-category .select-btn img{
	cursor: pointer;
}

.product-order-now.selected a button{
	background: #53CAF5;
}

.one-step-checkout-wrapper .checkout-billing-address select{
	border-radius: 27px !important;
	background: url(/pub/media/wysiwyg/WLImage/selec-arrow-img.png) right 15px center no-repeat #fff;
}
.one-step-checkout-wrapper #checkout-step-billing .field.field-select-billing select{
	padding-right: 40px !important;
}

.checkout-index-index .page-header{
	border-bottom: 1px solid #cccccc !important;
}





.h-title-2{
	width: 100%;
	float: left;
	padding: 0;
	margin: 0 0 10px 0;
	font-size: 15px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 18px; 
    font-weight: 700; 
    text-align: left;
    letter-spacing: 0.5px;
    text-transform: uppercase;
}
.h-title-3{
    width: 100%;
    float: left;
    padding: 0;
    margin: 0 0 7px 0;
    font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 40px;
    font-weight: 700;
    text-align: left;
}
.subsection .h-title-4{
    width: 100%;
    float: left;
    padding: 0;
    margin: 0 0 15px 0;
    font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px;
    font-weight: 900;
    text-align: left;
}
.subsection-2 .h-title-5{
    width: auto;
    float: left;
    padding: 0;
    margin: 0;
    font-size: 42px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 55px;
    font-weight: 300;
    text-align: left;
}
.subsection-2 .h-title-5 strong {
    font-weight: 700;
}

.meet-team-section .h-title-6{
    width: 100%;
    float: left;
    padding: 0;
    margin: 0 0 5px 0;
    font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px;
    font-weight: 900;
    text-align: left;
}

.team-2 .h-title-7{
    padding: 0;
    margin: 0 0 0 20px;
    font-size: 18px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 22px;
    font-weight: 700;
    text-align: left;
    float: left;
    width: 175px;
}

.home_block_1 .h-product-title{
    width: 100%;
    float: left;
    padding: 0;
    margin: 0 0 10px 0;
    font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 30px;
    font-weight: 900;
    text-align: left;
}

.footer-consultation .container .footer-title{
    width: auto;
    float: left;
    padding: 0;
    margin: 0;
    font-size: 42px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 55px;
    font-weight: 300;
    text-align: left;
    background: none !important;
}
.footer-consultation .container .footer-title span{
	font-size: 15px;
	line-height: 22px !important;
	width: 100%;
	float: left;
}

@media screen and (min-width: 768px) {
	.h-title{
	    width: 100%;
	    float: left;
	    padding: 0;
	    margin: 0 0 22px 0;
	    font-size: 38px;
	    color: #101010;
	    font-family: 'Lato', sans-serif;
	    line-height: 48px;
	    font-weight: 300;
	    text-align: center;
	}
	.blogs-section .h-title{
		margin-bottom: 40px !important;
	}
}

@media only screen and (min-width:768px) and (max-width:991px){
	.video-section .subsection-2 .h-title-5,
	.footer-consultation .container .footer-title{
	    font-size: 32px !important;
    	line-height: 44px !important;
	}
	.team-2 .h-title-7{
		font-size: 15px !important;
		width: 122px !important;
	}

}

@media only screen and (min-width:992px) and (max-width:1024px){

.team-2{
	width: 310px !important;
}

}

@media screen and (max-width: 767px) {
	.weight-loss-journey .h-title,
	.home-testimonilas .h-title,
	.google-review-section .h-title,
	.blogs-section .h-title,
	.faq-section .h-title,
	.stories-section .h-title,
	.meet-team-section .h-title,
	.video-section .h-title,
	.included-section .h-title,
	.treatment-options .h-title,
	.how-it-works-section .h-title{
		font-size: 32px !important;
		line-height: 40px !important;
		text-align: left;
		padding-left: 15px;
		padding-right: 15px;
		width: auto !important;
		font-weight: 300; 
    	margin: 0 0 45px 0;
	}
	.how-it-works-section .h-title{ 
    	margin-bottom: 0 !important;
	}
	.faq-section .h-title{
		padding-left: 0 !important;
		padding-right: 0 !important;
		margin-bottom: 25px !important;
	}
	.how-it-works-section .work-c .h-title-2{
	    width: 100% !important;
	    padding: 0 !important;
	    font-size: 20px !important;
	    font-family: 'Lato', sans-serif;
	    line-height: 25px !important;
	    margin-bottom: 10px !important; 
	}
	 
	.video-section .subsection-2 .h-title-5,
	.footer-consultation .container .footer-title{
	    width: 100% !important;
	    text-align: center !important;
	    font-size: 25px !important;
	}
}


.amform-body .amcform-popup-block .amcform-button.-close-popup{
	border: 0 !important; float: right;
}
.home-treatment-block .home_block_1:after{
	display: none;
}

.social-tab ul li.twitter-icon:before{
	content: " " !important;
	background: url(/pub/media/wysiwyg/WLImage/twitter-icon-new.png) left center no-repeat;
	width: 29px;
	height: 29px;
	display: inline-block;
}

@media screen and (max-width: 767px) {
	.social-tab ul li.twitter-icon:before{
		content: " " !important; 
		width: 20px;
		height: 30px;
		display: inline-block;
		background-size: 100%
	}

	.page-layout-1column.start_consultation{
		padding-top: 0 !important;
	}
	.faq-section button.accordion{
			font-size: 15px !important;
	}
	.footer-consultation .h-banner-btn a{
		margin-top: 15px;
		width: 145px !important;
	}

}

.page-layout-1column.start_consultation .product-info-main .product-config-price .price-wrapper:before{
	margin-bottom: 10px;
} 

.faq-section button.accordion{
	font-weight: 700 !important;
}

.amcform-popup-block .amcform-popup .amcform-button.-close-popup .amcform-icon.-cross:before{
	color: #fff !important;
	background-color: #EE0101 !important;
    border-radius: 50pc;
    padding: 10px 20px 10px 22px;
    background-position: 18px center !important;
}

.meet-team-section2 .team-2:after,
.weight-loss-journey .timeframe-subheading:after{
	display: none;
}



/* new css */
@import url('https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap');

html {
  scroll-behavior: smooth;
}

body{
	font-family: 'Lato', sans-serif !important;
	background-color: transparent !important;
	max-width: 100% !important;
}

body.cms-index-index{
	background-color: transparent !important;
}

/* main section */
.category-view .category-description.main-cat-desc{
    background: transparent linear-gradient(180deg, #EEF9FE 0%, #A9E0F3 100%) 0% 0% no-repeat padding-box;
}

.category-description.main-cat-desc .category-details .wl-product-name
.category-description.main-cat-desc .category-details p.wl-product-name,
.category-description.main-cat-desc .category-details h1.wl-product-name{
    text-align: left;
    font: normal normal bold 72px/80px Lato;
    letter-spacing: 0px;
    color:#002250;
}

.category-description.main-cat-desc .category-details p{
    text-align: left;
    font: normal normal normal 16px/22px Lato;
    letter-spacing: 0px;
    color: #101010;
    margin: -20px 0 30px 0;
}

.category-details .price-s .subworks{
    text-align: right;
    font: normal normal bold 12px/26px Lato;
    letter-spacing: 0px;
    color: #074A5B;
}
.category-details .price-s .subworks .question img{
    width: 25px;
    height: 25px;
} 

.category-details .price-s .subworks .question{
    margin-left: 9px;
}

.category-c{
    margin-bottom: 0px;
    padding: 0 0px;
}

.category-description.main-cat-desc .category-details{
    background: none;
    width: 505px;
    margin-top: 50px;
    margin-bottom: 70px;
    padding:0;
}

.category-details .secondbox{
    height: 243px;
}

.category-details .price-s span{
    text-align: left;
    font: normal normal normal 12px/22px Lato;
    letter-spacing: 0px;
    color: #101010;
}
.category-details .price-s span b{
    font: normal normal normal 20px/22px Lato;
    letter-spacing: 0px;

}
/* .category-details .price-s .subworks{
    font: normal normal bold 12px/22px Lato;
    letter-spacing: 0px;
    color: #074A5B;
} */

.category-details .price-s h4{
    text-align: left;
    font: normal normal normal 14px/22px Lato;
    letter-spacing: 0px;
    color: #101010;
    margin:0px 0px 16px 0px;
    padding:0;
    border-bottom: 1px solid #cdcbcb;
    min-height: 38px;
}



.category-details .start-const-btn{
    margin-top: 22px;
}

.category-details .start-const-btn button {
    width: 505px;
}

.category-view .category-description.main-cat-desc .category-image{
    background: none;
}

.category-section-2 {
    background: #E8F3F5 0% 0% no-repeat padding-box;
    height: 116px;
    margin-top: -5px;
}

.subsection-b{
    background: transparent;
    padding: 50px 0px;
    margin-right: 50px;
}
.subsection-b h3,
.subsection-b p.text-2{
    text-align: left;
    font: normal normal normal 17px/22px Lato;
    letter-spacing: 0px;
    color: #000000;
    margin: 0 0 10px 0;
}

.category-section-2 .container {
  display: flex;
  justify-content: space-between; /* Align sections with space between them */
  flex-wrap: wrap; /* Allow items to wrap to the next row */
}

.subsection-b {
  flex: 1 0 auto; /* Allow sections to grow and shrink as needed */
}

.category-s-i{
    float: left;
    margin-top: -35px;
    margin-left: -42px;
}

.active:after{
    display:none;
}

.category-s-i img{
    width: 26px;
    height: 26px;
}

.product-info-tab{
    margin-top: 62px;
}

.product-info-tab h2{
    margin: 0 0 40px 0px;
}
.product-info-tab .tab-container .tab-cont{
    width: 1141px;
    height: auto;
    border-radius: 8px;
}

.tab button.tablinks{
    font: normal normal bold 17px/46px Lato;
    letter-spacing: 0px;
    padding: 0 26px;
    text-transform: uppercase;
}

.tablinks.active{
    padding: 0px 28px;
}
.product-info-tab{
    padding: 0 0 60px 0;
}

.slider-wrapper .rating-img{
    /* display: inline-flex; */
    margin-bottom: 40px;
}

.slider-wrapper {
  display: flex;
  justify-content: center; 
}

.rating-img {
  display: flex;
  align-items: center; 
}


.rating-img img {
  margin-right: 10px; 
}

.rating-img p {
  margin-left: 10px;
  text-decoration: underline;
}

.review-list .review-img {
    margin-bottom: 10px;
}

.review-list p {
    margin-bottom: 15px;
}

.author-c img {
    float: left;
    border-radius: 50px;
    margin-right: 10px;
}

.author-c p{
    width: auto;
    float: left;
    padding: 0;
    margin: 0;
    font-size: 14px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 50px;
    font-weight: 700;
    letter-spacing: 0.31px;
    text-transform: uppercase;
}

.our-results{
    padding: 0 0;
}

.how-it-works-section{
    width: 100%;
    display: inline-block;
    padding: 60px 0 100px 0;
    text-align: center;
    margin-top: 0px !important;
}

.Works-1{
    width: 334px;
}

.work-c{
	position: absolute;
	top: 32px;
	left: 129px;
}

.work-c h2{
    font-size: 16px;
    line-height: 18px;
}

.work-c p{
    font-size: 13px;
}

.category-details .price-s li:before{
    border-top: 1px solid #D3DEE1;
}

.category-details .price-s li{
    text-align: left;
    font: normal normal bold 16px/30px Lato;
    letter-spacing: 0px;
        list-style: none;
}
.category-details .price-s li img {margin-right: 9px;}



.how-it-works-section.inner{
    background:none;
}
.left-column {
    width: 100%;
    text-align: center; /* Center the image */
    margin-bottom: 20px; /* Add some spacing between image and text */
}

.right-column {
    width: 100%;
}

.need-help-section .container{
    padding-left: 70px;
    padding-right: 70px;

}

.weightloss-journey{
    background: #000000;
}

.weightloss-journey .container h3{
    color: #ffffff;
    padding: 0 20px;
    font: normal normal 300 40px/48px Lato;
    letter-spacing: 0px;
}

/* meet the team section */
.treatment-options{
    margin-bottom: 60px;
}
.content-heading .title{
    font: normal normal normal 32px / 36px Lato;
    letter-spacing: 0px;
    color: #101010;
    text-align: center;
    line-height: 36px;
}
.custom-slider{
    margin-bottom: 50px;
}

.custom_content .subsection-content2{
    text-align: left;
    margin-top: 148px;
    margin-left: -12px;
}

.subsection-content2 .h-title-6 {
    font: normal normal 900 15px Lato;
    letter-spacing: 0px;
}
.subsection-content2 p{
    font: normal normal normal 13px / 20px Lato;
    letter-spacing: 0px;
}

button.plus-button{
    background: #FFFFFF 0% 0% no-repeat padding-box;
	display: inline-block;
	float : right;
	margin-top : -28px;
	margin-right:-34px;
	padding: 7px 12px;
    width: 40px;
    height: 40px;
    border: none;
    border-radius: 50%; /* Ensures the button is circular */
    font-size: 24px;
    text-align: center;
    cursor: pointer;
}

.our-results{
    background: #E7F2F4;
}

.our-results.our-results-2 .result-list h3,
.our-results.our-results-2 .result-number{
    text-align: left;
    padding: 0 17px;
}

.our-results.our-results-2 .result-list p{
    width: 90%;
    padding: 0 6px;
    text-align: left;
}

/* our blog page */
/*.post-list-wrapper .post-holder{
    width: 332px;
    float: none;
    display: inline-block;
    vertical-align: top;
    margin: 0 5px;
}

.post-content .post-description .post-ftimg-hld{
    margin-bottom: 20px;
}


.post-content .post-description .post-ftimg-hld img{
    border-radius: 8px;
}

.post-holder .post-header .post-info .label {
    font-size: 11px !important;
    color: #6B6B6B !important;
    font-family: 'Lato', sans-serif;
    line-height: 20px;
    font-weight: 400 !important;
    text-align: left;
    padding: 0px 0 0px 0;
    margin: 0;
    font-style: normal !important;
}

.post-holder .post-header .post-info .value{
    font-size: 11px !important;
    color: #6B6B6B !important;
    font-family: 'Lato', sans-serif;
    line-height: 20px;
    font-weight: 400 !important;
    text-align: left;
    padding: 0px 0 0px 0;
    margin: 0;
    font-style: normal !important;
}

.post-list-wrapper .post-title-holder {
    height: 67px;
    width: 100%;
    overflow-y: hidden;
    padding-bottom: 0;
    float: left;
    margin-bottom: 5px;
}


.post-list .post-header .post-title a{
    width: 100%;
    float: left;
    font-size: 20px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 26px;
    font-weight: 900;
    text-align: left;
    padding: 0px 0 10px 0;
    margin: 0;
}

.post-list-wrapper .post-holder .post-posed-date{
    float: left;
}*/




@media screen and (min-width: 768px) {
    .category-section-2 .subsection-b {
        width: auto;
    }


    .slider-wrapper {
    flex-direction: column; 
    align-items: center;
  }

  .slider-wrapper.desk-review-slider .slide-arrow {
        top: 0% !important;
    }


    .page-with-filter.page-products .category-cms{
        height: 767px;
        padding: 0;
        margin: 0;
        background-attachment: fixed;
        background-size: cover;
    }

    .catalog-category-view .category-view .main-cat-desc .category-image img{
        width: 100%;
        height: auto;
        max-height: none;
    }

    .page-with-filter.catalog-category-view .category-view .category-cms .category-description.main-cat-desc{
        margin-bottom: 0px;
    }

    .need-help-section h2,
    .need-help-section h3{
        text-align: center;
        font: normal normal 300 38px/46px Lato;
        letter-spacing: 0px;
        padding-top: 60px;
    }

    .need-help-section{
        background: #E7F2F4;
        height: 571px;
    }
    /* .new-two-column
 {
        display: flex;
        flex-wrap: wrap;
    } */

    .left-column img{
        width: 515px;
        height: auto;
    }

    .left-column {
        width: 50%;
        text-align: left; /* Align image to the left */
        margin-bottom: 0; /* Remove margin for larger screens */
    }

    .right-column {
        width: 50%;
        text-align: justify; /* Justify text in the right column */
    }

    .right-column h3,
    .need-help-section .right-column .content-title{
        margin-top: 0; /* Remove margin for h3 in the right column */
        font: normal normal bold 30px/40px Lato;
        letter-spacing: 0px;
        margin-bottom: 10px;
    }


    .category-details .price-s{
        width: 505px;
        text-align: left;
        font: normal normal normal 14px/22px Lato;
        letter-spacing: 0px;
        color: #101010;
        padding: 22px 25px !important;
        display: block;
        background: #ffffff;
        border-radius: 8px;
        margin-top: -15px;
    }

    .weightloss-journey{
        margin-top: 80px;
        margin-bottom: 80px;
    

    }

    .owl-carousel .owl-item .banner-item{
        margin: 0 10px;
        height: 270px;
     	overflow: hidden;
    }
    .owl-carousel .owl-item .banner-image img{
        /*height: 270px;*/ height: auto;
    }

    .owl-theme .owl-dots{
        bottom: -24px;
    }

    .our-results{
        height: auto; padding: 0 0 68px 0;
    }

    .our-results h2,
    .our-results.our-results-2 h3,
    .our-results.our-results-2 h3.result-number{
        margin: 50px 0 0 0;
    }

    .review-list{
        display: inline-block;
        border: 1px solid #DBDBDB;
        padding: 40px 28px;
        border-radius: 8px;
        text-align: left;
    }

    /* our blog page */
    .faq-section{
       margin-bottom:70px;
    }
    .post-list-wrapper .post-holder {
        width: 332px !important;
    }


    .our-results.our-results-2 .result-list{
        height: 290px;
    }

	.need-help-section .right-column{
    margin-top: -276px;
    float: right;
}

}



/* mobile responsile */
@media screen and (max-width: 768px) {

    html, body {
         overflow-x: hidden;
    }
    body {
        width:100%;
    }  
    .new-two-column
    {
        display:block;
    }

    .need-help-section{
        margin-top:60px;
    }

    .need-help-section .container{
        padding-left: 20px;
        padding-right: 20px;
    }

    .need-help-section h2,
    .need-help-section h3{
        text-align: left;
        font: normal normal 300 13px/46px Lato;
        letter-spacing: 0px;
        text-transform: uppercase;
        margin: 0;
    }

    .need-help-section .left-column{
        padding: 0;
        margin: 0;
    }

    .need-help-section .right-column{
        padding: 0;
        margin: 0 !important;
        float: none;

    }

    .need-help-section .right-column h3,
    .need-help-section .right-column .content-title{
        font: normal normal bold 30px/46px Lato;
    }

    .catalog-category-view .category-view .category-image img{
        width: 90% !important;
        max-height: none !important;
    }

    .how-it-works-section{
        padding: 0px;
    }

    .category-section-2{
        height: auto;
        margin-top: -20px;
    }

    .category-description.main-cat-desc .category-details{
        margin-top: 20px;
        margin-bottom: 40px;
    }

    .category-description.main-cat-desc .category-details p{
        margin: 0 0 20px 0;
    }

    .category-details .price-s{
        text-align: left;
        font: normal normal normal 13px/22px Lato;
        letter-spacing: 0px;
        color: #101010;
        padding: 22px 25px !important;
        background: #ffffff;
        border-radius: 8px;
        width: 89% !important;
        margin: 0 20px !important;
    }

    .category-details .price-s span{
        text-align: left;
        font: normal normal normal 12px / 22px Lato;
        letter-spacing: 0px;
        color: #101010;
    }

    .category-details .price-s span b{
        font: normal normal normal 16px/22px Lato;
    }

    .category-details .price-s h4{
        font: normal normal normal 13px/22px Lato;
    }

    .category-details .price-s .subworks{
        margin-top: 8px;
    }

    .category-details .start-const-btn button{
        width: 89% !important;
    }

    .product-info-tab .tab-container .tab-cont{
        height:auto;
    }

    .weightloss-journey{
        margin-top: 60px;
        margin-bottom: 60px;
        height: 279px;

    }

    .category-s-i{
        margin: 0; position: absolute; left: 0;
    }

    .category-section-2 .subsection-b{
        padding: 0; margin-right: 64px !important; margin-left: 0px;
    }

    .category-section-2{
        background: none;
    }

    .subsection-b h3,
    .subsection-b p.text-2{
        font: normal normal normal 20px/22px Lato !important; position: relative; left: 0; top: 0;
    }

    .category-section-2 .container{
        flex-wrap: nowrap;
    }

    .category-s-i img{
        width: auto !important;
        height: 26px;
        max-width: 100%;
        top: 0px; /*25px;*/
        position: relative;
        left: 0px; /*-75px;*/
    }

    .rating-img{
        justify-content: center;
    }

    .product-info-tab h2 {
        margin: 0 20px 20px 20px;
        text-align: left;
        font: normal normal normal 32px/46px Lato;
        letter-spacing: 0px;
    }

    .review-name-header{
        margin: 0 20px 20px 20px;
        text-align: left !important;
        font: normal normal normal 32px/36px Lato !important;
        letter-spacing: 0px;
    }

    .our-results h2,
    .our-results.our-results-2 h3,
    .our-results.our-results-2 .result-number{
        text-align: left;
        margin: 0 20px 20px 20px;
        font: normal normal normal 32px/38px Lato;
        letter-spacing: 0px;
    }

    .video-section h2{
        text-align: left;
        font: normal normal normal 32px/38px Lato;
        letter-spacing: 0px;
        margin: 0 20px 20px 20px;
    }

    /* .how-it-works-section h2{
        text-align: left;
        font: normal normal normal 32px/46px Lato;
        letter-spacing: 0px;
        margin: 0 20px 20px 20px;
    } */

    .review-slide .dots:checked{
        background-color: #074A5B !important;
        outline-color: #074A5B !important;
    }

    .our-results.our-results-2 .result-list{
        height: 180px !important;
    }

    .video-section .subsection video{
        width: 90% !important;
        height: 250px !important;
    }


    .owl-theme .owl-dots{
        bottom: -20px;
    }

    .owl-carousel .owl-item .banner-item{
        margin: 0 10px;
    }

    .review-slide .mainSlider{
        margin-top: 15px;
    }

    .review-slide .content{
        border: 1px solid #E5E5E5;
        border-radius: 8px;
    }   

}

/* end new css */








/*-----------03-06-2024----------*/


.custom-login-body .weightloss-custom-login {
    margin: 80px 0px 100px 0px;
    display:block;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-left-column{
	padding-left: 0 !important;
	padding-right: 0 !important;
}

.weightloss-custom-login .repeat-container.logged-in .repeat-right-column{
	padding: 40px 45px 55px 45px  !important;
	display: inline-block;
}

.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul{
	padding: 0;
	margin: 0;
}

.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li{
	width: 143px;
	float: left;
	text-align: center;
	list-style-type: none;
	margin: 0;
	padding-bottom: 0px;
	border-right: 1px solid #eec9c9;

}
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c .banner-icon {
    height: 50px;
}

.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c p{
	padding-bottom: 0 !important;
	margin-bottom: 0 !important;
}
 
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li:nth-child(4){ 
	border-right: 0 !important;
}

.weightloss-custom-login .repeat-container.logged-in .repeat-right-column p.offer-title{
	width: 100%;
    float: left;
    font-family: "Ubuntu", sans-serif;
    font-size: 34px;
    color: #000 !important;
    line-height: 46px;
    font-weight: 300 !important;
    text-align: left;
    padding: 0 0 25px 0;
    margin: 0;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column p{
	width: 100%;
    float: left;
    font-family: 'Lato', sans-serif;
    font-size: 14px;
    color: #000 !important;
    line-height: 20px;
    font-weight: 400 !important;
    text-align: center;
    padding: 0 0 15px 0;
    margin: 0 !important;
}


@media screen and (min-width: 1025px) {
	/*.weightloss-custom-login .repeat-left-column{
		width: 47%;
	} 
	.weightloss-custom-login .repeat-right-column{
		width: 46%;
	}*/

	.weightloss-custom-login .repeat-left-column #login-form,
	.weightloss-custom-login .repeat-left-column h2{
		width: 72%;
	}
}

.weightloss-custom-login .repeat-container.logged-in .repeat-left-column p{
	width: 100%;
	float: left;
	padding: 0 0 5px 0;
	margin: 0;
	font-size: 14px;
    color: #000000;
    font-family: "Ubuntu", sans-serif;
    line-height: 22px; 
    font-weight: 400; 
}
.weightloss-custom-login .repeat-container.logged-in .repeat-left-column p.cutomer-name{
	width: 100%;
	float: left;
	padding: 0 0 10px 0;
	margin: 0;
	font-size: 34px;
    color: #074A5B;
    font-family: "Ubuntu", sans-serif;
    line-height: 44px; 
    font-weight: 300; 
}


.weightloss-custom-login .repeat-container.logged-in .repeat-left-column .start-const-btn{
	width: 100%;
	float: left;
	padding: 0;
	margin: 22px 0 0 0;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-left-column .start-const-btn button{
	width: 290px;
	display: inline-block;
	text-align: center;
	background: #EC3237;
    font-size: 16px;
    color: #fff;
    font-family: "Ubuntu", sans-serif;
    line-height: 55px; 
    padding: 0 0px;
    font-weight: 500;
    border-radius: 30px;
    letter-spacing: 0;
    height: auto;
	text-transform: uppercase;
     
}
.weightloss-custom-login .repeat-container.logged-in .repeat-left-column .start-const-btn button:hover{
	background: #53CAF5 !important;
}


@media screen and (max-width: 767px) {


.custom-login-body .weightloss-custom-login .repeat-container.logged-in .banner-right-c{
	padding: 0 10px;
}
.custom-login-body .weightloss-custom-login {
    margin: 50px 0px 40px 0px !important;
    display: inline-block;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column{
	padding: 40px 0 40px 0 !important;
	margin-top: 50px !important;
	width: 100% !important;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column p.offer-title{
	text-align: center;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li{
	width: 49.7% !important;
	padding-bottom: 20px;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li:nth-child(2){ 
	border-right: 0 !important;
	border-bottom: 1px solid #eec9c9;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li:nth-child(1){  
	border-bottom: 1px solid #eec9c9;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c .banner-icon {
    height: 45px !important;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li:nth-child(4){  
	
	padding-top: 20px;
	padding-bottom: 0 !important;
}
.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li:nth-child(3){  
	padding-top: 20px;
	padding-bottom: 0 !important;
}

}



@media only screen and (min-width:768px) and (max-width:991px){

	.weightloss-custom-login .repeat-container.logged-in{
		display: inline-block !important;
		margin-bottom: 20px;
	}
	.weightloss-custom-login .repeat-container{
		display: block !important;
	}
	.custom-login-body .weightloss-custom-login { 
	    width: 95%;
	    margin: 40px auto;
	    float: none;
	    display: block;
	}

	.weightloss-custom-login .repeat-container.logged-in .repeat-left-column{
		width: 45% !important;
		float: left;
	} 
	.weightloss-custom-login .repeat-container.logged-in .repeat-right-column{
		width: 45% !important;
		float: right;
	}

	.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li{
		width: 49.7% !important;
		padding-bottom: 20px;
	}
	.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li:nth-child(2){ 
		border-right: 0 !important;
		border-bottom: 1px solid #eec9c9;
	}
	.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li:nth-child(1){  
		border-bottom: 1px solid #eec9c9;
	}
	.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c .banner-icon {
	    height: 45px !important;
	}
	.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li:nth-child(4){  
		
		padding-top: 20px;
		padding-bottom: 0 !important;
	}
	.weightloss-custom-login .repeat-container.logged-in .repeat-right-column .banner-right-c ul li:nth-child(3){  
		padding-top: 20px;
		padding-bottom: 0 !important;
	}

	.weightloss-custom-login .repeat-container.logged-in .repeat-right-column{
		padding: 25px 25px 35px 25px !important;
	}
	.weightloss-custom-login .repeat-container.logged-in .repeat-left-column p br{
		display: none;
	}


}



@media only screen and (min-width:992px) and (max-width:1024px){
	.custom-login-body .weightloss-custom-login { 
	    width: 95%;
	    margin: 40px auto;
	    float: none;
	    display: block;
	}

	.weightloss-custom-login .repeat-left-column{
		width: 75% !important;
		float: left;
	} 
	.weightloss-custom-login .repeat-right-column{
		width: 45% !important;
		float: right;
	}

	.weightloss-custom-login .repeat-right-column .banner-right-c ul li{
		width: 49.7% !important;
		padding-bottom: 20px;
	}
	.weightloss-custom-login .repeat-right-column .banner-right-c ul li:nth-child(2){ 
		border-right: 0 !important;
		border-bottom: 1px solid #eec9c9;
	}
	.weightloss-custom-login .repeat-right-column .banner-right-c ul li:nth-child(1){  
		border-bottom: 1px solid #eec9c9;
	}
	.weightloss-custom-login .repeat-right-column .banner-right-c .banner-icon {
	    height: 45px !important;
	}
	.weightloss-custom-login .repeat-right-column .banner-right-c ul li:nth-child(4){  
		
		padding-top: 20px;
		padding-bottom: 0 !important;
	}
	.weightloss-custom-login .repeat-right-column .banner-right-c ul li:nth-child(3){  
		padding-top: 20px;
		padding-bottom: 0 !important;
	}

	.weightloss-custom-login .repeat-right-column{
		padding: 25px 25px 35px 25px !important;
	}
	 


}


.page-with-filter #popup-modal .select-option-data{
	width: 100% !important;
}

.select-option-data table th{
	background-color: #96d9f1;
	font-size: 17px;
    color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 45px;
    font-weight: 700;
    padding: 0 15px !important;
}

.select-option-data table td{
	font-size: 15px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 24px;
    font-weight: 400;
    text-align: left;
    padding: 15px 15px !important;
    border-bottom: 1px solid #96d9f1;
}


@media screen and (max-width: 767px) {

	.page-products .page-wrapper #maincontent .category-view .category-cms .product-info-accordion button.accordion { 
        font-size: 17px;
	    color: #000;
	    font-family: 'Lato', sans-serif;
	    line-height: 21px;
	    font-weight: 700;
    }
    .page-products .page-wrapper #maincontent .category-view .category-cms .product-info-accordion div.panel p{
    	font-size: 15px;
	    color: #101010;
	    font-family: 'Lato', sans-serif;
	    line-height: 24px;
	    font-weight: 400;
	    text-align: left;
    }
    .page-products .page-wrapper #maincontent .category-view .category-cms .product-info-accordion div.panel ul{
    	padding: 0;
    	margin: 0;
    }
    .page-products .page-wrapper #maincontent .category-view .category-cms .product-info-accordion div.panel ul li{
    	font-size: 15px;
	    color: #101010;
	    font-family: 'Lato', sans-serif;
	    line-height: 24px;
	    font-weight: 400;
	    text-align: left;
	    list-style-type: disc;
    }
    .page-products .page-wrapper #maincontent .category-view .category-cms .product-info-accordion div.panel h3 {
        margin-top: 6px;
        padding: 0 !important;
        margin: 0 0 20px 0;
        font-size: 17px;
        font-weight: 700;
    }

    .page-with-filter #popup-modal .select-option-data #selected-data tr:nth-child(1),
    .page-with-filter #popup-modal .select-option-data #selected-data tr{
        display: flex !important;
    }
    .page-with-filter #popup-modal .select-option-data #selected-data th {
        display: block !important;
    }

    .page-with-filter #popup-modal .select-option-data #selected-data th{
    	font-size: 13px;
	    color: #000;
	    font-family: 'Lato', sans-serif;
	    line-height: 23px;
	    font-weight: 700;
	    padding: 10px 6px !important;
    }

    .page-with-filter #popup-modal .select-option-data #selected-data td{
    	padding: 0 6px 10px 6px !important;
    	border-bottom: 0 !important;
    	font-size: 14px !important;
    }
    .page-with-filter #popup-modal .select-option-data #selected-data th:nth-child(1) {
        width: 65px !important;
    }
    .page-with-filter #popup-modal .select-option-data #selected-data th:nth-child(2) {
        width: 100px !important;
    }
    .page-with-filter #popup-modal .select-option-data #selected-data th:nth-child(3) {
        width: 73px !important;
    }
    .page-with-filter #popup-modal .select-option-data #selected-data th:nth-child(4) {
        width: 80px !important;
    }

    .page-with-filter #popup-modal .select-option-data #selected-data td:nth-child(1) {
        width: 65px !important;
    }
    .page-with-filter #popup-modal .select-option-data #selected-data td:nth-child(2) {
        width: 100px !important;
    }
    .page-with-filter #popup-modal .select-option-data #selected-data td:nth-child(3) {
        width: 73px !important;
    }
    .page-with-filter #popup-modal .select-option-data #selected-data td:nth-child(4) {
        width: 80px !important;
    }
    .page-with-filter #popup-modal .select-option-data {
        padding: 12px 10px 16px 10px !important;
    }

    .page-with-filter #popup-modal .select-option-data #selected-data tr{
    	width: 100% !important;
    	padding: 10px 0 0 0 !important;
    }
    .product-info-accordion .panel{
    	border: 0 !important;
    	padding: 10px 0 !important;
    }
    .page-products .page-wrapper #maincontent .category-view .category-cms .product-info-accordion div.panel h3{
    	margin-bottom: 10px !important;
    	display: none;
    }
    .page-products .page-wrapper #maincontent .category-view .category-cms .product-info-accordion{
    	padding-bottom: 30px !important;
    	margin-bottom: 30px !important;
    }

    .weightloss-custom-login .repeat-right-column{
    	padding-bottom: 170px !important;
    }

    .weightloss-custom-login .repeat-right-column p{
    	padding: 0 30px;
    	line-height: 25px;
    }

}

.weightloss-custom-login .repeat-left-column h2{
	text-align: left !important;
	margin-bottom: 12px !important; 
}
.weightloss-custom-login .repeat-left-column .login-t{
	border-top: 1px solid #96d9f1;
	padding-top: 20px;
    margin-bottom: 25px !important;
    margin-top: 18px !important;
}

.weightloss-custom-login .repeat-left-column #login-form #email, 
.weightloss-custom-login .repeat-left-column #login-form #password{
	margin-bottom: 20px !important;
}

.weightloss-custom-login .repeat-left-column .login-t:before{
	content: " " !important;
	width: 15px;
	height: 17px;
	float: left;
	background: url(/pub/media/wysiwyg/WLImage/tick-img.png) left 7px no-repeat;
	margin-right: 10px;
}

.weightloss-custom-login .repeat-left-column #login-form #sign-in-button {
     
    font-family: 'Ubuntu', sans-serif;
    padding: 20px 35px !important;  
    text-transform: uppercase;
}

.customer-account-logoutsuccess .page-main{
	padding: 8% 0 12% 0;
}
.customer-account-logoutsuccess .columns .column.main p{
	margin-bottom: 0 !important;
}
.customer-account-logoutsuccess .page-main .page-title-wrapper{
	text-align: center;
	margin-top: 0px;
	font-size: 18px; 
	color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 28px; 
    font-weight: 400; 
}

 .customer-account-logoutsuccess .page-main .column.main p,
 .customer-account-logoutsuccess .page-main .page-title-wrapper span{
	font-size: 18px;
	color: #000;
    font-family: 'Lato', sans-serif;
    line-height: 28px; 
    font-weight: 400;
}

.weightloss-custom-login .repeat-right-column{
	background: url(/pub/media/wysiwyg/WLImage/new-cutomer-bg.svg) right bottom no-repeat #FEECEC !important;
}

.weightloss-custom-login .repeat-container.logged-in .repeat-right-column{
	background:#FEECEC !important;
}

.weightloss-custom-login .repeat-left-column h2, .weightloss-custom-login .repeat-right-column h2{
	color: #000 !important;
	font-family: 'Ubuntu', sans-serif;
	font-size: 34px !important;
	font-weight: 300 !important;
	line-height: 44px !important;
}


@media screen and (min-width: 1025px) {

	.weightloss-custom-login .repeat-left-column .login-t{
		width: 72% !important;
	}

	.weightloss-custom-login .repeat-right-column,
	.weightloss-custom-login .repeat-left-column{
		width: 41%;
	}
	.weightloss-custom-login .repeat-container.logged-in .repeat-right-column,
	.weightloss-custom-login .repeat-container.logged-in .repeat-left-column{
		width: 50%;
	}

	.weightloss-custom-login .repeat-right-column{
		padding-top: 85px !important;
	}
	.weightloss-custom-login .repeat-container.logged-in{
		height: auto !important;
		padding-bottom: 40px;
	}
	.weightloss-custom-login .repeat-container{
		height: 410px;
	}
	.home-treatment-block .fixed-image{
		height: 554px;
	}

}

.weight-cont .weight-i img{
	height: 100%;
}



/*-----------03-06-2024--------------*/


@media screen and (max-width: 767px) {
	.category-description .start-const-btn{
		width: 90%;
		margin: 0 auto;
	}
	.catalog-category-view .category-cms .start-const-btn button{
		width: 100% !important;
	}
	.page-products .page-wrapper #maincontent .category-view .category-cms .product-info-accordion h2{
		font-size: 32px !important;
	}
	.how-it-works-section h2{
		font-size: 15px !important;
		line-height: 20px !important;
	}

	.work-c h2 br{
		display: none;
	}
	.how-it-works-section.inner .Works-1 .work-c{
		top: 37px !important;
		left: 121px !important;
		padding-right: 8px !important;
	}
	.how-it-works-section.inner .Works-1:nth-child(2) .work-c {
        margin-top: 18px;
    }
    .how-it-works-section.inner .work-c .h-title-2 {
        font-size: 15px !important;
        line-height: 20px !important;
    }
    .how-it-works-section.inner .work-c .h-title-2 br{
    	display: none;
    }
    .how-it-works-section.inner .h-title{
    	font-weight: 400;
    	margin-bottom: 20px !important; 
    }
    .need-help-section .right-column h3,
    .need-help-section .right-column .content-title{
    	font-size: 25px !important;
    	line-height: 35px !important;
    	margin-top: 20px;
    	margin-bottom: 10px;
    }
    .hm-meet-team .custom-slider .owl-carousel .owl-stage-outer{
		overflow: hidden;
	}
    .hm-meet-team .custom-slider .owl-carousel .banner-item .content_slider{
		position: relative !important;
	}	
	.hm-meet-team .custom-slider .owl-carousel .owl-item .banner-image{
		display: inline-block;
	}
	.hm-meet-team .custom-slider .owl-carousel .custom_content .subsection-content2{
		margin-top: 0 !important;
	}

	.weightloss-custom-login .repeat-left-column h2{
		margin-top: 0 !important;
	}
}


@media only screen and (min-width:768px) and (max-width:991px){

	.header .rating-header{
	 	width: 180px !important;
	 	left: 0 !important;
	 }
	 .header .rating-header p{
	 	margin-left: 0 !important;
	 }
	 .page-header .header.content .customMenu{
	 	width: 175px !important;
	 	margin-top: 40px !important;
	 }
	.header.content .customMenu {
        margin-top: 40px !important;
        width: 430px !important;
    }
    .page-header .minicart-wrapper {
       top: 40px !important;
       right: 0 !important;
    } 

     

    .header .rating-header{
    	margin-top: 45px !important;
    }
    header.page-header .header.content .customMenu {
        width: 233px !important; 
    }
    header.page-header .logo {
        margin-left: 3% !important; 
    }

    .category-description .category-details .price-s span{
    	font-size: 12px !important;
    }
    .category-description.main-cat-desc .category-details .price-s{
    	line-height: 24px !important;
    }
    .category-description .amform-parent{
    	width: 90%;
    	margin-top: 40px;
    }
    .category-weightloss-sub .category-section-2{
    	padding-left: 0 !important;
    }
    .category-section-2 .subsection-b{
    	margin-right: 0px !important;
    	padding-right: 5px !important;
    }
    .category-section-2 .subsection-b{
    	padding: 25px 10px 25px 40px !important;
    }
    .category-section-2 .container{
    	max-width: 100% !important;
    }
    .category-section-2 .category-s-i{
    	top: 30px;
    }
    .need-help-section .right-column, .need-help-section .left-column{
    	vertical-align: top;
    }
    .need-help-section .left-column{
    	width: 47%;
    	margin-right: 2%;
    }
    .need-help-section .right-column{
    	text-align: left !important;
    }
    .need-help-section .right-column h3,
    .need-help-section .right-column .content-title{
    	font-size: 25px !important;
    	line-height: 35px !important;
    }

    .weightloss-treatment-comparison .weight-loss-com{
    	overflow-x: scroll;
    }
    	
    .subsection-b h3,
    .subsection-b p.text-2{
    	font-size: 14px !important;
    }
    .reveal1 { 
	    transform: none !important;
	    opacity: 1 !important; 
	}

	.page-with-filter.catalog-category-view .category-view .category-cms .category-description.main-cat-desc{
		padding-top: 50px;
	}
	.page-products.catalog-category-view.amform-body .category-view .category-image{
		margin-bottom: 0 !important;
	}
	.our-results.our-results-2 .container .result-list {
        width: 210px !important;
    }
    .our-results.our-results-2{
    	padding-top: 45px;
    }
    .how-it-works-section .Works-1{
    	width: 320px;
    	margin: 0 10px;
    }
    .how-it-works-section .Works-1 .work-c{
    	left: 133px;
    }
    .how-it-works-section .Works-1 .work-c .h-title-2{
    	font-size: 14px !important;
    }
    .how-it-works-section .Works-1 .work-c .h-title-2 br{
    	display: none;
    }
    .need-help-section{
    	height: auto !important;
    	padding-bottom: 50px;
    }

    .treatment-options .home-treatment-block .home_block_1{
    	width: 230px !important;
    	margin: 0 5px 15px 5px !important;
    	padding-left: 15px !important;
    	padding-right: 15px !important;
    }
    .treatment-options .home-treatment-block .home_block_1 p{
    	font-size: 13px !important;
    }
    .home_block_1 .h-product-title{
    	font-size: 16px !important;
    	line-height: 26px !important;
    }
    .home-treatment-block .fixed-image{
    	width: 40% !important;
    }
    .home-treatment-block .fixed-image .h-banner-btn {
        width: 100% !important;
    }
    .home-treatment-block .start-const-btn .amform-show-popup.amcform-button{
        width: 100% !important;
   }
   .treatment-options .container{
   	width: 100% !important;
   }
   .custom_content .subsection-content2{
   	margin-top: 80px !important;
   }
   .faq-section .container .h-title{
   	font-size: 32px !important;
   }
   .post-list-wrapper .post-holder {
        width: 240px !important;
    }
    .post-list .post-header .post-title{
    	margin-bottom: 15px !important;
    }
    .post-list .post-header .post-title a{
    	font-size: 20px !important;
    }

    .page-main .post-list-wrapper.blog-widget-recent{
    	max-width: 100% !important;
    	width: 100%;
    }
    .post-list-wrapper.blog-widget-recent:not(.blog-widget-recent-masonry) .post-holder {
	    width: 30% !important;
	}

	.categoryquestwl-index-index .page-main .main .included-section .subsection {
        width: 44% !important; 
    }
    .categoryquestwl-index-index .page-main .main .included-section .subsection p {
        width: 70% !important;
    }

    .page-product-configurable .product-info-main .product-det .product-desc{
    	width: 100% !important;
    }
    .page-layout-1column.start_consultation .product-det .product-name {
        width: 65% !important;
    }
    .page-product-configurable .product-info-main .test-product.test-new{
    	margin-left: 20px !important;
    }
    .page-product-configurable .page-main .product-info-main .product-det .product-desc .product-img{
    	margin-right: 15px !important;
    }
    .out-of-stock-new .wk-container-new.wk-container-outofstock{
    	left: 54%;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .columns .category-description.main-cat-desc .category-image-right{
    	width: 365px;
    	float: right;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .columns .category-description.main-cat-desc .category-image{
    	width: 90% !important;
    }
    .category-image-right .thumbnails .thumbnail{
    	width: 55px !important;
    }
    .custom-col-wrapper-category .product-order-now .out-of-stock{
    	top: -640px !important;
    }


}



@media only screen and (min-width:992px) and (max-width:1024px){

	.product-info-tab .tab button.tablinks{
		padding: 0 27px !important;
	}
	.slider-wrapper.desk-review-slider .slides-container {
        margin-left: 80px !important;
    }
    .how-it-works-section .work-c{
    	left: 110px !important;
    }
    .how-it-works-section .work-c .h-title-2 br{
    	display: none;
    }
    .how-it-works-section .work-c .h-title-2{
    	font-size: 14px !important;
    }
    .category-section-2 .container{
    	width: 92%;
    }
    .category-section-2 .subsection-b{
    	padding: 25px 25px !important;
    	margin-top: 15px;		
    }
    .category-section-2 .subsection-b .category-s-i {
	    float: left;
	    margin-top: 0;
	    margin-left: -42px;
	    position: absolute;
	    top: 27px;
	}

	.category-description .category-details .price-s span{
    	font-size: 14px !important;
    }
    .category-description.main-cat-desc .category-details .price-s{
    	line-height: 24px !important;
    }
    .product-info-tab .tab-container .tab-cont{
    	width: 93% !important;
    }
    .home-treatment-block .home_block_1{
    	width: 300px !important;
    }
    .post-list-wrapper .post-holder {
        width: 312px !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-tab .tab button.tablinks {
        font-size: 15px !important;
        padding: 0 25px !important;
    }
    .product-info-tab .tab-container .tab-cont .brand-label, .product-info-tab .tab-container .tab-cont .medistren-label{
    	width: 35% !important; 
    }
    .page-main .post-list-wrapper.blog-widget-recent{
    	max-width: 100% !important;
    	width: 100%;
    }
    .page-layout-1column.start_consultation .product-det .product-name {
        width: 70% !important;
    }
    .out-of-stock-new .wk-container-new.wk-container-outofstock{
    	right: -25px !important;
    }

    .category-description.main-cat-desc .category-details{
    	margin-bottom: 50px !important;
    }

    .cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .container .category-image img{
    	width: 350px !important;
    }

    .cms-page-view.page-layout-1column.amform-body .page-main .columns .category-description.main-cat-desc .category-image-right{
    	width: 450px;
    	float: right;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .columns .category-description.main-cat-desc .category-image{
    	width: 100% !important;
    }
     
}


@media only screen and (min-width:768px) and (max-width:1024px){
	 .page-header .logo {
	    margin-left: 8% !important;
	    float: left;
	}
	.header.content .customMenu {
        margin-top: 0% !important;
        width: 260px !important;
    }
    .header .rating-header{
    	position: relative;
    	left: 0px;
        margin-top: 53px;
        height: auto;
        display: block !important;
    }
    .owl-carousel .owl-item .banner-item .banner-image{
		position: relative;
	} 
	.owl-carousel .owl-item .banner-item .banner-image:before{
		background: linear-gradient(#00000000, #00000080), rgba(0, 0, 0, 0.1);
		content: " " !important;
	    width: 100%;
	    height: 100%;
	    display: inline-block;
	    opacity: 0.5;
	    position: absolute;
	    left: 0;
	    top: 0;
	    z-index: 99999;
	}

	.hm-meet-team .custom-slider .owl-carousel .banner-item .content_slider{
		z-index: 999999;
	}
	.weightloss-custom-login .repeat-container{
		width: 100% !important;
	}

	 

	 

}

.btn-login-signup a,
.h-banner-btn a, 
.h-banner-btn .start-const-btn button, 
.banner-left-c .start-const-btn button,
.treatment-options .fixed-image .start-const-btn .amform-show-popup,
.footer-consultation .h-banner-btn a,
.catalog-category-view .category-cms .start-const-btn button{
	transition: all .35s !important;
}

.treatment-options .fixed-image .start-const-btn .amform-show-popup{
	padding-left: 0 !important;
	padding-right: 0 !important;
}

.fill-wlcat-question p{
	padding: 0 30px;
}
.fill-wlcat-question p,
.fill-wlcat-question p a{
	color: #ff0000;
    font-size: 19px;
}
.fill-wlcat-question p a{
	text-decoration: underline;
}

.fill-wlcat-question p a:hover{
	text-decoration: none;
} 



.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc {
    background: transparent linear-gradient(180deg, #EEF9FE 0%, #A9E0F3 100%) 0% 0% no-repeat padding-box;
    display: inline-block;
    width: 100%;
    margin-bottom: 0;
}
.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image {
    margin-bottom: 72px;
}

.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .start-const-btn{
	display: inline-block;
}
.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .start-const-btn button {
    background: #ED3237;
    font-size: 15px;
    color: #fff;
    font-family: 'Ubuntu', sans-serif;
    line-height: 58px;
    border: 0;
    padding: 0 48px;
    font-weight: 500;
    box-shadow: none;
    border-radius: 50px;
    text-transform: none;
    -webkit-transition: all 0.1s;
    -moz-transition: all 0.1s;
    -o-transition: all 0.1s;
    transition: all 0.1s;
    border: 1px solid rgba(255, 255, 255, 0.5);
    position: relative;
    height: 60px;
    transition: all .35s !important;
}
.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .start-const-btn button:hover {
    background: #53CAF5;
}

.cms-page-view.page-layout-1column.amform-body .page-main .page-title-wrapper{
	display: none;
}

.cms-page-view.page-layout-1column.amform-body .page-main .brand-label, 
.cms-page-view.page-layout-1column.amform-body .page-main .medistren-label{
	margin-bottom: 20px;
}
.cms-page-view.page-layout-1column.amform-body .page-main .brand-label label, 
.cms-page-view.page-layout-1column.amform-body .page-main .medistren-label label{
	font-size: 16px;
    color: #101010;
    font-family: 'Lato', sans-serif;
    line-height: 35px;
    font-weight: 700;
}

.cms-page-view.page-layout-1column.amform-body .page-main .brand-label select, 
.cms-page-view.page-layout-1column.amform-body .page-main .medistren-label select{
	background-color: #f1f7f9 !important;
    border-radius: 40px !important;
    padding: 15px 23px !important;
    height: auto !important;
    border-color: #c4d8de !important
}

 @media screen and (min-width: 768px) {
	.cms-page-view.page-layout-1column.amform-body .page-main {
	     max-width: 100% !important;
	} 
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .container{
        max-width: 1260px !important;
    }

    .cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image-right{
    	width: 635px;
    	float: right;
    }
    
    .cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image {
	    width: 100%;
	    height: auto;
	    float: right;
	    border-radius: 0;
	    background: none;
	    text-align: center;
	    align-items: center;
	    display: flex !important;
	    margin-top: 50px !important;
	    margin-bottom: 15px !important;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image img {
        width: 100%;
        height: auto;
        max-height: none;
        object-fit: contain;
        margin: 0 auto;
        border-radius: 50px;
    }
    .product-info-tab .tab-container .tab-cont .brand-label, 
    .product-info-tab .tab-container .tab-cont .medistren-label{
    	width: 25%;
    }
    .cms-page-view.page-layout-1column.amform-body .page-wrapper > .breadcrumbs{
    	margin-bottom: 0 !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc{
		padding-bottom: 50px !important;
	}
	.weightloss-custom-login .repeat-right-column h2 br{
		display: none;
	}
	.cms-home-repeat .weightloss-custom-login .repeat-left-column #login-form #sign-in-button{
		margin-top: 5px !important;
	}
}


@media only screen and (min-width:768px) and (max-width:1024px){

	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc{
		padding-bottom: 40px;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .container{
        max-width: 95% !important;
    }
	 .cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image{
		width: 50% !important;
		height: 385px !important;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-details{
		width: 45% !important;
		margin-top: 30px;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image img {
        width: 230px !important;
    }
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-details h2,
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-details .wl-product-name,
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-details p.wl-product-name,
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-details h1.wl-product-name{
		font-size: 45px !important;
		line-height: 55px !important;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .category-details .price-s,
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .start-const-btn button{
		width: 100% !important;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .category-details .start-const-btn a, 
	.cms-page-view.page-layout-1column.amform-body .page-main .category-details .start-const-btn button{
		width: 300px !important;
	}
	.category-section-2{
		margin-top: 20px !important;
	}
	.product-info-tab .tab-container .tab-cont{
		width: 100% !important;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .tab button.tablinks {
        font-size: 12px !important;
        padding: 0 8px !important;
    }
    .product-info-tab .tab-container .tab-cont .brand-label, .product-info-tab .tab-container .tab-cont .medistren-label{
    	width: 45% !important;
    	text-align: left;
    }
}


@media screen and (min-width: 1025px) {

	.page-main .post-list-wrapper.blog-widget-recent{
		width: 100%; 
		display: block !important;
	}
	.post-list-wrapper.blog-widget-recent .post-holder{
		margin: 0 5px !important;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image-right{
    	width: 520px;
    	float: right;
    }
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image {
	    width: 100%;
	}


}

 @media screen and (max-width: 767px) {

 	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image .mySlides{
 		height: auto !important;
 	}
 	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image{
 		margin-bottom: 20px !important;
 		margin-top: 40px;
 		text-align: center;
 	}
 	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image img{
 		width: 90%;
 		margin: 0 auto;
 		border-radius: 50px;

 	}
 	.cms-page-view.page-layout-1column.amform-body .page-main{
        padding: 0 !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .start-const-btn {
	    display: block;
	    width: 90%;
	    margin: 0 auto;
	    float: none;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .category-section-2 { 
	    height: auto !important;
	    margin-top: 20px !important;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc{
		padding-bottom: 50px !important;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .category-section-2 {
        /*overflow-y: scroll;*/
        padding-left: 5%;
        padding-top: 14px;
    }

    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-tab {
        display: none;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion {
        background-color: #FAFAFA;
        padding: 37px 5% 72px 5%;
        margin-bottom: 0px;
        border: 0;
        display: block !important;
        width: 100% !important;
    }

    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion button.accordion { 
        font-size: 17px;
	    color: #000;
	    font-family: 'Lato', sans-serif;
	    line-height: 21px;
	    font-weight: 700;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion div.panel p{
    	font-size: 15px;
	    color: #101010;
	    font-family: 'Lato', sans-serif;
	    line-height: 24px;
	    font-weight: 400;
	    text-align: left;
    }

    /*.cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion{
    	background-color: #FAFAFA; 
    	padding: 37px 5% 72px 5%; 
    	margin-bottom: 58px; 
    	border: 0; 
    	display: block;
    }*/
	 
	.cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion button.accordion {
	    border-radius: 52px; 
	    padding: 20px 40px 20px 25px; 
	    margin-bottom: 7px; 
	    background-color: #E6F1F3;
	    border: 0px solid #cccccc;
	    font-size: 15px;
	    color: #000;
	    font-family: 'Lato', sans-serif;
	    line-height: 21px;
	    font-weight: 700;
	    text-align: left;
	    position: relative;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion .accordion:after {
	    /*float: right;*/
	      content: " ";
	      position: absolute;
	      right: 20px;
	      top: 25px;
	      display: block;
	      transition: all 0.4s;
	      display: block;
	      color: #fff;
	      font-size: 12px; 
	      background: url(/pub/media/wysiwyg/WLImage/arrow-img.png) 0 0 no-repeat; 
	      width: 10px;
	      height: 12px;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion button.accordion.active {
		background-color: #46C0EC !important;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion div.panel p {    
		line-height: 25px; 
		margin-bottom: 23px;
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion div.panel h3 {
		margin-top: 6px;
		margin-top: 6px;
        padding: 0 !important;
        margin: 0 0 20px 0;
        font-size: 17px;
        font-weight: 700;
	}
 
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion div.panel ul{
    	padding: 0;
    	margin: 0 0 10px 17px;
    	width: 92%;
    	display: inline-block;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion div.panel ul li{
    	font-size: 15px;
	    color: #101010;
	    font-family: 'Lato', sans-serif;
	    line-height: 24px;
	    font-weight: 400;
	    text-align: left;
	    list-style-type: disc;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion div.panel h3 {
        margin-top: 6px;
        padding: 0 !important;
        margin: 0 0 20px 0;
        font-size: 17px;
        font-weight: 700;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion h2,
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion .tab-heading-mob{
        font-size: 32px !important;
        font-weight: 400;
        margin-top: 10px;
        margin-bottom: 20px;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion div.panel h3{
    	display: none;
    }

    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data tr:nth-child(1),
    .page-with-filter #popup-modal .select-option-data #selected-data tr{
        display: flex !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data th {
        display: block !important;
    }

    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data th{
    	font-size: 13px;
	    color: #000;
	    font-family: 'Lato', sans-serif;
	    line-height: 23px;
	    font-weight: 700;
	    padding: 10px 6px !important;
    }

    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data td{
    	padding: 0 6px 10px 6px !important;
    	border-bottom: 0 !important;
    	font-size: 14px !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data th:nth-child(1) {
        width: 65px !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data th:nth-child(2) {
        width: 110px !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data th:nth-child(3) {
        width: 350px !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data th:nth-child(4) {
        width: 80px !important;
    }

    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data td:nth-child(1) {
        width: 65px !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data td:nth-child(2) {
        width: 110px !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data td:nth-child(3) {
        width: 350px !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data td:nth-child(4) {
        width: 80px !important;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data {
        padding: 12px 10px 16px 10px !important;
        overflow-x: scroll;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data{ 
	    overflow-x: auto; 
	    margin-bottom: 40px;
	}
    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data::-webkit-scrollbar {
	  width: 7px;
	  background-color: rgba(255, 255, 255, 0.1);
	}
	.cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data::-webkit-scrollbar-thumb {
	  border-radius: 0px;
	  border: 0px solid white;
	  background-color: rgba(230, 241, 243, 1);
	}


    .cms-page-view.page-layout-1column.amform-body .page-main .product-info-accordion #popup-modal .select-option-data #selected-data tr{
    	width: 100% !important;
    	padding: 10px 0 0 0 !important;
    	display: inline-block;
    }

    .post-list-wrapper.blog-widget-recent{
    	display: inline-block;
    	max-width: 100% !important;
    	padding: 30px 10px 0 10px;
    }
    .checkout-cart-index .cart-totals {
	    padding-left: 0 !important;
	    padding-right: 0 !important;
	    margin-top: 30px;
	}
	.cart-summary .checkout-methods-items{
		padding: 0 !important;
	}
	.cart.table-wrapper .product-item-details {
        margin-top: 30px !important;
        width: 90% !important;
    }
    .checkout-cart-index .form-cart .cart.item .item-actions .actions-toolbar {
        right: 0 !important;
    }
    .page-product-configurable .product-info-main .config-price{
    	padding-left: 15px !important;
    }
    .out-of-stock-new .wk-container-new.wk-container-outofstock{
    	margin-top: 75px !important;
    }
    .page-product-configurable .product-info-main .product-det .product-desc{
    	width: 100% !important;
    }

    .cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc{
		padding-bottom: 30px !important;
	}

	.custom-login-body .weightloss-custom-login{
		margin-top: 20px !important;
	}
	.weightloss-custom-login .repeat-left-column h2{
		margin-bottom: 5px !important;
	}
	.weightloss-custom-login .repeat-left-column .login-t{
		margin-bottom: 15px !important;
	}
	.weightloss-custom-login .repeat-left-column #login-form #email, .weightloss-custom-login .repeat-left-column #login-form #password{
		margin-bottom: 10px !important;
	}
	.weightloss-custom-login .repeat-left-column #login-form #sign-in-button{
		margin-top: 10px !important;
	}
	.weightloss-custom-login .repeat-left-column #login-form .forgot-pass{
		margin-top: -55px !important;
	}
	.weightloss-custom-login .repeat-left-column #login-form{
		margin-bottom: 30px !important;
	}
	.weightloss-custom-login .repeat-right-column h2{
		margin-top: 0 !important;
	}
	.weightloss-custom-login .repeat-right-column p {
	    margin-bottom: 20px !important;
	}

	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .start-const-btn{
		float: left !important;
		margin-top: 25px;
	}
	.rendered-form .fieldset .fields .field.fb-radio.form-group, .rendered-form .fieldset .fields .field.fb-text.form-group, .rendered-form .fieldset .fields .field.fb-undefined.form-group, .rendered-form .fieldset .fields .field.fb-file.form-group, .rendered-form .fieldset .fields .field.fb-checkbox.form-group{
		padding-left: 23px;
		padding-right: 23px;
	}
	 
 }



.included-section{
	padding-top: 0;
}


button:focus{
    border:0;
    box-shadow:none !important;
}
.amcform-button.-default:focus, .amcform-button.-error:focus{
	border:0 !important;
    box-shadow:none !important;
}
.revealr{
  position: relative;
  transform: translateX(150px);
  opacity: 0;
  transition: 1s all ease !important;
}

.revealr.active{
  transform: translateX(0);
  opacity: 1;
}

.reveal-l{
  position: relative;
  transform: translateX(-150px);
  opacity: 0;
  transition: 1s all ease !important;
}

.reveal-l.active{
  transform: translateX(0);
  opacity: 1;
}


.hm-meet-team .custom-slider .owl-carousel .owl-item .banner-item .banner-image{
		position: relative;
} 
.hm-meet-team .custom-slider .owl-carousel .owl-item .banner-item .banner-image:before{
		background: linear-gradient(#00000000, #00000080), rgba(0, 0, 0, 0.1);
		content: " " !important;
	    width: 100%;
	    height: 100%;
	    display: inline-block;
	    opacity: 0.5;
	    position: absolute;
	    left: 0;
	    top: 0;
	    z-index: 99999;
}

.hm-meet-team .custom-slider .owl-carousel .banner-item .content_slider{
		z-index: 999999;
}


.cms-home-repeat .rendered-form .fieldset .fields .field.fb-checkbox.form-group .amform-groupv2,
.cms-home-repeat .rendered-form .fieldset .fields .field.fb-checkbox.form-group label{
	background: transparent !important;
	border: 0 !important;
}
.cms-home-repeat .rendered-form .fieldset .fields .field.fb-checkbox.form-group .amform-groupv2{
	width: 100%;
	float: left;
}

.amform-parent .amcform-popup .rendered-form .fieldset .fields .field.fb-checkbox.form-group label.amform-versiontwo-label{
	padding-left: 25px !important;
	padding-top: 0 !important;
	padding-bottom: 0 !important;
	width: 90% !important;
	min-width: 100% !important;
	float: left;
	text-align: left;
	line-height: 28px;
}
.cms-home-repeat .rendered-form .fieldset .fields .field.fb-checkbox.form-group label span.required,
.rendered-form .fieldset .fields .field.fb-radio.form-group.field-radio-1718026770077 label span.required,
.rendered-form .fieldset .fields .field.fb-radio.form-group.field-radio-1718026605788 label span.required,
.rendered-form .fieldset .fields .field.fb-radio.form-group.field-radio-1718025970982 label span.required{
	display: none;
}
.cms-home-repeat .rendered-form .fieldset .fields .field.fb-checkbox.form-group label.fb-checkbox-group-label span.required,
.rendered-form .fieldset .fields .field.fb-file.form-group.field-file-1718026399473 label span.required{
	display: inline-block !important;
}
.cms-home-repeat .rendered-form .fieldset .fields .field.fb-checkbox.form-group input[type="checkbox"]{
	opacity: 1;
	height: 26px;
}


.cms-home-repeat .rendered-form .fieldset .fields .field.fb-checkbox.form-group input[type="checkbox"]{

    margin-right: 15px !important;
    float: left;
    margin-bottom: 10px;

   

}

.cms-home-repeat .rendered-form .fieldset .fields .field.fb-checkbox.form-group input[type="checkbox"]:after{

  content:'';

  display:inline-block;

  background-color:#fff;

  border:1px solid #000;

  border-radius:0;

  cursor:pointer;

  height:15px;

  line-height:2;

  left:0px;

  position:relative;

  top:3px;

  width:15px;

  text-align:center;

}

.cms-home-repeat .rendered-form .fieldset .fields .field.form-group.fb-checkbox input[type="checkbox"]:checked:after{

  background-color:#46C0EC;

  border:1px solid #46C0EC;

  content: '\2714';

  color:white;

  opacity:1; 

  line-height: 17px;
  top: 2px;
 

}


span.wl-require,
.rendered-form .fieldset .fields .field.fb-file.form-group p span.wl-require{
	color: #C10000 !important;
	margin-left: 3px;
	font-size: 14px !important;
    font-family: 'Lato', sans-serif !important;
}
.rendered-form .fieldset .fields .field.fb-file.form-group span.required, 
.rendered-form .fieldset .fields .field.fb-number.form-group span.required{
	display: none;
}


.fixed-image .h-banner-btn a,
.fixed-image .h-banner-btn button{
	width: 100%;
	display: inline-block;
	text-align: center;
	background: #EC3237;
    font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 55px; 
    padding: 0 0px;
    font-weight: 400;
    border-radius: 30px;
    letter-spacing: 0.26px;
    height: auto;
	text-transform: uppercase;
     
}
.fixed-image .h-banner-btn a:hover,
.fixed-image .h-banner-btn button:hover{
	background: #53CAF5 !important;
	text-decoration: none !important;
}



@media screen and (min-width: 768px) {
	.cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image-right .category-image {
        width: 100%;
        height: 500px;
        border-radius: 50px;
        background: #fff;
        margin-bottom: 20px;
    }
    .cms-page-view.page-layout-1column.amform-body .page-main .category-description.main-cat-desc .category-image-right .category-image img{
    	height: 100% !important;
    }
    .product-det.mf-initial .product-desc.mf-initial .product-name.mf-initial{
    margin-top: 55px !important;
    width: 37%;
}

}


@media screen and (max-width: 767px) {
	.category-image-right .thumbnails {
	    width: 90% !important; 
	    margin: 0 auto; 
	}
	.category-image-right .thumbnails .thumbnail{
		width: 60px;
	}
	.category-image-right{
		width: 100%;
	    display: inline-block;
	    text-align: center;
	    margin-bottom: 34px;
	}

	.cms-page-view.page-layout-1column.amform-body .page-main .category-section-2{
		-webkit-animation-name: move;
		  -webkit-animation-duration: 7s;
		  -webkit-animation-iteration-count: infinite;
		  -webkit-animation-direction: left;
		  -webkit-animation-timing-function: linear;
	}


	.cms-page-view.page-layout-1column.amform-body .page-main .category-section-2{
	  /* animation properties */
	  -moz-transform: translateX(100%);
	  -webkit-transform: translateX(100%);
	  transform: translateX(100%);
	  
	  -moz-animation: my-animation 15s linear infinite;
	  -webkit-animation: my-animation 15s linear infinite;
	  animation: my-animation 15s linear infinite;
	}

	/* for Firefox */
	@-moz-keyframes my-animation {
	  from { -moz-transform: translateX(100%); }
	  to { -moz-transform: translateX(-100%); }
	}

	/* for Chrome */
	@-webkit-keyframes my-animation {
	  from { -webkit-transform: translateX(100%); }
	  to { -webkit-transform: translateX(-100%); }
	}

	@keyframes my-animation {
	  from {
	    -moz-transform: translateX(100%);
	    -webkit-transform: translateX(100%);
	    transform: translateX(100%);
	  }
	  to {
	    -moz-transform: translateX(-330%);
	    -webkit-transform: translateX(-330%);
	    transform: translateX(-330%);
	  }


	/*.cms-page-view.page-layout-1column.amform-body .page-main .category-section-2{
		-webkit-animation-name: move;
		  -webkit-animation-duration: 10s;
		  -webkit-animation-iteration-count: infinite;
		  -webkit-animation-direction: left;
		  -webkit-animation-timing-function: linear;
	}
	@-webkit-keyframes move {
	  0% {
	    margin-left: -920px;
	  }
	  100% {
	    margin-left:100px;
	  }
	}*/
	/*.cms-page-view.page-layout-1column.amform-body .page-main .category-section-2:hover {
	  -webkit-animation-play-state: paused;
	}*/
	

	.fixed-image{
		height: 555px;
	}
	.categoryquestwl-index-index .main .content .selected-product .select-product h2{
		margin-top: 5px !important;
	}


	.customer-account-logoutsuccess .page-main{
		padding: 15% 0 12% 0 !important;
	}

	.page-layout-1column.amform-body.amform-poup-opened .rendered-form .fieldset .fields .field.form-group .control input[type=file]{
		width: 100% !important;
	}
	 
	  
}

.start-my-consultation-btn a,
.start-my-consultation-btn button{
    width: 280px;
    display: inline-block;
    text-align: center;
    background: #EC3237;
    font-size: 13px;
    color: #fff;
    font-family: 'Lato', sans-serif;
    line-height: 60px; 
    height: 60px;
    padding: 0 0px;
    font-weight: 400;
    border-radius: 30px;
    letter-spacing: 0.26px; 
    transition: all .35s !important
     
}
.start-my-consultation-btn a:hover,
.start-my-consultation-btn button:hover{
    background: #53CAF5 !important;
    text-decoration: none;
}

.start-my-consultation-btn a:focus,
.start-my-consultation-btn button:focus{
    background: #53CAF5 !important;
    box-shadow:none !important;
}

.page-layout-1column.amform-body.amform-poup-opened .rendered-form .fieldset .fields .field.form-group .control input[type=file]{
	padding-right: 0 !important;
}

@media only screen and (min-width: 768px) and (max-width: 1024px) {
	.revealr{
	  position: relative;
	  transform: translateX(0px);
	  opacity: 1 !important;
	  transition: 1s all ease !important;
	}
 

	.reveal-l{
	  position: relative;
	  transform: translateX(0px);
	  opacity: 1 !important;
	  transition: 1s all ease !important;
	}
}


 
</style>