<!-- <div>
    <button id="modal-btn" style="color: Green;"><strong><?php //echo $block->myFunction() . ' ' . 'Response' ?></strong></button>
</div> -->
<?php
// $AnsCollection = $block->getAnserCollection();
// $data = $AnsCollection->getData();
// $order = $block->getOrderDetails($block->getOrderId());
// // $collection = $order->getAllItems();
// $collection = $order->getAllVisibleItems();
// $hashKey = json_decode($block->getQuestionnaireHashKey());
?>
