

<div class="block-2">
<!-- <div class="block-img"><img src="{{skin url='images/trust-pilot-img.jpg'}}" alt="Trustpilot" /></div> -->

<!-- TrustBox script -->
<!-- <script type="text/javascript" src="//widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js" async></script> -->
<!-- End TrustBox script -->

<!-- TrustBox widget - Micro Combo -->
<div class="trustpilot-widget" data-locale="en-GB" data-schema-type="Organization" data-template-id="5419b6ffb0d04a076446a9af" data-businessunit-id="5b55f778afee7a0001b505dc" data-style-height="20px" data-style-width="100%" data-theme="light">
  <a href="https://uk.trustpilot.com/review/pharmacyplanet.co.uk" target="_blank" rel="noopener">Trustpilot</a>
</div>
<!-- End TrustBox widget -->

</div>