<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Customer Jumio Information') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
            <tr>
                <th>Customer Jumio Status:</th>
                <td><?php echo $block->getStatus(); ?></td>
            </tr>
        </tbody>
    </table>
</div>
