<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog import item template
 *
 * @var \Magento\Backend\Block\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */

if (!isset($escaper)) {
    /* Compatability fix for old Magento versions */
    $escaper = $block;
}
?>

<div class="item">
    <div class="itm-hld"
         <?php
            if ($block->getImportUrl() && !$block->getImportType()) {
                $action = 'window.open(\'' . $escaper->escapeUrl($block->getImportUrl()) . '\')';
            } else {
                if ($block->getImportPath()) {
                    $url = $block->getUrl($block->getImportPath());
                } else {
                    $url = $block->getUrl('blogimport/import/form', ['type' => $block->getImportType()]);
                }
                $action = 'window.location=\'' .  $escaper->escapeUrl($url) . '\'';
            } ?>
         onclick="<?= /* @noEscape */ $action ?>">
        <img class="img" src="<?= $escaper->escapeUrl($block->getViewFileUrl($block->getImage())) ?>" />

        <span class="lable"><?= $escaper->escapeHtml(__($block->getLabel())) ?></span>
    </div>
</div>
