<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\AuthenticationPopup $block */
?>
<div id="authenticationPopup" data-bind="scope:'authenticationPopup'" style="display: none;">
    <script>
        window.authenticationPopup = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#authenticationPopup": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            },
            "*": {
                "Magento_Ui/js/block-loader": "<?= $block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))) ?>"
            }
        }
    </script>
</div>

<script>
        require(['jquery'], function($){
            // Add hide show password
            $('body').on('click', '#showpassword1', function() {
                // e.preventDefault();
                var x = document.getElementById("pass");
                if (x.type === "password") {
                    x.type = "text";
                    $(this).html(`<i class="fa fa-eye-slash" aria-hidden="true"></i>`);
                } else {
                    x.type = "password";
                    $(this).html(`<i class="fa fa-eye" aria-hidden="true"></i>`);
                }
            });
        });
    </script>
