<?php
/** @var \Mirasvit\Helpdesk\Block\Adminhtml\Ticket\Edit\Tab\History $block */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?= $block->escapeHtml(__("Ticket History")) ?></h4>
    <div class="form-buttons"></div>
</div>
	<div class="fieldset " id="edit_fieldset">
		<div class="hor-scroll">
<table class="data-grid">
	<caption class="admin__table-caption"><?= $block->escapeHtml(__('Ticket History')) ?></caption>
	<thead>
		<tr>
			<th class="data-grid-th" scope="col"><span><?= $block->escapeHtml(__('Date'))?></span></th>
			<th class="data-grid-th" scope="col"><span><?= $block->escapeHtml(__('Done by'))?></span></th>
			<th class="data-grid-th" scope="col"><span><?= $block->escapeHtml(__('Changes'))?></span></th>
		</tr>
	</thead>
	<tbody>
<?php foreach ($block->getHistoryCollection() as $history): ?>
	<tr>
		<td><?= $block->escapeHtml($block->formatDate($history->getCreatedAt(), \IntlDateFormatter::MEDIUM)) ?> <?= $block->escapeHtml($block->formatTime($history->getCreatedAt(), \IntlDateFormatter::SHORT)) ?></td>
		<td><?= $block->escapeHtml($history->getName()) ?></td>
		<td><?= /* @noEscape */ str_replace("\n", "<br>", $block->escapeHtml($history->getMessage())) ?></td>
	</tr>
<?php endforeach ?>
	</tbody>
</table>
		</div>
	</div>
</div>